---
permalink: api-automation/concept_manage_fileshares_api.html 
sidebar: sidebar 
keywords: manage, file, share 
summary: Você pode usar a API /storage-provider/file-shares para visualizar, adicionar, modificar e excluir os volumes de compartilhamento de arquivos CIFS e NFS no seu ambiente de data center. 
---
= Gerenciar compartilhamentos de arquivos usando APIs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `/storage-provider/file-shares` API para visualizar, adicionar, modificar e excluir os volumes de compartilhamento de arquivos CIFS e NFS no seu ambiente de data center.

Antes de provisionar os volumes de compartilhamento de arquivos, certifique-se de que o SVM tenha sido criado e provisionado com os protocolos suportados.  Se você estiver atribuindo Níveis de Serviço de Desempenho (PSLs) ou Políticas de Eficiência de Armazenamento (SEPs), durante o provisionamento, os PSLs ou SEPs deverão ser criados antes de criar os compartilhamentos de arquivos.



[[view-file-shares]]
== Ver compartilhamentos de arquivos

Você pode usar o método a seguir para visualizar os volumes de compartilhamento de arquivos disponíveis no seu ambiente do Unified Manager.  Quando você adiciona um cluster ONTAP como uma fonte de dados no Active IQ Unified Manager, as cargas de trabalho de armazenamento para esses clusters são adicionadas automaticamente à sua instância do Unified Manager.  Esta API recupera os compartilhamentos de arquivos automaticamente e os adiciona manualmente à sua instância do Unified Manager.  Você pode visualizar os detalhes de um compartilhamento de arquivo específico executando esta API com a chave de compartilhamento de arquivo.

[cols="3*"]
|===
| Categoria | verbo HTTP | Caminho 


 a| 
provedor de armazenamento
 a| 
PEGAR
 a| 
`/storage-provider/file-shares`

`/storage-provider/file-shares/\{key}`

|===


[[add-file-shares]]
== Adicionar compartilhamentos de arquivos

Você pode usar o seguinte método para adicionar compartilhamentos de arquivos CIFS e NFS no seu SVM.  Você deve inserir os detalhes do compartilhamento de arquivos que deseja criar como parâmetros de entrada.  Você não pode usar esta API para adicionar volumes FlexGroup .

[cols="3*"]
|===
| Categoria | verbo HTTP | Caminho 


 a| 
provedor de armazenamento
 a| 
PUBLICAR
 a| 
`/storage-provider/file-shares`

|===
[NOTE]
====
Dependendo se os parâmetros da lista de controle de acesso (ACL) ou os parâmetros da política de exportação são fornecidos, compartilhamentos CIFS ou compartilhamentos de arquivos NFS são criados.  Se você não fornecer os valores para os parâmetros da ACL, os compartilhamentos CIFS não serão criados e os compartilhamentos NFS serão criados por padrão, fornecendo acesso a todos.

====
*Criando volumes de proteção de dados*: Quando você adiciona compartilhamentos de arquivos ao seu SVM, o tipo de volume que é montado, por padrão, é `rw` (leitura-escrita).  Para criar volumes de proteção de dados (DP), especifique `dp` como o valor para o `type` parâmetro.



[[delete-file-shares]]
== Excluir compartilhamentos de arquivos

Você pode usar o seguinte método para excluir um compartilhamento de arquivo específico.  Você precisa inserir a chave de compartilhamento de arquivos como um parâmetro de entrada para excluir um compartilhamento de arquivo específico.

[cols="3*"]
|===
| Categoria | verbo HTTP | Caminho 


 a| 
provedor de armazenamento
 a| 
EXCLUIR
 a| 
`/storage-provider/file-shares/\{key}`

|===


[[modify-file-shares]]
== Modificar compartilhamentos de arquivos

Você pode usar o seguinte método para modificar um compartilhamento de arquivos e atualizar suas propriedades.

Você precisa fornecer a chave de compartilhamento de arquivos para modificar um compartilhamento de arquivos específico.  Além disso, você precisa inserir o imóvel que deseja atualizar, juntamente com seu valor.

[NOTE]
====
Observe que você pode atualizar apenas uma propriedade em uma única invocação desta API.  Para múltiplas atualizações, você precisa executar esta API quantas vezes quiser.

====
[cols="3*"]
|===
| Categoria | verbo HTTP | Caminho 


 a| 
provedor de armazenamento
 a| 
CORREÇÃO
 a| 
`/storage-provider/file-shares/\{key}`

|===