---
permalink: api-automation/concept_get_started_with_um_apis.html 
sidebar: sidebar 
keywords: active iq, unified manager 
summary: O Active IQ Unified Manager fornece um conjunto de APIs para gerenciar seus recursos de armazenamento nos sistemas de armazenamento suportados por meio de uma interface de serviço web RESTful para qualquer integração de terceiros. 
---
= Comece a usar as APIs Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Active IQ Unified Manager fornece um conjunto de APIs para gerenciar seus recursos de armazenamento nos sistemas de armazenamento suportados por meio de uma interface de serviço web RESTful para qualquer integração de terceiros.

Nestes tópicos, você encontrará informações sobre APIs do Unified Manager, exemplos de fluxos de trabalho para resolver problemas específicos e alguns códigos de exemplo.  Usando essas informações, você pode criar clientes RESTful de soluções de software NetApp Manageability para gerenciar sistemas NetApp .  As APIs são baseadas no estilo arquitetônico Representational State Transfer (REST).  Todas as quatro operações REST Criar, Ler, Atualizar e Excluir (também conhecidas como CRUD) são suportadas.

Verlink:https://docs.netapp.com/us-en/netapp-automation/api/aiqum.html["Active IQ Unified Manager"^] para obter recursos adicionais e detalhes sobre os benefícios da API REST do Active IQ Unified Manager .
