---
permalink: api-automation/concept_manage_lun.html 
sidebar: sidebar 
keywords: manage, lun 
summary: Você pode usar a API /storage-provider/luns para visualizar, adicionar, modificar e excluir os LUNs no seu ambiente de data center. 
---
= Gerenciar LUNs usando APIs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `/storage-provider/luns` API para visualizar, adicionar, modificar e excluir LUNs no seu ambiente de data center.

Antes de provisionar os LUNs, certifique-se de que o SVM tenha sido criado e provisionado com os protocolos suportados.  Se você estiver atribuindo Níveis de Serviço de Desempenho (PSLs) ou Políticas de Eficiência de Armazenamento (SEPs), durante o provisionamento, os PSLs ou SEPs deverão ser criados antes de criar o LUN.



== Exibir LUNs

Você pode usar o seguinte método para visualizar os LUNs no seu ambiente do Unified Manager.  Quando você adiciona um cluster ONTAP como uma fonte de dados no Active IQ Unified Manager, as cargas de trabalho de armazenamento para esses clusters são adicionadas automaticamente à sua instância do Unified Manager.  Esta API recupera todos os LUNs automaticamente e os adiciona manualmente à sua instância do Unified Manager.  Você pode visualizar os detalhes de um LUN específico executando esta API com a chave LUN.

[cols="3*"]
|===
| Categoria | verbo HTTP | Caminho 


 a| 
provedor de armazenamento
 a| 
PEGAR
 a| 
`/storage-provider/luns`

`/storage-provider/luns/\{key}`

|===


== Adicionar LUNs

Você pode usar o seguinte método para adicionar LUNs às suas SVMs.

[cols="3*"]
|===
| Categoria | verbo HTTP | Caminho 


 a| 
provedor de armazenamento
 a| 
PUBLICAR
 a| 
`/storage-provider/luns`

|===
[NOTE]
====
Na sua solicitação cURL, se você fornecer um valor para o parâmetro opcional volume_name_tag na entrada, esse valor será usado ao nomear o volume durante a criação do LUN.  Esta tag permite pesquisar o volume facilmente.  Se você fornecer a chave de volume na solicitação, a marcação será ignorada.

====


== Excluir LUNs

Você pode usar o seguinte método para excluir um LUN específico.  Você precisa fornecer a chave LUN para excluir um LUN específico.

[NOTE]
====
Se você tiver criado um volume no ONTAP e então provisionado LUNs por meio do Unified Manager nesse volume, quando você excluir todos os LUNs usando esta API, o volume também será excluído do cluster ONTAP .

====
[cols="3*"]
|===
| Categoria | verbo HTTP | Caminho 


 a| 
provedor de armazenamento
 a| 
EXCLUIR
 a| 
`/storage-provider/luns/\{key}`

|===


== Modificar LUNs

Você pode usar o seguinte método para modificar um LUN e atualizar suas propriedades.  Você precisa fornecer a chave LUN para modificar um LUN específico.  Você também precisa inserir a propriedade LUN que deseja atualizar, juntamente com seu valor.  Para atualizar matrizes LUN usando esta API, você deve revisar as recomendações em "`Recomendações para usar as APIs`".

[NOTE]
====
Você pode atualizar apenas uma propriedade em uma única invocação desta API.  Para múltiplas atualizações, você precisa executar esta API quantas vezes quiser.

====
|===


| Categoria | verbo HTTP | Caminho 


 a| 
provedor de armazenamento
 a| 
CORREÇÃO
 a| 
`/storage-provider/luns/\{key}`

|===