---
permalink: api-automation/concept_metrics_apis.html 
sidebar: sidebar 
keywords: view, performance, metrics 
summary: O Active IQ Unified Manager fornece um conjunto de APIs na categoria /datacenter que permite visualizar os dados de desempenho dos seus clusters e objetos de armazenamento em um data center.  Essas APIs recuperam os dados de desempenho dos diferentes objetos de armazenamento, como clusters, nós, LUNs, volumes, agregados e VMs de armazenamento. 
---
= Visualizar métricas de desempenho usando APIs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Active IQ Unified Manager fornece um conjunto de APIs sob o `/datacenter` categoria que permite visualizar os dados de desempenho dos seus clusters e objetos de armazenamento em um data center.  Essas APIs recuperam os dados de desempenho de diferentes objetos de armazenamento, como clusters, nós, LUNs, volumes, agregados, VMs de armazenamento, interfaces FC, portas FC, portas Ethernet e interfaces IP.

O `/metrics` e `/analytics` As APIs fornecem diferentes visões das métricas de desempenho, usando as quais você pode detalhar diferentes níveis dos seguintes objetos de armazenamento no seu data center:

* aglomerados
* nós
* VMs de armazenamento
* agregados
* volumes
* LUNs
* Interfaces FC
* Portas FC
* Portas Ethernet
* Interfaces IP


A tabela a seguir faz uma comparação entre os `/metrics` e `/analytics` APIs com relação aos detalhes dos dados de desempenho recuperados.

[cols="2*"]
|===
| Métricas | Análise 


 a| 
Detalhes de desempenho para um único objeto.  Por exemplo, o `/datacenter/cluster/clusters/\{key}/metrics` A API exige que a chave do cluster seja inserida como parâmetro de caminho para recuperar as métricas desse cluster específico.
 a| 
Detalhes de desempenho para vários objetos do mesmo tipo em um data center.  Por exemplo, o `/datacenter/cluster/clusters/analytics` A API recupera as métricas coletivas de todos os clusters em um data center.



 a| 
Exemplo de métricas de desempenho para um objeto de armazenamento com base no parâmetro de intervalo de tempo para recuperação.
 a| 
O valor agregado de alto nível de desempenho para um determinado tipo de objeto de armazenamento por um determinado período (acima de 72 horas).



 a| 
Detalhes básicos do objeto são recuperados, como detalhes de um nó ou cluster.
 a| 
Nenhum detalhe específico é recuperado.



 a| 
Contadores acumulados, como mínimo, máximo, 95º percentil e valores médios de desempenho ao longo de um período de tempo, são recuperados para um único objeto, como contadores de leitura, gravação, total e outros.
 a| 
Um único valor agregado é exibido para todos os objetos do mesmo tipo.



 a| 
O intervalo de tempo e os dados de amostra são baseados no seguinte cronograma: O intervalo de tempo para os dados.  Exemplos podem ser 1h, 12h, 1d, 2d, 3d, 15d, 1s, 1m, 2m, 3m, 6m.  Você obtém amostras de 1 hora se o intervalo for maior que 3 dias (72 horas); caso contrário, são amostras de 5 minutos.  O período para cada intervalo de tempo é o seguinte:

* 1h: Métricas da hora mais recente amostradas em 5 minutos.
* 12h: Métricas das últimas 12 horas amostradas em 5 minutos.
* 1d: Métricas do dia mais recente amostradas ao longo de 5 minutos.
* 2d: Métricas dos últimos 2 dias amostradas ao longo de 5 minutos.
* 3d: Métricas dos últimos 3 dias amostradas em 5 minutos.
* 15d: Métricas dos últimos 15 dias amostradas em 1 hora.
* 1 semana: métricas da semana mais recente amostradas ao longo de 1 hora.
* 1m: Métricas do mês mais recente amostradas ao longo de 1 hora.
* 2m: Métricas dos últimos 2 meses amostradas ao longo de 1 hora.
* 3m: Métricas dos últimos 3 meses amostradas ao longo de 1 hora.
* 6m: Métricas dos últimos 6 meses amostradas ao longo de 1 hora.
+
Valores disponíveis: 1h, 12h, 1d, 2d, 3d, 15d, 1w, 1m, 2m, 3m, 6m

+
Valor padrão: 1h


 a| 
Acima de 72 horas.  A duração durante a qual esta amostra é calculada é representada no formato padrão ISO-8601.

|===


[[output-sample-for-metrics-apis]]
== Exemplo de saída para APIs de métricas

Por exemplo, o `/datacenter/cluster/nodes/\{key}/metrics` A API recupera os seguintes detalhes (entre outros) para um nó:


NOTE: O percentil 95 no valor resumido indica que 95% das amostras coletadas no período têm um valor de contador menor que o valor especificado como percentil 95.

[listing]
----
{
     "iops": {
       "local": {
         "other": 100.53,
         "read": 100.53,
         "total": 100.53,
         "write": 100.53
       },
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "latency": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "performance_capacity": {
       "available_iops_percent": 0,
       "free_percent": 0,
       "system_workload_percent": 0,
       "used_percent": 0,
       "user_workload_percent": 0
     },
     "throughput": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "timestamp": "2018-01-01T12:00:00-04:00",
     "utilization_percent": 0
   }
 ],
 "start_time": "2018-01-01T12:00:00-04:00",
 "summary": {
   "iops": {
     "local_iops": {
       "other": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "read": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "total": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "write": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       }
     },
----


[[output-sample-for-analytics-apis]]
== Exemplo de saída para APIs de análise

Por exemplo, o `/datacenter/cluster/nodes/analytics` A API recupera os seguintes valores (entre outros) para todos os nós:

[listing]
----
{     "iops": 1.7471,
     "latency": 60.0933,
     "throughput": 5548.4678,
     "utilization_percent": 4.8569,
     "period": 72,
     "performance_capacity": {
       "used_percent": 5.475,
       "available_iops_percent": 168350
     },
     "node": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "uuid": "95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "name": "ocum-infinity-01",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/nodes/37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a"
         }
       }
     },
     "cluster": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a",
       "uuid": "37387241-8b57-11e9-8974-00a098e0219a",
       "name": "ocum-infinity",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/clusters/37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a"
         },
     "_links": {
       "self": {
         "href": "/api/datacenter/cluster/nodes/analytics"
       }
     }
   },
----


[[list-of-the-available-apis]]
== Lista de APIs disponíveis

A tabela a seguir descreve o `/metrics` e `/analytics` APIs em detalhes.

[NOTE]
====
As métricas de IOPS e desempenho retornadas por essas APIs são valores duplos, por exemplo `100.53` .  Não há suporte para filtrar esses valores flutuantes pelos caracteres pipe (|) e curinga (*).

====
[cols="3*"]
|===
| Verbo HTTP | Caminho | Descrição 


 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/\{key}/metrics`
 a| 
Recupera dados de desempenho (amostra e resumo) para um cluster especificado pelo parâmetro de entrada da chave do cluster.  Informações como a chave do cluster e o UUID, intervalo de tempo, IOPS, taxa de transferência e número de amostras são retornadas.



 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/analytics`
 a| 
Recupera métricas de desempenho de alto nível para todos os clusters em um data center.  Você pode filtrar seus resultados com base nos critérios necessários.  Valores como IOPS agregado, taxa de transferência e período de coleta (em horas) são retornados.



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/\{key}/metrics`
 a| 
Recupera dados de desempenho (amostra e resumo) para um nó especificado pelo parâmetro de entrada da chave do nó.  Informações como o UUID do nó, intervalo de tempo, resumo do IOPS, taxa de transferência, latência e desempenho, número de amostras coletadas e porcentagem utilizada são retornadas.



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/analytics`
 a| 
Recupera métricas de desempenho de alto nível para todos os nós em um data center.  Você pode filtrar seus resultados com base nos critérios necessários.  Informações, como chaves de nó e cluster, e valores, como IOPS agregado, taxa de transferência e período de coleta (em horas) são retornados.



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/\{key}/metrics`
 a| 
Recupera dados de desempenho (amostra e resumo) para um agregado especificado pelo parâmetro de entrada da chave de agregação.  Informações como intervalo de tempo, resumo do IOPS, latência, taxa de transferência e capacidade de desempenho, número de amostras coletadas para cada contador e porcentagem utilizada são retornadas.



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/analytics`
 a| 
Recupera métricas de desempenho de alto nível para todos os agregados em um data center.  Você pode filtrar seus resultados com base nos critérios necessários.  Informações, como chaves agregadas e de cluster, e valores, como IOPS agregado, taxa de transferência e período de coleta (em horas) são retornados.



 a| 
`GET`
 a| 
`/datacenter/storage/luns/\{key}/metrics`

`/datacenter/storage/volumes/\{key}/metrics`
 a| 
Recupera dados de desempenho (amostra e resumo) para um LUN ou um compartilhamento de arquivo (volume) especificado pelo parâmetro de entrada do LUN ou da chave de volume.  Informações como o resumo do mínimo, máximo e média de IOPS de leitura, gravação e total, latência e taxa de transferência, além do número de amostras coletadas para cada contador, são retornadas.



 a| 
`GET`
 a| 
`/datacenter/storage/luns/analytics`

`/datacenter/storage/volumes/analytics`
 a| 
Recupera métricas de desempenho de alto nível para todos os LUNs ou volumes em um data center.  Você pode filtrar seus resultados com base nos critérios necessários.  Informações, como chaves de cluster e VM de armazenamento, e valores, como IOPS agregado, taxa de transferência e período de coleta (em horas) são retornados.



 a| 
`GET`
 a| 
`/datacenter/svm/svms/{key}/metrics`
 a| 
Recupera dados de desempenho (amostra e resumo) para uma VM de armazenamento especificada pelo parâmetro de entrada da chave da VM de armazenamento.  Resumo do IOPS com base em cada protocolo suportado, como `nvmf, fcp, iscsi,` e `nfs` , a taxa de transferência, a latência e o número de amostras coletadas são retornados.



 a| 
`GET`
 a| 
`/datacenter/svm/svms/analytics`
 a| 
Recupera métricas de desempenho de alto nível para todas as VMs de armazenamento em um data center.  Você pode filtrar seus resultados com base nos critérios necessários.  Informações como UUID da VM de armazenamento, IOPS agregados, latência, taxa de transferência e período de coleta (em horas) são retornadas.



 a| 
`GET`
 a| 
`/datacenter/network/ethernet/ports/{key}/metrics`
 a| 
Recupera as métricas de desempenho para uma porta Ethernet específica especificada pelo parâmetro de entrada da chave da porta.  Quando um intervalo (intervalo de tempo) é fornecido a partir do intervalo suportado, a API retorna os contadores acumulados, como valores mínimos, máximos e médios de desempenho ao longo do período de tempo.



 a| 
`GET`
 a| 
`/datacenter/network/ethernet/ports/analytics`
 a| 
Recupera as métricas de desempenho de alto nível para todas as portas Ethernet no seu ambiente de data center.  Informações como chave do cluster e do nó, UUID, taxa de transferência, período de coleta e porcentagem de utilização das portas são retornadas.  Você pode filtrar o resultado pelos parâmetros disponíveis, como chave de porta, porcentagem de utilização, nome do cluster e do nó, UUID e assim por diante.



 a| 
`GET`
 a| 
`/datacenter/network/fc/interfaces/{key}/metrics`
 a| 
Recupera as métricas de desempenho para uma interface FC de rede específica especificada pelo parâmetro de entrada da chave de interface.  Quando um intervalo (intervalo de tempo) é fornecido a partir do intervalo suportado, a API retorna os contadores acumulados, como valores mínimos, máximos e médios de desempenho ao longo do período de tempo.



 a| 
`GET`
 a| 
`/datacenter/network/fc/interfaces/analytics`
 a| 
Recupera as métricas de desempenho de alto nível para todas as portas Ethernet no seu ambiente de data center.  Informações como o cluster e a chave da interface FC e UUID, taxa de transferência, IOPS, latência e VM de armazenamento são retornadas.  Você pode filtrar o resultado pelos parâmetros disponíveis, como o nome e o UUID da interface do cluster e do FC, VM de armazenamento, taxa de transferência e assim por diante.



 a| 
`GET`
 a| 
`/datacenter/network/fc/ports/{key}/metrics`
 a| 
Recupera as métricas de desempenho para uma porta FC específica especificada pelo parâmetro de entrada da chave da porta.  Quando um intervalo (intervalo de tempo) é fornecido a partir do intervalo suportado, a API retorna os contadores acumulados, como valores mínimos, máximos e médios de desempenho ao longo do período de tempo.



 a| 
`GET`
 a| 
`/datacenter/network/fc/ports/analytics`
 a| 
Recupera as métricas de desempenho de alto nível para todas as portas FC no seu ambiente de data center.  Informações como chave do cluster e do nó, UUID, taxa de transferência, período de coleta e porcentagem de utilização das portas são retornadas.  Você pode filtrar o resultado pelos parâmetros disponíveis, como chave de porta, porcentagem de utilização, nome do cluster e do nó, UUID e assim por diante.



 a| 
`GET`
 a| 
`/datacenter/network/ip/interfaces/{key}/metrics`
 a| 
Recupera as métricas de desempenho para uma interface IP de rede, conforme especificado pelo parâmetro de entrada da chave da interface.  Quando um intervalo (intervalo de tempo) é fornecido a partir do intervalo suportado, a API retorna informações, como o número de amostras, contadores acumulados, taxa de transferência e o número de pacotes recebidos e transmitidos.



 a| 
`GET`
 a| 
`/datacenter/network/ip/interfaces/analytics`
 a| 
Recupera as métricas de desempenho de alto nível para todas as interfaces IP de rede no seu ambiente de data center.  Informações como o cluster e a chave da interface IP e UUID, taxa de transferência, IOPS e latência são retornadas.  Você pode filtrar o resultado pelos parâmetros disponíveis, como o nome do cluster e da interface IP, UUID, IOPS, latência, taxa de transferência e assim por diante.

|===