---
permalink: api-automation/concept_api_url_and_categories.html 
sidebar: sidebar 
keywords: active iq, unified manager, api, access, categories 
summary: As APIs do Active IQ Unified Manager permitem que você gerencie e provisione objetos de armazenamento em seu ambiente.  Você também pode acessar a interface da Web do Unified Manager para executar algumas dessas funções. 
---
= Acesso e categorias da API do Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
As APIs do Active IQ Unified Manager permitem que você gerencie e provisione objetos de armazenamento em seu ambiente.  Você também pode acessar a interface da Web do Unified Manager para executar algumas dessas funções.



== Construir uma URL para acessar diretamente as APIs REST

Você pode acessar as APIs REST diretamente por meio de uma linguagem de programação, como Python, C#, C{pp}, JavaScript e assim por diante.  Insira o nome do host ou endereço IP e a URL para acessar as APIs REST no formato

+https://<nome do host>/api+

[NOTE]
====
A porta padrão é 443. Você pode configurar a porta conforme exigido pelo seu ambiente.

====


== Acesse a página de documentação da API online

Você pode acessar a página de conteúdo de referência _Documentação da API_ que acompanha o produto para exibir a documentação da API, bem como emitir manualmente uma chamada de API (na interface, por exemplo, Swagger).  Você pode acessar esta documentação clicando em *Barra de Menu* > *Botão Ajuda* > *Documentação da API*

Como alternativa, insira o nome do host ou endereço IP e a URL para acessar a página da API REST no formato

+https://<nome do host>/docs/api/+



== Categorias

As chamadas de API são organizadas funcionalmente com base em áreas ou categorias.  Para localizar uma API específica, clique na categoria de API aplicável.

As APIs REST fornecidas com o Unified Manager ajudam você a executar funções administrativas, de monitoramento e provisionamento.  As APIs são agrupadas nas seguintes categorias.

* *centro de dados*
+
Esta categoria contém as APIs que ajudam você no gerenciamento e análise de armazenamento do datacenter usando ferramentas como Work Flow Automation e Ansible.  As APIs REST nesta categoria fornecem informações sobre clusters, nós, agregados, volumes, LUNs, compartilhamentos de arquivos, namespaces e outros elementos no seu data center.

* *servidor de gerenciamento*
+
As APIs na categoria *management-server* contêm o `jobs, system,` e `events` APIs.  Trabalhos são operações agendadas para execução assíncrona relacionadas ao gerenciamento de objetos de armazenamento ou cargas de trabalho no Unified Manager.  O `events` A API retorna eventos no seu data center e o `system` A API retorna os detalhes da instância do Unified Manager.

* *provedor de armazenamento*
+
Esta categoria contém todas as APIs de provisionamento necessárias para gerenciar e provisionar compartilhamentos de arquivos, LUNs, níveis de serviço de desempenho e políticas de eficiência de armazenamento.  As APIs também permitem que você configure pontos de extremidade de acesso, diretórios ativos, bem como atribua níveis de serviço de desempenho e políticas de eficiência de armazenamento em cargas de trabalho de armazenamento.

* *administração*
+
Esta categoria contém as APIs usadas para executar tarefas administrativas, como manter configurações de backup, visualizar certificados de armazenamento confiável para as fontes de dados do Unified Manager e gerenciar clusters ONTAP como fontes de dados para o Unified Manager.

* *portal*
+
O Unified Manager permite que você invoque APIs REST do ONTAP por meio das APIs na categoria gateway e gerencie os objetos de armazenamento no seu data center.

* *segurança*
+
Esta categoria contém APIs para gerenciar usuários do Unified Manager.


