---
permalink: api-automation/concept_data_center_apis.html 
sidebar: sidebar 
keywords: manage, storage, objects, data center 
summary: As APIs REST na categoria datacenter permitem que você gerencie os objetos de armazenamento no seu datacenter, como clusters, nós, agregados, VMs de armazenamento, volumes, LUNs, compartilhamentos de arquivos e namespaces.  Essas APIs estão disponíveis para consultar a configuração dos objetos, enquanto algumas delas permitem que você execute as operações de adicionar, excluir ou modificar esses objetos. 
---
= Gerenciar objetos de armazenamento em um data center usando APIs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As APIs REST sob o `datacenter` A categoria permite que você gerencie os objetos de armazenamento no seu data center, como clusters, nós, agregados, VMs de armazenamento, volumes, LUNs, compartilhamentos de arquivos e namespaces.  Essas APIs estão disponíveis para consultar a configuração dos objetos, enquanto algumas delas permitem que você execute as operações de adicionar, excluir ou modificar esses objetos.

A maioria dessas APIs são chamadas GET que fornecem agregação entre clusters com suporte para filtragem, classificação e paginação.  Ao executar essas APIs, elas retornam dados do banco de dados.  Portanto, os objetos recém-criados precisam ser descobertos pelo próximo ciclo de aquisição para aparecerem na resposta.

Se quiser consultar os detalhes de um objeto específico, você precisa inserir o ID exclusivo desse objeto para visualizar seus detalhes.  Por exemplo, para obter informações de métricas e análises dos objetos de armazenamento, consultelink:concept_metrics_apis.html["Visualizando métricas de desempenho"] .

[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
[NOTE]
====
Os comandos CURL, exemplos, solicitações e respostas às APIs estão disponíveis na sua interface de API do Swagger.  Você pode filtrar e ordenar os resultados por parâmetros específicos, conforme indicado no Swagger.  Essas APIs permitem filtrar os resultados para objetos de armazenamento específicos, como cluster, volume ou VM de armazenamento.

====


[[apis-for-storage-objects-in-your-data-center]]
== APIs para objetos de armazenamento em seu data center

[cols="3*"]
|===
| verbo HTTP | Caminho | Descrição 


 a| 
`GET`
 a| 
`/datacenter/cluster/clusters`

`/datacenter/cluster/clusters/\{key}`
 a| 
Você pode usar este método para visualizar os detalhes dos clusters ONTAP no data center.  A API retorna informações, como o endereço IPv4 ou IPv6 do cluster, informações sobre o nó, como integridade do nó, capacidade de desempenho e par de alta disponibilidade (HA), e indica se o cluster é All SAN Array.



 a| 
`GET`
 a| 
`/datacenter/cluster/licensing/licenses /datacenter/cluster/licensing/licenses/\{key}`
 a| 
Retorna os detalhes das licenças instaladas nos clusters do seu data center.  Você pode filtrar seus resultados com base nos critérios necessários.  Informações como chave de licença, chave de cluster, data de expiração e escopo da licença são retornadas.  Você pode inserir uma chave de licença para recuperar os detalhes de uma licença específica.



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes`

`/datacenter/cluster/nodes/\{key}`
 a| 
Você pode usar este método para visualizar os detalhes dos nós no data center.  Você pode visualizar informações sobre o cluster, a integridade do nó, a capacidade de desempenho e o par de alta disponibilidade (HA) do nó.



 a| 
`GET`
 a| 
`/datacenter/protocols/cifs/shares`

`/datacenter/protocols/cifs/shares/\{key}`
 a| 
Você pode usar este método para visualizar os detalhes dos compartilhamentos CIFS no data center.  Além dos detalhes do cluster, SVM e volume, informações sobre a Lista de Controle de Acesso (ACL) também são retornadas.



 a| 
`GET`
 a| 
`/datacenter/protocols/nfs/export-policies`

`/datacenter/protocols/nfs/export-policies/\{key}`
 a| 
Você pode usar este método para visualizar os detalhes das políticas de exportação para os serviços NFS suportados.

Você pode consultar as políticas de exportação de um cluster ou VM de armazenamento e reutilizar a chave da política de exportação para provisionar compartilhamentos de arquivos NFS.  Para obter mais informações sobre como atribuir e reutilizar políticas de exportação em cargas de trabalho, consulte "`Provisionando compartilhamentos de arquivos CIFS e NFS`".



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates`

`/datacenter/storage/aggregates/\{key}`
 a| 
Você pode usar esse método para visualizar a coleção de agregados no data center ou um agregado específico para provisionar cargas de trabalho neles ou monitorar.  Informações como detalhes do cluster e do nó, capacidade de desempenho usada, espaço disponível e usado e eficiência de armazenamento são retornadas.



 a| 
`GET`
 a| 
`/datacenter/storage/luns`

`/datacenter/storage/luns/\{key}`
 a| 
Você pode usar este método para visualizar a coleção de LUNs em todo o data center.  Você pode visualizar informações sobre o LUN, como detalhes do cluster e do SVM, políticas de QoS e igroups.



 a| 
`GET`
 a| 
`/datacenter/storage/qos/policies`

`/datacenter/storage/qos/policies/\{key}`
 a| 
Você pode usar este método para visualizar os detalhes de todas as políticas de QoS aplicáveis aos objetos de armazenamento no data center.  Informações como detalhes do cluster e do SVM, detalhes da política fixa ou adaptável e número de objetos aplicáveis a essa política são retornadas.



 a| 
`GET`
 a| 
`/datacenter/storage/qtrees`

`/datacenter/storage/qtrees/\{key}`
 a| 
Você pode usar este método para visualizar os detalhes do qtree no data center para todos os volumes FlexVol ou FlexGroup .  Informações como detalhes do cluster e do SVM, FlexVol volume e política de exportação são retornadas.



 a| 
`GET`
 a| 
`/datacenter/storage/volumes`

`/datacenter/storage/volumes/{key}`
 a| 
Você pode usar este método para visualizar a coleção de volumes no data center.  Informações sobre os volumes, como detalhes do SVM e do cluster, QoS e políticas de exportação, e se o volume é do tipo leitura-gravação, proteção de dados ou compartilhamento de carga, são retornadas.

Para volumes FlexVol e FlexClone , você pode visualizar as informações sobre os respectivos agregados.  Para um volume FlexGroup , a consulta retorna a lista de agregados constituintes.



 a| 
`GET`

`POST`

`DELETE`

`PATCH`
 a| 
`/datacenter/protocols/san/igroups`

`/datacenter/protocols/san/igroups/{key}`
 a| 
Você pode atribuir grupos iniciadores (igroups) autorizados a acessar destinos LUN específicos.  Se houver um igroup existente, você poderá atribuí-lo.  Você também pode criar igroups e atribuí-los aos LUNs.

Você pode usar esses métodos para consultar, criar, excluir e modificar igroups, respectivamente.

Pontos a serem observados:

* `POST:`Ao criar um igroup, você pode designar a VM de armazenamento à qual deseja atribuir acesso.
* `DELETE:`Você precisa fornecer a chave igroup como um parâmetro de entrada para excluir um igroup específico.  Se você já atribuiu um igroup a um LUN, não poderá excluir esse igroup.
* `PATCH:`Você precisa fornecer a chave igroup como um parâmetro de entrada para modificar um igroup específico.  Você também deve inserir o imóvel que deseja atualizar, juntamente com seu valor.




 a| 
`GET`

`POST`

`DELETE`

`PATCH`
 a| 
`/datacenter/svm/svms`

`/datacenter/svm/svms/\{key}`
 a| 
Você pode usar esses métodos para visualizar, criar, excluir e modificar Máquinas Virtuais de Armazenamento (VMs de armazenamento).

* `POST:`Você deve inserir o objeto de VM de armazenamento que deseja criar como um parâmetro de entrada.  Você pode criar uma VM de armazenamento personalizada e, em seguida, atribuir as propriedades necessárias a ela.
* `DELETE:`Você precisa fornecer a chave da VM de armazenamento para excluir uma VM de armazenamento específica.
* `PATCH:`Você precisa fornecer a chave da VM de armazenamento para modificar uma VM de armazenamento específica.  Você também precisa inserir as propriedades que deseja atualizar, juntamente com seus valores.


|===

NOTE: Pontos a serem observados:

Se você tiver habilitado o provisionamento de carga de trabalho baseado em SLO em seu ambiente, ao criar a VM de armazenamento, certifique-se de que ela ofereça suporte a todos os protocolos necessários para provisionar LUNs e compartilhamentos de arquivos nelas, por exemplo, CIFS ou SMB, NFS, FCP e iSCSI.  Os fluxos de trabalho de provisionamento podem falhar se a VM de armazenamento não oferecer suporte aos serviços necessários.  É recomendável que os serviços para os respectivos tipos de cargas de trabalho também sejam habilitados na VM de armazenamento.

Se você tiver habilitado o provisionamento de carga de trabalho baseado em SLO em seu ambiente, não poderá excluir a VM de armazenamento na qual as cargas de trabalho de armazenamento foram provisionadas.  Quando você exclui uma VM de armazenamento na qual um servidor CIFS ou SMB foi configurado, esta API também exclui o servidor CIFS ou SMB, juntamente com a configuração local do Active Directory.  No entanto, o nome do servidor CIFS ou SMB continua na configuração do Active Directory que você deve excluir manualmente do servidor do Active Directory.



[[apis-for-network-elements-in-your-data-center]]
== APIs para elementos de rede em seu data center

As seguintes APIs na categoria datacenter recuperam informações sobre as portas e interfaces de rede em seu ambiente, especificamente as portas FC, interfaces FC, portas Ethernet e interfaces IP.

[cols="3*"]
|===
| verbo HTTP | Caminho | Descrição 


 a| 
`GET`
 a| 
`/datacenter/network/ethernet/ports`

`/datacenter/network/ethernet/ports/{key}`
 a| 
Recupera informações sobre todas as portas Ethernet no seu ambiente de data center.  Com uma chave de porta como parâmetro de entrada, você pode visualizar as informações dessa porta específica.  Informações, como detalhes do cluster, domínio de transmissão, detalhes da porta, como estado, velocidade e tipo, e se a porta está habilitada, são recuperadas.



 a| 
`GET`
 a| 
`/datacenter/network/fc/interfaces`

`/datacenter/network/fc/interfaces/{key}`
 a| 
Você pode usar este método para visualizar os detalhes das interfaces FC no seu ambiente de data center.  Com uma chave de interface como parâmetro de entrada, você pode visualizar as informações dessa interface específica.  Informações, como detalhes do cluster, detalhes do nó inicial e detalhes da porta inicial, são recuperadas.



 a| 
`GET`
 a| 
`/datacenter/network/fc/ports`

`/datacenter/network/fc/ports/{key}`
 a| 
Recupera informações sobre todas as portas FC usadas nos nós do seu ambiente de data center.  Com uma chave de porta como parâmetro de entrada, você pode visualizar as informações dessa porta específica.  Informações como detalhes do cluster, descrição da porta, protocolo suportado e estado da porta são recuperadas.



 a| 
`GET`
 a| 
`/datacenter/network/ip/interfaces`

`/datacenter/network/ip/interfaces/{key}`
 a| 
Você pode usar este método para visualizar os detalhes das interfaces IP no seu ambiente de data center.  Com uma chave de interface como parâmetro de entrada, você pode visualizar as informações dessa interface específica.  Informações como detalhes do cluster, detalhes do IPspace, detalhes do nó inicial e se o failover está habilitado são recuperadas.

|===