---
permalink: api-automation/concept_view_workloads.html 
sidebar: sidebar 
keywords: view, storage, workloads 
summary: 'As APIs listadas aqui permitem que você visualize uma lista consolidada de cargas de trabalho de armazenamento para todos os clusters ONTAP no seu data center.  As APIs também fornecem uma visão resumida do número de cargas de trabalho de armazenamento provisionadas no seu ambiente do Active IQ Unified Manager e suas estatísticas de capacidade e desempenho (IOPS).' 
---
= Visualize cargas de trabalho de armazenamento usando APIs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As APIs listadas aqui permitem que você visualize uma lista consolidada de cargas de trabalho de armazenamento para todos os clusters ONTAP no seu data center.  As APIs também fornecem uma visão resumida do número de cargas de trabalho de armazenamento provisionadas no seu ambiente do Active IQ Unified Manager e suas estatísticas de capacidade e desempenho (IOPS).



[[view-storage-workloads]]
== Exibir cargas de trabalho de armazenamento

Você pode usar o método a seguir para visualizar todas as cargas de trabalho de armazenamento em todos os clusters do seu data center.  Para obter informações sobre como filtrar a resposta com base em colunas específicas, consulte a documentação de referência da API disponível na sua instância do Unified Manager.

[cols="3*"]
|===
| Categoria | verbo HTTP | Caminho 


 a| 
provedor de armazenamento
 a| 
PEGAR
 a| 
`/storage-provider/workloads`

|===


[[view-storage-workloads-summary]]
== Exibir resumo das cargas de trabalho de armazenamento

Você pode usar o método a seguir para avaliar a capacidade usada, a capacidade disponível, o IOPS usado, o IOPS disponível e o número de cargas de trabalho de armazenamento gerenciadas por cada Nível de Serviço de Desempenho.  As cargas de trabalho de armazenamento exibidas podem ser para qualquer LUN, compartilhamento de arquivos NFS ou compartilhamento CIFS.  A API fornece uma visão geral das cargas de trabalho de armazenamento, uma visão geral das cargas de trabalho de armazenamento provisionadas pelo Unified Manager, uma visão geral do data center, uma visão geral do espaço total, usado e disponível e IOPS no data center, em termos dos Níveis de Serviço de Desempenho atribuídos.  As informações recebidas em resposta a esta API são usadas para preencher o painel na interface do usuário do Unified Manager.

[cols="3*"]
|===
| Categoria | verbo HTTP | Caminho 


 a| 
provedor de armazenamento
 a| 
PEGAR
 a| 
`/storage-provider/workloads-summary`

|===