---
permalink: api-automation/reference_authentication_errors.html 
sidebar: sidebar 
keywords: http, status, code, active iq, unified manager 
summary: Ao executar as APIs ou solucionar problemas, você deve estar ciente dos vários códigos de status HTTP e códigos de erro usados ​​pelas APIs do Active IQ Unified Manager . 
---
= Códigos de status HTTP usados ​​no Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao executar as APIs ou solucionar problemas, você deve estar ciente dos vários códigos de status HTTP e códigos de erro usados ​​pelas APIs do Active IQ Unified Manager .

A tabela a seguir lista os códigos de erro relacionados à autenticação:

[cols="3*"]
|===
| Código de status HTTP | Título do código de status | Descrição 


 a| 
200
 a| 
OK
 a| 
Retornado na execução bem-sucedida de chamadas de API síncronas.



 a| 
201
 a| 
Criado
 a| 
Criação de novos recursos por chamadas síncronas, como configuração do Active Directory.



 a| 
202
 a| 
Aceito
 a| 
Retornado na execução bem-sucedida de chamadas assíncronas para funções de provisionamento, como criação de LUNs e compartilhamentos de arquivos.



 a| 
400
 a| 
Solicitação inválida
 a| 
Indica falha na validação de entrada.  O usuário precisa corrigir as entradas, por exemplo, chaves válidas no corpo de uma solicitação.



 a| 
401
 a| 
Solicitação não autorizada
 a| 
Você não está autorizado a visualizar o recurso/Não autorizado.



 a| 
403
 a| 
Pedido proibido
 a| 
O acesso ao recurso que você estava tentando acessar é proibido.



 a| 
404
 a| 
Recurso não encontrado
 a| 
O recurso que você estava tentando acessar não foi encontrado.



 a| 
405
 a| 
Método não permitido
 a| 
Método não permitido.



 a| 
429
 a| 
Muitas solicitações
 a| 
Retornado quando o usuário envia muitas solicitações em um período específico.



 a| 
500
 a| 
Erro do Servidor Interno
 a| 
Erro do Servidor Interno.  Falha ao obter resposta do servidor.  Este erro interno do servidor pode ou não ser permanente.  Por exemplo, se você executar um `GET` ou `GET ALL` operação e receber esse erro, é recomendável repetir essa operação por no mínimo cinco tentativas.  Se for um erro permanente, o código de status retornado continua sendo 500.  Se a operação for bem-sucedida, o código de status retornado será 200.

|===