---
permalink: api-automation/reference_recommendations_to_use_um_apis.html 
sidebar: sidebar 
keywords: recommendations, apis, active iq, unified, manager 
summary: Ao usar as APIs no Active IQ Unified Manager, você deve seguir determinadas práticas recomendadas. 
---
= Recomendações para usar as APIs do Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao usar as APIs no Active IQ Unified Manager, você deve seguir determinadas práticas recomendadas.

* Todo tipo de conteúdo de resposta deve estar no seguinte formato para uma execução válida:
+
[listing]
----
application/json
----
* O número da versão da API não está relacionado ao número da versão do produto.  Você deve usar a versão mais recente da API disponível para sua instância do Unified Manager.  Para obter mais informações sobre as versões da API do Unified Manager, consulte a seção "`Versão da API REST no Active IQ Unified Manager`".
* Ao atualizar valores de matriz usando uma API do Unified Manager, você deve atualizar toda a sequência de valores.  Não é possível anexar valores a uma matriz.  Você só pode substituir uma matriz existente.
* Você pode usar operadores de filtro, como pipe (|) e curinga (+*+) para todos os parâmetros de consulta, exceto para valores duplos, por exemplo, IOPS e desempenho nas APIs de métricas.
* Evite consultar objetos usando uma combinação dos operadores de filtro curinga (+*+) e barra vertical (|).  Ele pode recuperar um número incorreto de objetos.
* Ao usar valores para filtro, certifique-se de que o valor não contenha nenhum `?` personagem.  Isso é para mitigar riscos de injeção de SQL.
* Note que o `GET` (todas) as solicitações de qualquer API retornam no máximo 1000 registros.  Mesmo que você execute a consulta definindo o `max_records` parâmetro para um valor maior que 1000, apenas 1000 registros serão retornados.
* Para executar funções administrativas, é recomendável usar a interface do usuário do Unified Manager.

