---
permalink: reporting/concept_schedule_reports.html 
sidebar: sidebar 
keywords: scheduling, reports 
summary: Depois de ter uma exibição que deseja reutilizar e compartilhar como um relatório, você pode agendá-la usando o Active IQ Unified Manager.  Você pode gerenciar relatórios agendados, alterando os destinatários e a frequência de distribuição para cada agendamento de relatório. 
---
= Agendar relatórios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de ter uma exibição que deseja reutilizar e compartilhar como um relatório, você pode agendá-la usando o Active IQ Unified Manager.  Você pode gerenciar relatórios agendados, alterando os destinatários e a frequência de distribuição para cada agendamento de relatório.

Você pode agendar a maioria das visualizações ou páginas de inventário no Unified Manager.  As exceções são eventos, que são relatórios que você pode baixar como arquivos CSV, mas não pode agendar eventos para regeneração e compartilhamento.  Você também não pode baixar ou agendar os painéis, favoritos ou páginas de configuração.

A partir do Active IQ Unified Manager 9.8, você pode baixar visualizações no formato Microsoft® Excel e personalizá-las.  Você pode usar recursos avançados do Excel, como classificações complexas, filtros em camadas, tabelas dinâmicas e gráficos.  Quando estiver satisfeito com o relatório do Excel resultante, você pode carregar o arquivo do Excel para uso sempre que o relatório for agendado e compartilhado.

Você pode agendar as visualizações integradas ou as visualizações que você personalizar.  Você pode escolher qual tipo de arquivo enviar: CSV, PDF ou XSLX.  Ao agendar um relatório pela primeira vez, você pode baixá-lo e se definir como o único destinatário a vê-lo, assim como seus destinatários o verão.
