---
permalink: reporting/concept_report_access_points.html 
sidebar: sidebar 
keywords: access, points, generating, reports 
summary: Você pode reunir informações no Unified Manager sobre seus clusters para criar relatórios da interface do usuário, consultas ao banco de dados MySQL e APIs REST. 
---
= Pontos de acesso para geração de relatórios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode reunir informações no Unified Manager sobre seus clusters para criar relatórios da interface do usuário, consultas ao banco de dados MySQL e APIs REST.

Estas seções descrevem os relatórios e o agendamento do Unified Manager por meio da interface do usuário.

Há três maneiras de acessar os recursos de relatórios fornecidos pelo Unified Manager:

* Extraindo dados diretamente das páginas de inventário na interface do usuário.
* Usando Open Database Connectivity (ODBC) e ferramentas ODBC para acessar todos os objetos disponíveis.
* Executando APIs REST do Unified Manager para retornar as informações que você deseja revisar.


Estas seções descrevem os relatórios e o agendamento do Unified Manager por meio da interface do usuário.
