---
permalink: reporting/concept_unified_manager_reporting.html 
sidebar: sidebar 
keywords: unified, manager, reporting 
summary: 'O Active IQ Unified Manager (antigo OnCommand Unified Manager) oferece a capacidade de visualizar, personalizar, baixar e agendar relatórios para seus sistemas de armazenamento ONTAP .  Os relatórios podem fornecer detalhes sobre a capacidade, integridade, desempenho e relacionamentos de proteção do sistema de armazenamento.' 
---
= Relatórios do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Active IQ Unified Manager (antigo OnCommand Unified Manager) oferece a capacidade de visualizar, personalizar, baixar e agendar relatórios para seus sistemas de armazenamento ONTAP .  Os relatórios podem fornecer detalhes sobre a capacidade, integridade, desempenho, segurança e relacionamentos de proteção do sistema de armazenamento.

A nova funcionalidade de relatórios e agendamento do Unified Manager introduzida no Active IQ Unified Manager 9.6 substitui o mecanismo de relatórios anterior que foi descontinuado na versão 9.5 do Unified Manager.

Os relatórios fornecem diferentes visões da sua rede, oferecendo inteligência acionável sobre capacidade, integridade, desempenho, segurança e dados de proteção.  Você pode personalizar suas visualizações mostrando, ocultando e reorganizando colunas, filtrando dados, classificando dados e pesquisando os resultados.  Você pode salvar visualizações personalizadas para reutilização, baixá-las como relatórios e programá-las como relatórios recorrentes para distribuir por e-mail.

Você pode baixar visualizações no formato Microsoft® Excel e personalizá-las.  Você pode usar recursos avançados do Excel, como classificações complexas, filtros em camadas, tabelas dinâmicas e gráficos.  Quando estiver satisfeito com o relatório do Excel resultante, você pode carregar o arquivo do Excel para uso sempre que o relatório for agendado e compartilhado.

Além de gerar relatórios da interface do usuário, você pode extrair dados de integridade, segurança e desempenho do Unified Manager usando estes métodos adicionais:

* Usando Open Database Connectivity (ODBC) e ferramentas ODBC para acessar diretamente o banco de dados para obter informações do cluster
* Executando APIs REST do Unified Manager para retornar as informações que você está interessado em revisar


A partir desta versão do Active IQ Unified Manager, os seguintes aprimoramentos foram feitos nos relatórios:

* Um e-mail é enviado para um relatório conforme o cronograma configurado.  Mesmo quando você gera um relatório sob demanda, você receberá um e-mail.
* O nome do arquivo do relatório e os metadados do relatório incluem o nome do host de onde o relatório foi gerado.  Mesmo que alguém altere o nome do arquivo, você ainda poderá identificar o nome do host de onde o relatório foi gerado devido a esse aprimoramento.

