---
permalink: reporting/reference_reporting_limitations.html 
sidebar: sidebar 
keywords: reporting, limitations 
summary: Há algumas limitações na nova funcionalidade de relatórios do Active IQ Unified Manager das quais você deve estar ciente. 
---
= Limitações de relatórios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Há algumas limitações na nova funcionalidade de relatórios do Active IQ Unified Manager das quais você deve estar ciente.



[[existing-reports-from-previous-versions-of-unified-manager]]
== Relatórios existentes de versões anteriores do Unified Manager

Você só pode editar o agendamento e os destinatários de relatórios existentes que foram criados e importados (como arquivos .rptdesign) no Unified Manager 9.5 e versões anteriores.  Se você personalizou qualquer um dos relatórios padrão fornecidos com o Unified Manager 9.5 ou anterior, esses relatórios personalizados não serão importados para a nova ferramenta de relatórios.

Se você precisar editar relatórios existentes importados de arquivos .rptdesign, siga um destes procedimentos e remova o relatório importado:

* crie uma nova visualização e agende um relatório a partir dessa visualização (preferencial)
* passe o mouse sobre o relatório, copie o SQL e extraia os dados usando uma ferramenta externa


As visualizações padrão podem ser geradas como relatórios sem a necessidade de qualquer personalização.  Você pode usar a nova solução de relatórios para recriar quaisquer relatórios personalizados.



[[schedule-and-report-relationship]]
== Relacionamento entre agendamento e relatório

Você pode criar muitos agendamentos diferentes com qualquer combinação de destinatários para cada relatório salvo.  No entanto, você não pode reutilizar o agendamento para vários relatórios.



[[report-protection]]
== Proteção de relatórios

Qualquer usuário com as permissões apropriadas pode editar ou excluir relatórios.  Não há como impedir que outros usuários removam ou façam alterações em visualizações ou programações salvas.



[[event-reports]]
== Relatórios de eventos

Embora você possa personalizar a visualização do evento e baixar o relatório resultante no formato CSV, não é possível agendar relatórios de eventos recorrentes para geração e distribuição.



[[report-attachments]]
== Anexos de relatórios

Relatórios não podem ser enviados no corpo de um e-mail.  Em vez disso, os relatórios são enviados apenas como anexos em PDF, Excel ou CSV.
