---
permalink: performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html 
sidebar: sidebar 
keywords: managing, performance, performance, capacity, available, iops, information 
summary: A capacidade de desempenho indica quanta produtividade você pode obter de um recurso sem ultrapassar o desempenho útil desse recurso.  Quando visualizada usando contadores de desempenho existentes, a capacidade de desempenho é o ponto em que você obtém a utilização máxima de um nó ou agregado antes que a latência se torne um problema. 
---
= Gerencie o desempenho usando a capacidade de desempenho e as informações de IOPS disponíveis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
_Capacidade de desempenho_ indica quanta produtividade você pode obter de um recurso sem ultrapassar o desempenho útil desse recurso.  Quando visualizada usando contadores de desempenho existentes, a capacidade de desempenho é o ponto em que você obtém a utilização máxima de um nó ou agregado antes que a latência se torne um problema.

O Unified Manager coleta estatísticas de capacidade de desempenho de nós e agregados em cada cluster.  _Capacidade de desempenho utilizada_ é a porcentagem da capacidade de desempenho que está sendo usada atualmente, e _capacidade de desempenho livre_ é a porcentagem da capacidade de desempenho que ainda está disponível.

Enquanto a capacidade de desempenho livre fornece uma porcentagem do recurso que ainda está disponível, _IOPS disponível_ informa o número de IOPS que podem ser adicionados ao recurso antes de atingir a capacidade máxima de desempenho.  Ao usar essa métrica, você pode ter certeza de que pode adicionar cargas de trabalho de um número predeterminado de IOPS a um recurso.

Monitorar as informações de capacidade de desempenho tem os seguintes benefícios:

* Auxilia no provisionamento e balanceamento do fluxo de trabalho.
* Ajuda a evitar a sobrecarga de um nó ou o uso excessivo de seus recursos além do ponto ideal, reduzindo assim a necessidade de solução de problemas.
* Ajuda você a determinar com maior precisão onde equipamentos de armazenamento adicionais podem ser necessários.

