---
permalink: performance-checker/concept_unified_manager_performance_monitoring_features.html 
sidebar: sidebar 
keywords: unified manager, performance, monitoring, features 
summary: O Unified Manager coleta e analisa estatísticas de desempenho de sistemas que executam o software ONTAP .  Ele usa limites de desempenho dinâmicos e limites de desempenho definidos pelo usuário para monitorar uma variedade de contadores de desempenho em muitos componentes do cluster. 
---
= Recursos de monitoramento de desempenho do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Unified Manager coleta e analisa estatísticas de desempenho de sistemas que executam o software ONTAP .  Ele usa limites de desempenho dinâmicos e limites de desempenho definidos pelo usuário para monitorar uma variedade de contadores de desempenho em muitos componentes do cluster.

Um alto tempo de resposta (latência) indica que o objeto de armazenamento, por exemplo, um volume, está com desempenho mais lento que o normal.  Esse problema também indica que o desempenho diminuiu para aplicativos clientes que estão usando o volume.  O Unified Manager identifica o componente de armazenamento onde está o problema de desempenho e fornece uma lista de ações sugeridas que você pode tomar para resolver o problema.

O Unified Manager inclui os seguintes recursos:

* Monitora e analisa estatísticas de desempenho da carga de trabalho de um sistema que executa o software ONTAP .
* Rastreia contadores de desempenho para clusters, nós, agregados, portas, SVMs, volumes, LUNs, namespaces NVMe e interfaces de rede (LIFs).
* Exibe gráficos detalhados que mostram a atividade da carga de trabalho ao longo do tempo, incluindo IOPS (operações), MB/s (taxa de transferência), latência (tempo de resposta), utilização, capacidade de desempenho e taxa de cache.
* Permite que você crie políticas de limite de desempenho definidas pelo usuário que acionam eventos e enviam alertas por e-mail quando os limites são violados.
* Usa limites definidos pelo sistema e limites de desempenho dinâmicos que aprendem sobre sua atividade de carga de trabalho para identificar e alertá-lo sobre problemas de desempenho.
* Identifica as políticas de qualidade de serviço (QoS) e as políticas de nível de serviço de desempenho (PSLs) que são aplicadas aos seus volumes e LUNs.
* Identifica claramente o componente do cluster que está em disputa.
* Identifica cargas de trabalho que estão usando excessivamente os componentes do cluster e as cargas de trabalho cujo desempenho é afetado pelo aumento da atividade.

