---
permalink: performance-checker/concept_what_expected_range_of_performance_is.html 
sidebar: sidebar 
keywords: expected, range, performance, latency, forecast, formed 
summary: A previsão de latência é uma previsão de quais são os valores máximos e mínimos de desempenho esperados em um momento específico.  Para a latência da carga de trabalho, os valores superiores formam o limite de desempenho.  Quando o valor real ultrapassa o limite de desempenho, o Unified Manager aciona um evento de desempenho dinâmico. 
---
= Qual é a faixa de desempenho esperada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A previsão de latência é uma previsão de quais são os valores máximos e mínimos de desempenho esperados em um momento específico.  Para a latência da carga de trabalho, os valores superiores formam o limite de desempenho.  Quando o valor real ultrapassa o limite de desempenho, o Unified Manager aciona um evento de desempenho dinâmico.

Por exemplo, durante o horário comercial normal, entre 9h e 17h, a maioria dos funcionários pode verificar seus e-mails entre 9h e 10h30. O aumento da demanda nos servidores de e-mail significa um aumento na atividade de carga de trabalho no armazenamento de back-end durante esse período.  Os funcionários podem notar um tempo de resposta lento de seus clientes de e-mail.

Durante o horário de almoço, entre 12h e 13h, e no final do dia de trabalho, após as 17h, a maioria dos funcionários provavelmente está longe de seus computadores.  A demanda nos servidores de e-mail normalmente diminui, diminuindo também a demanda no armazenamento de back-end.  Como alternativa, pode haver operações de carga de trabalho agendadas, como backups de armazenamento ou verificação de vírus, que começam depois das 17h e aumentam a atividade no armazenamento de back-end.

Ao longo de vários dias, o aumento e a diminuição na atividade da carga de trabalho determinam o intervalo esperado (previsão de latência) da atividade, com limites superior e inferior para uma carga de trabalho.  Quando a atividade de carga de trabalho real de um objeto está fora dos limites superiores ou inferiores e permanece fora dos limites por um período de tempo, isso pode indicar que o objeto está sendo usado em excesso ou em falta.



== Como a previsão de latência é formada

O Unified Manager deve coletar no mínimo 3 dias de atividade de carga de trabalho antes de poder iniciar sua análise e antes que a previsão de latência para o tempo de resposta de E/S possa ser exibida na GUI.  A coleta mínima de dados necessária não leva em conta todas as mudanças que ocorrem na atividade da carga de trabalho.  Após coletar os primeiros 3 dias de atividade, o Unified Manager ajusta a previsão de latência a cada 24 horas às 00:00 para refletir as alterações na atividade da carga de trabalho e estabelecer um limite de desempenho dinâmico mais preciso.

[NOTE]
====
O horário de verão (DST) altera a hora do sistema, o que altera a previsão de latência das estatísticas de desempenho para cargas de trabalho monitoradas.  O Unified Manager começa imediatamente a corrigir a previsão de latência, o que leva aproximadamente 15 dias para ser concluído.  Durante esse período, você pode continuar a usar o Unified Manager, mas, como o Unified Manager usa a previsão de latência para detectar eventos dinâmicos, alguns eventos podem não ser precisos.  Eventos detectados antes da mudança de horário não são afetados.

====