---
permalink: performance-checker/concept_roles_of_workloads_involved_in_performance_incident.html 
sidebar: sidebar 
keywords: roles, workloads, involved, performance, event 
summary: O Unified Manager usa funções para identificar o envolvimento de uma carga de trabalho em um evento de desempenho.  Os papéis incluem vítimas, valentões e tubarões.  Uma carga de trabalho definida pelo usuário pode ser uma vítima, um agressor e um tubarão ao mesmo tempo. 
---
= Funções das cargas de trabalho envolvidas em um evento de desempenho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Unified Manager usa funções para identificar o envolvimento de uma carga de trabalho em um evento de desempenho.  Os papéis incluem vítimas, valentões e tubarões.  Uma carga de trabalho definida pelo usuário pode ser uma vítima, um agressor e um tubarão ao mesmo tempo.

|===
| Papel | Descrição 


 a| 
Vítima
 a| 
Uma carga de trabalho definida pelo usuário cujo desempenho diminuiu devido a outras cargas de trabalho, chamadas de bullies, que estão usando excessivamente um componente do cluster.  Somente cargas de trabalho definidas pelo usuário são identificadas como vítimas.  O Unified Manager identifica as cargas de trabalho das vítimas com base no desvio de latência, onde a latência real, durante um evento, aumentou muito em relação à previsão de latência (intervalo esperado).



 a| 
Valentão
 a| 
Uma carga de trabalho definida pelo usuário ou pelo sistema cujo uso excessivo de um componente do cluster fez com que o desempenho de outras cargas de trabalho, chamadas vítimas, diminuísse.  O Unified Manager identifica cargas de trabalho agressivas com base no desvio no uso de um componente do cluster, onde o uso real, durante um evento, aumentou muito em relação ao intervalo de uso esperado.



 a| 
Tubarão
 a| 
Uma carga de trabalho definida pelo usuário com o maior uso de um componente de cluster em comparação com todas as cargas de trabalho envolvidas em um evento.  O Unified Manager identifica cargas de trabalho tubarões com base no uso de um componente de cluster durante um evento.

|===
As cargas de trabalho em um cluster podem compartilhar muitos dos componentes do cluster, como agregados e a CPU para processamento de rede e dados.  Quando uma carga de trabalho, como um volume, aumenta o uso de um componente de cluster a ponto de o componente não conseguir atender às demandas de carga de trabalho com eficiência, o componente está em contenção.  A carga de trabalho que utiliza excessivamente um componente do cluster é um problema.  As outras cargas de trabalho que compartilham esses componentes e cujo desempenho é afetado pelo agressor são as vítimas.  Atividades de cargas de trabalho definidas pelo sistema, como desduplicação ou cópias de instantâneos, também podem evoluir para "bullying".

Quando o Unified Manager detecta um evento, ele identifica todas as cargas de trabalho e componentes de cluster envolvidos, incluindo as cargas de trabalho agressivas que causaram o evento, o componente de cluster que está em contenção e as cargas de trabalho vítimas cujo desempenho diminuiu devido ao aumento da atividade das cargas de trabalho agressivas.

[NOTE]
====
Se o Unified Manager não conseguir identificar as cargas de trabalho agressivas, ele alertará apenas sobre as cargas de trabalho das vítimas e o componente do cluster envolvido.

====
O Unified Manager pode identificar cargas de trabalho que são vítimas de cargas de trabalho de intimidação e também identificar quando essas mesmas cargas de trabalho se tornam cargas de trabalho de intimidação.  Uma carga de trabalho pode ser um agressor para si mesma.  Por exemplo, uma carga de trabalho de alto desempenho que está sendo limitada por um limite de grupo de políticas faz com que todas as cargas de trabalho no grupo de políticas sejam limitadas, incluindo ela mesma.  Uma carga de trabalho que é um agressor ou uma vítima em um evento de desempenho em andamento pode mudar sua função ou não ser mais um participante do evento.
