---
permalink: performance-checker/concept_understand_events_from_adaptive_qos_policies.html 
sidebar: sidebar 
keywords: understand, events, adaptive, qos, policies, defined, block, size 
summary: Os grupos de políticas de QoS adaptáveis ​​dimensionam automaticamente um teto ou piso de taxa de transferência com base no tamanho do volume, mantendo a proporção de IOPS para TBs conforme o tamanho do volume muda.  A partir do ONTAP 9.5, você pode especificar o tamanho do bloco na política de QoS para aplicar efetivamente um limite de MB/s ao mesmo tempo. 
---
= Entenda eventos de políticas de QoS adaptáveis que têm um tamanho de bloco definido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os grupos de políticas de QoS adaptáveis ​​dimensionam automaticamente um teto ou piso de taxa de transferência com base no tamanho do volume, mantendo a proporção de IOPS para TBs conforme o tamanho do volume muda.  A partir do ONTAP 9.5, você pode especificar o tamanho do bloco na política de QoS para aplicar efetivamente um limite de MB/s ao mesmo tempo.

Atribuir um limite de IOPS em uma política de QoS adaptável impõe um limite apenas ao número de operações que ocorrem em cada carga de trabalho.  Dependendo do tamanho do bloco definido no cliente que gera as cargas de trabalho, alguns IOPS incluem muito mais dados e, portanto, colocam uma carga muito maior nos nós que processam as operações.

O valor MB/s para uma carga de trabalho é gerado usando a seguinte fórmula:

[listing]
----
MB/s = (IOPS * Block Size) / 1000
----
Se uma carga de trabalho tiver uma média de 3.000 IOPS e o tamanho do bloco no cliente estiver definido como 32 KB, o MB/s efetivo para essa carga de trabalho será 96.  Se essa mesma carga de trabalho tiver uma média de 3.000 IOPS e o tamanho do bloco no cliente estiver definido como 48 KB, então o MB/s efetivo para essa carga de trabalho será 144.  Você pode ver que o nó está processando 50% mais dados quando o tamanho do bloco é maior.

Vejamos a seguinte política de QoS adaptável que tem um tamanho de bloco definido e como os eventos são acionados com base no tamanho de bloco definido no cliente.

Crie uma política e defina o pico de transferência para 2.500 IOPS/TB com um tamanho de bloco de 32 KB.  Isso efetivamente define o limite de MB/s para 80 MB/s ((2500 IOPS * 32 KB) / 1000) para um volume com capacidade utilizada de 1 TB.  Observe que o Unified Manager gera um evento de aviso quando o valor da taxa de transferência é 10% menor que o limite definido.  Os eventos são gerados nas seguintes situações:

|===
| Capacidade Utilizada 2+| O evento é gerado quando a taxa de transferência excede esse número de ... 


|  | IOPS | MB/s 


 a| 
1 TB
 a| 
2.250 IOPS
 a| 
72 MB/s



 a| 
2 TB
 a| 
4.500 IOPS
 a| 
144 MB/s



 a| 
5 TB
 a| 
11.250 IOPS
 a| 
360 MB/s

|===
Se o volume estiver usando 2 TB do espaço disponível, o IOPS for 4.000 e o tamanho do bloco de QoS estiver definido como 32 KB no cliente, a taxa de transferência de MB/ps será de 128 MB/s ((4.000 IOPS * 32 KB) / 1.000).  Nenhum evento é gerado neste cenário porque 4.000 IOPS e 128 MB/s estão abaixo do limite para um volume que está usando 2 TB de espaço.

Se o volume estiver usando 2 TB do espaço disponível, o IOPS for 4.000 e o tamanho do bloco de QoS estiver definido como 64 KB no cliente, a taxa de transferência de MB/s será de 256 MB/s ((4.000 IOPS * 64 KB) / 1.000).  Neste caso, os 4.000 IOPS não geram um evento, mas o valor de MB/s de 256 MB/s está acima do limite de 144 MB/s e um evento é gerado.

Por esse motivo, quando um evento é acionado com base em uma violação de MB/s para uma política de QoS adaptável que inclui o tamanho do bloco, um gráfico de MB/s é exibido na seção Diagnóstico do Sistema da página Detalhes do Evento.  Se o evento for acionado com base em uma violação de IOPS para a política de QoS adaptável, um gráfico de IOPS será exibido na seção Diagnóstico do Sistema.  Se ocorrer uma violação tanto para IOPS quanto para MB/s, você receberá dois eventos.

Para obter mais informações sobre como ajustar as configurações de QoS, consulte https://docs.netapp.com/us-en/ontap/performance-admin/index.html["Visão geral da gestão de desempenho"] .
