---
permalink: performance-checker/concept_analyze_events_from_system_defined_performance_thresholds.html 
sidebar: sidebar 
keywords: analyze, events, system-defined, performance, thresholds 
summary: Eventos gerados a partir de limites de desempenho definidos pelo sistema indicam que um contador de desempenho, ou conjunto de contadores de desempenho, para um determinado objeto de armazenamento ultrapassou o limite de uma política definida pelo sistema.  Isso indica que o objeto de armazenamento, por exemplo, um agregado ou nó, está enfrentando um problema de desempenho. 
---
= Analisar eventos a partir de limites de desempenho definidos pelo sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eventos gerados a partir de limites de desempenho definidos pelo sistema indicam que um contador de desempenho, ou conjunto de contadores de desempenho, para um determinado objeto de armazenamento ultrapassou o limite de uma política definida pelo sistema.  Isso indica que o objeto de armazenamento, por exemplo, um agregado ou nó, está enfrentando um problema de desempenho.

Use a página Detalhes do evento para analisar o evento de desempenho e tomar medidas corretivas, se necessário, para retornar o desempenho ao normal.

[NOTE]
====
As políticas de limite definidas pelo sistema não estão habilitadas nos sistemas Cloud Volumes ONTAP, ONTAP Edge ou ONTAP Select .

====