---
permalink: performance-checker/concept_understand_performance_panels_on_dashboard.html 
sidebar: sidebar 
keywords: understand, performance, panels, dashboard 
summary: O Painel do Gerenciador Unificado fornece alguns painéis que exibem o status de desempenho de alto nível para todos os clusters que estão sendo monitorados em seu ambiente.  Você pode escolher visualizar o status de todos os clusters ou de um cluster individual. 
---
= Entenda os painéis de desempenho no Dashboard
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Painel do Gerenciador Unificado fornece alguns painéis que exibem o status de desempenho de alto nível para todos os clusters que estão sendo monitorados em seu ambiente.  Você pode escolher visualizar o status de todos os clusters ou de um cluster individual.

Além de mostrar informações de desempenho, a maioria dos painéis também exibe o número de eventos ativos naquela categoria e o número de novos eventos adicionados nas últimas 24 horas.  Essas informações ajudam você a decidir quais clusters você pode precisar analisar mais detalhadamente para resolver os eventos relatados.  Clicar nos eventos exibe os principais eventos e fornece um link para a página de inventário do Gerenciamento de Eventos filtrada para mostrar os eventos naquela categoria.

Os painéis a seguir fornecem o status de desempenho.

* *Painel de Capacidade de Desempenho*
+
Ao visualizar todos os clusters, este painel exibe o valor da capacidade de desempenho de cada cluster (média da última hora) e o número de dias até que a capacidade de desempenho atinja o limite superior (com base na taxa de crescimento diária).  Clicar no gráfico de barras leva você para a página de inventário de nós daquele cluster.  Observe que a página de inventário de nós exibe a capacidade de desempenho média das últimas 72 horas, portanto, esse valor pode não corresponder ao valor do Painel.

+
Ao visualizar um único cluster, este painel exibe a capacidade de desempenho do cluster, o IOPS total e os valores de taxa de transferência total.

* *Painel de carga de trabalho IOPS*
+
Quando o gerenciamento ativo da carga de trabalho está habilitado e ao visualizar um único cluster, este painel exibe o número total de cargas de trabalho que estão sendo executadas em um determinado intervalo de IOPS.

* *Painel de desempenho da carga de trabalho*
+
Quando o gerenciamento ativo da carga de trabalho está habilitado, este painel exibe o número total de cargas de trabalho em conformidade e não em conformidade atribuídas a cada Nível de Serviço de Desempenho definido.  Clicar em um gráfico de barras leva você às cargas de trabalho atribuídas a essa política na página Cargas de trabalho.

* *Painel de Visão Geral de Uso*
+
Ao visualizar todos os clusters, você pode optar por visualizá-los classificados pelo maior IOPS ou taxa de transferência (MB/s).

+
Ao visualizar um único cluster, você pode optar por visualizar as cargas de trabalho nesse cluster classificadas pelo maior IOPS ou taxa de transferência (MB/s).


