---
permalink: performance-checker/concept_performance_threshold_policies_when_object_is_moved.html 
sidebar: sidebar 
keywords: happens, performance, threshold, policies, object, moved 
summary: Como as políticas de limite de desempenho são atribuídas a objetos de armazenamento, se você mover um objeto, todas as políticas de limite atribuídas permanecerão anexadas ao objeto após a conclusão da movimentação.  Por exemplo, se você mover um volume ou LUN para um agregado diferente, as políticas de limite ainda estarão ativas para o volume ou LUN no novo agregado. 
---
= O que acontece com as políticas de limite de desempenho quando um objeto é movido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como as políticas de limite de desempenho são atribuídas a objetos de armazenamento, se você mover um objeto, todas as políticas de limite atribuídas permanecerão anexadas ao objeto após a conclusão da movimentação.  Por exemplo, se você mover um volume ou LUN para um agregado diferente, as políticas de limite ainda estarão ativas para o volume ou LUN no novo agregado.

Se existir uma condição de contador secundário para a política de limite (uma política de combinação) — por exemplo, se uma condição adicional for atribuída a um agregado ou nó — a condição de contador secundário será aplicada ao novo agregado ou nó para o qual o volume ou LUN foi movido.

Se houver novos eventos ativos para objetos que estejam usando a política de limite alterada, os eventos serão marcados como obsoletos e a política de limite começará a monitorar o contador como uma política de limite recém-definida.

Uma operação de movimentação de volume faz com que o ONTAP envie um evento de alteração informativa.  Um ícone de evento de alteração aparece na linha do tempo Eventos na página Performance Explorer e na página Análise de carga de trabalho para indicar o horário em que a operação de movimentação foi concluída.

[NOTE]
====
Se você mover um objeto para um cluster diferente, a política de limite definida pelo usuário será removida do objeto.  Se necessário, você deve atribuir uma política de limite ao objeto após a conclusão da operação de movimentação.  No entanto, políticas de limite dinâmicas e definidas pelo sistema são aplicadas automaticamente a um objeto depois que ele é movido para um novo cluster.

====


[[threshold-policy-functionality-during-ha-takeover-and-giveback]]
== Funcionalidade de política de limite durante aquisição e devolução de HA

Quando uma operação de aquisição ou devolução ocorre em uma configuração de alta disponibilidade (HA), os objetos que são movidos de um nó para outro mantêm suas políticas de limite da mesma maneira que nas operações de movimentação manual.  Como o Unified Manager verifica se há alterações na configuração do cluster a cada 15 minutos, o impacto da alternância para o novo nó não é identificado até a próxima pesquisa da configuração do cluster.

[NOTE]
====
Se uma operação de aquisição e devolução ocorrer dentro do período de coleta de alterações de configuração de 15 minutos, talvez você não veja as estatísticas de desempenho passarem de um nó para o outro.

====


[[threshold-policy-functionality-during-aggregate-relocation]]
== Funcionalidade de política de limite durante a realocação de agregados

Se você mover um agregado de um nó para outro usando o `aggregate relocation start` comando, as políticas de limite simples e combinadas são mantidas em todos os objetos, e a parte do nó da política de limite é aplicada ao novo nó.



[[threshold-policy-functionality-during-metrocluster-switchover]]
== Funcionalidade de política de limite durante a troca do MetroCluster

Objetos que são movidos de um cluster para outro em uma configuração MetroCluster não mantêm suas configurações de política de limite definidas pelo usuário.  Se necessário, você pode aplicar políticas de limite nos volumes e LUNs que foram movidos para o cluster de parceiros.  Depois que um objeto retorna ao seu cluster original, a política de limite definida pelo usuário é reaplicada automaticamente.

Para obter informações, consultelink:../storage-mgmt/concept_volume_behavior_during_switchover_and_switchback.html["Comportamento do volume durante a comutação e o retorno"] .
