---
permalink: performance-checker/concept_how_storage_qos_can_control_workload_throughput.html 
sidebar: sidebar 
keywords: storage, qos, control, workload, throughput 
summary: 'Você pode criar um grupo de políticas de Qualidade de Serviço (QoS) para controlar o limite de E/S por segundo (IOPS) ou de taxa de transferência (MB/s) para as cargas de trabalho que ele contém.  Se as cargas de trabalho estiverem em um grupo de políticas sem limite definido, como o grupo de políticas padrão, ou se o limite definido não atender às suas necessidades, você poderá aumentar o limite ou mover as cargas de trabalho para um grupo de políticas novo ou existente que tenha o limite desejado.' 
---
= Como o QoS de armazenamento pode controlar a taxa de transferência da carga de trabalho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar um grupo de políticas de Qualidade de Serviço (QoS) para controlar o limite de E/S por segundo (IOPS) ou de taxa de transferência (MB/s) para as cargas de trabalho que ele contém.  Se as cargas de trabalho estiverem em um grupo de políticas sem limite definido, como o grupo de políticas padrão, ou se o limite definido não atender às suas necessidades, você poderá aumentar o limite ou mover as cargas de trabalho para um grupo de políticas novo ou existente que tenha o limite desejado.

Grupos de políticas de QoS "tradicionais" podem ser atribuídos a cargas de trabalho individuais; por exemplo, um único volume ou LUN.  Nesse caso, a carga de trabalho pode usar o limite de taxa de transferência total.  Grupos de políticas de QoS também podem ser atribuídos a várias cargas de trabalho; nesse caso, o limite de taxa de transferência é "`compartilhado`" entre as cargas de trabalho.  Por exemplo, um limite de QoS de 9.000 IOPS atribuído a três cargas de trabalho restringiria o IOPS combinado de exceder 9.000 IOPS.

Grupos de políticas de QoS "adaptáveis" também podem ser atribuídos a cargas de trabalho individuais ou a múltiplas cargas de trabalho.  No entanto, mesmo quando atribuída a várias cargas de trabalho, cada carga de trabalho obtém o limite de taxa de transferência total em vez de compartilhar o valor de taxa de transferência com outras cargas de trabalho.  Além disso, as políticas de QoS adaptáveis ajustam automaticamente a configuração de taxa de transferência com base no tamanho do volume, por carga de trabalho, mantendo assim a proporção de IOPS para terabytes conforme o tamanho do volume muda.  Por exemplo, se o pico for definido como 5.000 IOPS/TB em uma política de QoS adaptável, um volume de 10 TB terá uma taxa de transferência máxima de 50.000 IOPS.  Se o volume for redimensionado posteriormente para 20 TB, o QoS adaptável ajustará o máximo para 100.000 IOPS.

A partir do ONTAP 9.5, você pode incluir o tamanho do bloco ao definir uma política de QoS adaptável.  Isso efetivamente converte a política de um limite de IOPS/TB para um limite de MB/s para casos em que as cargas de trabalho estão usando tamanhos de bloco muito grandes e, por fim, usando uma grande porcentagem de taxa de transferência.

Para políticas de QoS de grupo compartilhado, quando o IOPS ou MB/s de todas as cargas de trabalho em um grupo de políticas excede o limite definido, o grupo de políticas limita as cargas de trabalho para restringir sua atividade, o que pode diminuir o desempenho de todas as cargas de trabalho no grupo de políticas.  Se um evento de desempenho dinâmico for gerado pela limitação do grupo de políticas, a descrição do evento exibirá o nome do grupo de políticas envolvido.

Na exibição Desempenho: Todos os volumes, você pode classificar os volumes afetados por IOPS e MB/s para ver quais cargas de trabalho têm o maior uso que pode ter contribuído para o evento.  Na página Performance/Volumes Explorer, você pode selecionar outros volumes ou LUNs no volume para comparar com o uso de throughput de IOPS ou MBps da carga de trabalho afetada.

Ao atribuir as cargas de trabalho que estão usando excessivamente os recursos do nó a uma configuração de grupo de políticas mais restritiva, o grupo de políticas limita as cargas de trabalho para restringir sua atividade, o que pode reduzir o uso dos recursos naquele nó.  No entanto, se você quiser que a carga de trabalho possa usar mais recursos do nó, você pode aumentar o valor do grupo de políticas.

Você pode usar o System Manager, os comandos ONTAP ou os Níveis de Serviço de Desempenho do Unified Manager para gerenciar grupos de políticas, incluindo as seguintes tarefas:

* Criando um grupo de políticas
* Adicionar ou remover cargas de trabalho em um grupo de políticas
* Movendo uma carga de trabalho entre grupos de políticas
* Alterando o limite de taxa de transferência de um grupo de políticas
* Mover uma carga de trabalho para um agregado e/ou nó diferente

