---
permalink: performance-checker/concept_performance_incident_analysis_for_metrocluster_configuration.html 
sidebar: sidebar 
keywords: performance, event, analysis, metrocluster, configuration 
summary: Você pode usar o Unified Manager para analisar um evento de desempenho para uma configuração do MetroCluster .  Você pode identificar as cargas de trabalho envolvidas no evento e revisar as ações sugeridas para resolvê-lo. 
---
= Análise de eventos de desempenho para uma configuração do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o Unified Manager para analisar um evento de desempenho para uma configuração do MetroCluster .  Você pode identificar as cargas de trabalho envolvidas no evento e revisar as ações sugeridas para resolvê-lo.

Os eventos de desempenho do MetroCluster podem ser devido a cargas de trabalho _bully_ que estão utilizando excessivamente os links de interconexão (ISLs) entre os clusters ou devido a problemas de integridade do link.  O Unified Manager monitora cada cluster em uma configuração do MetroCluster de forma independente, sem considerar eventos de desempenho em um cluster parceiro.

Os eventos de desempenho de ambos os clusters na configuração do MetroCluster também são exibidos na página do Painel do Unified Manager.  Você também pode visualizar as páginas de integridade do Unified Manager para verificar a integridade de cada cluster e visualizar seu relacionamento.
