---
permalink: performance-checker/concept_metrocluster_configuration_health_check.html 
sidebar: sidebar 
keywords: metrocluster, configuration, health, check 
summary: Você pode usar o Unified Manager para revisar a integridade dos clusters em uma configuração do MetroCluster .  O status de integridade e os eventos ajudam a determinar se há problemas de hardware ou software que podem estar afetando o desempenho de suas cargas de trabalho. 
---
= Verificação de integridade da configuração do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o Unified Manager para revisar a integridade dos clusters em uma configuração do MetroCluster por IP ou FC.  O status de integridade e os eventos ajudam a determinar se há problemas de hardware ou software que podem estar afetando o desempenho de suas cargas de trabalho.

Se você configurar o Unified Manager para enviar alertas por e-mail, poderá verificar seu e-mail em busca de quaisquer problemas de integridade no cluster local ou remoto que possam ter contribuído para um evento de desempenho.  Na GUI do Unified Manager, você pode selecionar *Gerenciamento de Eventos* para ver uma lista de eventos atuais e, em seguida, usar os filtros para exibir somente eventos de configuração do MetroCluster .

Para mais informações, consultelink:../health-checker/task_check_health_of_clusters_in_metrocluster_configuration.html["Verificando a integridade dos clusters em uma configuração MetroCluster"]
