---
permalink: performance-checker/concept_collect_data_and_monitor_workload_performance.html 
sidebar: sidebar 
keywords: collect, data, monitor, workload, performance 
summary: O Unified Manager coleta e analisa a atividade da carga de trabalho a cada 5 minutos para identificar eventos de desempenho e detecta alterações de configuração a cada 15 minutos.  Ele retém no máximo 30 dias de dados históricos de desempenho e eventos de 5 minutos e usa esses dados para prever o intervalo de latência esperado para todas as cargas de trabalho monitoradas. 
---
= Coletar dados e monitorar o desempenho da carga de trabalho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Unified Manager coleta e analisa a atividade da carga de trabalho a cada 5 minutos para identificar eventos de desempenho e detecta alterações de configuração a cada 15 minutos.  Ele retém no máximo 30 dias de dados históricos de desempenho e eventos de 5 minutos e usa esses dados para prever o intervalo de latência esperado para todas as cargas de trabalho monitoradas.

O Unified Manager deve coletar no mínimo 3 dias de atividade de carga de trabalho antes de poder iniciar sua análise e antes que a previsão de latência para o tempo de resposta de E/S possa ser exibida na página Análise de Carga de Trabalho e na página Detalhes do Evento.  Enquanto essa atividade está sendo coletada, a previsão de latência não exibe todas as alterações que ocorrem na atividade da carga de trabalho.  Após coletar 3 dias de atividade, o Unified Manager ajusta a previsão de latência a cada 24 horas às 00:00, para refletir as alterações na atividade da carga de trabalho e estabelecer um limite de desempenho dinâmico mais preciso.

Durante os primeiros 4 dias em que o Unified Manager estiver monitorando uma carga de trabalho, se mais de 24 horas tiverem se passado desde a última coleta de dados, os gráficos de latência não exibirão a previsão de latência para essa carga de trabalho.  Os eventos detectados antes da última coleta ainda estão disponíveis.

[NOTE]
====
O horário de verão (DST) altera a hora do sistema, o que altera a previsão de latência das estatísticas de desempenho para cargas de trabalho monitoradas.  O Unified Manager começa imediatamente a corrigir a previsão de latência, o que leva aproximadamente 15 dias para ser concluído.  Durante esse período, você pode continuar a usar o Unified Manager, mas, como o Unified Manager usa a previsão de latência para detectar eventos dinâmicos, alguns eventos podem não ser precisos.  Eventos detectados antes da mudança de horário não são afetados.

====