---
permalink: performance-checker/concept_add_disks_and_reallocate_data.html 
sidebar: sidebar 
keywords: add, disks, reallocate, data 
summary: Você pode adicionar discos a um agregado para aumentar a capacidade de armazenamento e o desempenho desse agregado.  Depois de adicionar os discos, você verá uma melhoria no desempenho de leitura somente após realocar os dados entre os discos adicionados. 
---
= Adicionar discos e realocar dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar discos a um agregado para aumentar a capacidade de armazenamento e o desempenho desse agregado.  Depois de adicionar os discos, você verá uma melhoria no desempenho de leitura somente após realocar os dados entre os discos adicionados.

Você pode usar estas instruções quando o Unified Manager receber eventos agregados acionados por limites dinâmicos ou por limites de desempenho definidos pelo sistema:

* Quando você recebe um evento de limite dinâmico, na página Detalhes do evento, o ícone do componente do cluster que representa o agregado em contenção é destacado em vermelho.
+
Abaixo do ícone, entre parênteses, está o nome do agregado, que identifica o agregado ao qual você pode adicionar discos.

* Quando você recebe um evento de limite definido pelo sistema, na página Detalhes do evento, o texto da descrição do evento lista o nome do agregado que está apresentando o problema.
+
Você pode adicionar discos e realocar dados neste agregado.



Os discos que você adiciona ao agregado já devem existir no cluster.  Se o cluster não tiver discos extras disponíveis, talvez seja necessário entrar em contato com o administrador ou comprar mais discos.  Você pode usar o ONTAP System Manager ou os comandos ONTAP para adicionar discos a um agregado.

[NOTE]
====
Você deve realocar dados somente ao usar agregados de HDD e Flash Pool.  Não realoque dados em agregados SSD ou FabricPool .

====