---
permalink: performance-checker/concept_counter_charts_zoom_view.html 
sidebar: sidebar 
keywords: counter, charts, zoom, view 
summary: Os gráficos de contador fornecem uma visualização de zoom que permite que você amplie os detalhes de desempenho ao longo do período de tempo especificado.  Isso permite que você veja detalhes de desempenho e eventos com granularidade muito maior, o que é benéfico ao solucionar problemas de desempenho. 
---
= Visualização de zoom de gráficos de contador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os gráficos de contador fornecem uma visualização de zoom que permite que você amplie os detalhes de desempenho ao longo do período de tempo especificado.  Isso permite que você veja detalhes de desempenho e eventos com granularidade muito maior, o que é benéfico ao solucionar problemas de desempenho.

Quando exibidos na Visualização de Zoom, alguns gráficos de detalhamento fornecem informações adicionais do que aquelas que aparecem quando o gráfico não está na Visualização de Zoom.  Por exemplo, as páginas de exibição de zoom do gráfico de detalhamento de IOPS, IOPS/TB e MBps exibem valores de política de QoS para volumes e LUNs, se eles tiverem sido definidos no ONTAP.

[NOTE]
====
Para políticas de limite de desempenho definidas pelo sistema, somente as políticas "`Recursos do nó superutilizados`" e "`Limite de taxa de transferência de QoS violado`" estão disponíveis na lista *Políticas*.  As outras políticas de limite definidas pelo sistema não estão disponíveis no momento.

====