---
permalink: performance-checker/concept_use_performance_capacity_used_counter.html 
sidebar: sidebar 
keywords: performance, capacity, counter, manage, performance 
summary: Normalmente, as organizações desejam operar com uma porcentagem de capacidade de desempenho utilizada abaixo de 100 para que os recursos sejam usados de forma eficiente, ao mesmo tempo em que reservam alguma capacidade de desempenho adicional para dar suporte às demandas dos períodos de pico.  Você pode usar políticas de limite para personalizar quando os alertas são enviados para valores de alta capacidade de desempenho utilizados. 
---
= Use o contador de capacidade de desempenho usado para gerenciar o desempenho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Normalmente, as organizações desejam operar com uma porcentagem de capacidade de desempenho utilizada abaixo de 100 para que os recursos sejam usados de forma eficiente, ao mesmo tempo em que reservam alguma capacidade de desempenho adicional para dar suporte às demandas dos períodos de pico.  Você pode usar políticas de limite para personalizar quando os alertas são enviados para valores de alta capacidade de desempenho utilizados.

Você pode estabelecer metas específicas com base em seus requisitos de desempenho.  Por exemplo, empresas de serviços financeiros podem reservar mais capacidade de desempenho para garantir a execução oportuna das negociações.  Essas empresas podem querer definir limites de capacidade de desempenho usados na faixa de 70-80 por cento.  Empresas de manufatura com margens menores podem optar por reservar menos capacidade de desempenho se estiverem dispostas a arriscar o desempenho para gerenciar melhor os custos de TI.  Essas empresas podem definir limites de capacidade de desempenho utilizados na faixa de 85-95 por cento.

Quando o valor da capacidade de desempenho usada excede a porcentagem definida em uma política de limite definida pelo usuário, o Unified Manager envia um e-mail de alerta e adiciona o evento à página Inventário de Eventos.  Isso permite que você gerencie problemas potenciais antes que eles afetem o desempenho.  Esses eventos também podem ser usados como indicadores de que você precisa fazer movimentações e alterações na carga de trabalho em seus nós e agregados.
