---
permalink: performance-checker/concept_review_impact_of_configuration_changes.html 
sidebar: sidebar 
keywords: review, impact, configuration, changes, workload, performance 
summary: Alterações de configuração no cluster, como falha de disco, failover de HA ou movimentação de volume, podem afetar negativamente o desempenho do volume e causar aumento de latência. 
---
= Analise o impacto das alterações de configuração no desempenho da carga de trabalho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alterações de configuração no cluster, como falha de disco, failover de HA ou movimentação de volume, podem afetar negativamente o desempenho do volume e causar aumento de latência.

No Unified Manager, você pode revisar a página Análise de carga de trabalho para ver quando ocorreu uma alteração de configuração recente e compará-la com as operações e a latência (tempo de resposta) para ver se houve uma alteração na atividade da carga de trabalho do volume selecionado.

As páginas de desempenho do Unified Manager só podem detectar um número limitado de eventos de alteração.  As páginas de saúde fornecem alertas para outros eventos causados por alterações de configuração.  Você pode pesquisar o volume no Unified Manager para ver o histórico de eventos.
