---
permalink: performance-checker/concept_understand_root_object.html 
sidebar: sidebar 
keywords: understand, root, object 
summary: O objeto raiz é a linha de base com a qual outras comparações de objetos são feitas.  Isso permite que você visualize e compare os dados de outros objetos com o objeto raiz, fornecendo análise de dados de desempenho que ajuda a solucionar problemas e melhorar o desempenho do objeto. 
---
= Entenda o objeto raiz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O objeto raiz é a linha de base com a qual outras comparações de objetos são feitas.  Isso permite que você visualize e compare os dados de outros objetos com o objeto raiz, fornecendo análise de dados de desempenho que ajuda a solucionar problemas e melhorar o desempenho do objeto.

O nome do objeto raiz é exibido na parte superior do painel Comparação.  Objetos adicionais são exibidos abaixo do objeto raiz.  Embora não haja limite para o número de objetos adicionais que você pode adicionar ao painel Comparação, somente um objeto raiz é permitido.  Os dados do objeto raiz são exibidos automaticamente nos gráficos no painel Gráficos do Contador.

Não é possível alterar o objeto raiz; ele é sempre definido como a página do objeto que você está visualizando.  Por exemplo, se você abrir a página Volume Performance Explorer do Volume1, o Volume1 será o objeto raiz e não poderá ser alterado.  Se quiser comparar com um objeto raiz diferente, você deve clicar no link de um objeto e abrir sua página de destino.

[NOTE]
====
Eventos e Limites são exibidos somente para objetos raiz.

====