---
permalink: performance-checker/reference_how_enabling_flash_cache_improve_workload_performance.html 
sidebar: sidebar 
keywords: enabling, flash cache, node, improve, workload, performance 
summary: Você pode melhorar o desempenho da carga de trabalho habilitando o cache de dados inteligente do Flash Cache™ em cada nó do cluster. 
---
= Como habilitar o Flash Cache em um nó pode melhorar o desempenho da carga de trabalho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode melhorar o desempenho da carga de trabalho habilitando o cache de dados inteligente do Flash Cache™ em cada nó do cluster.

Um módulo Flash Cache, ou módulo de memória baseado em PCIe do Performance Acceleration Module, otimiza o desempenho de cargas de trabalho aleatórias com uso intensivo de leitura, funcionando como um cache de leitura externo inteligente.  Este hardware funciona em conjunto com o componente de software WAFL External Cache do ONTAP.

No Unified Manager, na página Detalhes do evento, o ícone do componente do cluster que representa o agregado em contenção é destacado em vermelho.  Abaixo do ícone, entre parênteses, está o nome do agregado, que o identifica.  Você pode habilitar o Flash Cache no nó em que o agregado reside.

Você pode usar o ONTAP System Manager ou os comandos ONTAP para verificar se o Flash Cache está instalado ou habilitado e habilitá-lo caso ainda não esteja.  O comando a seguir indica se o Flash Cache está habilitado em um nó específico: `*cluster::> run local options flexscale.enable*`

Para obter mais informações sobre o Flash Cache e os requisitos para usá-lo, consulte o seguinte relatório técnico:

https://www.netapp.com/pdf.html?item=/media/19754-tr-3832.pdf["Relatório Técnico 3832: Guia de Melhores Práticas de Cache Flash"^]
