---
permalink: performance-checker/reference_what_data_does_workload_analyzer_display.html 
sidebar: sidebar 
keywords: workload analyzer, charts, display, data 
summary: A página do analisador de carga de trabalho exibe informações sobre quaisquer eventos atuais que possam estar afetando a carga de trabalho, recomendações para potencialmente corrigir o problema que está causando o evento e gráficos para analisar o histórico de desempenho e capacidade. 
---
= Quais dados o analisador de carga de trabalho exibe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página do analisador de carga de trabalho exibe informações sobre quaisquer eventos atuais que possam estar afetando a carga de trabalho, recomendações para potencialmente corrigir o problema que está causando o evento e gráficos para analisar o histórico de desempenho e capacidade.

Na parte superior da página, você especifica o nome da carga de trabalho (volume ou LUN) que deseja analisar e o período durante o qual deseja ver estatísticas.  Você pode alterar o período de tempo a qualquer momento se quiser visualizar um período de tempo mais curto ou mais longo.

As outras áreas da página exibem os resultados da análise e os gráficos de desempenho e capacidade.

[NOTE]
====
Os gráficos de carga de trabalho para LUNs não fornecem o mesmo nível de estatísticas que os gráficos para volumes, portanto, você notará diferenças ao analisar esses dois tipos de cargas de trabalho.

====
* *Área de resumo de eventos*
+
Exibe uma breve visão geral do número e dos tipos de eventos que ocorreram ao longo do período.  Quando há eventos de diferentes áreas de impacto (por exemplo, desempenho e capacidade), essas informações são exibidas para que você possa selecionar detalhes para o tipo de evento no qual está interessado. Clique no tipo de evento para visualizar uma lista dos nomes dos eventos.

+
Se houver apenas um evento durante o período, uma lista de recomendações para corrigir o problema será listada para alguns eventos.

* *Cronograma do evento*
+
Mostra todas as ocorrências de eventos durante o período especificado.  Passe o cursor sobre cada evento para ver o nome do evento.

+
Se você chegou a esta página clicando no botão *Analisar carga de trabalho* na página Detalhes do evento, o ícone do evento selecionado aparecerá maior para que você possa identificá-lo.

* *Área de gráficos de desempenho*
+
Exibe gráficos de latência, taxa de transferência (IOPS e MB/s) e utilização (para o nó e o agregado) com base no período selecionado.  Você pode clicar no link Exibir detalhes de desempenho para exibir a página do Performance Explorer da carga de trabalho, caso queira realizar análises mais detalhadas.

+
** *Latência* exibe a latência da carga de trabalho durante o período selecionado.  O gráfico tem três visualizações que permitem que você veja:
+
*** Latência *Total*
*** Latência de *detalhamento* (dividida por leituras, gravações e outros processos)
*** Latência dos *Componentes do Cluster* (dividida por componente do cluster)






Verlink:concept_cluster_components_and_why_they_can_be_in_contention.html["Componentes do cluster e por que eles podem estar em disputa"] para uma descrição dos componentes do cluster que são exibidos aqui.  ** *Throughput* exibe a taxa de transferência de IOPS e MB/s para a carga de trabalho durante o período selecionado.  O gráfico tem quatro visualizações que permitem que você veja: *** Taxa de transferência *Total* *** Taxa de transferência *Detalhada* (dividida por leituras, gravações e outros processos) *** *Taxa de transferência na nuvem* (os MB/s usados ​​para gravar e ler dados na nuvem; para as cargas de trabalho que estão escalonando a capacidade para a nuvem) *** *IOPS com previsão* (uma previsão de quais eram os valores de taxa de transferência de IOPS superior e inferior esperados ao longo do período) Este gráfico também exibe as configurações de limite de taxa de transferência máxima e mínima de Qualidade de Serviço (QoS), se configuradas, para que você possa ver onde o sistema pode estar limitando a taxa de transferência intencionalmente com políticas de QoS.  ** *Utilização* exibe a utilização do agregado e do nó no qual a carga de trabalho está sendo executada durante o período selecionado.  A partir daqui, você pode ver se seu agregado ou nó está sendo superutilizado, possivelmente causando alta latência.  Ao analisar volumes do FlexGroup , há vários nós e vários agregados listados nos gráficos de utilização.

* *Área do gráfico de capacidade*
+
Exibe gráficos de capacidade de dados e capacidade de instantâneo do último mês para a carga de trabalho.

+
Para volumes, você pode clicar no link Exibir detalhes de capacidade para exibir a página Detalhes de integridade da carga de trabalho, caso queira realizar análises adicionais.  Os LUNs não fornecem esse link porque não há uma página de Detalhes de integridade para LUNs.

+
** *Capacity View* exibe o espaço total disponível alocado para a carga de trabalho e o espaço lógico usado (após todas as otimizações do NetApp ).
** *Visualização de instantâneo* exibe o espaço total reservado para cópias de instantâneo e a quantidade de espaço que está sendo usada no momento.  Observe que os LUNs não fornecem uma Visualização de Instantâneo.
** *Cloud Tier View* exibe quanta capacidade está sendo usada no nível de desempenho local e quanta está sendo usada no nível de nuvem.  Esses gráficos incluem uma estimativa da quantidade de tempo restante antes que a capacidade dessa carga de trabalho esteja cheia.  Essas informações são baseadas no uso histórico e exigem no mínimo 10 dias de dados.  Quando restam menos de 30 dias de capacidade, o Unified Manager identifica o armazenamento como "`quase cheio`".



