---
permalink: performance-checker/reference_performance_event_severity_types.html 
sidebar: sidebar 
keywords: performance, event, severity, types 
summary: Cada evento de desempenho é associado a um tipo de gravidade para ajudar você a priorizar os eventos que exigem ação corretiva imediata. 
---
= Tipos de gravidade de eventos de desempenho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada evento de desempenho é associado a um tipo de gravidade para ajudar você a priorizar os eventos que exigem ação corretiva imediata.

* *Crítico*
+
Ocorreu um evento de desempenho que pode levar à interrupção do serviço se uma ação corretiva não for tomada imediatamente.

+
Eventos críticos são enviados somente a partir de limites definidos pelo usuário.

* *Aviso*
+
Um contador de desempenho para um objeto de cluster está fora da faixa normal e deve ser monitorado para garantir que não atinja a gravidade crítica.  Eventos dessa gravidade não causam interrupção do serviço e pode não ser necessária ação corretiva imediata.

+
Eventos de aviso são enviados a partir de limites definidos pelo usuário, definidos pelo sistema ou dinâmicos.

* *Informação*
+
O evento ocorre quando um novo objeto é descoberto ou quando uma ação do usuário é executada.  Por exemplo, quando qualquer objeto de armazenamento é excluído ou quando há alguma alteração de configuração, o evento com tipo de gravidade Informação é gerado.

+
Eventos de informação são enviados diretamente do ONTAP quando ele detecta uma alteração de configuração.



Para mais informações, consulte os seguintes links:

* link:../events/concept_what_happens_when_an_event_is_received.html["O que acontece quando um evento é recebido"]
* link:../events/concept_what_information_is_contained_in_an_alert_email.html["Quais informações estão contidas em um e-mail de alerta"]
* link:../events/task_add_alerts.html["Adicionando alertas"]
* link:../events/task_add_alerts_for_performance_events.html["Adicionar alertas para eventos de desempenho"]

