---
permalink: performance-checker/reference_what_objects_can_be_used_in_threshold_policies.html 
sidebar: sidebar 
keywords: objects, counters, combination, threshold, policies 
summary: Somente alguns contadores de desempenho podem ser usados juntos em políticas combinadas.  Quando contadores de desempenho primário e secundário são especificados, ambos os contadores de desempenho devem exceder seus limites máximos antes que um evento seja gerado. 
---
= Quais objetos e contadores podem ser usados em políticas de limite de combinação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Somente alguns contadores de desempenho podem ser usados juntos em políticas combinadas.  Quando contadores de desempenho primário e secundário são especificados, ambos os contadores de desempenho devem exceder seus limites máximos antes que um evento seja gerado.

|===
| Objeto de armazenamento primário e contador | Objeto de armazenamento secundário e contador 


 a| 
Latência de volume
 a| 
IOPS do volume



 a| 
Volume MB/s



 a| 
Utilização agregada



 a| 
Capacidade de Desempenho Agregada Utilizada



 a| 
Utilização de nós



 a| 
Capacidade de desempenho do nó usada



 a| 
Capacidade de desempenho do nó usada - aquisição



 a| 
Latência de LUN
 a| 
LUN IOPS



 a| 
LUNMB/s



 a| 
Utilização agregada



 a| 
Capacidade de Desempenho Agregada Utilizada



 a| 
Utilização de nós



 a| 
Capacidade de desempenho do nó usada



 a| 
Capacidade de desempenho do nó usada - aquisição

|===
[NOTE]
====
Quando uma política de combinação de volume é aplicada a um volume FlexGroup , em vez de a um FlexVol volume, somente os atributos "`Volume IOPS`" e "`Volume MB/s`" podem ser selecionados como o contador secundário.  Se a política de limite contiver um dos atributos de nó ou agregado, a política não será aplicada ao volume FlexGroup e você receberá uma mensagem de erro descrevendo esse caso.  Isso ocorre porque os volumes FlexGroup podem existir em mais de um nó ou agregado.

====