---
permalink: performance-checker/reference_components_of_node_failover_planning_page.html 
sidebar: sidebar 
keywords: components, node, failover, planning page, performance, statistics, grid 
summary: Os componentes da página Planejamento de failover de desempenho/nó são exibidos em uma grade e no painel Comparação.  Essas seções permitem que você avalie o impacto de um failover de nó no desempenho do nó de aquisição. 
---
= Componentes da página de planejamento de failover de nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os componentes da página Planejamento de failover de desempenho/nó são exibidos em uma grade e no painel Comparação.  Essas seções permitem que você avalie o impacto de um failover de nó no desempenho do nó de aquisição.



== Grade de estatísticas de desempenho

A página Planejamento de failover de desempenho/nó exibe uma grade contendo estatísticas de latência, IOPS, utilização e capacidade de desempenho utilizada.

[NOTE]
====
Os valores de latência e IOPS exibidos nesta página e na página Desempenho/Explorador de Desempenho do Nó podem não corresponder porque diferentes contadores de desempenho são usados para calcular os valores para prever o failover do nó.

====
Na grade, cada nó recebe uma das seguintes funções:

* Primário
+
O nó que assume o lugar do parceiro de HA quando o parceiro falha.  O objeto raiz é sempre o nó primário.

* Parceiro
+
O nó que falha no cenário de failover.

* Aquisição estimada
+
O mesmo que o nó primário.  As estatísticas de desempenho exibidas para este nó mostram o desempenho do nó de aquisição depois que ele assume o parceiro com falha.



[NOTE]
====
Embora a carga de trabalho do nó de aquisição seja equivalente às cargas de trabalho combinadas de ambos os nós após um failover, as estatísticas do nó de aquisição estimada não são a soma das estatísticas do nó primário e do nó parceiro.  Por exemplo, se a latência do nó primário for de 2 ms/op e a latência do nó parceiro for de 3 ms/op, o nó de aquisição estimada poderá ter uma latência de 4 ms/op.  Este valor é um cálculo realizado pelo Unified Manager.

====
Você pode clicar no nome do nó Parceiro se quiser que ele se torne o objeto raiz.  Depois que a página Performance/Node Performance Explorer for exibida, você pode clicar na guia *Failover Planning* para ver como o desempenho muda neste cenário de falha de nó.  Por exemplo, se o Nó1 for o nó primário e o Nó2 for o nó parceiro, você pode clicar no Nó2 para torná-lo o nó primário.  Dessa forma, você pode ver como o desempenho estimado muda dependendo de qual nó falha.



== Painel de comparação

A lista a seguir descreve os componentes exibidos no painel Comparação por padrão:

* *Gráficos de eventos*
+
Eles são exibidos no mesmo formato daqueles na página Performance/Node Performance Explorer.  Elas pertencem somente ao nó primário.

* *Gráficos de contador*
+
Eles exibem estatísticas históricas para o contador de desempenho mostrado na grade.  Em cada gráfico, o gráfico do nó Estimated Takeover mostra o desempenho estimado se um failover tivesse ocorrido em um determinado momento.

+
Por exemplo, suponha que o gráfico de Utilização mostre 73% para o nó de Aquisição Estimada às 11h do dia 8 de fevereiro.  Se um failover tivesse ocorrido naquele momento, a utilização do nó de aquisição teria sido de 73%.

+
As estatísticas históricas ajudam você a encontrar o momento ideal para iniciar um failover, minimizando a possibilidade de sobrecarregar o nó de aquisição.  Você pode agendar um failover somente em momentos em que o desempenho previsto do nó de aquisição for aceitável.



Por padrão, as estatísticas do objeto raiz e do nó parceiro são exibidas no painel Comparação.  Diferentemente da página Performance/Node Performance Explorer, esta página não exibe o botão *Adicionar* para você adicionar objetos para comparação de estatísticas.

Você pode personalizar o painel Comparação da mesma forma que faz na página Desempenho/Explorador de Desempenho do Nó.  A lista a seguir mostra exemplos de personalização dos gráficos:

* Clique no nome de um nó para mostrar ou ocultar as estatísticas do nó nos gráficos do Contador.
* Clique em *Visualização com Zoom* para exibir um gráfico detalhado de um contador específico em uma nova janela.

