---
permalink: performance-checker/reference_what_performance_metrics_can_be_monitored_using_thresholds.html 
sidebar: sidebar 
keywords: performance, counters, tracked, thresholds 
summary: Alguns contadores de desempenho comuns, como IOPS e MB/s, podem ter limites definidos para todos os objetos de armazenamento.  Há outros contadores que podem ter limites definidos apenas para determinados objetos de armazenamento. 
---
= Quais contadores de desempenho podem ser rastreados usando limites
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alguns contadores de desempenho comuns, como IOPS e MB/s, podem ter limites definidos para todos os objetos de armazenamento.  Há outros contadores que podem ter limites definidos apenas para determinados objetos de armazenamento.



[[available-performance-counters]]
== Contadores de desempenho disponíveis

|===
| Objeto de armazenamento | Contador de desempenho | Descrição 


 a| 
Conjunto
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída que o cluster processa por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este cluster por segundo.



 a| 
Nó
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída que o nó processa por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este nó por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o nó leva para responder às solicitações do aplicativo.



 a| 
Utilização
 a| 
Porcentagem média da CPU e da RAM do nó que está sendo usada.



 a| 
Capacidade de Desempenho Utilizada
 a| 
Porcentagem média de capacidade de desempenho que está sendo consumida pelo nó.



 a| 
Capacidade de Desempenho Utilizada - Aquisição
 a| 
Porcentagem média da capacidade de desempenho que está sendo consumida pelo nó, mais a capacidade de desempenho do nó parceiro.



 a| 
Agregar
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída processadas pelo agregado por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este agregado por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o agregado leva para responder às solicitações do aplicativo.



 a| 
Utilização
 a| 
Porcentagem média de discos do agregado que estão sendo utilizados.



 a| 
Capacidade de Desempenho Utilizada
 a| 
Porcentagem média da capacidade de desempenho que está sendo consumida pelo agregado.



 a| 
VM de armazenamento
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída que o SVM processa por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este SVM por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o SVM leva para responder às solicitações do aplicativo.



 a| 
Volume
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída que o volume processa por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este volume por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o volume leva para responder às solicitações do aplicativo.



 a| 
Taxa de perda de cache
 a| 
Porcentagem média de solicitações de leitura de aplicativos cliente que são retornadas do volume em vez de serem retornadas do cache.



 a| 
LUN
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída que o LUN processa por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este LUN por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o LUN leva para responder às solicitações do aplicativo.



 a| 
Espaço de nomes
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída processadas pelo namespace por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este namespace por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o namespace leva para responder às solicitações do aplicativo.



 a| 
Porta
 a| 
Utilização de largura de banda
 a| 
Porcentagem média da largura de banda disponível da porta que está sendo usada.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para esta porta por segundo.



 a| 
Interface de rede (LIF)
 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este LIF por segundo.

|===