---
permalink: performance-checker/task_move_workloads_to_node_in_different_ha_pair.html 
sidebar: sidebar 
keywords: move, workloads, node, different, ha pair 
summary: 'Você pode usar o Unified Manager para ajudar a identificar um agregado em um nó em um par de alta disponibilidade (HA) diferente que tenha mais capacidade de desempenho livre do que o par de HA onde suas cargas de trabalho estão sendo executadas no momento.  Em seguida, você pode mover volumes selecionados para agregados no novo par HA.' 
---
= Mover cargas de trabalho para um nó em um par de HA diferente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o Unified Manager para ajudar a identificar um agregado em um nó em um par de alta disponibilidade (HA) diferente que tenha mais capacidade de desempenho livre do que o par de HA onde suas cargas de trabalho estão sendo executadas no momento.  Em seguida, você pode mover volumes selecionados para agregados no novo par HA.

.Antes de começar
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.
* Seu cluster deve consistir em um mínimo de dois pares de HA
+
Você não pode usar esse processo de correção se tiver apenas um par de HA no seu cluster.

* Você deve ter registrado os nomes dos dois nós no par HA que estão apresentando problemas de desempenho.
* Você deve ter registrado a data e a hora em que os nós receberam o evento de desempenho.
* O Unified Manager deve ter coletado e analisado dados de desempenho por um mês ou mais.


Mover cargas de trabalho de alto desempenho para um agregado em um nó com mais capacidade de desempenho livre permite que as cargas de trabalho em ambos os nós tenham um desempenho mais eficiente.  Este procedimento ajuda você a identificar os seguintes recursos para que você possa mover cargas de trabalho de alto desempenho para um nó que tenha mais capacidade de desempenho livre em um par de HA diferente:

* Os nós em um par de HA diferente no mesmo cluster que têm a maior capacidade de desempenho livre
* Os agregados nos novos nós que têm a maior capacidade de desempenho livre
* Os volumes de maior desempenho nos nós atuais


.Passos
. Identifique os nós que fazem parte de um par de HA diferente no mesmo cluster:
+
.. Na página *Detalhes do evento*, clique no nome do cluster no qual os nós residem.
+
Os detalhes do cluster são exibidos na página Desempenho/Aterrissagem do cluster.

.. Na página *Resumo*, clique em *Nós* no painel *Objetos gerenciados*.
+
A lista de nós neste cluster é exibida na exibição Desempenho: Todos os nós.

.. Anote os nomes dos nós que estão em pares de HA diferentes do par de HA que está apresentando problemas de desempenho.


. Identifique um nó no novo par HA que tenha a maior capacidade de desempenho livre:
+
.. Na exibição *Desempenho: Todos os nós*, clique na coluna *Capacidade de desempenho usada* para classificar os nós pela menor porcentagem usada.
+
Isso fornece uma lista de nós potenciais para os quais você pode querer mover cargas de trabalho.

.. Anote o nome do nó em um par de HA diferente para o qual você deseja mover as cargas de trabalho.


. Identifique um agregado no novo nó que tenha a maior capacidade de desempenho livre:
+
.. Na exibição *Desempenho: Todos os nós*, clique no nó.
+
Os detalhes do nó são exibidos na página Desempenho/Explorador de Nós.

.. No menu *Exibir e comparar*, selecione *Agregados neste nó*.
+
Os agregados neste nó são exibidos na grade.

.. Clique na coluna *Capacidade de desempenho utilizada* para classificar os agregados pelos menos utilizados.
+
Isso fornece uma lista de possíveis agregados para os quais você pode querer mover cargas de trabalho.

.. Anote o nome do agregado para o qual você deseja mover as cargas de trabalho.


. Identifique as cargas de trabalho de alto desempenho dos nós que receberam o evento:
+
.. Retorne para a página de detalhes do *Evento*.
.. No campo *Volumes afetados*, clique no link para o número de volumes do primeiro nó.
+
A exibição Desempenho: Todos os volumes é exibida com uma lista filtrada dos volumes naquele nó.

.. Clique na coluna *Capacidade total* para classificar os volumes pelo maior espaço alocado.
+
Isso fornece uma lista de volumes potenciais que você pode querer mover.

.. Anote os nomes dos volumes que você deseja mover e os nomes dos agregados atuais nos quais eles residem.
.. Execute as etapas 4c e 4d para o segundo nó que fez parte deste evento para identificar possíveis volumes que você deseja mover desse nó também.


. Mova os volumes para os agregados que você identificou como tendo maior capacidade de desempenho livre no novo nó.
+
Você pode executar a operação de movimentação usando o ONTAP System Manager, o OnCommand Workflow Automation, os comandos ONTAP ou uma combinação dessas ferramentas.



Após alguns dias, você pode verificar se está recebendo o mesmo tipo de eventos deste nó ou agregado.
