---
permalink: performance-checker/task_display_information_about_performance_event.html 
sidebar: sidebar 
keywords: display, information, performance, events 
summary: Você pode usar a página de inventário do Gerenciamento de Eventos para visualizar uma lista de todos os eventos de desempenho nos clusters monitorados pelo Unified Manager.  Ao visualizar essas informações, você pode determinar os eventos mais críticos e, em seguida, obter informações detalhadas para determinar a causa do evento. 
---
= Exibir informações sobre eventos de desempenho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a página de inventário do Gerenciamento de Eventos para visualizar uma lista de todos os eventos de desempenho nos clusters monitorados pelo Unified Manager.  Ao visualizar essas informações, você pode determinar os eventos mais críticos e, em seguida, obter informações detalhadas para determinar a causa do evento.

.Antes de começar
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.


A lista de eventos é classificada por hora detectada, com os eventos mais recentes listados primeiro.  Você pode clicar no cabeçalho de uma coluna para classificar os eventos com base nessa coluna.  Por exemplo, você pode classificar pela coluna Status para visualizar eventos por gravidade.  Se você estiver procurando por um evento específico ou por um tipo específico de evento, você pode usar os mecanismos de filtro e pesquisa para refinar a lista de eventos que aparecem na lista.

Eventos de todas as fontes são exibidos nesta página:

* Política de limite de desempenho definida pelo usuário
* Política de limite de desempenho definida pelo sistema
* Limite de desempenho dinâmico


A coluna Tipo de evento lista a origem do evento.  Você pode selecionar um evento para ver detalhes sobre ele na página Detalhes do evento.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de eventos*.
. No menu Exibir, selecione *Eventos de desempenho ativos*.
+
A página exibe todos os eventos de desempenho novos e reconhecidos que foram gerados nos últimos 7 dias.

. Localize um evento que você deseja analisar e clique no nome do evento.
+
A página de detalhes do evento é exibida.

+
[NOTE]
====
Você também pode exibir a página de detalhes de um evento clicando no link do nome do evento na página do Performance Explorer e em um e-mail de alerta.

====

