---
permalink: performance-checker/task_analyze_performance_incident_in_metrocluster.html 
sidebar: sidebar 
keywords: analyzing, dynamic, performance, event, remote, cluster, metrocluster, configuration 
summary: Você pode usar o Unified Manager para analisar eventos de desempenho dinâmico em um cluster remoto em uma configuração do MetroCluster .  A análise ajuda a determinar se um evento no cluster remoto causou um evento no cluster parceiro. 
---
= Analisar um evento de desempenho dinâmico para um cluster remoto em uma configuração MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o Unified Manager para analisar eventos de desempenho dinâmico em um cluster remoto em uma configuração do MetroCluster .  A análise ajuda a determinar se um evento no cluster remoto causou um evento no cluster parceiro.

.Antes de começar
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter analisado um evento de desempenho em um cluster local em uma configuração MetroCluster e obtido o tempo de detecção do evento.
* Você deve ter verificado a integridade do cluster local e do cluster parceiro envolvido no evento de desempenho e obtido o nome do cluster parceiro.


.Passos
. Efetue login na instância do Unified Manager que está monitorando o cluster de parceiros.
. No painel de navegação esquerdo, clique em *Eventos* para exibir a lista de eventos.
. No seletor *Intervalo de tempo*, selecione *Última hora* e clique em *Aplicar intervalo*.
. No seletor *Filtragem*, selecione *Cluster* no menu suspenso à esquerda, digite o nome do cluster parceiro no campo de texto e clique em *Aplicar filtro*.
+
Se não houver eventos para o cluster selecionado na última hora, isso indica que o cluster não apresentou problemas de desempenho durante o tempo em que o evento foi detectado em seu parceiro.

. Se o cluster selecionado tiver eventos detectados na última hora, compare o tempo de detecção do evento com o tempo de detecção do evento no cluster local.
+
Se esses eventos envolverem cargas de trabalho agressivas causando contenção no componente de processamento de dados, um ou mais desses agressores podem ter causado o evento no cluster local.  Você pode clicar no evento para analisá-lo e revisar as ações sugeridas para resolvê-lo na página Detalhes do evento.

+
Se esses eventos não envolverem cargas de trabalho agressivas, eles não causaram o evento de desempenho no cluster local.


