---
permalink: performance-checker/task_edit_user_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: edit, user-defined, performance, threshold, policies 
summary: Você pode editar as configurações de limite para políticas de limite de desempenho existentes.  Isso pode ser útil se você perceber que está recebendo muitos ou poucos alertas para determinadas condições limite. 
---
= Editar políticas de limite de desempenho definidas pelo usuário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar as configurações de limite para políticas de limite de desempenho existentes.  Isso pode ser útil se você perceber que está recebendo muitos ou poucos alertas para determinadas condições limite.

.Antes de começar
Você deve ter a função de Administrador do Aplicativo.

Não é possível alterar o nome da política ou o tipo de objeto de armazenamento que está sendo monitorado para políticas de limite existentes.

.Passos
. No painel de navegação esquerdo, selecione *Limites de evento* > *Desempenho*.
+
A página Limites de desempenho é exibida.

. Selecione a política de limite que você deseja alterar e clique em *Editar*.
+
A página Editar política de limite de desempenho é exibida.

. Faça suas alterações na política de limite e clique em *Salvar*.
+
Você retornará à página Limites de desempenho.



Depois de salvas, as alterações são atualizadas imediatamente em todos os objetos de armazenamento que usam a política.

Dependendo do tipo de alterações feitas na política, talvez você queira revisar as configurações de alerta definidas para os objetos que usam a política na página Configuração de alerta.
