---
permalink: performance-checker/task_select_performance_charts_to_display.html 
sidebar: sidebar 
keywords: select, performance, charts, display 
summary: A lista suspensa Escolher gráficos permite que você selecione os tipos de gráficos de contadores de desempenho a serem exibidos no painel Gráficos de contadores.  Isso permite que você visualize dados e contadores específicos, com base em seus requisitos de desempenho. 
---
= Selecione gráficos de desempenho para exibir
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A lista suspensa Escolher gráficos permite que você selecione os tipos de gráficos de contadores de desempenho a serem exibidos no painel Gráficos de contadores.  Isso permite que você visualize dados e contadores específicos, com base em seus requisitos de desempenho.

.Passos
. No painel *Gráficos do contador*, clique na lista suspensa *Escolher gráficos*.
. Adicionar ou remover gráficos:
+
|===
| Para... | Faça isso... 


 a| 
Adicionar ou remover gráficos individuais
 a| 
Clique nas caixas de seleção ao lado dos gráficos que você deseja mostrar ou ocultar



 a| 
Adicionar todos os gráficos
 a| 
Clique em *Selecionar tudo*



 a| 
Remover todos os gráficos
 a| 
Clique em *Desmarcar tudo*

|===
+
Suas seleções de gráficos são exibidas no painel Gráficos de Contadores.  Observe que, à medida que você adiciona gráficos, os novos gráficos são inseridos no painel Gráficos do contador para corresponder à ordem dos gráficos listados na lista suspensa Escolher gráficos.  Selecionar gráficos adicionais pode exigir rolagem adicional.


