---
permalink: performance-checker/task_respond_to_system_defined_qos_policy_group_performance_event.html 
sidebar: sidebar 
keywords: qos, policy, group, performance, events 
summary: 'O Unified Manager gera eventos de aviso de política de QoS quando a taxa de transferência de carga de trabalho (IOPS, IOPS/TB ou MBps) excede a configuração de política de QoS do ONTAP definida e a latência da carga de trabalho está sendo afetada.  Esses eventos definidos pelo sistema oferecem a oportunidade de corrigir possíveis problemas de desempenho antes que muitas cargas de trabalho sejam afetadas pela latência.' 
---
= Responder a eventos de desempenho do grupo de políticas de QoS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Unified Manager gera eventos de aviso de política de QoS quando a taxa de transferência de carga de trabalho (IOPS, IOPS/TB ou MBps) excede a configuração de política de QoS do ONTAP definida e a latência da carga de trabalho está sendo afetada.  Esses eventos definidos pelo sistema oferecem a oportunidade de corrigir possíveis problemas de desempenho antes que muitas cargas de trabalho sejam afetadas pela latência.

.Antes de começar
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.
* Deve haver eventos de performance novos, reconhecidos ou obsoletos.


O Unified Manager gera eventos de aviso para violações de política de QoS quando a taxa de transferência de carga de trabalho excede a configuração de política de QoS definida durante cada período de coleta de desempenho da hora anterior.  A taxa de transferência da carga de trabalho pode exceder o limite de QoS por apenas um curto período de tempo durante cada período de coleta, mas o Unified Manager exibe apenas a taxa de transferência "média" durante o período de coleta no gráfico.  Por esse motivo, você pode receber eventos de QoS mesmo que a taxa de transferência de uma carga de trabalho não tenha ultrapassado o limite da política mostrado no gráfico.

Você pode usar o Gerenciador do Sistema ou os comandos ONTAP para gerenciar grupos de políticas, incluindo as seguintes tarefas:

* Criando um novo grupo de políticas para a carga de trabalho
* Adicionar ou remover cargas de trabalho em um grupo de políticas
* Movendo uma carga de trabalho entre grupos de políticas
* Alterando o limite de taxa de transferência de um grupo de políticas
* Mover uma carga de trabalho para um agregado ou nó diferente


.Passos
. Exiba a página *Detalhes do evento* para visualizar informações sobre o evento.
. Revise a *Descrição*, que descreve a violação do limite que causou o evento.
+
Por exemplo, a mensagem "`O valor de IOPS de 1.352 IOPS no vol1_NFS1 acionou um evento de AVISO para identificar possíveis problemas de desempenho para a carga de trabalho`" indica que um evento de QoS Max IOPS ocorreu no volume vol1_NFS1.

. Revise a seção *Informações do evento* para ver mais detalhes sobre quando o evento ocorreu e há quanto tempo ele está ativo.
+
Além disso, para volumes ou LUNs que compartilham a taxa de transferência de uma política de QoS, você pode ver os nomes das três principais cargas de trabalho que estão consumindo mais IOPS ou MBps.

. Na seção *Diagnóstico do Sistema*, revise os dois gráficos: um para IOPS ou MBps médios totais (dependendo do evento) e um para latência.  Quando organizado dessa forma, você pode ver quais componentes do cluster estão afetando mais a latência quando a carga de trabalho se aproxima do limite máximo de QoS.
+
Para um evento de política de QoS compartilhada, as três principais cargas de trabalho são mostradas no gráfico de taxa de transferência.  Se mais de três cargas de trabalho estiverem compartilhando a política de QoS, cargas de trabalho adicionais serão adicionadas em uma categoria "`Outras cargas de trabalho`".  Além disso, o gráfico de latência mostra a latência média em todas as cargas de trabalho que fazem parte da política de QoS.

+
Observe que, para eventos de política de QoS adaptável, os gráficos de IOPS e MBps mostram valores de IOPS ou MBps que o ONTAP converteu da política de limite de IOPS/TB atribuída com base no tamanho do volume.

. Na seção *Ações sugeridas*, revise as sugestões e determine quais ações você deve executar para evitar um aumento na latência da carga de trabalho.
+
Se necessário, clique no botão *Ajuda* para ver mais detalhes sobre as ações sugeridas que você pode executar para tentar resolver o evento de desempenho.


