---
permalink: performance-checker/task_display_counter_charts_zoom_view.html 
sidebar: sidebar 
keywords: display, counter charts, zoom, view 
summary: A visualização de zoom dos gráficos de contador fornece um nível mais fino de detalhes para o gráfico de contador selecionado e sua linha do tempo associada.  Isso amplia os dados do gráfico de contador, permitindo que você tenha uma visão mais nítida dos eventos de desempenho e suas causas subjacentes. 
---
= Exibir a visualização de zoom dos gráficos do contador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A visualização de zoom dos gráficos de contador fornece um nível mais fino de detalhes para o gráfico de contador selecionado e sua linha do tempo associada.  Isso amplia os dados do gráfico de contador, permitindo que você tenha uma visão mais nítida dos eventos de desempenho e suas causas subjacentes.

Você pode exibir a Visualização de Zoom dos Gráficos de Contadores para qualquer gráfico de contadores.

.Passos
. Clique em *Visualização com Zoom* para abrir o gráfico selecionado em uma nova janela do navegador.
. Se você estiver visualizando um gráfico de detalhamento e clicar em *Visualização com zoom*, o gráfico de detalhamento será exibido na Visualização com zoom.  Você pode selecionar *Total* enquanto estiver na Visualização de Zoom se quiser alterar a opção de visualização.

