---
permalink: performance-checker/task_identify_shark_workloads_involved_in_performance_event.html 
sidebar: sidebar 
keywords: identify, shark workloads, involved, dynamic, performance, event 
summary: No Unified Manager, você pode identificar quais cargas de trabalho têm o maior desvio no uso de um componente de armazenamento em contenção.  Identificar essas cargas de trabalho ajuda a determinar se elas devem ser movidas para um cluster menos utilizado. 
---
= Identificar cargas de trabalho de tubarão envolvidas em um evento de desempenho dinâmico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
No Unified Manager, você pode identificar quais cargas de trabalho têm o maior desvio no uso de um componente de armazenamento em contenção.  Identificar essas cargas de trabalho ajuda a determinar se elas devem ser movidas para um cluster menos utilizado.

.Antes de começar
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.
* Existem eventos dinâmicos de desempenho novos, reconhecidos ou obsoletos.


A página Detalhes do evento exibe uma lista das cargas de trabalho definidas pelo usuário e pelo sistema, classificadas pelo maior uso do componente ou mais impactadas pelo evento.  Os valores são baseados nos picos que o Unified Manager identificou quando detectou e analisou o evento pela última vez.

.Passos
. Exiba a página *Detalhes do evento* para visualizar informações sobre o evento.
. Nos gráficos Latência da carga de trabalho e Atividade da carga de trabalho, selecione *Cargas de trabalho do Shark*.
. Passe o cursor sobre os gráficos para visualizar as principais cargas de trabalho definidas pelo usuário que estão afetando o componente e o nome da carga de trabalho do tubarão.

