---
permalink: performance-checker/task_identify_bully_workloads_involved_in_performance_event.html 
sidebar: sidebar 
keywords: identify, bully workloads, dynamic, performance, event 
summary: 'No Unified Manager, você pode identificar quais cargas de trabalho têm o maior desvio no uso de um componente de cluster em contenção.  Identificar essas cargas de trabalho ajuda você a entender por que certos volumes no cluster têm tempos de resposta lentos (latência).' 
---
= Identificar cargas de trabalho agressivas envolvidas em um evento de desempenho dinâmico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
No Unified Manager, você pode identificar quais cargas de trabalho têm o maior desvio no uso de um componente de cluster em contenção.  Identificar essas cargas de trabalho ajuda você a entender por que certos volumes no cluster têm tempos de resposta lentos (latência).

.Antes de começar
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.
* Deve haver eventos de desempenho dinâmico novos, reconhecidos ou obsoletos.


A página Detalhes do evento exibe uma lista das cargas de trabalho definidas pelo usuário e pelo sistema, classificadas pelo maior uso do componente ou mais impactadas pelo evento.  Os valores são baseados nos picos que o Unified Manager identificou quando detectou e analisou o evento pela última vez.

.Passos
. Exiba a página Detalhes do evento para visualizar informações sobre o evento.
. Nos gráficos Latência da carga de trabalho e Atividade da carga de trabalho, selecione *Cargas de trabalho agressivas*.
. Passe o cursor sobre os gráficos para visualizar as principais cargas de trabalho de intimidação definidas pelo usuário que estão afetando o componente.

