---
permalink: performance-checker/task_move_workloads_to_an_aggregate_on_different_node.html 
sidebar: sidebar 
keywords: moving, workloads, aggregate, different, node 
summary: Você pode usar o Unified Manager para ajudar a identificar um agregado em um nó diferente que esteja menos ocupado do que o nó onde suas cargas de trabalho estão sendo executadas no momento e, então, você pode mover volumes selecionados para esse agregado.  Mover cargas de trabalho de alto desempenho para um agregado em um nó menos ocupado permite que as cargas de trabalho em ambos os nós tenham um desempenho mais eficiente. 
---
= Mover cargas de trabalho para um agregado em um nó diferente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o Unified Manager para ajudar a identificar um agregado em um nó diferente que esteja menos ocupado do que o nó onde suas cargas de trabalho estão sendo executadas no momento e, então, você pode mover volumes selecionados para esse agregado.  Mover cargas de trabalho de alto desempenho para um agregado em um nó menos ocupado permite que as cargas de trabalho em ambos os nós tenham um desempenho mais eficiente.

.Antes de começar
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter registrado o nome do nó que está apresentando problemas de desempenho.
* Você deve ter registrado a data e a hora em que o nó recebeu o evento de desempenho.
* O Unified Manager deve ter coletado e analisado um mês ou mais de dados de desempenho.


Estas etapas ajudam a identificar os seguintes recursos para que você possa mover cargas de trabalho de alto desempenho para um nó com menor utilização:

* Os nós no mesmo cluster que são menos utilizados
* Os agregados no novo nó que são os menos utilizados
* Os volumes de maior desempenho no nó atual


.Passos
. Identifique um nó no cluster que seja o menos utilizado:
+
.. Na página de detalhes do *Evento*, clique no nome do cluster no qual o nó reside.
+
Os detalhes do cluster são exibidos na página Desempenho/Aterrissagem do cluster.

.. Na página *Resumo*, clique em *Nós* no painel *Objetos gerenciados*.
+
A lista de nós neste cluster é exibida.

.. Clique na coluna *Utilização* para classificar os nós pelos menos utilizados.
+
Você também pode identificar os nós que têm a maior *Capacidade Livre*.  Isso fornece uma lista de nós potenciais para os quais você pode querer mover cargas de trabalho.

.. Anote o nome do nó para o qual você deseja mover as cargas de trabalho.


. Identifique um agregado no novo nó que seja o menos utilizado:
+
.. No painel de navegação esquerdo, clique em *Armazenamento* > *Agregados* e selecione *Desempenho* > *Todos os agregados* no menu Exibir.
+
A exibição Desempenho: Todos os agregados é exibida.

.. Clique em *Filtragem*, selecione *Nó* no menu suspenso à esquerda, digite o nome do nó no campo de texto e clique em *Aplicar filtro*.
+
A exibição Desempenho: Todos os agregados é exibida novamente com a lista de agregados disponíveis neste nó.

.. Clique na coluna *Utilização* para classificar os agregados pelos menos utilizados.
+
Você também pode identificar os agregados que têm a maior *Capacidade Livre*.  Isso fornece uma lista de possíveis agregados para os quais você pode querer mover cargas de trabalho.

.. Anote o nome do agregado para o qual você deseja mover as cargas de trabalho.


. Identifique as cargas de trabalho de alto desempenho do nó que recebeu o evento:
+
.. Retorne para a página de detalhes do *Evento*.
.. No campo *Volumes afetados*, clique no link para o número de volumes.
+
A exibição Desempenho: Todos os volumes é exibida com uma lista filtrada dos volumes naquele nó.

.. Clique na coluna *Capacidade total* para classificar os volumes pelo maior espaço alocado.
+
Isso fornece uma lista de volumes potenciais que você pode querer mover.

.. Anote os nomes dos volumes que você deseja mover e os nomes dos agregados atuais nos quais eles residem.


. Mova os volumes para os agregados que você identificou como tendo baixa utilização no novo nó.
+
Você pode executar a operação de movimentação usando o ONTAP System Manager, o OnCommand Workflow Automation, os comandos ONTAP ou uma combinação dessas ferramentas.



Após alguns dias, verifique se você está recebendo o mesmo tipo de eventos deste nó ou agregado.
