---
permalink: performance-checker/task_configure_connection_between_um_server_and_external_data_provider.html 
sidebar: sidebar 
keywords: configuring, connection, unified manager, server, external, data, provider 
summary: O Unified Manager pode enviar dados de desempenho do cluster para um servidor externo.  Você pode especificar o tipo de dados estatísticos que são enviados e o intervalo em que os dados são enviados. 
---
= Configurar uma conexão de um servidor do Unified Manager para um provedor de dados externo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Unified Manager pode enviar dados de desempenho do cluster para um servidor externo.  Você pode especificar o tipo de dados estatísticos que são enviados e o intervalo em que os dados são enviados.

.Antes de começar
* Você deve ter uma ID de usuário autorizada para efetuar login no console de manutenção do servidor do Unified Manager.
* Você deve ter as seguintes informações sobre o provedor de dados externo:
+
** Nome do servidor ou endereço IP (IPv4 ou IPv6)
** Porta padrão do servidor (se não estiver usando a porta padrão 2003)


* Você deve ter configurado o servidor remoto e o software de terceiros para que ele possa receber dados estatísticos do servidor do Unified Manager.
* Você deve saber qual grupo de estatísticas deseja enviar:
+
** INDICADOR_DE_PERFORMANCE: Estatísticas do monitor de desempenho
** RESOURCE_UTILIZATION: Estatísticas de utilização de recursos e monitor de desempenho
** DRILL_DOWN: Todas as estatísticas


* Você deve saber o intervalo de tempo em que deseja transmitir estatísticas: 5, 10 ou 15 minutos
+
Por padrão, o Unified Manager coleta estatísticas em intervalos de 5 minutos.  Se você definir o intervalo de transmissão para 10 (ou 15) minutos, a quantidade de dados enviados durante cada transmissão será duas (ou três) vezes maior do que quando usar o intervalo padrão de 5 minutos.

+
[NOTE]
====
Se você alterar o intervalo de coleta de desempenho do Unified Manager para 10 ou 15 minutos, deverá alterar o intervalo de transmissão para que seja igual ou maior que o intervalo de coleta do Unified Manager.

====


Você pode configurar uma conexão entre um servidor do Unified Manager e um servidor de provedor de dados externo.

.Passos
. Efetue login como usuário de manutenção no console de manutenção do servidor do Unified Manager.
+
Os prompts do console de manutenção do Unified Manager são exibidos.

. No console de manutenção, digite o número da opção de menu *Provedor de Dados Externo*.
+
O menu Conexão de servidor externo é exibido.

. Digite o número da opção de menu *Adicionar/Modificar conexão do servidor*.
+
As informações atuais de conexão do servidor são exibidas.

. Quando solicitado, digite `*y*` para continuar.
. Quando solicitado, insira o endereço IP ou o nome do servidor de destino e as informações da porta do servidor (se diferente da porta padrão 2003).
. Quando solicitado, digite `*y*` para verificar se as informações inseridas estão corretas.
. Pressione qualquer tecla para retornar ao menu Conexão de servidor externo.
. Digite o número da opção de menu *Modificar configuração do servidor*.
+
As informações atuais de configuração do servidor são exibidas.

. Quando solicitado, digite `*y*` para continuar.
. Quando solicitado, insira o tipo de estatísticas a serem enviadas, o intervalo de tempo em que as estatísticas são enviadas e se deseja habilitar a transmissão de estatísticas agora:
+
|===
| Para.. | Digitar... 


 a| 
ID do grupo de estatísticas
 a| 
`*0*`- INDICADOR_DE_DESEMPENHO (padrão)

`*1*`- UTILIZAÇÃO_DE_RECURSOS

`*2*`- DETALHE



 a| 
Etiqueta do fornecedor
 a| 
Um nome descritivo para a pasta onde as estatísticas serão armazenadas no servidor externo.  "`netapp-performance`" é o nome padrão, mas você pode inserir outro valor.

Usando a notação pontilhada, você pode definir uma estrutura de pastas hierárquica.  Por exemplo, ao inserir `*stats.performance.netapp*` as estatísticas estarão localizadas em *stats* > *performance* > *netapp*.



 a| 
Intervalo de transmissão
 a| 
`*5*`(padrão), `*10*` , ou `*15*` minutos



 a| 
Habilitar/desabilitar
 a| 
`*0*`- Desabilitar

`*1*`- Habilitar (padrão)

|===
. Quando solicitado, digite `*y*` para verificar se as informações inseridas estão corretas.
. Pressione qualquer tecla para retornar ao menu Conexão de servidor externo.
. Tipo `*x*` para sair do console de manutenção.


Depois de configurar a conexão, os dados de desempenho selecionados são enviados ao servidor de destino no intervalo de tempo especificado.  Demora alguns minutos até que as métricas comecem a aparecer na ferramenta externa.  Talvez seja necessário atualizar seu navegador para ver as novas métricas na hierarquia de métricas.
