---
permalink: performance-checker/task_view_performance_status_of_all_san_array_clusters.html 
sidebar: sidebar 
keywords: all san, array, performance, clusters 
summary: 'Você pode usar a exibição Desempenho: Todos os clusters para exibir o status de desempenho dos seus clusters do All SAN Array.' 
---
= Veja o desempenho de todos os clusters do SAN Array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a exibição Desempenho: Todos os clusters para exibir o status de desempenho dos seus clusters do All SAN Array.

.Antes de começar
Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.

Você pode visualizar informações gerais para todos os clusters do SAN Array na exibição Desempenho: Todos os clusters e detalhes na página Cluster/Desempenho Explorer.

.Passos
. No painel de navegação esquerdo, clique em *Armazenamento* > *Clusters*.
. Certifique-se de que a coluna "`Personalidade`" seja exibida na exibição *Saúde: Todos os Clusters* ou adicione-a usando o controle *Mostrar / Ocultar*.
+
Esta coluna exibe "`All SAN Array`" para seus clusters All SAN Array.

. Para visualizar informações sobre o desempenho desses clusters, selecione a visualização *Desempenho: Todos os clusters*.
+
Veja as informações de desempenho do cluster All SAN Array.

. Para visualizar informações detalhadas sobre o desempenho desses clusters, clique no nome de um cluster All SAN Array.
. Clique na aba *Explorer*.
. Na página *Cluster / Performance Explorer*, selecione *Nós neste cluster* no menu *Exibir e comparar*.
+
Você pode comparar as estatísticas de desempenho de ambos os nós neste cluster para garantir que a carga seja quase idêntica em ambos os nós.  Se houver grandes discrepâncias entre os dois nós, você pode adicionar o segundo nó aos gráficos e comparar os valores em um período maior para identificar quaisquer problemas de configuração.


