---
permalink: performance-checker/task_create_user_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: create, user-defined, performance, threshold, policies 
summary: Crie políticas de limite de desempenho para objetos de armazenamento para que notificações sejam enviadas quando um contador de desempenho exceder um valor específico.  A notificação de evento identifica que o cluster está enfrentando um problema de desempenho. 
---
= Crie políticas de limite de desempenho definidas pelo usuário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Crie políticas de limite de desempenho para objetos de armazenamento para que notificações sejam enviadas quando um contador de desempenho exceder um valor específico.  A notificação de evento identifica que o cluster está enfrentando um problema de desempenho.

.Antes de começar
Você deve ter a função de Administrador do Aplicativo.

Crie políticas de limite de desempenho inserindo os valores de limite na página Criar política de limite de desempenho.  Você pode criar novas políticas definindo todos os valores de política nesta página ou pode fazer uma cópia de uma política existente e alterar os valores na cópia (chamado de _clonagem_).

Os valores limite válidos são de 0,001 a 10.000.000 para números, 0,001 a 100 para porcentagens e 0,001 a 200 para porcentagens de Capacidade de Desempenho Utilizada.

[NOTE]
====
A versão atual fornece limites que enviam eventos quando um valor de contador excede a configuração de limite.  Não é possível definir limites que enviem eventos quando um valor do contador cair abaixo de uma configuração de limite.

====
.Passos
. No painel de navegação esquerdo, selecione *Limites de evento* > *Desempenho*.
+
A página Limites de desempenho é exibida.

. Clique no botão apropriado dependendo se você deseja criar uma nova política ou se deseja clonar uma política semelhante e modificar a versão clonada.
+
|===
| Para... | Clique... 


 a| 
Criar uma nova política
 a| 
*Criar*



 a| 
Clonar uma política existente
 a| 
Selecione uma política existente e clique em *Clonar*

|===
+
A página Criar política de limite de desempenho ou Clonar política de limite de desempenho é exibida.

. Defina a política de limite especificando os valores de limite do contador de desempenho que você deseja definir para objetos de armazenamento específicos:
+
.. Selecione o tipo de objeto de armazenamento e especifique um nome e uma descrição para a política.
.. Selecione o contador de desempenho a ser rastreado e especifique os valores limite que definem eventos de Aviso e Críticos.
+
Você deve definir pelo menos um Aviso ou um limite Crítico.  Você não precisa definir os dois tipos de limites.

.. Selecione um contador de desempenho secundário, se necessário, e especifique os valores limite para eventos de Aviso e Críticos.
+
Incluir um contador secundário exige que ambos os contadores excedam os valores limite antes que o limite seja violado e um evento seja relatado.  Somente determinados objetos e contadores podem ser configurados usando uma política de combinação.

.. Selecione o período de tempo durante o qual os valores limite devem ser violados para que um evento seja enviado.


+
Ao clonar uma política existente, você deve inserir um novo nome para a política.

. Clique em *Salvar* para salvar a política.
+
Você retornará à página Limites de desempenho.  Uma mensagem de sucesso no topo da página confirma que a política de limite foi criada e fornece um link para a página Inventário para esse tipo de objeto, para que você possa aplicar a nova política aos objetos de armazenamento imediatamente.



Se você quiser aplicar a nova política de limite aos objetos de armazenamento neste momento, clique no link *Ir para object_type agora* para ir para a página Inventário.
