---
permalink: performance-checker/task_sort_on_object_inventory_performance_pages.html 
sidebar: sidebar 
keywords: sort, object, inventory, performance, pages 
summary: Você pode classificar todos os dados nas páginas de Desempenho do Inventário de Objetos por qualquer coluna em ordem crescente ou decrescente.  Isso permite que você localize rapidamente dados de inventário de objetos, o que é útil ao examinar o desempenho ou iniciar um processo de solução de problemas. 
---
= Classificar nas páginas de desempenho do inventário de objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode classificar todos os dados nas páginas de Desempenho do Inventário de Objetos por qualquer coluna em ordem crescente ou decrescente.  Isso permite que você localize rapidamente dados de inventário de objetos, o que é útil ao examinar o desempenho ou iniciar um processo de solução de problemas.

A coluna selecionada para classificação é indicada por um nome de título de coluna destacado e um ícone de seta indicando a direção da classificação à direita do nome.  Uma seta para cima indica ordem crescente; uma seta para baixo indica ordem decrescente.  A ordem de classificação padrão é por *Status* (criticidade do evento) em ordem decrescente, com os eventos de desempenho mais críticos listados primeiro.

.Etapa
. Você pode clicar no nome de uma coluna para alternar a ordem de classificação da coluna em ordem crescente ou decrescente.
+
O conteúdo da página Desempenho do inventário de objetos é classificado em ordem crescente ou decrescente, com base na coluna selecionada.


