---
permalink: storage-mgmt/concept_assign_policies_on_workloads.html 
sidebar: sidebar 
keywords: assign, policies, workloads, single, multiple, storage, system-recommended, psls 
summary: 'Você pode atribuir Políticas de Eficiência de Armazenamento (SEPs) e Níveis de Serviço de Desempenho (PSLs) a cargas de trabalho de armazenamento na página Todas as Cargas de Trabalho usando as diferentes opções de navegação.' 
---
= Atribuir políticas a cargas de trabalho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atribuir Políticas de Eficiência de Armazenamento (SEPs) e Níveis de Serviço de Desempenho (PSLs) a cargas de trabalho de armazenamento na página Todas as Cargas de Trabalho usando as diferentes opções de navegação.



[[assign-policies-to-a-single-workload]]
== Atribuir políticas a uma única carga de trabalho

Você pode atribuir um PSL ou um SEP, ou ambos, a uma única carga de trabalho. Siga estes passos:

. Selecione a carga de trabalho.
. Clique no ícone de edição ao lado da linha e depois clique em *Editar*.
+
Os campos *Nível de serviço de desempenho atribuído* e *Política de eficiência de armazenamento* estão habilitados.

. Selecione o PSL ou SEP desejado, ou ambos.
. Clique no ícone de verificação para aplicar as alterações.


[NOTE]
====
Você também pode selecionar uma carga de trabalho e clicar em *Mais ações* para atribuir as políticas.

====


[[assign-policies-to-multiple-storage-workloads]]
== Atribuir políticas a várias cargas de trabalho de armazenamento

Você pode atribuir um PSL ou um SEP a várias cargas de trabalho de armazenamento juntas. Siga estes passos:

. Marque as caixas de seleção das cargas de trabalho às quais você deseja atribuir a política ou selecione todas as cargas de trabalho no seu data center.
. Clique em *Mais ações*.
. Para atribuir um PSL, selecione *Atribuir Nível de Serviço de Desempenho*.  Para atribuir um SEP, selecione *Atribuir política de eficiência de armazenamento*.  Um pop-up será exibido para você selecionar a política.
. Selecione a política apropriada e clique em *Aplicar*.  O número de cargas de trabalho nas quais as políticas são atribuídas é exibido.  As cargas de trabalho nas quais as políticas não são atribuídas também são listadas, com a causa.
+
[NOTE]
====
A aplicação de políticas em cargas de trabalho em massa pode levar algum tempo, dependendo do número de cargas de trabalho selecionadas.  Você pode clicar no botão *Executar em segundo plano* e continuar com outras tarefas enquanto a operação é executada em segundo plano.  Quando a atribuição em massa estiver concluída, você poderá visualizar o status de conclusão.  Se você estiver aplicando um PSL em várias cargas de trabalho, não poderá acionar outra solicitação quando o trabalho anterior de atribuição em massa estiver em execução.

====




[[assign-system-recommended-psls-to-workloads]]
== Atribuir PSLs recomendados pelo sistema às cargas de trabalho

Você pode atribuir PSLs recomendados pelo sistema às cargas de trabalho de armazenamento em um data center que não têm PSLs atribuídos ou que os PSLs atribuídos não correspondem à recomendação do sistema.  Para usar esta funcionalidade, clique no botão *Atribuir PSLs recomendados pelo sistema*.  Você não precisa selecionar cargas de trabalho específicas.

A recomendação é determinada internamente pela análise do sistema e é ignorada para as cargas de trabalho cujos IOPS e outros parâmetros não coincidem com as definições de nenhum PSL disponível.  Cargas de trabalho de armazenamento com `Waiting for I/O` e os status de Aprendizagem também são excluídos.

[NOTE]
====
Há palavras-chave especiais que o Unified Manager procura no nome da carga de trabalho para substituir a análise do sistema e recomendar um PSL diferente para a carga de trabalho.  Quando a carga de trabalho tem as letras "`ora`" no nome, o **Extreme Performance**PSL é recomendado.  E quando a carga de trabalho tem as letras "`vm`" no nome, o **Performance**PSL é recomendado.

====
Veja também o artigo da base de conhecimento (KB) https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/Performance_Service_Level'_is_not_adaptive_to_a_highly_variable_workload["O ActiveIQ Unified Manager 'Atribuir Nível de Serviço de Desempenho Recomendado ao Sistema' não é adaptável a uma carga de trabalho altamente variável"]
