---
permalink: storage-mgmt/concept_what_quota_limits_are.html 
sidebar: sidebar 
keywords: quota, limits 
summary: Os limites de cota do usuário são valores que o servidor do Unified Manager usa para avaliar se o consumo de espaço por um usuário está se aproximando do limite ou atingiu o limite definido pela cota do usuário.  Se o limite flexível for ultrapassado ou se o limite rígido for atingido, o servidor do Unified Manager gerará eventos de cota de usuário. 
---
= Quais são os limites de cota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os limites de cota do usuário são valores que o servidor do Unified Manager usa para avaliar se o consumo de espaço por um usuário está se aproximando do limite ou atingiu o limite definido pela cota do usuário.  Se o limite flexível for ultrapassado ou se o limite rígido for atingido, o servidor do Unified Manager gerará eventos de cota de usuário.

Por padrão, o servidor do Unified Manager envia um e-mail de notificação aos usuários que ultrapassaram o limite flexível da cota ou atingiram o limite rígido da cota e para os quais eventos de cota do usuário estão configurados.  Usuários com a função de Administrador do Aplicativo podem configurar alertas que notificam os destinatários especificados sobre eventos de cota do usuário ou grupo de usuários.

Você pode especificar limites de cota usando o ONTAP System Manager ou o ONTAP CLI.
