---
permalink: storage-mgmt/concept_what_options_do_i_have_in_fix_it_button.html 
sidebar: sidebar 
keywords: fix it,fix all 
summary: A página Ações de gerenciamento fornece o botão Corrigir ou Corrigir tudo para corrigir problemas sobre os quais o Unified Manager foi notificado por meio de um evento. 
---
= Quais opções tenho quando vejo o botão Corrigir ou Corrigir tudo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página Ações de gerenciamento fornece o botão *Corrigir* ou *Corrigir tudo* para corrigir problemas sobre os quais o Unified Manager foi notificado por meio de um evento.

Recomendamos que você clique nos botões para corrigir um problema, conforme necessário.  No entanto, se não tiver certeza de que deseja resolver o problema conforme recomendado pelo Unified Manager, você pode executar as seguintes ações:

|===
| O que você quer fazer? | *Ação* 


 a| 
Peça ao Unified Manager para corrigir o problema em todos os objetos identificados.
 a| 
Clique no botão *Corrigir tudo*.



 a| 
Não corrija o problema para nenhum dos objetos identificados neste momento e oculte esta ação de gerenciamento até que o evento seja gerado novamente.
 a| 
Clique na seta para baixo e clique em *Descartar tudo*.



 a| 
Corrija o problema apenas em alguns dos objetos identificados.
 a| 
Clique no nome da ação de gerenciamento para expandir a lista e mostrar todas as ações individuais de *Corrigir*. Em seguida, siga as etapas para corrigir ou descartar ações de gerenciamento individuais.

|===
|===
| O que você quer fazer? | Ação 


 a| 
Peça ao Unified Manager para corrigir o problema.
 a| 
Clique no botão *Corrigir*.



 a| 
Não corrija o problema neste momento e oculte esta ação de gerenciamento até que o evento seja gerado novamente.
 a| 
Clique na seta para baixo e clique em *Descartar*.



 a| 
Exiba os detalhes deste evento para que você possa entender melhor o problema.
 a| 
* Clique no botão *Corrigir* e revise a correção que será aplicada na caixa de diálogo resultante.
* Clique na seta para baixo e clique em *Exibir detalhes do evento* para exibir a página de detalhes do evento.


Em seguida, clique em *Corrigir* em qualquer uma dessas páginas resultantes se quiser corrigir o problema.



 a| 
Exiba os detalhes deste objeto de armazenamento para que você possa entender melhor o problema.
 a| 
Clique no nome do objeto de armazenamento para exibir detalhes na página Performance Explorer ou Detalhes de integridade.

|===
Em alguns casos, a correção é refletida na próxima pesquisa de configuração de 15 minutos.  Em outros casos, pode levar muitas horas para que a alteração de configuração seja verificada e o evento se torne obsoleto.

Para ver a lista de ações de gerenciamento concluídas ou em andamento, clique no ícone de filtro e selecione *Concluídas* ou *Em andamento*.

Corrigir Todas as operações são executadas em série, então quando você visualiza o painel *Em andamento* alguns objetos terão o status *Em andamento* enquanto outros terão o status *Agendado*; o que significa que eles ainda estão aguardando para serem implementados.
