---
permalink: storage-mgmt/concept_monitor_and_manage_clusters_from_dashboard.html 
sidebar: sidebar 
keywords: monitor, manage, clusters, dashboard 
summary: O painel fornece informações cumulativas e rápidas sobre a integridade atual dos seus sistemas ONTAP monitorados.  O painel fornece “painéis” que permitem avaliar a capacidade geral, o desempenho e a integridade da segurança dos clusters que você está monitorando. 
---
= Monitore e gerencie clusters no painel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O painel fornece informações cumulativas e rápidas sobre a integridade atual dos seus sistemas ONTAP monitorados.  O painel fornece "`painéis`" que permitem avaliar a capacidade geral, o desempenho e a integridade da segurança dos clusters que você está monitorando.

Além disso, há certos problemas do ONTAP que você pode corrigir diretamente na interface do usuário do Unified Manager, em vez de ter que usar o ONTAP System Manager ou o ONTAP CLI.

Na parte superior do painel, você pode selecionar se os painéis mostram informações para todos os clusters monitorados ou para um cluster individual.  Você pode começar visualizando o status de todos os clusters e depois detalhar clusters individuais quando quiser visualizar informações detalhadas.

[NOTE]
====
Alguns dos painéis listados abaixo podem não aparecer na página com base na sua configuração.

====
|===
| Painéis | Descrição 


 a| 
Ações de Gestão
 a| 
Quando o Unified Manager consegue diagnosticar e determinar uma única resolução para um problema, essas resoluções são exibidas neste painel com um botão *Corrigir*.



 a| 
Capacidade
 a| 
Exibe a capacidade total e utilizada para o nível local e o nível de nuvem, e o número de dias até que a capacidade local atinja o limite superior.



 a| 
Capacidade de Desempenho
 a| 
Exibe o valor da capacidade de desempenho para cada cluster e o número de dias até que a capacidade de desempenho atinja o limite superior.



 a| 
Carga de trabalho IOPS
 a| 
Exibe o número total de cargas de trabalho que estão sendo executadas em um determinado intervalo de IOPS.



 a| 
Desempenho da carga de trabalho
 a| 
Exibe o número total de cargas de trabalho em conformidade e não em conformidade atribuídas a cada Nível de Serviço de Desempenho definido.



 a| 
Segurança
 a| 
Exibe o número de clusters que estão em conformidade ou não, o número de SVMs que estão em conformidade ou não e o número de volumes que estão criptografados ou não criptografados.



 a| 
Proteção
 a| 
Exibe o número de VMs de armazenamento protegidas pelo relacionamento SVM-DR, volumes protegidos pelo relacionamento SnapMirror , volumes protegidos pelo Snapshot e clusters protegidos pelo MetroCluster.



 a| 
Visão geral do uso
 a| 
Exibe clusters classificados pelo maior IOPS, maior taxa de transferência (MBps) ou maior capacidade física utilizada.

|===