---
permalink: storage-mgmt/reference_dashboard_page.html 
sidebar: sidebar 
keywords: dashboard page, 
summary: A página Painel tem “painéis” que exibem a capacidade de alto nível, o desempenho e a integridade da segurança dos clusters que você está monitorando.  Esta página também fornece um painel Ações de Gerenciamento que lista correções que o Unified Manager pode fazer para resolver determinados eventos. 
---
= Página do painel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página Painel tem "painéis" que exibem a capacidade de alto nível, o desempenho e a integridade da segurança dos clusters que você está monitorando.  Esta página também fornece um painel Ações de Gerenciamento que lista correções que o Unified Manager pode fazer para resolver determinados eventos.

A maioria dos painéis também exibe o número de eventos ativos nessa categoria e o número de novos eventos adicionados nas últimas 24 horas.  Essas informações ajudam você a decidir quais clusters você pode precisar analisar mais detalhadamente para resolver eventos.  Clicar nos eventos exibe os principais eventos e fornece um link para a página de inventário do Gerenciamento de Eventos filtrada para mostrar os eventos ativos naquela categoria.

Na parte superior do painel, você pode selecionar se os painéis mostram informações para todos os clusters monitorados ("Todos os clusters") ou para um cluster individual.  Você pode começar visualizando o status de todos os clusters e depois detalhar clusters individuais quando quiser visualizar informações detalhadas.

[NOTE]
====
Alguns dos painéis listados abaixo aparecem no painel com base na sua configuração.

====


== Painel de Ações de Gestão

Há certos problemas que o Unified Manager pode diagnosticar completamente e fornecer uma única resolução.  Quando disponíveis, essas resoluções são exibidas neste painel com um botão *Corrigir* ou *Corrigir tudo*.  Você pode corrigir esses problemas imediatamente no Unified Manager em vez de ter que usar o ONTAP System Manager ou o ONTAP CLI.  Para visualizar todas as edições, clique em Verlink:concept_fix_ontap_issues_directly_from_unified_manager.html["Corrija problemas do ONTAP diretamente do Unified Manager"] para mais informações.



== Painel de capacidade

Ao visualizar todos os clusters, este painel exibe a capacidade física utilizada (após aplicar economias de eficiência de armazenamento) e a capacidade física disponível (sem incluir economias potenciais de eficiência de armazenamento) para cada cluster, o número de dias até que os discos sejam projetados para ficarem cheios e a taxa de redução de dados (sem cópias de instantâneo) com base nas configurações de eficiência de armazenamento do ONTAP .  Ele também lista a capacidade usada para quaisquer níveis de nuvem configurados.  Clicar no gráfico de barras leva você para a página de inventário de agregados daquele cluster.  Clicar no texto "Dias para atingir a capacidade máxima" exibe uma mensagem que identifica o agregado com o menor número de dias de capacidade restantes; clique no nome do agregado para ver mais detalhes.

Ao visualizar um único cluster, este painel exibe a capacidade física utilizada e a capacidade física disponível para os agregados de dados classificados por cada tipo de disco individual na camada local e na camada de nuvem.  Clicar no gráfico de barras de um tipo de disco leva você à página de inventário de volumes que usam esse tipo de disco.



== Painel de capacidade de desempenho

Ao visualizar todos os clusters, este painel exibe o valor da capacidade de desempenho de cada cluster (média da última hora) e o número de dias até que a capacidade de desempenho atinja o limite superior (com base na taxa de crescimento diária).  Clicar no gráfico de barras leva você para a página de inventário de nós daquele cluster.  Observe que a página de inventário de nós exibe a capacidade de desempenho média das últimas 72 horas.  Clicar no texto "Dias para atingir a capacidade máxima" exibe uma mensagem que identifica o nó com o menor número de dias de capacidade de desempenho restantes; clique no nome do nó para ver mais detalhes.

Ao visualizar um único cluster, este painel exibe a porcentagem de capacidade de desempenho do cluster utilizada, os valores de IOPS total e taxa de transferência total (MB/s), além do número de dias até que cada uma dessas três métricas atinja seu limite superior.



== Painel IOPS de carga de trabalho

Ao visualizar um único cluster, este painel exibe o número total de cargas de trabalho que estão sendo executadas em um determinado intervalo de IOPS e indica o número para cada tipo de disco quando você passa o cursor sobre o gráfico.



== Painel de desempenho da carga de trabalho

Este painel exibe o número total de cargas de trabalho em conformidade e não em conformidade atribuídas a cada política de Nível de Serviço de Desempenho (PSL).  Ele também exibe o número de cargas de trabalho que não têm um PSL atribuído.  Clicar em um gráfico de barras leva você às cargas de trabalho em conformidade atribuídas àquela política na página Cargas de trabalho.  Clicar no número que segue o gráfico de barras leva você às cargas de trabalho em conformidade e não conformidade atribuídas àquela política.



== Painel de segurança

O painel Segurança apresenta o status de segurança de alto nível para todos os clusters ou um único cluster, dependendo da sua visualização atual.  Este painel exibe:

* uma lista dos eventos de segurança recebidos nas últimas 24 horas.  Clique em um evento para ver os detalhes na página Detalhes do evento
* o status de segurança do cluster (contagem de clusters compatíveis e não compatíveis)
* o status de segurança da VM de armazenamento (contagem de VMs de armazenamento compatíveis e não compatíveis)
* o status de criptografia do volume (contagem dos volumes criptografados ou não criptografados)
* o status do volume anti-ransomware (contagem de volumes com anti-ransomware que estão habilitados ou desabilitados)


Você pode clicar nos gráficos de barras dos clusters compatíveis e não compatíveis, VMS de armazenamento, volumes criptografados e não criptografados e status anti-ransomware do volume para acessar as respectivas páginas e visualizar os detalhes de segurança dos clusters filtrados, VMs de armazenamento e volumes.

A conformidade é baseada na https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["Guia de reforço de segurança da NetApp para ONTAP 9"^] .  Clique na seta para a direita na parte superior do painel para visualizar detalhes de segurança de todos os clusters na página Segurança.  Para obter informações, consultelink:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["Visualizando o status de segurança detalhado para clusters e VMs de armazenamento"] .



== Painel de Proteção de Dados

Este painel exibe o resumo da proteção de dados para um ou todos os clusters em um data center.  Ele exibe o número total de eventos de proteção de dados, eventos do MetroCluster e número de eventos ativos gerados nas últimas 24 horas no ONTAP.  Clicar no link de cada um desses eventos leva você para a página de detalhes do evento.  Você pode clicar no link *Exibir tudo* para visualizar todos os eventos de proteção ativos na página de inventário do Gerenciamento de eventos.  O painel exibe:

* O número de volumes em um cluster ou todos os clusters em um data center protegidos por cópias de Snapshot.
* O número de volumes em um cluster ou todos os clusters em um data center protegidos por relacionamentos SnapMirror .  Para relacionamentos SnapMirror , a contagem de volumes no cluster de origem é considerada.
* O número de clusters ou todos os clusters em um data center protegidos pela configuração do MetroCluster sobre IP ou FC.
* O número de relacionamentos de volume com o objetivo do ponto de recuperação (RPO) do SnapMirror varia com base no status do atraso.


Você pode passar o mouse para visualizar as respectivas contagens e legendas.  Você pode clicar na seta para a direita na parte superior do painel para visualizar os detalhes de um ou de todos os clusters na página Proteção de Dados.  Você também pode clicar em:

* Os gráficos de barras para volumes desprotegidos e volumes protegidos por cópias de Snapshot permitem acessar a página Volumes e visualizar os detalhes.
* Os gráficos de barras para os clusters protegidos ou não protegidos pela configuração do MetroCluster permitem acessar a página Clusters e visualizar os detalhes.
* Os gráficos de barras de todos os relacionamentos vão para a página Relacionamentos, onde os detalhes são filtrados com base no cluster de origem.


Para mais informações, consulte link:../data-protection/view-protection-status.html["Visualizando o status de proteção do volume"].



== Painel Visão geral de uso

Ao visualizar todos os clusters, você pode optar por visualizá-los classificados pelo maior IOPS, maior taxa de transferência (MB/s) ou maior capacidade física utilizada.

Ao visualizar um único cluster, você pode optar por visualizar cargas de trabalho classificadas pelo maior IOPS, maior taxa de transferência (MB/s) ou maior capacidade lógica utilizada.

*Informações relacionadas*

link:../events/task_fix_issues_using_um_automatic_remediations.html["Corrigindo problemas usando remediações automáticas do Unified Manager"]

link:../performance-checker/task_display_information_about_performance_event.html["Exibindo informações sobre eventos de desempenho"]

link:../performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html["Gerenciando o desempenho usando a capacidade de desempenho e as informações de IOPS disponíveis"]

link:../health-checker/reference_health_volume_details_page.html["Página de detalhes de volume/saúde"]

link:../performance-checker/reference_performance_event_analysis_and_notification.html["Análise e notificação de eventos de desempenho"]

link:../events/reference_description_of_event_severity_types.html["Descrição dos tipos de gravidade do evento"]

link:../performance-checker/concept_sources_of_performance_events.html["Fontes de eventos de desempenho"]

link:../health-checker/concept_manage_cluster_security_objectives.html["Gerenciar objetivos de segurança do cluster"]

link:../performance-checker/concept_monitor_cluster_performance_from_cluster_landing_page.html["Monitore o desempenho do cluster na página inicial do Performance Cluster"]

link:../performance-checker/concept_monitor_performance_using_object_performance.html["Monitore o desempenho usando as páginas do Inventário de Desempenho"]
