---
permalink: storage-mgmt/reference_unknown_authentication_error.html 
sidebar: sidebar 
keywords: unknown, authentication, error 
summary: 'Solução de problemas: erro de autenticação desconhecido' 
---
= Erro de autenticação desconhecido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao executar uma operação relacionada à autenticação, como adicionar, editar, excluir ou testar usuários ou grupos remotos, a seguinte mensagem de erro pode ser exibida: `Unknown authentication error.`

*Causa*

Esse problema pode ocorrer se você tiver definido um valor incorreto para as seguintes opções:

* Nome do administrador do serviço de autenticação do Active Directory
* Vincular nome distinto do serviço de autenticação OpenLDAP


*Ação corretiva*

. No painel de navegação esquerdo, clique em *Geral* > *Autenticação Remota*.
. Com base no serviço de autenticação selecionado, insira as informações apropriadas para Nome do administrador ou Nome distinto do vínculo.
. Clique em *Testar autenticação* para testar a autenticação com os detalhes que você especificou.
. Clique em *Salvar*.

