---
permalink: storage-mgmt/task_edit_clusters.html 
sidebar: sidebar 
keywords: edit, clusters 
summary: Você pode modificar as configurações de um cluster existente, como o nome do host ou endereço IP, nome de usuário, senha e porta, usando a caixa de diálogo Editar cluster. 
---
= Editar clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode modificar as configurações de um cluster existente, como o nome do host ou endereço IP, nome de usuário, senha e porta, usando a caixa de diálogo Editar cluster.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou a função de Administrador de Armazenamento.

[NOTE]
====
A partir do Unified Manager 9.7, os clusters podem ser adicionados usando somente HTTPS.

====
.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de cluster*.
. Na página *Configuração do cluster*, selecione o cluster que deseja editar e clique em *Editar*.
. Na caixa de diálogo *Editar Cluster*, modifique os valores conforme necessário.  + Se você tiver modificado os detalhes de um cluster adicionado ao Unified Manager, poderá visualizar os detalhes do certificado para comunicação TLS mútua, com base na versão do ONTAP .  Para mais informações sobre a versão ONTAP , consultelink:../storage-mgmt/task_add_clusters.html["Certificados para comunicação TLS mútua"] .  + Você pode visualizar os detalhes do certificado clicando em *Detalhes do certificado*.  Se o certificado estiver expirado, clique no botão *Regenerar* para incorporar o novo certificado.
. Clique em *Enviar*.
. Na caixa de diálogo Autorizar Host, clique em *Exibir Certificado* para visualizar as informações do certificado sobre o cluster.
. Clique em *Sim*.


*Informações relacionadas*

link:../config/task_add_users.html["Adicionando usuários"]

link:../health-checker/task_view_cluster_list_and_details.html["Visualizando a lista de clusters e detalhes"]
