---
permalink: storage-mgmt/task_create_rules_to_generate_email_addresses.html 
sidebar: sidebar 
keywords: create, rules, generate, email, addresses 
summary: 'Você pode criar regras para especificar o endereço de e-mail com base na cota de usuários associada a clusters, máquinas virtuais de armazenamento (SVMs), volumes, qtrees, usuários ou grupos de usuários.  Uma notificação é enviada para o endereço de e-mail especificado quando há uma violação de cota.' 
---
= Crie regras para gerar endereços de e-mail
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar regras para especificar o endereço de e-mail com base na cota de usuários associada a clusters, máquinas virtuais de armazenamento (SVMs), volumes, qtrees, usuários ou grupos de usuários.  Uma notificação é enviada para o endereço de e-mail especificado quando há uma violação de cota.

.Antes de começar
* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter revisado as diretrizes na página Regras para gerar endereços de e-mail de cota de usuários e grupos.


Você deve definir as regras para endereços de e-mail de cota e inseri-las na ordem em que deseja executá-las.  Por exemplo, se você quiser usar o endereço de e-mail abc@xyz.com para receber notificações sobre violações de cota para abc e usar o endereço de e-mail dl-$GROUP@$DOMAIN para todos os outros grupos, as regras devem ser listadas na seguinte ordem:

* se ($USER == 'abc') então abc@xyz.com
* se ($GROUP == *) então dl-$GROUP@$DOMAIN


Se nenhum dos critérios para as regras especificadas for atendido, a regra padrão será usada:

se ($USER_OR_GROUP == *) então $USER_OR_GROUP@$DOMAIN

.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Regras de cota de e-mail*.
. Insira a regra com base em seus critérios.
. Clique em *Validar* para validar a sintaxe da regra.
+
Uma mensagem de erro será exibida se a sintaxe da regra estiver incorreta.  Você deve corrigir a sintaxe e clicar em *Validar* novamente.

. Clique em *Salvar*.
. Verifique se o endereço de e-mail que você criou é exibido na guia *Cotas de usuário e grupo* da página de detalhes *VM / Integridade* do armazenamento.

