---
permalink: storage-mgmt/task_add_space_to_data_disk_of_vmware.html 
sidebar: sidebar 
keywords: add space, data, disk, vmware, virtual, machine 
summary: Se precisar aumentar a quantidade de espaço no disco de dados para o banco de dados do Unified Manager, você poderá adicionar capacidade após a instalação aumentando o espaço em disco usando o console de manutenção do Unified Manager. 
---
= Adicionar espaço ao disco de dados da máquina virtual VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se precisar aumentar a quantidade de espaço no disco de dados para o banco de dados do Unified Manager, você poderá adicionar capacidade após a instalação aumentando o espaço em disco usando o console de manutenção do Unified Manager.

.Antes de começar
* Você deve ter acesso ao vSphere Client.
* A máquina virtual não deve ter instantâneos armazenados localmente.
* Você deve ter as credenciais de usuário de manutenção.


Recomendamos que você faça backup da sua máquina virtual antes de aumentar o tamanho dos discos virtuais.

.Passos
. No cliente vSphere, selecione a máquina virtual do Unified Manager e adicione mais capacidade de disco aos dados `disk 3` .  Consulte a documentação do VMware para obter detalhes.
+
Em alguns casos raros, a implantação do Unified Manager usa "Disco Rígido 2" para o disco de dados em vez de "Disco Rígido 3".  Se isso ocorreu na sua implantação, aumente o espaço do disco que for maior.  O disco de dados sempre terá mais espaço que o outro disco.

. No cliente vSphere, selecione a máquina virtual Unified Manager e, em seguida, selecione a guia *Console*.
. Clique na janela do console e faça login no console de manutenção usando seu nome de usuário e senha.
. No *Menu Principal*, insira o número da opção *Configuração do Sistema*.
. No *Menu de Configuração do Sistema*, insira o número da opção *Aumentar Tamanho do Disco de Dados*.

