---
permalink: storage-mgmt/task_monitor_metrocluster_replication.html 
sidebar: sidebar 
keywords: monitor, metrocluster, replication 
summary: Você pode monitorar e diagnosticar a condição geral de saúde das conexões lógicas enquanto espelha os dados.  Você pode identificar os problemas ou qualquer risco que interrompa o espelhamento de componentes do cluster, como agregados, nós e máquinas virtuais de armazenamento. 
---
= Monitorar a replicação do MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode monitorar e diagnosticar a condição geral de saúde das conexões lógicas enquanto espelha os dados.  Você pode identificar os problemas ou qualquer risco que interrompa o espelhamento de componentes do cluster, como agregados, nós e máquinas virtuais de armazenamento.

O Unified Manager usa alertas de integridade do sistema para monitorar o status dos componentes e a conectividade na configuração do MetroCluster .

.Antes de começar
Tanto o cluster local quanto o remoto na configuração do MetroCluster devem ser adicionados ao Unified Manager



[[view-replication-for-metrocluster-over-ip-configurations]]
== Exibir replicação para configurações do MetroCluster sobre IP

Para configurações do MetroCluster sobre IP, o status da replicação de dados é exibido na visualização de visualização da topologia para um cluster protegido pelo MetroCluster sobre IP nas seguintes visualizações do painel de navegação esquerdo do Unified Manager:

* *Armazenamento* > *Clusters* > *Proteção: MetroCluster* view
* *Proteção* > *Relacionamentos* > *Relacionamento: MetroCluster* visualizar


Para obter informações, consultelink:../storage-mgmt/task_monitor_metrocluster_configurations.html#monitor-connectivity-issues-in-metrocluster-over-ip-configuration["Monitorar problemas de conectividade no MetroCluster por IP"] .



[[view-replication-for-metrocluster-over-fc-configurations]]
== Exibir replicação para MetroCluster sobre configurações de FC

Siga estas etapas para determinar quaisquer problemas na replicação de dados para a configuração do MetroCluster sobre FC.

.Passos
. No painel de navegação esquerdo, clique em *Armazenamento* > *Clusters*.
+
Uma lista dos clusters monitorados é exibida.

. Na exibição *Saúde: Todos os clusters*, clique no nome do cluster para o qual você deseja visualizar os detalhes de replicação do MetroCluster .  Na página *Detalhes do cluster/saúde*, clique na guia *Replicação do MetroCluster *.
+
A topologia da configuração do MetroCluster a ser replicada é exibida no site local na área de objeto do cluster correspondente com as informações sobre o site remoto onde os dados estão sendo espelhados.  Se você mover o ponteiro sobre o ícone, poderá visualizar informações detalhadas sobre o evento gerado.



Você pode usar as informações exibidas na página Detalhes do cluster/integridade para corrigir quaisquer problemas de replicação.  Se você descobrir problemas de espelhamento na configuração do MetroCluster , deverá efetuar login no Gerenciador do Sistema ou acessar o ONTAP CLI para resolver os problemas.

*Informações relacionadas*

link:../health-checker/reference_health_cluster_details_page.html["Página de detalhes do cluster/saúde"]
