---
permalink: storage-mgmt/task_add_space_to_data_directory_of_um_linux_host.html 
sidebar: sidebar 
keywords: add, space, data directory, linux host 
summary: 'Se você alocou espaço em disco insuficiente para o `/opt/netapp/data` diretório para oferecer suporte ao Unified Manager quando você configurou originalmente o host Linux e depois instalou o Unified Manager, você pode adicionar espaço em disco após a instalação aumentando o espaço em disco no `/opt/netapp/data` diretório.' 
---
= Adicionar espaço ao diretório de dados do host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você alocou espaço em disco insuficiente para o `/opt/netapp/data` diretório para oferecer suporte ao Unified Manager quando você configurou originalmente o host Linux e depois instalou o Unified Manager, você pode adicionar espaço em disco após a instalação aumentando o espaço em disco no `/opt/netapp/data` diretório.

.Antes de começar
Você deve ter acesso de usuário root à máquina Red Hat Enterprise Linux na qual o Unified Manager está instalado.

Recomendamos que você faça backup do banco de dados do Unified Manager antes de aumentar o tamanho do diretório de dados.

.Passos
. Efetue login como usuário root na máquina Linux na qual você deseja adicionar espaço em disco.
. Pare o serviço Unified Manager e o software MySQL associado na ordem mostrada: `systemctl stop ocieau ocie mysqld`
. Crie uma pasta de backup temporária (por exemplo, `/backup-data` ) com espaço em disco suficiente para conter os dados no atual `/opt/netapp/data` diretório.
. Copie o conteúdo e a configuração de privilégios do existente `/opt/netapp/data` diretório para o diretório de dados de backup:
+
`cp -arp /opt/netapp/data/* /backup-data`

. Se o SE Linux estiver habilitado:
+
.. Obtenha o tipo SE Linux para pastas existentes `/opt/netapp/data` pasta:
+
`se_type=`ls -Z /opt/netapp/data| awk '{print $4}'| awk -F: '{print $3}'| head -1`

+
O sistema retorna uma confirmação semelhante à seguinte:

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. Execute o `chcon` comando para definir o tipo SE Linux para o diretório de backup:
+
`chcon -R --type=mysqld_db_t /backup-data`



. Remova o conteúdo do `/opt/netapp/data` diretório:
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. Expandir o tamanho do `/opt/netapp/data` diretório para um mínimo de 150 GB por meio de comandos LVM ou adicionando discos extras.
+
[NOTE]
====
Se você criou `/opt/netapp/data` de um disco, então você não deve tentar montar `/opt/netapp/data` como um compartilhamento NFS ou CIFS.  Porque, neste caso, se você tentar expandir o espaço em disco, alguns comandos LVM, como `resize` e `extend` pode não funcionar como esperado.

====
. Confirme que o `/opt/netapp/data` o proprietário do diretório (mysql) e o grupo (root) não foram alterados:
+
`ls -ltr /opt/netapp/ | grep data`

+
O sistema retorna uma confirmação semelhante à seguinte:

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. Se o SE Linux estiver habilitado, confirme se o contexto para o `/opt/netapp/data` o diretório ainda está definido como mysqld_db_t:
+
.. `touch /opt/netapp/data/abc`
.. `ls -Z /opt/netapp/data/abc`
+
O sistema retorna uma confirmação semelhante à seguinte:

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----


. Excluir o arquivo `abc` para que esse arquivo estranho não cause um erro no banco de dados no futuro.
. Copie o conteúdo de `backup-data` de volta ao expandido `/opt/netapp/data` diretório:
+
`cp -arp /backup-data/* /opt/netapp/data/`

. Se o SE Linux estiver habilitado, execute o seguinte comando:
+
`chcon -R --type=mysqld_db_t /opt/netapp/data`

. Inicie o serviço MySQL:
+
`systemctl start mysqld`

. Após o serviço MySQL ser iniciado, inicie os serviços ocie e ocieau na ordem mostrada:
+
`systemctl start ocie ocieau`

. Depois que todos os serviços forem iniciados, exclua a pasta de backup `/backup-data` :
+
`rm -rf /backup-data`


