---
permalink: storage-mgmt/task_add_clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: Você pode adicionar um cluster ao Active IQ Unified Manager para poder monitorá-lo.  Isso inclui a capacidade de obter informações do cluster, como integridade, capacidade, desempenho e configuração do cluster, para que você possa localizar e resolver quaisquer problemas que possam ocorrer. 
---
= Adicionar clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar um cluster ao Active IQ Unified Manager para poder monitorá-lo.  Isso inclui a capacidade de obter informações do cluster, como integridade, capacidade, desempenho e configuração do cluster, para que você possa localizar e resolver quaisquer problemas que possam ocorrer.

.Antes de começar
* Você deve ter a função de Administrador de Aplicativos ou a função de Administrador de Armazenamento.
* Você deve ter as seguintes informações:
+
** O Unified Manager oferece suporte a clusters ONTAP locais, ONTAP Select e Cloud Volumes ONTAP.
** Você deve ter o nome do host ou o endereço IP de gerenciamento do cluster (IPv4 ou IPv6) para o cluster.
+
Ao usar o nome do host, ele deve ser resolvido para o endereço IP de gerenciamento do cluster para o LIF de gerenciamento do cluster.  Se você usar um LIF de gerenciamento de nó, a operação falhará.

** Você deve ter o nome de usuário e a senha para acessar o cluster.
+
Esta conta deve ter a função _admin_ com acesso ao aplicativo definido como _ontapi_, _console_ e _http_.

** Você deve saber o número da porta para se conectar ao cluster usando o protocolo HTTPS (normalmente porta 443).
** O cluster deve estar executando o software ONTAP versão 9.9 ou superior.
** Você deve ter espaço adequado no servidor do Unified Manager.  Você não poderá adicionar um cluster ao servidor quando mais de 90% do espaço já estiver consumido.
** Você possui os certificados necessários:
+
*Certificado SSL (HTTPS)*: Este certificado é de propriedade do Unified Manager.  Um certificado SSL autoassinado padrão (HTTPS) é gerado com uma nova instalação do Unified Manager.  A NetApp recomenda que você atualize para um certificado assinado por CA para maior segurança.  Se o certificado do servidor expirar, você deverá regenerá-lo e reiniciar o Unified Manager para que os serviços incorporem o novo certificado.  Para obter mais informações sobre a regeneração do certificado SSL, consultelink:../config/task_generate_an_https_security_certificate_ocf.html["Gerando um certificado de segurança HTTPS"] .

+
*Certificado EMS*: Este certificado é de propriedade do Unified Manager.  É usado durante a autenticação para notificações EMS recebidas do ONTAP.

+
*Certificados para comunicação TLS mútua*: usados ​​durante a comunicação TLS mútua entre o Unified Manager e o ONTAP.  A autenticação baseada em certificado é habilitada para um cluster, com base na versão do ONTAP .  Se o cluster que executa a versão do ONTAP for inferior à 9.5, a autenticação baseada em certificado não será habilitada.

+
A autenticação baseada em certificado não será habilitada automaticamente para um cluster se você estiver atualizando uma versão mais antiga do Unified Manager.  No entanto, você pode habilitá-lo modificando e salvando os detalhes do cluster.  Se o certificado expirar, você deverá regenerá-lo para incorporar o novo certificado.  Para obter mais informações sobre como visualizar e regenerar o certificado, consultelink:../storage-mgmt/task_edit_clusters.html["Editando clusters"] .

+
[NOTE]
====
*** Você pode adicionar um cluster a partir da interface da web, e a autenticação baseada em certificado será ativada automaticamente.
*** Você pode adicionar um cluster por meio do Unified Manager CLI; a autenticação baseada em certificado não está habilitada por padrão.  Se você adicionar um cluster usando a CLI do Unified Manager, será necessário editar o cluster usando a interface do usuário do Unified Manager.  Você pode verlink:https://docs.netapp.com/us-en/active-iq-unified-manager/events/reference_supported_unified_manager_cli_commands.html["Comandos CLI do Unified Manager suportados"] para adicionar um cluster usando o Unified Manager CLI.
*** Se a autenticação baseada em certificado estiver habilitada para um cluster e você fizer o backup do Unified Manager de um servidor e restaurar em outro servidor do Unified Manager onde o nome do host ou endereço IP for alterado, o monitoramento do cluster poderá falhar.  Para evitar a falha, edite e salve os detalhes do cluster.  Para obter mais informações sobre a edição de detalhes do cluster, consultelink:../storage-mgmt/task_edit_clusters.html["Editando clusters"] .
*** No nível do cluster, a interface do Active IQ adiciona duas novas entradas de grupo de usuários para o método de autenticação "cert".


====
+
*Certificados de cluster*: Este certificado é de propriedade da ONTAP.  Não é possível adicionar um cluster ao Unified Manager com um certificado expirado e, se o certificado já tiver expirado, você deverá regenerá-lo antes de adicionar o cluster.  Para obter informações sobre a geração de certificados, consulte o artigo da base de conhecimento (KB) https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["Como renovar um certificado autoassinado ONTAP na interface de usuário do System Manager"^] .



* Uma única instância do Unified Manager pode suportar um número específico de nós.  Se você precisar monitorar um ambiente que exceda a contagem de nós suportada, deverá instalar uma instância adicional do Unified Manager para monitorar alguns dos clusters.  Para visualizar a lista de contagem de nós suportados, consulte o https://www.netapp.com/media/13504-tr4621.pdf["Guia de práticas recomendadas do Unified Manager"^] .


.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de cluster*.
. Na página Configuração do cluster, clique em *Adicionar*.
. Na caixa de diálogo Adicionar cluster, especifique os valores conforme necessário e clique em *Enviar*.
. Na caixa de diálogo Autorizar Host, clique em *Exibir Certificado* para visualizar as informações do certificado sobre o cluster.
. Clique em *Sim*.
+
Depois de salvar os detalhes do cluster, você pode ver o certificado para comunicação TLS mútua de um cluster.

+
Se a autenticação baseada em certificado não estiver habilitada, o Unified Manager verificará o certificado somente quando o cluster for adicionado inicialmente.  O Unified Manager não verifica o certificado para cada chamada de API para o ONTAP.



Depois que todos os objetos de um novo cluster são descobertos, o Unified Manager começa a coletar dados históricos de desempenho dos 15 dias anteriores.  Essas estatísticas são coletadas usando a funcionalidade de coleta de continuidade de dados.  Este recurso fornece mais de duas semanas de informações de desempenho para um cluster imediatamente após ele ser adicionado.  Após a conclusão do ciclo de coleta de continuidade de dados, os dados de desempenho do cluster em tempo real são coletados, por padrão, a cada cinco minutos.

[NOTE]
====
* A coleta de 15 dias de dados de desempenho exige muito da CPU. A NetApp recomenda que você escalone a adição de novos clusters para que as pesquisas de coleta de continuidade de dados não sejam executadas em muitos clusters ao mesmo tempo. Além disso, se você reiniciar o Unified Manager durante o período de coleta de continuidade de dados, a coleta será interrompida e você verá lacunas nos gráficos de desempenho para o período ausente.
* Quando você adiciona um cluster ONTAP com a versão 9.14.1 ou posterior, a comunicação ocorre por meio do recurso do agente de nuvem. O ONTAP cria automaticamente um usuário de conta de serviço interno com privilégios somente leitura (por exemplo, clus-agent-xxxx). O Unified Manager para de coletar dados desses clusters se o `clus-agent` o usuário é excluído.


====
[TIP]
====
Se você receber uma mensagem de erro informando que não é possível adicionar o cluster, verifique se os seguintes problemas existem:

* Se os relógios nos dois sistemas não estiverem sincronizados e a data de início do certificado HTTPS do Unified Manager for posterior à data no cluster.  Você deve garantir que os relógios estejam sincronizados usando NTP ou um serviço similar.
* Se o cluster atingir o número máximo de destinos de notificação EMS, o endereço do Unified Manager não poderá ser adicionado.  Por padrão, apenas 20 destinos de notificação EMS podem ser definidos no cluster.


====
*Informações relacionadas*

link:../config/task_add_users.html["Adicionando usuários"]

link:../health-checker/task_view_cluster_list_and_details.html["Visualizando a lista de clusters e detalhes"]

link:../config/task_install_ca_signed_and_returned_https_certificate.html#example-certificate-chain["Instalando um certificado HTTPS assinado e retornado por uma CA"]
