---
permalink: storage-mgmt/task_remove_clusters.html 
sidebar: sidebar 
keywords: remove, cluster 
summary: Você pode remover um cluster do Unified Manager usando a página Configuração do Cluster.  Por exemplo, você pode remover um cluster se a descoberta do cluster falhar ou quando quiser desativar um sistema de armazenamento. 
---
= Remover clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode remover um cluster do Unified Manager usando a página Configuração do Cluster.  Por exemplo, você pode remover um cluster se a descoberta do cluster falhar ou quando quiser desativar um sistema de armazenamento.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou a função de Administrador de Armazenamento.

Esta tarefa remove o cluster selecionado do Unified Manager.  Depois que um cluster é removido, ele não é mais monitorado.  A instância do Unified Manager registrada no cluster removido também não é registrada no cluster.

A remoção de um cluster também exclui todos os seus objetos de armazenamento, dados históricos, serviços de armazenamento e todos os eventos associados do Unified Manager.  Essas alterações são refletidas nas páginas de inventário e nas páginas de detalhes após o próximo ciclo de coleta de dados.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de cluster*.
. Na página Configuração do cluster, selecione o cluster que você deseja remover e clique em *Remover*.
. Na caixa de diálogo da mensagem *Remover fonte de dados*, clique em *Remover* para confirmar a solicitação de remoção.


*Informações relacionadas*

link:../config/task_add_users.html["Adicionando usuários"]

link:../health-checker/task_view_cluster_list_and_details.html["Visualizando a lista de clusters e detalhes"]
