---
permalink: health-checker/concept_understand_capacity_events_and_thresholds_for_node.html 
sidebar: sidebar 
keywords: understand, events, thresholds, node, root, aggregates 
summary: Você pode monitorar o agregado raiz do nó usando o Unified Manager.  A melhor prática é provisionar densamente o volume raiz no agregado raiz para evitar que o nó pare. 
---
= Entenda eventos e limites para agregados de raiz de nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode monitorar o agregado raiz do nó usando o Unified Manager.  A melhor prática é provisionar densamente o volume raiz no agregado raiz para evitar que o nó pare.

Por padrão, eventos de capacidade e desempenho não são gerados para agregados raiz.  Além disso, os valores limite usados pelo Unified Manager não são aplicáveis aos agregados raiz do nó.  Somente um representante de suporte técnico pode modificar as configurações para que esses eventos sejam gerados.  Quando as configurações são modificadas pelo representante de suporte técnico, os valores de limite de capacidade são aplicados ao agregado raiz do nó.

Você pode tomar as medidas apropriadas para evitar que o nó pare usando o ONTAP System Manager ou o ONTAP CLI.


NOTE: A funcionalidade de monitoramento de agregados raiz de nós não estará disponível se os clusters executarem o ONTAP versão 9.14.1 ou posterior.
