---
permalink: health-checker/concept_how_group_actions_work_on_storage_objects.html 
sidebar: sidebar 
keywords: group actions, work, storage, objects 
summary: Uma ação de grupo é uma operação executada em todos os objetos de armazenamento em um grupo.  Por exemplo, você pode configurar a ação do grupo de limite de volume para alterar simultaneamente os valores de limite de volume de todos os volumes em um grupo. 
---
= Como as ações de grupo funcionam em objetos de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma ação de grupo é uma operação executada em todos os objetos de armazenamento em um grupo.  Por exemplo, você pode configurar a ação do grupo de limite de volume para alterar simultaneamente os valores de limite de volume de todos os volumes em um grupo.

Os grupos oferecem suporte a tipos exclusivos de ações de grupo.  Você pode ter um grupo com apenas um tipo de ação de grupo de limite de integridade de volume.  No entanto, você pode configurar um tipo diferente de ação de grupo, se disponível, para o mesmo grupo.  A classificação de uma ação de grupo determina a ordem em que a ação é aplicada aos objetos de armazenamento.  A página de detalhes de um objeto de armazenamento fornece informações sobre qual ação de grupo é aplicada no objeto de armazenamento.



[[example-of-unique-group-actions]]
== Exemplo de ações de grupo exclusivas

Considere um volume A que pertence aos grupos G1 e G2, e as seguintes ações de grupo de limite de integridade de volume são configuradas para esses grupos:

* `Change_capacity_threshold`ação de grupo com classificação 1, para configurar a capacidade do volume
* `Change_snapshot_copies`ação de grupo com classificação 2, para configurar as cópias de Snapshot do volume


O `Change_capacity_threshold` a ação do grupo sempre tem prioridade sobre a `Change_snapshot_copies` ação de grupo e é aplicada ao volume A. Quando o Unified Manager conclui um ciclo de monitoramento, os eventos relacionados ao limite de integridade do volume A são reavaliados de acordo com o `Change_capacity_threshold` ação em grupo.  Não é possível configurar outro tipo de limite de volume de ação de grupo para o grupo G1 ou G2.
