---
permalink: health-checker/concept_what_annotations_are.html 
sidebar: sidebar 
keywords: annotations 
summary: 'Uma anotação é uma sequência de texto (o nome) que é atribuída a outra sequência de texto (o valor).  Cada par nome-valor de anotação pode ser associado dinamicamente a objetos de armazenamento usando regras de anotação.  Ao associar objetos de armazenamento a anotações predefinidas, você pode filtrar e visualizar os eventos relacionados a eles.  Você pode aplicar anotações a clusters, volumes e máquinas virtuais de armazenamento (SVMs).' 
---
= O que são anotações
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma anotação é uma sequência de texto (o nome) que é atribuída a outra sequência de texto (o valor).  Cada par nome-valor de anotação pode ser associado dinamicamente a objetos de armazenamento usando regras de anotação.  Ao associar objetos de armazenamento a anotações predefinidas, você pode filtrar e visualizar os eventos relacionados a eles.  Você pode aplicar anotações a clusters, volumes e máquinas virtuais de armazenamento (SVMs).

Cada nome de anotação pode ter vários valores; cada par nome-valor pode ser associado a um objeto de armazenamento por meio de regras.

Por exemplo, você pode criar uma anotação chamada "`data-center`" com os valores "`Boston`" e "`Canada`".  Você pode então aplicar a anotação "`data-center`" com o valor "`Boston`" ao volume v1.  Quando um alerta é gerado para qualquer evento em um volume v1 anotado com "`data-center`", o e-mail gerado indica a localização do volume, "`Boston`", e isso permite que você priorize e resolva o problema.
