---
permalink: health-checker/concept_configure_destination_and_schedule_for_database_dump_backups.html 
sidebar: sidebar 
keywords: configure, destination, schedule, database dump, backups, snapshot copy, copies 
summary: Você pode configurar as definições de backup de despejo do banco de dados do Unified Manager para definir o caminho do backup do banco de dados, a contagem de retenção e o agendamento de backup.  Você pode habilitar backups agendados diários ou semanais.  Por padrão, os backups agendados estão desabilitados, mas você deve definir um agendamento de backup. 
---
= Configurar o destino e a programação para backups de despejo de banco de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar as definições de backup de despejo do banco de dados do Unified Manager para definir o caminho do backup do banco de dados, a contagem de retenção e o agendamento de backup.  Você pode habilitar backups agendados diários ou semanais.  Por padrão, os backups agendados estão desabilitados, mas você deve definir um agendamento de backup.

.Antes de começar
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter no mínimo 150 GB de espaço disponível no local definido como caminho de backup.
+
É recomendável que você use um local remoto externo ao sistema host do Unified Manager.

* Quando o Unified Manager estiver instalado em um sistema Linux e usando o backup do MySQL, certifique-se de que as seguintes permissões e propriedades estejam definidas no diretório de backup.
+
Permissões: 0750, Propriedade: jboss:maintenance

* Quando o Unified Manager estiver instalado em um sistema Windows e usando o backup do MySQL, certifique-se de que somente o administrador tenha acesso ao diretório de backup.


É necessário mais tempo na primeira vez que um backup é executado do que nos backups subsequentes, porque o primeiro backup é um backup completo.  Um backup completo pode ter mais de 1 GB e levar de três a quatro horas.  Os backups subsequentes são incrementais e exigem menos tempo.

[NOTE]
====
* Se você achar que o número de arquivos de backup incremental é muito grande para o espaço alocado para backups, você pode fazer um backup completo periodicamente para substituir o backup antigo e seus arquivos incrementais.  Como outra opção, você pode fazer um backup usando cópias instantâneas.
* O backup feito durante os primeiros 15 dias de adição de um novo cluster pode não ser preciso o suficiente para obter os dados históricos de desempenho.


====
.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Backup de banco de dados*.
. Na página *Backup do banco de dados*, clique em *Configurações de backup*.
. Configure os valores apropriados para um caminho de backup, contagem de retenção e agendamento.
+
O valor padrão para contagem de retenção é 10; você pode usar 0 para criar backups ilimitados.

. Selecione o botão *Agendado diariamente* ou *Agendado semanalmente* e especifique os detalhes da programação.
. Clique em *Aplicar*.


Os arquivos de backup de despejo do banco de dados são criados com base na programação.  Você pode ver os arquivos de backup disponíveis na página Backup do banco de dados.
