---
permalink: health-checker/concept_how_group_rules_work_for_groups.html 
sidebar: sidebar 
keywords: group rules, work, groups 
summary: 'Uma regra de grupo é um critério que você define para permitir que objetos de armazenamento (volumes, clusters ou SVMs) sejam incluídos em um grupo específico.  Você pode usar grupos de condições ou condições para definir regras de grupo para um grupo.' 
---
= Como as regras de grupo funcionam para grupos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma regra de grupo é um critério que você define para permitir que objetos de armazenamento (volumes, clusters ou SVMs) sejam incluídos em um grupo específico.  Você pode usar grupos de condições ou condições para definir regras de grupo para um grupo.

* Você deve associar uma regra de grupo a um grupo.
* Você deve associar um tipo de objeto a uma regra de grupo; somente um tipo de objeto é associado a uma regra de grupo.
* Objetos de armazenamento são adicionados ou removidos do grupo após cada ciclo de monitoramento ou quando uma regra é criada, editada ou excluída.
* Uma regra de grupo pode ter um ou mais grupos de condições, e cada grupo de condições pode ter uma ou mais condições.
* Os objetos de armazenamento podem pertencer a vários grupos com base nas regras de grupo que você criar.




[[conditions]]
== Condições

Você pode criar vários grupos de condições, e cada grupo de condições pode ter uma ou mais condições.  Você pode aplicar todos os grupos de condições definidos em uma regra de grupo para grupos, a fim de especificar quais objetos de armazenamento estão incluídos no grupo.

As condições dentro de um grupo de condições são executadas usando AND lógico.  Todas as condições em um grupo de condições devem ser atendidas.  Quando você cria ou modifica uma regra de grupo, é criada uma condição que aplica, seleciona e agrupa somente os objetos de armazenamento que atendem a todas as condições no grupo de condições.  Você pode usar várias condições dentro de um grupo de condições quando quiser restringir o escopo de quais objetos de armazenamento incluir em um grupo.

Você pode criar condições com objetos de armazenamento usando os seguintes operandos e operadores e especificando o valor necessário.

[cols="2*"]
|===
| Tipo de objeto de armazenamento | Operandos aplicáveis 


 a| 
Volume
 a| 
* Nome do objeto
* Nome do cluster proprietário
* Possuir nome SVM
* Anotações




 a| 
SVM
 a| 
* Nome do objeto
* Nome do cluster proprietário
* Anotações




 a| 
Conjunto
 a| 
* Nome do objeto
* Anotações


|===
Quando você seleciona anotação como um operando para qualquer objeto de armazenamento, o operador "`Is`" fica disponível.  Para todos os outros operandos, você pode selecionar "`Is`" ou "`Contains`" como operador.

* Operando
+
A lista de operandos no Unified Manager muda com base no tipo de objeto selecionado.  A lista inclui o nome do objeto, o nome do cluster proprietário, o nome do SVM proprietário e as anotações que você define no Unified Manager.

* Operador
+
A lista de operadores muda com base no operando selecionado para uma condição.  Os operadores suportados no Unified Manager são "`Is`" e "`Contains`".

+
Quando você seleciona o operador "`Is`", a condição é avaliada para correspondência exata do valor do operando com o valor fornecido para o operando selecionado.

+
Quando você seleciona o operador "`Contém`", a condição é avaliada para atender a um dos seguintes critérios:

+
** O valor do operando é uma correspondência exata ao valor fornecido para o operando selecionado
** O valor do operando contém o valor fornecido para o operando selecionado


* Valor
+
O campo de valor muda com base no operando selecionado.





[[example-of-a-group-rule-with-conditions]]
== Exemplo de uma regra de grupo com condições

Considere um grupo de condições para um volume com as duas condições a seguir:

* O nome contém "`vol`"
* O nome do SVM é "`data_svm`"


Este grupo de condições seleciona todos os volumes que incluem "`vol`" em seus nomes e que estão hospedados em SVMs com o nome "`data_svm`".



[[condition-groups]]
== Grupos de condições

Grupos de condições são executados usando OR lógico e depois aplicados a objetos de armazenamento.  Os objetos de armazenamento devem satisfazer um dos grupos de condições para serem incluídos em um grupo.  Os objetos de armazenamento de todos os grupos de condições são combinados.  Você pode usar grupos de condições para aumentar o escopo de objetos de armazenamento a serem incluídos em um grupo.



[[example-of-a-group-rule-with-condition-groups]]
== Exemplo de uma regra de grupo com grupos de condições

Considere dois grupos de condições para um volume, com cada grupo contendo as duas condições a seguir:

* Grupo de condição 1
+
** O nome contém "`vol`"
** O nome do SVM é "`data_svm`". O grupo de condições 1 seleciona todos os volumes que incluem "`vol`" em seus nomes e que estão hospedados em SVMs com o nome "`data_svm`".


* Grupo de condição 2
+
** O nome contém "`vol`"
** O valor de anotação de data-priority é "`crítico`". O grupo de condições 2 seleciona todos os volumes que incluem "`vol`" em seus nomes e que são anotados com o valor de anotação de data-priority como "`crítico`".




Quando uma regra de grupo contendo esses dois grupos de condições é aplicada em objetos de armazenamento, os seguintes objetos de armazenamento são adicionados a um grupo selecionado:

* Todos os volumes que incluem "`vol`" em seus nomes e que estão hospedados no SVM com o nome "`data_svm`".
* Todos os volumes que incluem "`vol`" em seus nomes e que são anotados com o valor de anotação de prioridade de dados "`critical`".

