---
permalink: health-checker/concept_manage_backup_and_restore_operations.html 
sidebar: sidebar 
keywords: backup, types, manage, restore, operations 
summary: 'Você pode criar backups do Active IQ Unified Manager e usar o recurso de restauração para restaurar o backup no mesmo sistema (local) ou em um novo sistema (remoto) em caso de falha do sistema ou perda de dados.' 
---
= Gerenciar operações de backup e restauração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar backups do Active IQ Unified Manager e usar o recurso de restauração para restaurar o backup no mesmo sistema (local) ou em um novo sistema (remoto) em caso de falha do sistema ou perda de dados.

Há três métodos de backup e restauração, dependendo do sistema operacional no qual você instalou o Unified Manager e com base no número de clusters e nós que estão sendo gerenciados:

[cols="3*"]
|===
| Sistema operacional | Tamanho da implantação | Método de backup recomendado 


 a| 
VMware vSphere
 a| 
Qualquer
 a| 
Instantâneo do VMware do appliance virtual do Unified Manager



.2+| Red Hat Enterprise Linux  a| 
Pequeno
 a| 
Despejo de banco de dados MySQL do Unified Manager



 a| 
Grande
 a| 
Instantâneo do NetApp do banco de dados do Unified Manager



.2+| Microsoft Windows  a| 
Pequeno
 a| 
Despejo de banco de dados MySQL do Unified Manager



 a| 
Grande
 a| 
Instantâneo do NetApp do banco de dados do Unified Manager com protocolo iSCSI

|===
Esses diferentes métodos são descritos nas seções a seguir.
