---
permalink: health-checker/concept_configure_backup_for_windows.html 
sidebar: sidebar 
keywords: backup, restore, windows, netapp, snapshot copy, copies, configure, backup 
summary: O Active IQ Unified Manager oferece suporte a backup e restauração usando NetApp Snapshots no sistema operacional Windows com a ajuda de LUN usando o protocolo iSCSI. 
---
= Configurar backup no Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Active IQ Unified Manager oferece suporte a backup e restauração usando NetApp Snapshots no sistema operacional Windows com a ajuda de LUN usando o protocolo iSCSI.

O backup baseado em instantâneo pode ser feito enquanto todos os serviços do Unified Manager estão em execução.  Um estado consistente do banco de dados é capturado como parte do Snapshot, pois o backup coloca um bloqueio de leitura global em todo o banco de dados que impede qualquer gravação simultânea.  Para que seu sistema Unified Manager instalado no sistema operacional Windows execute backup e restauração usando o NetApp Snapshots, você deve primeiro configurar o backup do Unified Manager para Snapshot usando o console de manutenção.

Antes de configurar o Unified Manager para criar cópias de Snapshot, você deve executar as seguintes tarefas de configuração.

* Configurar cluster ONTAP
* Configurar máquina host do Windows

