---
permalink: health-checker/reference_configure_ontap_cluster.html 
sidebar: sidebar 
keywords: netapp, snapshot copy, copies, backup, windows, configure, ontap, cluster 
summary: Você precisa executar algumas etapas de pré-configuração em clusters ONTAP antes de poder fazer backup e restaurar o Active IQ Unified Manager usando a cópia de instantâneo em sistemas Windows. 
---
= Configurar cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa executar algumas etapas de pré-configuração em clusters ONTAP antes de poder fazer backup e restaurar o Active IQ Unified Manager usando a cópia de instantâneo em sistemas Windows.

Você pode configurar o cluster ONTAP usando o prompt de comando ou a interface de usuário do System Manager.  A configuração do cluster ONTAP envolve a configuração de LIFs de dados para que fiquem disponíveis para serem atribuídos como LIFs iSCSI à VM de armazenamento.  A próxima etapa é configurar uma VM de armazenamento habilitada para iSCSI usando a interface de usuário do System Manager.  Você precisará configurar uma rota de rede estática para esta VM de armazenamento para controlar como os LIFs usam a rede para tráfego de saída.

[NOTE]
====
Você deve ter um volume dedicado e um LUN para configuração de backup.  O volume selecionado deve incluir apenas um LUN.  O tamanho do LUN deve ser pelo menos duas vezes o tamanho dos dados que o Active IQ Unified Manager espera manipular.

====
Você precisa executar a seguinte configuração:

.Passos
. Configure uma VM de armazenamento habilitada para iSCSI ou use uma VM de armazenamento existente que tenha a mesma configuração.
. Configure uma rota de rede para a VM de armazenamento configurada.
. Configure um volume de capacidade apropriada e um único LUN interno, garantindo que o volume seja dedicado somente para esse LUN.
+

NOTE: Em um cenário em que o LUN é criado no Gerenciador do Sistema, desmapear o LUN pode excluir o igroup e a restauração pode falhar.  Para evitar esse cenário, certifique-se de que, ao criar um LUN, ele seja criado explicitamente e não seja excluído quando o LUN for desmapeado.

. Configure um grupo de iniciadores na VM de armazenamento.
. Configurar um conjunto de portas.
. Integre o igroup com o portset.
. Mapeie o LUN para o igroup.

