---
permalink: health-checker/reference_volume_compliance_categories.html 
sidebar: sidebar 
keywords: volume, encryption, compliance, categories 
summary: Esta tabela descreve os parâmetros de criptografia de volume que o Unified Manager avalia para determinar se os dados em seus volumes estão adequadamente protegidos contra acesso por usuários não autorizados. 
---
= Categorias de conformidade de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta tabela descreve os parâmetros de criptografia de volume que o Unified Manager avalia para determinar se os dados em seus volumes estão adequadamente protegidos contra acesso por usuários não autorizados.

Observe que os parâmetros de criptografia de volume não afetam se o cluster ou a VM de armazenamento são considerados compatíveis.

[cols="2*"]
|===
| Parâmetro | Descrição 


 a| 
Software criptografado
 a| 
Exibe o número de volumes protegidos usando soluções de criptografia de software NetApp Volume Encryption (NVE) ou NetApp Aggregate Encryption (NAE).



 a| 
Hardware criptografado
 a| 
Exibe o número de volumes protegidos usando a criptografia de hardware NetApp Storage Encryption (NSE).



 a| 
Software e hardware criptografados
 a| 
Exibe o número de volumes protegidos por criptografia de software e hardware.



 a| 
Não criptografado
 a| 
Exibe o número de volumes que não estão criptografados.

|===