---
permalink: health-checker/reference_description_of_cluster_object_windows_and_dialog_boxes.html 
sidebar: sidebar 
keywords: description, cluster, object, windows, dialog boxes 
summary: Você pode visualizar todos os seus clusters e objetos de cluster na respectiva página de objeto de armazenamento.  Você também pode visualizar os detalhes na página de detalhes do objeto de armazenamento correspondente.  Agora você pode iniciar a interface de usuário do System Manager nas seguintes seções ARMAZENAMENTO e PROTEÇÃO do INVENTÁRIO. 
---
= Descrição das janelas e caixas de diálogo de objetos de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar todos os seus clusters e objetos de cluster na respectiva página de objeto de armazenamento.  Você também pode visualizar os detalhes na página de detalhes do objeto de armazenamento correspondente.  Agora você pode iniciar a interface de usuário do System Manager nas seguintes seções ARMAZENAMENTO e PROTEÇÃO do INVENTÁRIO.

* Páginas de inventário de cluster, integridade do cluster e desempenho do cluster
* Páginas de Inventário Agregado, Saúde Agregada e Desempenho Agregado
* Páginas de Inventário de Volume, Saúde do Volume e Desempenho do Volume
* Páginas de inventário de nós e desempenho de nós
* Páginas de inventário do StorageVM, integridade do StorageVM e desempenho do StorageVM
* Páginas de relacionamento de proteção

