---
permalink: health-checker/reference_svm_compliance_categories.html 
sidebar: sidebar 
keywords: storage vm, compliance, svm compliance, categories 
summary: 'Esta tabela descreve os critérios de conformidade de segurança da máquina virtual de armazenamento (SVM) que o Unified Manager avalia, a recomendação da NetApp e se o parâmetro afeta a determinação geral de que a SVM está em conformidade ou não.' 
---
= Categorias de conformidade de VM de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta tabela descreve os critérios de conformidade de segurança da máquina virtual de armazenamento (SVM) que o Unified Manager avalia, a recomendação da NetApp e se o parâmetro afeta a determinação geral de que a SVM está em conformidade ou não.

[cols="4*"]
|===
| Parâmetro | Descrição | Recomendação | Afeta a conformidade do SVM 


 a| 
Registro de auditoria
 a| 
Indica se o registro de auditoria está habilitado ou desabilitado.
 a| 
Habilitado
 a| 
Sim



 a| 
Configurações SSH inseguras
 a| 
Indica se o SSH usa cifras inseguras, por exemplo, cifras que começam com `cbc*` .
 a| 
Não
 a| 
Sim



 a| 
Banner de login
 a| 
Indica se o banner de login está habilitado ou desabilitado para usuários que acessam SVMs no sistema.
 a| 
Habilitado
 a| 
Sim



 a| 
Criptografia LDAP
 a| 
Indica se a criptografia LDAP está habilitada ou desabilitada.
 a| 
Habilitado
 a| 
Não



 a| 
Autenticação NTLM
 a| 
Indica se a autenticação NTLM está habilitada ou desabilitada.
 a| 
Habilitado
 a| 
Não



 a| 
Assinatura de carga útil LDAP
 a| 
Indica se a assinatura de carga útil LDAP está habilitada ou desabilitada.
 a| 
Habilitado
 a| 
Não



 a| 
Configurações do CHAP
 a| 
Indica se o CHAP está habilitado ou desabilitado.
 a| 
Habilitado
 a| 
Não



 a| 
Kerberos V5
 a| 
Indica se a autenticação Kerberos V5 está habilitada ou desabilitada.
 a| 
Habilitado
 a| 
Não



 a| 
Autenticação NIS
 a| 
Indica se o uso da autenticação NIS está configurado.
 a| 
Desabilitado
 a| 
Não



 a| 
Status do FPolicy ativo
 a| 
Indica se FPolicy foi criado ou não.
 a| 
Sim
 a| 
Não



 a| 
Criptografia SMB habilitada
 a| 
Indica se a assinatura e selagem SMB não está habilitada.
 a| 
Sim
 a| 
Não



 a| 
Assinatura SMB habilitada
 a| 
Indica se a assinatura SMB não está habilitada.
 a| 
Sim
 a| 
Não

|===