---
permalink: health-checker/task_view_volume_list_and_details.html 
sidebar: sidebar 
keywords: view, volume list, details 
summary: 'Na visualização Saúde: Todos os volumes, você pode monitorar seu inventário de volumes.  A exibição Capacidade: Todos os volumes permite que você visualize informações sobre a capacidade e a utilização de volumes em um cluster.' 
---
= Veja a lista de volumes e detalhes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na visualização Saúde: Todos os volumes, você pode monitorar seu inventário de volumes.  A exibição Capacidade: Todos os volumes permite que você visualize informações sobre a capacidade e a utilização de volumes em um cluster.

.Antes de começar
Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.

Você também pode usar a página Detalhes do volume/saúde para visualizar informações detalhadas sobre os volumes monitorados, incluindo capacidade, eficiência, configuração e proteção dos volumes.  Você também pode visualizar informações sobre os dispositivos relacionados e alertas relacionados para um volume específico.

.Passos
. No painel de navegação esquerdo, clique em *Armazenamento* > *Volumes*.
. Escolha uma das seguintes maneiras de visualizar os detalhes do volume:
+
** Para visualizar informações detalhadas sobre a integridade dos volumes em um cluster, no menu Exibir, selecione Integridade: visualização Todos os volumes.
** Para visualizar informações detalhadas sobre a capacidade e a utilização de volumes em um cluster, no menu Exibir, selecione Capacidade: visualização Todos os volumes.
** Para ver os detalhes completos, clique no nome do volume.
+
Você também pode visualizar os detalhes completos clicando em *Exibir detalhes* na caixa de diálogo de detalhes mínimos.



. *Opcional:* visualize os objetos relacionados ao volume clicando em *Exibir relacionados* na caixa de diálogo de detalhes mínimos.


*Informações relacionadas*

* link:../health-checker/reference_health_volume_details_page.html["Volume: Página de detalhes de saúde"]
* link:../performance-checker/performance-view-all.html#performance-all-volumes-view["Desempenho: Visualização de todos os volumes"]
* link:../health-checker/task_view_antiransomware_status_of_all_volumes_storage_vms.html#view-security-details-of-all-volumes-with-anti-ransomware-detection["Segurança: Visão anti-ransomware"]
* link:../data-protection/task_view_volume_protection_relationships.html["Visualizando relacionamentos de proteção de volume"]
* link:../reporting/task_create_report_to_view_available_volume_capacity_charts.html["Criação de um relatório para visualizar gráficos de capacidade de volume disponíveis"]

