---
permalink: health-checker/task_view_svm_list_and_details.html 
sidebar: sidebar 
keywords: view, storage vm list, details 
summary: 'Na exibição Saúde: todas as VMs de armazenamento, você pode monitorar seu inventário de máquinas virtuais de armazenamento (SVMs).  Você pode usar a página Detalhes da VM de armazenamento/Integridade para visualizar informações detalhadas sobre as SVMs monitoradas.' 
---
= Veja a lista e os detalhes da VM de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na exibição Saúde: todas as VMs de armazenamento, você pode monitorar seu inventário de máquinas virtuais de armazenamento (SVMs).  Você pode usar a página Detalhes da VM de armazenamento/Integridade para visualizar informações detalhadas sobre as SVMs monitoradas.

.Antes de começar
Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.

Você pode visualizar detalhes do SVM, como capacidade, eficiência e configuração de um SVM.  Você também pode visualizar informações sobre os dispositivos relacionados e alertas relacionados para esse SVM.

.Passos
. No painel de navegação esquerdo, clique em *Armazenamento* > *VMs de armazenamento*.
. Escolha uma das seguintes maneiras de visualizar os detalhes do SVM:
+
** Para visualizar informações sobre a integridade de todas as SVMs em todos os clusters, no menu Exibir, selecione Integridade: visualização Todas as VMs de armazenamento.
** Para visualizar os detalhes completos, clique no nome da VM de armazenamento.
+
Você também pode visualizar os detalhes completos clicando em *Exibir detalhes* na caixa de diálogo de detalhes mínimos.



. Visualize os objetos relacionados ao SVM clicando em *Visualizar relacionados* na caixa de diálogo de detalhes mínimos.


*Informações relacionadas*

* link:../health-checker/reference_health_svm_details_page.html["VM de armazenamento: página de detalhes de integridade"]
* link:../performance-checker/performance-view-all.html#performance-all-storage-vms-view["Desempenho: visualização de todas as VMs de armazenamento"]
* link:../health-checker/task_view_antiransomware_status_of_all_volumes_storage_vms.html#view-security-details-of-all-volumes-with-anti-ransomware-detection["Segurança: Visão anti-ransomware"]
* link:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["Visualizando o status de segurança de clusters e VMs de armazenamento"]
* link:../data-protection/reference_relationship_all_relationships_view.html["Relacionamento: Visualização de todos os relacionamentos"]

