---
permalink: health-checker/task_test_script_execution.html 
sidebar: sidebar 
keywords: test, script, execution 
summary: Você pode verificar se seu script é executado corretamente quando um alerta é gerado para um objeto de armazenamento. 
---
= Execução do script de teste
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode verificar se seu script é executado corretamente quando um alerta é gerado para um objeto de armazenamento.

* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter carregado um script no formato de arquivo suportado para o Unified Manager.


.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Scripts*.
. Na página Scripts, adicione seu script de teste.
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de alerta*.
. Na página *Configuração de alerta*, execute uma das seguintes ações:
+
[cols="2*"]
|===
| Para... | Faça isso... 


 a| 
Adicionar um alerta
 a| 
.. Clique em *Adicionar*.
.. Na seção Ações, associe o alerta ao seu script de teste.




 a| 
Editar um alerta
 a| 
.. Selecione um alerta e clique em *Editar*.
.. Na seção Ações, associe o alerta ao seu script de teste.


|===
. Clique em *Salvar*.
. Na página *Configuração de alerta*, selecione o alerta que você adicionou ou modificou e clique em *Testar*.
+
O script é executado com o argumento "`-test`", e um alerta de notificação é enviado para os endereços de e-mail que foram especificados quando o alerta foi criado.


