---
permalink: health-checker/task_unconfigure_netapp_snapshot_backup.html 
sidebar: sidebar 
keywords: netapp, modify, snapshot copy, copies, windows, unconfigure, backup type 
summary: Se você quiser alterar o tipo de backup do seu sistema Active IQ Unified Manager , poderá usar as opções do console de manutenção.  A opção Desconfigurar backup de instantâneo do NetApp permite que você retorne ao backup baseado em MySQL. 
---
= Modificar o tipo de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você quiser alterar o tipo de backup do seu sistema Active IQ Unified Manager , poderá usar as opções do console de manutenção.  A opção *Desconfigurar backup de instantâneo do NetApp * permite que você retorne ao backup baseado em MySQL.

.Antes de começar
Você deve ter um ID de usuário e uma senha autorizados para efetuar login no console de manutenção do servidor do Unified Manager.

.Passos
. Acesse o console de manutenção.
. Selecione 4 no *Menu Principal* para backup e restauração.
. Selecione 2 no *Menu de Backup e Restauração*.
. Selecione 4 para *Desconfigurar NetApp Snapshot Backup*.
+
As ações executadas são exibidas, como interromper os serviços, quebrar o link simbólico, mover os dados do armazenamento para o diretório e, em seguida, iniciar os serviços novamente.

+
Após o método de backup ser modificado, o mecanismo de backup é alterado de cópia instantânea para backup padrão do MySQL.  Essa alteração aparece na seção Backup do banco de dados das Configurações gerais.


