---
permalink: health-checker/task_define_schedule_for_snapshot_backups.html 
sidebar: sidebar 
keywords: define, backup, schedule, linux, windows, snapshot copy, copies 
summary: Você pode configurar o agendamento no qual as cópias do Unified Manager Snapshot são criadas usando a interface do usuário do Unified Manager. 
---
= Definir um agendamento de backup para Linux e Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o agendamento no qual as cópias do Unified Manager Snapshot são criadas usando a interface do usuário do Unified Manager.

.Antes de começar
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter configurado as definições para criar cópias de snapshots no console de manutenção para identificar o destino onde os snapshots serão criados.


Cópias de instantâneos são criadas em apenas alguns minutos e o banco de dados do Unified Manager fica bloqueado apenas por alguns segundos.

[NOTE]
====
O backup feito durante os primeiros 15 dias de adição de um novo cluster pode não ser preciso o suficiente para obter os dados históricos de desempenho.

====
.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Backup de banco de dados*.
. Na página *Backup do banco de dados*, clique em *Configurações de backup*.
. Insira o número máximo de cópias do Snapshot que você deseja reter no campo *Contagem de retenção*.
+
O valor padrão para contagem de retenção é 10.  O número máximo de cópias do Snapshot é determinado pela versão do software ONTAP no cluster.  Você pode deixar este campo em branco para implementar o valor máximo, independentemente da versão do ONTAP .

. Selecione o botão *Agendado diariamente* ou *Agendado semanalmente* e especifique os detalhes da programação.
. Clique em *Aplicar*.


Cópias instantâneas são criadas com base na programação.  Você pode ver os arquivos de backup disponíveis na página Backup do banco de dados.

Devido à importância deste volume e dos instantâneos, você pode querer criar um ou dois alertas para este volume para ser notificado quando:

* O espaço do volume está 90% cheio.  Use o evento *Volume Space Full* para configurar o alerta.
+
Você pode adicionar capacidade ao volume usando o ONTAP System Manager ou o ONTAP CLI para que o banco de dados do Unified Manager não fique sem espaço.

* O número de instantâneos está próximo de atingir o número máximo.  Use o evento *Muitas cópias de instantâneos* para configurar o alerta.
+
Você pode excluir snapshots mais antigos usando o ONTAP System Manager ou o ONTAP CLI para que sempre haja espaço para novas cópias de snapshots.



Você configura alertas na página Configuração de alertas.
