---
permalink: health-checker/task_view_security_events_that_require_software_or_firmware_updates.html 
sidebar: sidebar 
keywords: upgrade events, view, security events, software, firmware updates 
summary: 'Existem certos eventos de segurança que têm uma área de impacto de “Atualização”.  Esses eventos são relatados pela plataforma Active IQ e identificam problemas cuja resolução exige que você atualize o software ONTAP , o firmware do nó ou o software do sistema operacional (para avisos de segurança).' 
---
= Visualize eventos de segurança que podem exigir atualizações de software ou firmware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Há certos eventos de segurança que têm uma área de impacto de "`Atualização`".  Esses eventos são relatados pela plataforma Active IQ e identificam problemas cuja resolução exige que você atualize o software ONTAP , o firmware do nó ou o software do sistema operacional (para avisos de segurança).

.Antes de começar
Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.

Talvez você queira executar ações corretivas imediatas para alguns desses problemas, enquanto outros podem esperar até a próxima manutenção programada.  Você pode visualizar todos esses eventos e atribuí-los a usuários que podem resolver os problemas.  Além disso, se houver determinados eventos de atualização de segurança sobre os quais você não deseja ser notificado, esta lista pode ajudar a identificá-los para que você possa desativá-los.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de eventos*.
+
Por padrão, todos os eventos ativos (novos e confirmados) são exibidos na página de inventário do Gerenciamento de eventos.

. No menu Exibir, selecione *Atualizar eventos*.
+
A página exibe todos os eventos de segurança de atualização ativos.


