---
permalink: health-checker/task_configure_windows_host_machine.html 
sidebar: sidebar 
keywords: netapp, snapshot copy, copies windows, configure, windows host machine 
summary: Você precisa configurar sua máquina host Windows antes de poder usar o NetApp Snapshot para fazer backup e restaurar o Active IQ Unified Manager.  Para iniciar o iniciador iSCSI da Microsoft em uma máquina host Windows, digite “iscsi” na barra de pesquisa e clique em Iniciador iSCSI. 
---
= Configurar máquina host do Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa configurar sua máquina host Windows antes de poder usar o NetApp Snapshot para fazer backup e restaurar o Active IQ Unified Manager.  Para iniciar o iniciador iSCSI da Microsoft em uma máquina host Windows, digite "`iscsi`" na barra de pesquisa e clique em *Iniciador iSCSI*.

.Antes de começar
Você deve limpar todas as configurações anteriores na máquina host.

Se você estiver tentando iniciar o iniciador iSCSI em uma nova instalação do Windows, será solicitada uma confirmação e, após a confirmação, a caixa de diálogo Propriedades do iSCSI será exibida.  Se for uma instalação existente do Windows, a caixa de diálogo Propriedades do iSCSI será exibida com um destino inativo ou tentando se conectar.  Portanto, você precisará garantir que todas as configurações anteriores no host Windows sejam removidas.

.Passos
. Limpe todas as configurações anteriores na máquina host.
. Descubra o portal de destino.
. Conecte-se ao portal de destino.
. Conecte-se usando multicaminho ao portal de destino.
. Descubra os dois LIFs.
. Descubra o LUN configurado na máquina Windows como um dispositivo.
. Configure o LUN descoberto como uma nova unidade de volume no Windows.

