---
permalink: health-checker/task_restore_mysql_database_backup_on_windows.html 
sidebar: sidebar 
keywords: restore, windows, mysql, database, backup 
summary: Em caso de perda ou corrupção de dados, você pode usar o recurso de restauração para restaurar o Unified Manager ao estado estável anterior com perda mínima.  Você pode restaurar o banco de dados MySQL do Unified Manager para um sistema Windows local ou remoto usando o console de manutenção do Unified Manager. 
---
= Restaurar um backup de banco de dados MySQL no Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em caso de perda ou corrupção de dados, você pode usar o recurso de restauração para restaurar o Unified Manager ao estado estável anterior com perda mínima.  Você pode restaurar o banco de dados MySQL do Unified Manager para um sistema Windows local ou remoto usando o console de manutenção do Unified Manager.

.Antes de começar
* Você deve ter privilégios de administrador do Windows.
* Você deve ter copiado o arquivo de backup do Unified Manager e o conteúdo do diretório do repositório do banco de dados para o sistema no qual você executará a operação de restauração.
+
É recomendável que você copie o arquivo de backup para o diretório padrão `\ProgramData\NetApp\OnCommandAppData\ocum\backup` .  Os arquivos do repositório do banco de dados devem ser copiados para o `\database_dumps_repo` subdiretório sob o `\backup` diretório.

* Os arquivos de backup devem ser de `.7z` tipo.


O recurso de restauração é específico da plataforma e da versão.  Você pode restaurar um backup do MySQL do Unified Manager somente na mesma versão do Unified Manager, e um backup do Windows só pode ser restaurado em uma plataforma Windows.

[TIP]
====
Se os nomes das pastas contiverem um espaço, você deverá incluir o caminho absoluto ou relativo do arquivo de backup entre aspas duplas.

====
.Passos
. Se você estiver executando uma restauração em um novo servidor, após instalar o Unified Manager, não inicie a interface do usuário nem configure nenhum cluster, usuário ou configuração de autenticação quando a instalação estiver concluída.  O arquivo de backup preenche essas informações durante o processo de restauração.
. Efetue login no sistema Unified Manager com credenciais de administrador.
. Inicie o PowerShell ou o prompt de comando como administrador do Windows.
. Digite o comando `maintenance_console` e pressione Enter.
. No console de manutenção *Menu Principal*, insira o número da opção *Restauração de Backup*.
. Digite o número do *Restaurar Backup do MySQL*.
. Quando solicitado, insira o caminho absoluto do arquivo de backup.
+
[listing]
----
Bundle to restore from: \ProgramData\NetApp\OnCommandAppData\ocum\backup\UM_9.8.N151118.2300_backup_windows_02-20-2020-02-51.7z
----
+
Após a conclusão da operação de restauração, você poderá efetuar login no Unified Manager.



Após restaurar o backup, se o servidor OnCommand Workflow Automation não funcionar, execute as seguintes etapas:

. No servidor de automação de fluxo de trabalho, altere o endereço IP do servidor do Unified Manager para apontar para a máquina mais recente.
. No servidor do Unified Manager, redefina a senha do banco de dados se a aquisição falhar na etapa 1.

