---
permalink: health-checker/task_view_how_user_authentication_is_being_managed_on_all_clusters.html 
sidebar: sidebar 
keywords: view, cluster authentication status, user authentication, manage, clusters 
summary: A página Segurança exibe os tipos de autenticação usados para autenticar usuários em cada cluster e o número de usuários que estão acessando o cluster usando cada tipo.  Isso permite que você verifique se a autenticação do usuário está sendo realizada com segurança, conforme definido pela sua organização. 
---
= Veja como a autenticação do usuário está sendo gerenciada em todos os clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página Segurança exibe os tipos de autenticação usados para autenticar usuários em cada cluster e o número de usuários que estão acessando o cluster usando cada tipo.  Isso permite que você verifique se a autenticação do usuário está sendo realizada com segurança, conforme definido pela sua organização.

.Passos
. No painel de navegação esquerdo, clique em *Painel*.
. Na parte superior do painel, selecione *Todos os clusters* no menu suspenso.
. Clique na seta para a direita no painel *Segurança* e a página *Segurança* será exibida.
. Visualize o cartão *Autenticação de Cluster* para ver o número de usuários que estão acessando o sistema usando cada tipo de autenticação.
. Visualize o cartão *Segurança do Cluster* para visualizar os mecanismos de autenticação usados para autenticar usuários em cada cluster.


Se houver alguns usuários acessando o sistema usando um método inseguro ou usando um método não recomendado pela NetApp, você poderá desabilitar o método.
