---
permalink: health-checker/task_reorder_group_actions.html 
sidebar: sidebar 
keywords: reorder, group actions 
summary: Você pode alterar a ordem das ações de grupo que serão aplicadas aos objetos de armazenamento em um grupo.  Ações de grupo são aplicadas a objetos de armazenamento sequencialmente com base em sua classificação.  A classificação mais baixa é atribuída à ação de grupo que você configurou por último.  Você pode alterar a classificação da ação de grupo dependendo de suas necessidades. 
---
= Reordenar ações de grupo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar a ordem das ações de grupo que serão aplicadas aos objetos de armazenamento em um grupo.  Ações de grupo são aplicadas a objetos de armazenamento sequencialmente com base em sua classificação.  A classificação mais baixa é atribuída à ação de grupo que você configurou por último.  Você pode alterar a classificação da ação de grupo dependendo de suas necessidades.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Você pode selecionar uma única linha ou várias linhas e, em seguida, executar várias operações de arrastar e soltar para alterar a classificação das ações do grupo.  No entanto, você deve salvar as alterações para que a repriorização seja refletida na grade de ações do grupo.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Grupos*.
. Na aba *Ações de grupo*, clique em *Reordenar*.
. Na caixa de diálogo *Reordenar ações de grupo*, arraste e solte as linhas para reorganizar a sequência de ações de grupo conforme necessário.
. Clique em *Salvar*.

