---
permalink: health-checker/task_calculate_reclaimable_space_for_snapshot_copies.html 
sidebar: sidebar 
keywords: calculate, reclaimable space, snapshot copies 
summary: Você pode calcular a quantidade de espaço em disco que pode ser recuperada se uma ou mais cópias do Snapshot forem excluídas. 
---
= Calcular espaço recuperável para cópias de Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode calcular a quantidade de espaço em disco que pode ser recuperada se uma ou mais cópias do Snapshot forem excluídas.

.Antes de começar
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.
* O volume deve estar online.
* O volume deve ser um FlexVol volume; esse recurso não é suportado com volumes FlexGroup .


.Passos
. No painel de navegação esquerdo, clique em *Armazenamento* > *Volumes*.
. Na exibição *Saúde: Todos os volumes*, selecione o volume que contém as cópias do Snapshot que você deseja visualizar.
+
A lista de cópias do Snapshot é exibida.

. Na página de detalhes *Volume / Saúde*, clique na aba *Capacidade*.
. No painel *Detalhes* da guia *Capacidade*, na seção Outros detalhes, clique no link ao lado de *Cópias instantâneas*.
+
O número de cópias do Snapshot é um link que exibe a lista de cópias do Snapshot.

. Na exibição *Cópias de instantâneo*, selecione as cópias de instantâneo para as quais você deseja calcular o espaço recuperável.
. Clique em *Calcular*.
+
O espaço recuperável (em porcentagem, KB, MB, GB e assim por diante) no volume é exibido.

. Para recalcular o espaço recuperável, selecione as cópias do Snapshot necessárias e clique em *Recalcular*.

