---
permalink: health-checker/task_add_annotations_manually_to_individual_storage_objects.html 
sidebar: sidebar 
keywords: add, annotations, manually, individual, storage objects 
summary: Você pode anotar manualmente volumes, clusters e SVMs selecionados sem usar regras de anotação.  Você pode anotar um único objeto de armazenamento ou vários objetos de armazenamento e especificar a combinação de pares nome-valor necessária para a anotação. 
---
= Adicionar anotações manualmente a objetos de armazenamento individuais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode anotar manualmente volumes, clusters e SVMs selecionados sem usar regras de anotação.  Você pode anotar um único objeto de armazenamento ou vários objetos de armazenamento e especificar a combinação de pares nome-valor necessária para a anotação.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

.Passos
. Navegue até os objetos de armazenamento que você deseja anotar:
+
[cols="2*"]
|===
| Para adicionar anotações a... | Faça isso... 


 a| 
Aglomerados
 a| 
.. Clique em *Armazenamento* > *Clusters*.
.. Selecione um ou mais clusters.




 a| 
Volumes
 a| 
.. Clique em *Armazenamento* > *Volumes*.
.. Selecione um ou mais volumes.




 a| 
SVMs
 a| 
.. Clique em *Armazenamento* > *SVMs*.
.. Selecione uma ou mais SVMs.


|===
. Clique em *Anotar* e selecione um par nome-valor.
. Clique em *Aplicar*.

