---
permalink: health-checker/task_perform_suggested_remedial_actions_for_full_volume.html 
sidebar: sidebar 
keywords: perform, suggested, remedial actions, volume 
summary: Após receber um evento de erro “Espaço de volume cheio”, você revisa as ações corretivas sugeridas na página Detalhes do evento e decide executar uma das ações sugeridas. 
---
= Execute as ações corretivas sugeridas para um volume total
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após receber um evento de erro "`Volume Space Full`", você revisa as ações corretivas sugeridas na página Detalhes do evento e decide executar uma das ações sugeridas.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Um usuário com qualquer função pode executar todas as tarefas neste fluxo de trabalho que usam o Unified Manager.

Neste exemplo, você viu um evento de erro de Espaço de Volume Cheio na página de inventário do Unified ManagerEvent Management e clicou no nome do evento.

Possíveis ações corretivas que você pode executar para um volume completo incluem o seguinte:

* Habilitando crescimento automático, desduplicação ou compactação no volume
* Redimensionar ou mover o volume
* Excluir ou mover dados do volume


Embora todas essas ações devam ser executadas no ONTAP System Manager ou no ONTAP CLI, você pode usar o Unified Manager para encontrar informações que podem ser necessárias para determinar quais ações tomar.

.Passos
. Na página de detalhes do *Evento*, clique no nome do volume no campo Origem para visualizar detalhes sobre o volume afetado.
. Na página de detalhes *Volume / Saúde*, clique em *Configuração* e veja que a desduplicação e a compactação já estão habilitadas no volume.
+
Você decide redimensionar o volume.

. No painel *Dispositivos relacionados*, clique no nome do agregado de hospedagem para ver se o agregado pode acomodar um volume maior.
. Na página de detalhes *Agregado / Saúde*, você vê que o agregado que hospeda o volume completo tem capacidade não comprometida suficiente, então você usa o ONTAP System Manager para redimensionar o volume, dando a ele mais capacidade.


*Informações relacionadas*

link:../events/reference_event_details_page.html["Página de detalhes do evento"]
