---
permalink: health-checker/task_add_alerts_for_security_events.html 
sidebar: sidebar 
keywords: add, alerts, security events 
summary: Você pode configurar alertas para eventos de segurança individuais, assim como quaisquer outros eventos recebidos pelo Unified Manager.  Além disso, se você quiser tratar todos os eventos de segurança da mesma forma e enviar e-mails para a mesma pessoa, poderá criar um único alerta para notificá-lo quando algum evento de segurança for acionado. 
---
= Adicionar alertas para eventos de segurança
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar alertas para eventos de segurança individuais, assim como quaisquer outros eventos recebidos pelo Unified Manager.  Além disso, se você quiser tratar todos os eventos de segurança da mesma forma e enviar e-mails para a mesma pessoa, poderá criar um único alerta para notificá-lo quando algum evento de segurança for acionado.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

O exemplo abaixo mostra como criar um alerta para o evento de segurança "`Protocolo Telnet habilitado`".  Isso enviará um alerta se o acesso Telnet estiver configurado para acesso administrativo remoto ao cluster.  Você pode usar essa mesma metodologia para criar alertas para todos os eventos de segurança.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de alerta*.
. Na página *Configuração de alerta*, clique em *Adicionar*.
. Na caixa de diálogo *Adicionar alerta*, clique em *Nome* e insira um nome e uma descrição para o alerta.
. Clique em *Recursos* e selecione o cluster ou cluster no qual você deseja habilitar este alerta.
. Clique em *Eventos* e execute as seguintes ações:
+
.. Na lista Gravidade do Evento, selecione *Aviso*.
.. Na lista Eventos correspondentes, selecione *Protocolo Telnet habilitado*.


. Clique em *Ações* e selecione o nome do usuário que receberá o e-mail de alerta no campo *Alertar estes usuários*.
. Configure quaisquer outras opções nesta página para frequência de notificação, emissão de toques SNMP e execução de um script.
. Clique em *Salvar*.

