---
permalink: health-checker/task_configure_lag_threshold_settings_for_unmanaged_protection.html 
sidebar: sidebar 
keywords: configure, lag, threshold settings, unmanaged, protection, relationships 
summary: Você pode editar as configurações globais de limite de integridade de erro e aviso de atraso padrão para relacionamentos de proteção não gerenciados, para que os eventos sejam gerados em intervalos apropriados às suas necessidades. 
---
= Configurar configurações de limite de atraso para relacionamentos de proteção não gerenciados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar as configurações globais de limite de integridade de erro e aviso de atraso padrão para relacionamentos de proteção não gerenciados, para que os eventos sejam gerados em intervalos apropriados às suas necessidades.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

O tempo de atraso não deve ser maior que o intervalo definido no cronograma de transferência.  Por exemplo, se o cronograma de transferência for de hora em hora, o tempo de atraso não deve ser superior a uma hora.  O limite de atraso especifica uma porcentagem que o tempo de atraso não deve exceder.  Usando o exemplo de uma hora, se o limite de atraso for definido como 150%, você receberá um evento quando o tempo de atraso for maior que 1,5 hora.

As configurações descritas nesta tarefa são aplicadas globalmente a todos os relacionamentos de proteção não gerenciados.  As configurações não podem ser especificadas e aplicadas exclusivamente a um relacionamento de proteção não gerenciado.

.Passos
. No painel de navegação esquerdo, clique em *Limites de evento* > *Relacionamento*.
. Aumente ou diminua a porcentagem global de tempo de atraso de aviso ou erro padrão, conforme necessário.
. Para desabilitar o acionamento de um evento de aviso ou erro a partir de qualquer limite de atraso, desmarque a caixa ao lado de *Ativado*.
. Clique em *Salvar*.


*Informações relacionadas*

link:../config/task_add_users.html["Adicionando usuários"]
