---
permalink: health-checker/task_edit_individual_qtree_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, qtree, health, threshold, settings 
summary: Você pode editar as configurações de limite de integridade para capacidade de qtree para uma ou mais qtrees.  Quando um limite é ultrapassado, alertas são gerados e você recebe notificações.  Essas notificações ajudam você a tomar medidas preventivas com base no evento gerado. 
---
= Editar configurações individuais de limite de integridade do qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar as configurações de limite de integridade para capacidade de qtree para uma ou mais qtrees.  Quando um limite é ultrapassado, alertas são gerados e você recebe notificações.  Essas notificações ajudam você a tomar medidas preventivas com base no evento gerado.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Com base nas alterações nos valores limite, os eventos são gerados ou tornados obsoletos no próximo ciclo de monitoramento.

.Passos
. No painel de navegação esquerdo, clique em *Armazenamento* > *Qtrees*.
. Na visualização *Capacidade: Todas as Qtrees*, selecione uma ou mais qtrees e clique em *Editar Limites*.
. Na caixa de diálogo *Editar Limites de Qtree*, altere os limites de capacidade para a qtree ou qtrees selecionadas e clique em *Salvar*.
+
[NOTE]
====
Você também pode definir limites individuais de qtree na guia Qtrees na página de detalhes da VM de armazenamento/integridade.

====

