---
permalink: install-vapp/concept_virtual_infrastructure_or_hardware_system_requirements.html 
sidebar: sidebar 
keywords: virtual, infrastructure, hardware, system, requirements, virtual appliance 
summary: A instalação do Unified Manager em uma infraestrutura virtual ou em um sistema físico deve atender aos requisitos mínimos de memória, CPU e espaço em disco. 
---
= Requisitos de infraestrutura virtual e sistema de hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A instalação do Unified Manager em uma infraestrutura virtual ou em um sistema físico deve atender aos requisitos mínimos de memória, CPU e espaço em disco.

A tabela a seguir exibe os valores recomendados para recursos de memória, CPU e espaço em disco.  Esses valores foram qualificados para que o Unified Manager atenda a níveis de desempenho aceitáveis.

[cols="2*"]
|===
| Configuração de hardware | Configurações recomendadas 


 a| 
BATER
 a| 
12 GB (requisito mínimo de 8 GB)



 a| 
Processadores
 a| 
4 CPUs



 a| 
Capacidade do ciclo da CPU
 a| 
9572 MHz total (requisito mínimo 9572 MHz)



 a| 
Espaço livre em disco
 a| 
* 5 GB (provisionamento fino)
* 152 GB (provisionamento denso)


|===
O Unified Manager pode ser instalado em sistemas com pouca memória, mas os 12 GB de RAM recomendados garantem que haja memória suficiente disponível para um desempenho ideal e para que o sistema possa acomodar clusters e objetos de armazenamento adicionais conforme sua configuração cresce.  Você não deve definir nenhum limite de memória na VM onde o Unified Manager está implantado e não deve habilitar nenhum recurso (por exemplo, balão) que impeça o software de utilizar a memória alocada no sistema.

Além disso, existe um limite para o número de nós que uma única instância do Unified Manager pode monitorar antes de você instalar uma segunda instância do Unified Manager. Para mais informações, consulte link:https://www.netapp.com/pdf.html?item=/media/13504-tr4621.pdf["Guia de práticas recomendadas do Unified Manager"^].

A troca de páginas de memória afeta negativamente o desempenho do sistema e do aplicativo de gerenciamento.  Competir por recursos de CPU que não estão disponíveis devido à utilização geral do host pode prejudicar o desempenho.



[[requirement-for-dedicated-use]]
== Requisito de uso dedicado

O sistema físico ou virtual no qual você instala o Unified Manager deve ser usado exclusivamente para o Unified Manager e não deve ser compartilhado com outros aplicativos.  Outros aplicativos podem consumir recursos do sistema e reduzir drasticamente o desempenho do Unified Manager.



[[space-requirements-for-backups]]
== Requisitos de espaço para backups

Se você planeja usar o recurso de backup e restauração do Unified Manager, aloque capacidade adicional para que o diretório ou disco "`data`" tenha 150 GB de espaço.  Um backup pode ser gravado em um destino local ou remoto.  A prática recomendada é identificar um local remoto externo ao sistema host do Unified Manager que tenha no mínimo 150 GB de espaço.



[[requirements-for-host-connectivity]]
== Requisitos para conectividade do host

O sistema físico ou virtual no qual você instala o Unified Manager deve ser configurado de forma que você possa `ping` o nome do host do próprio host.  No caso de configuração IPv6, você deve verificar se `ping6` para o nome do host for bem-sucedido para garantir que a instalação do Unified Manager seja bem-sucedida.

Você pode usar o nome do host (ou o endereço IP do host) para acessar a interface da web do produto.  Se você configurou um endereço IP estático para sua rede durante a implantação, você designou um nome para o host da rede.  Se você configurou a rede usando DHCP, deverá obter o nome do host do DNS.

Se você planeja permitir que os usuários acessem o Unified Manager usando o nome curto em vez de usar o nome de domínio totalmente qualificado (FQDN) ou endereço IP, sua configuração de rede precisa resolver esse nome curto para um FQDN válido.
