---
permalink: install-vapp/qsg-vapp.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, VMWare QSG, vApp QSG, quick installation 
summary: Guia de início rápido para o Unified Manager na plataforma VMWare vSphere. 
---
= Instruções de início rápido para instalações do VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode baixar o `.tar` arquivo que contém um certificado raiz, um `README` arquivo e um `OVA` arquivo e implante o Unified Manager como um dispositivo virtual.



== Requisitos do sistema

* Sistema operacional: VMware ESXi 8.0
* RAM: 12 GB
* CPU: 9572 MHz no total
* Espaço livre em disco: 5 GB (provisionamento fino), 152 GB (provisionamento espesso)


Para obter requisitos detalhados do sistema, consulte olink:../install-vapp/concept_requirements_for_installing_unified_manager.html["Requisitos para instalar o Unified Manager"] elink:http://mysupport.netapp.com/matrix["Matriz de Interoperabilidade"] .



== Instalar o Active IQ Unified Manager



=== Baixe o instalador

. Baixe o `.tar` arquivo que contém um certificado raiz, um `README` arquivo e um `OVA` arquivo.
. Salve o arquivo em um diretório local ou de rede que seja acessível ao seu vSphere Client.
. No diretório onde você baixou o `.tar` arquivo, digite o `tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz` comando.  + O necessário `OVA` arquivo, um certificado raiz e um `README` arquivo são descompactados no diretório de destino.




=== Verificar integridade

Você pode verificar a integridade do `OVA` arquivo seguindo os passos fornecidos no `README` arquivo.



=== Instalar o Unified Manager

. No vSphere Client, clique em *Arquivo > Implantar modelo OVF*.
. Localize o arquivo OVA e use o assistente para implantar o dispositivo virtual no servidor ESXi.
. Na página Detalhes da revisão, na seção Editor, a mensagem `Entrust Code Signing - OVCS2 (Trusted certificate)` confirma a integridade do arquivo baixado `OVA` arquivo.  Para a mensagem `Entrust Code Signing - OVCS2 (Invalid certificate)` , atualize o VMware vCenter Server para a versão 7.0U3E ou superior.
. Na página Personalizar modelo, na guia Propriedades, preencha os campos conforme necessário para o tipo de instalação que você está executando:
+
** Para configuração estática, insira as informações necessárias em todos os campos.  Não é necessário adicionar informações para o campo *DNS secundário*.
** Para DHCP usando IPv4, não adicione nenhuma informação em nenhum campo.
** Para DHCP usando IPv6, marque a caixa “Ativar endereçamento IPv6 automático”.  Não adicione nenhuma informação em nenhum outro campo.


. Ligue a VM.
. Clique na aba Console para visualizar o processo de inicialização.
. Configurar o fuso horário.
. Insira um nome de usuário e uma senha de manutenção do Unified Manager.


No final da instalação, as informações para se conectar à interface web do Unified Manager são exibidas.
