---
permalink: install-vapp/task_remove_unified_manager_vapp.html 
sidebar: sidebar 
keywords: remove unified manager 
summary: 'Você pode desinstalar o Unified Manager removendo a máquina virtual (VM) na qual o software Unified Manager está instalado.' 
---
= Remover o Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desinstalar o Unified Manager removendo a máquina virtual (VM) na qual o software Unified Manager está instalado.

.Antes de começar
* Você deve ter credenciais para acessar o VMware vCenter Server e o vSphere Web Client.
* Qualquer conexão ativa do servidor Unified Manager com um servidor de automação de fluxo de trabalho deve ser fechada.
* Todos os clusters (fontes de dados) devem ser removidos do servidor do Unified Manager antes de remover a máquina virtual (VM).


.Passos
. Use o console de manutenção do Unified Manager para verificar se o servidor do Unified Manager não tem uma conexão ativa com um provedor de dados externo.
. No vSphere Client, clique em *Início* > *Inventário* > *VMs e Modelos*.
. Selecione a VM que você deseja remover e clique na aba *Resumo*.
. Se a VM estiver em execução, clique em *Energia* > *Desligar convidado*.
. Clique com o botão direito do mouse na VM que você deseja remover e clique em *Excluir do disco*.

