---
permalink: install-vapp/task_restart_unified_manager_virtual_machine.html 
sidebar: sidebar 
keywords: restart, unified manager, virtual, machine 
summary: 'Você pode reiniciar a máquina virtual (VM) do Unified Manager a partir do console de manutenção.  Você deve reiniciar a VM após gerar um novo certificado de segurança ou se houver um problema com a VM.' 
---
= Reinicie a máquina virtual do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode reiniciar a máquina virtual (VM) do Unified Manager a partir do console de manutenção.  Você deve reiniciar a VM após gerar um novo certificado de segurança ou se houver um problema com a VM.

.Antes de começar
* O dispositivo virtual deve estar ligado.
* Você deve estar conectado ao console de manutenção do Unified Manager como usuário de manutenção.


Você também pode reiniciar a máquina virtual a partir do vSphere usando a opção VMware *Restart Guest*. Consulte https://developer.broadcom.com/powercli/latest/vmware.vimautomation.core/commands/restart-vmguest/["o cmdlet Restart-VMGuest na referência do CMDLET VMware vSphere PowerCLI da Broadcom."^]

.Passos
. No console de manutenção, selecione *Configuração do sistema* > *Reinicializar máquina virtual*.
. Inicie a interface de usuário da Web do Unified Manager no seu navegador e faça login.

