---
permalink: install-vapp/task_download_unified_manager_ova_file.html 
sidebar: sidebar 
keywords: download, unified manager, installation, file 
summary: Baixe o arquivo de instalação do Unified Manager no site de suporte da NetApp para implantar o Unified Manager como um dispositivo virtual. 
---
= Baixe o arquivo de instalação do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Baixe o arquivo de instalação do Unified Manager no site de suporte da NetApp para implantar o Unified Manager como um dispositivo virtual.

.Antes de começar
Você deve ter as credenciais de login para o site de suporte da NetApp .

O arquivo de instalação é um `.tar` arquivo que contém um certificado raiz, um `README` arquivo e um `OVA` arquivo contendo o software Unified Manager configurado para um dispositivo virtual.

.Passos
. Efetue login no site de suporte da NetApp e navegue até a página de download do Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Site de suporte da NetApp"]

. Selecione a versão necessária do Unified Manager e aceite o contrato de licença de usuário final (EULA).
. Baixe e salve o `.tar` arquivo para instalação do VMware vSphere em um diretório local ou diretório de rede que seja acessível ao seu vSphere Client.
. Verifique a soma de verificação para garantir que o software foi baixado corretamente.
. Navegue até o diretório onde você baixou o `.tar` arquivo e digite o seguinte comando na janela do terminal para expandir o pacote do Unified Manager:
+
[listing]
----
tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz
----
+
O necessário `OVA` arquivo, um certificado raiz e um `README` arquivo para o Unified Manager são descompactados no diretório de destino.

. Verifique a integridade do `OVA` arquivo seguindo os passos fornecidos no `README` arquivo.

