---
permalink: install-windows/qsg-windows.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer 
summary: Guia de início rápido para o Unified Manager na plataforma Windows. 
---
= Instruções de início rápido para instalações do Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode baixar o pacote de instalação e instalar o Unified Manager para monitorar e solucionar problemas de capacidade de armazenamento de dados, disponibilidade, desempenho e proteção.



== Requisitos do sistema

* Sistemas Operacionais
+
** Microsoft Windows Server 2019 Standard e Datacenter Edition
** Microsoft Windows Server 2022 Standard e Datacenter Edition
+
O Unified Manager é compatível com o sistema operacional Windows de 64 bits para os seguintes idiomas:

** Inglês
** japonês
** Chinês simplificado


* RAM: 12 GB
* CPU: 9572 MHz no total
* Espaço livre em disco: 100 GB de espaço em disco para o diretório de instalação, 50 GB de espaço em disco para o diretório de dados MySQL


Para obter requisitos detalhados do sistema, consulte olink:../install-windows/concept_requirements_for_installing_unified_manager.html["Requisitos para instalar o Unified Manager"] elink:http://mysupport.netapp.com/matrix["Matriz de Interoperabilidade"^] .



== Instalar o Active IQ Unified Manager



=== Baixe o instalador

. Baixe o `ActiveIQUnifiedManager-<version>.exe` pacote de instalação.
. Copie o arquivo de instalação para um diretório no sistema de destino.




=== Instalar o Unified Manager

Para instalar o Unified Manager, certifique-se de ter o Microsoft .NET 4.5.2 ou uma versão posterior instalado.  Como parte do processo de instalação, o Unified Manager instala outros pacotes de terceiros, conforme necessário.  Para obter mais informações sobre os pacotes de software dependentes, consulte olink:../install-windows/reference_windows_software_and_installation_requirements.html["Requisitos de software e instalação do Windows"] .

. Efetue login no Windows usando a conta de administrador local padrão.
. No diretório onde você baixou o arquivo de instalação, clique com o botão direito do mouse e execute o arquivo executável (.exe) do Unified Manager como administrador.
. Quando solicitado, insira o nome de usuário e a senha para criar o usuário de manutenção do Unified Manager.
. No assistente de conexão de banco de dados, insira a senha root do MySQL.
. Siga as instruções restantes para concluir a instalação.
. Clique em *Concluir* no final da instalação e a interface de usuário da Web do Unified Manager será exibida.

