---
permalink: install-windows/task_install_unified_manager_on_windows.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: Você pode instalar o Unified Manager para monitorar e solucionar problemas de capacidade de armazenamento de dados, disponibilidade, desempenho e proteção. 
---
= Instalar o Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode instalar o Unified Manager para monitorar e solucionar problemas de capacidade de armazenamento de dados, disponibilidade, desempenho e proteção.

.Antes de começar
* O sistema no qual você planeja instalar o Unified Manager deve atender aos requisitos de sistema e software.
+
Verlink:concept_virtual_infrastructure_or_hardware_system_requirements.html["Requisitos do sistema de hardware"] .

+
Verlink:reference_windows_software_and_installation_requirements.html["Requisitos de software e instalação do Windows"] .

+
[NOTE]
====
A partir do Unified Manager 9.5, o OpenJDK é fornecido no pacote de instalação e instalado automaticamente.  O Oracle Java não é mais suportado a partir do Unified Manager 9.5.

====
* Você deve ter privilégios de administrador do Windows.  Certifique-se de que seu nome de usuário não comece com um ponto de exclamação "`!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "` !`".
* Todos os clusters são suportados, exceto os sistemas ASA r2.
* Você deve ter um navegador da web compatível.
* A senha do usuário de manutenção do Unified Manager deve ter entre 8 e 20 caracteres, conter letras maiúsculas ou minúsculas, numerais e caracteres especiais.
* Os seguintes caracteres especiais não são permitidos na sequência de senha do usuário de manutenção ou do usuário root do MySQL: " ' ` % , = & < > | ^ \ / ( ) [ ] ;:
+
Os seguintes caracteres especiais são permitidos: ~ !  @ # $ * - ? .  + { }



.Passos
. Efetue login no Windows usando a conta de administrador local padrão.
. Efetue login no site de suporte da NetApp e navegue até a página de download do Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Site de suporte da NetApp"^]

. Selecione a versão necessária do Unified Manager e aceite o contrato de licença de usuário final (EULA).
. Baixe o arquivo de instalação do Unified Manager para Windows ou o arquivo zip para um diretório de destino no sistema Windows.
. Extraia o arquivo zip, se necessário, e navegue até o diretório onde o arquivo de instalação está localizado.
. Clique com o botão direito do mouse e execute o arquivo executável (.exe) do instalador do Unified Manager como administrador.
+
O Unified Manager detecta pacotes de terceiros ausentes ou pré-instalados e os lista.  Se os pacotes de terceiros necessários não estiverem instalados no sistema, o Unified Manager os instalará como parte da instalação.

. Clique em *Avançar*.
. Digite o nome de usuário e a senha para criar o usuário de manutenção.
. No assistente de conexão de banco de dados, insira a senha root do MySQL.
. Clique em *Alterar* para especificar um novo local para o diretório de instalação do Unified Manager e o diretório de dados do MySQL.
+
Se você não alterar o diretório de instalação, o Unified Manager será instalado no diretório de instalação padrão.

. Clique em *Avançar*.
. No assistente Pronto para instalar o Shield, clique em *Instalar*.
. Após a conclusão da instalação, clique em *Concluir*.
. Se você tiver um software antivírus ativo instalado no seu sistema Windows, exclua manualmente os seguintes caminhos da verificação antivírus após a conclusão da instalação:
+
** Diretório de dados do Unified Manager
** Diretório de instalação do Unified Manager
** Diretório de dados MySQL




A instalação cria vários diretórios:

* Diretório de instalação
+
Este é o diretório raiz do Unified Manager, que você especificou durante a instalação.  Exemplo: `C:\Program Files\NetApp\`

* Diretório de dados MySQL
+
Este é o diretório onde os bancos de dados MySQL são armazenados, que você especificou durante a instalação.  Exemplo: `C:\ProgramData\MySQL\MySQLServerData\`

* Diretório Java
+
Este é o diretório onde o OpenJDK está instalado.  Exemplo: `C:\Program Files\NetApp\JDK\`

* Diretório de dados do aplicativo Unified Manager (appDataDir)
+
Este é o diretório onde todos os dados gerados pelo aplicativo são armazenados.  Isso inclui logs, pacotes de suporte, backup e todos os outros dados adicionais.  Exemplo: `C:\ProgramData\NetApp\OnCommandAppData\`



Você pode acessar a interface da web para executar a configuração inicial do Unified Manager, conforme descrito nolink:../config/concept_configure_unified_manager.html["Configurando o Active IQ Unified Manager"] .
