---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: Você pode redefinir a senha do JBoss específica da instância definida durante a instalação.  Você pode redefinir a senha opcionalmente, caso seu site exija esse recurso de segurança para substituir a configuração de instalação do Unified Manager.  Esta operação também altera a senha que o JBoss usa para acessar o MySQL. 
---
= Alterar a senha do JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode redefinir a senha do JBoss específica da instância definida durante a instalação.  Você pode redefinir a senha opcionalmente, caso seu site exija esse recurso de segurança para substituir a configuração de instalação do Unified Manager.  Esta operação também altera a senha que o JBoss usa para acessar o MySQL.

.Antes de começar
* Você deve ter privilégios de administrador do Windows para o sistema no qual o Unified Manager está instalado.
* Você deve ter a senha do usuário root do MySQL.
* Você deve conseguir acessar o NetApp fornecido `password.bat` script no diretório
+
`C:\Program Files\NetApp\essentials\bin`.



.Passos
. Efetue login como usuário administrador na máquina host do Unified Manager.
. Use o console de Serviços do Windows para interromper os seguintes serviços do Unified Manager:
+
** Serviço de aquisição NetApp Active IQ (Ocie-au)
** Serviço de servidor de gerenciamento NetApp Active IQ (Oncommandsvc)


. Lançar o `password.bat` script para iniciar o processo de alteração de senha:
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`

. Quando solicitado, digite a senha do usuário root do MySQL.
. Quando solicitado, digite a nova senha de usuário do JBoss e digite-a novamente para confirmação.
+
Observe que a senha deve ter entre 8 e 16 caracteres e deve conter pelo menos um dígito, uma letra maiúscula e uma minúscula e pelo menos um destes caracteres especiais:

+
`+!@%^*-_+=[]:<>.?/~+`

. Quando o script for concluído, inicie os serviços do Unified Manager usando o console de Serviços do Windows:
+
** Serviço de servidor de gerenciamento NetApp Active IQ (Oncommandsvc)
** Serviço de aquisição NetApp Active IQ (Ocie-au)


. Depois que todos os serviços forem iniciados, você poderá efetuar login na interface do usuário do Unified Manager.

