---
permalink: config/concept_security_dashboard.html 
sidebar: sidebar 
keywords: security compliance settings, security feature settings, ONTAP hardening guide, AutoSupport settings, authentication settings 
summary: você pode habilitar ou desabilitar os parâmetros de segurança para monitoramento de conformidade no Unified Manager. 
---
= Habilitar e desabilitar configurações de segurança para conformidade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao usar o botão *Personalizar* no painel *Painel de Segurança* da página Configurações de Recursos, você pode habilitar ou desabilitar os parâmetros de segurança para monitoramento de conformidade no Unified Manager.

As configurações habilitadas ou desabilitadas nesta página controlam o status geral de conformidade dos clusters e VMs de armazenamento no Unified Manager.  Com base nas seleções, as colunas correspondentes ficam visíveis na exibição *Segurança: Todos os clusters* da página de inventário de clusters e na exibição *Segurança: Todas as VMs de armazenamento* da página de inventário de VMs de armazenamento.

[NOTE]
====
Somente usuários com função de administrador podem editar essas configurações.

====
Os critérios de segurança para seus clusters ONTAP , VMs de armazenamento e volumes são avaliados em relação às recomendações definidas nolink:https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["Guia de reforço de segurança para NetApp ONTAP 9"] .  O painel Segurança no painel e a página Segurança exibem o status de conformidade de segurança padrão dos seus clusters, VMs de armazenamento e volumes.  Eventos de segurança também são gerados e ações de gerenciamento são habilitadas para clusters e VMs de armazenamento que têm violações de segurança.



== Personalizar configurações de segurança

Para personalizar as configurações de monitoramento de conformidade aplicáveis ​​ao seu ambiente ONTAP , siga estas etapas:

.Passos
. Clique em *Geral > Configurações de recursos > Painel de segurança > Personalizar*.  O pop-up *Personalizar configurações do painel de segurança* é exibido.
+
[NOTE]
====
Os parâmetros de conformidade de segurança que você habilita ou desabilita podem afetar diretamente as exibições de segurança padrão, relatórios e relatórios agendados nas telas Clusters e VMs de armazenamento.  Se você tiver carregado um relatório do Excel dessas telas antes de modificar os parâmetros de segurança, os relatórios do Excel baixados podem estar com defeito.

====
. Para habilitar ou desabilitar as configurações personalizadas para seus clusters ONTAP , selecione a configuração geral necessária em *Cluster*.  Para obter informações sobre as opções de personalização da conformidade do cluster, consultelink:../health-checker/reference_cluster_compliance_categories.html["Categorias de conformidade do cluster"] .
. Para habilitar ou desabilitar as configurações personalizadas para suas VMs de armazenamento, selecione a configuração geral necessária em *VM de armazenamento*.  Para obter informações sobre as opções de personalização da conformidade da VM de armazenamento, consultelink:../health-checker/reference_svm_compliance_categories.html["Categorias de conformidade de VM de armazenamento"] .




== Personalize as configurações de AutoSupport e autenticação

Na seção * Configurações do AutoSupport *, você pode especificar se o transporte HTTPS deve ser usado para enviar mensagens do AutoSupport do ONTAP.

Na seção *Configurações de autenticação*, você pode habilitar alertas do Unified Manager para serem gerados para o usuário administrador padrão do ONTAP .

'''