---
permalink: config/concept_what_functionality_maintenance_console_provides.html 
sidebar: sidebar 
keywords: functionality, maintenance, console 
summary: O console de manutenção do Unified Manager permite que você mantenha as configurações do seu sistema Unified Manager e faça as alterações necessárias para evitar que problemas ocorram. 
---
= Que funcionalidade o console de manutenção fornece
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O console de manutenção do Unified Manager permite que você mantenha as configurações do seu sistema Unified Manager e faça as alterações necessárias para evitar que problemas ocorram.

Dependendo do sistema operacional no qual você instalou o Unified Manager, o console de manutenção fornece as seguintes funções:

* Solucione quaisquer problemas com seu dispositivo virtual, especialmente se a interface da Web do Unified Manager não estiver disponível
* Atualize para versões mais recentes do Unified Manager
* Gerar pacotes de suporte para enviar ao suporte técnico
* Configurar as configurações de rede
* Alterar a senha do usuário de manutenção
* Conecte-se a um provedor de dados externo para enviar estatísticas de desempenho
* Alterar a coleta interna de dados de desempenho
* Restaure o banco de dados do Unified Manager e as definições de configuração de uma versão de backup anterior.

