---
permalink: config/concept_authentication_with_active_directory_or_openldap.html 
sidebar: sidebar 
keywords: authentication, active directory, openldap 
summary: Você pode habilitar a autenticação remota no servidor de gerenciamento e configurá-lo para se comunicar com seus servidores de autenticação para que os usuários dentro dos servidores de autenticação possam acessar o Unified Manager. 
---
= Autenticação com Active Directory ou OpenLDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode habilitar a autenticação remota no servidor de gerenciamento e configurá-lo para se comunicar com seus servidores de autenticação para que os usuários dentro dos servidores de autenticação possam acessar o Unified Manager.

Você pode usar um dos seguintes serviços de autenticação predefinidos ou especificar seu próprio serviço de autenticação:

* Diretório Ativo da Microsoft
+
[NOTE]
====
Você não pode usar o Microsoft Lightweight Directory Services.

====
* OpenLDAP


Você pode selecionar o serviço de autenticação necessário e adicionar os servidores de autenticação apropriados para permitir que usuários remotos no servidor de autenticação acessem o Unified Manager.  As credenciais para usuários ou grupos remotos são mantidas pelo servidor de autenticação.  O servidor de gerenciamento usa o Lightweight Directory Access Protocol (LDAP) para autenticar usuários remotos dentro do servidor de autenticação configurado.

Para usuários locais criados no Unified Manager, o servidor de gerenciamento mantém seu próprio banco de dados de nomes de usuários e senhas.  O servidor de gerenciamento executa a autenticação e não usa o Active Directory ou o OpenLDAP para autenticação.
