---
permalink: config/concept_api_gateway.html 
sidebar: sidebar 
keywords: api gateway 
summary: O recurso API Gateway permite que o Active IQ Unified Manager seja um único plano de controle a partir do qual você pode gerenciar vários clusters ONTAP , sem precisar fazer login neles individualmente. 
---
= Habilitar API Gateway
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O recurso API Gateway permite que o Active IQ Unified Manager seja um único plano de controle a partir do qual você pode gerenciar vários clusters ONTAP , sem precisar fazer login neles individualmente.

Você pode habilitar esse recurso nas páginas de configuração que aparecem quando você faz login pela primeira vez no Unified Manager.  Como alternativa, você pode habilitar ou desabilitar esse recurso em *Geral* > *Configurações de recursos* > *Gateway de API*.

As APIs REST do Unified Manager são diferentes das APIs REST do ONTAP , e nem todas as funcionalidades das APIs REST do ONTAP podem ser aproveitadas usando as APIs REST do Unified Manager.  No entanto, se você tiver um requisito comercial específico de acesso às APIs do ONTAP para gerenciar recursos específicos que não são expostos ao Unified Manager, você pode habilitar o recurso API Gateway e executar as APIs do ONTAP .  O gateway atua como um proxy para encapsular as solicitações de API, mantendo o cabeçalho e o corpo das solicitações no mesmo formato das APIs ONTAP .  Você pode usar suas credenciais do Unified Manager e executar as APIs específicas para acessar e gerenciar os clusters ONTAP sem passar credenciais de cluster individuais.  O Unified Manager funciona como um único ponto de gerenciamento para executar as APIs nos clusters ONTAP gerenciados pela sua instância do Unified Manager.  A resposta retornada pelas APIs é a mesma que a resposta retornada pelas respectivas APIs REST do ONTAP executadas diretamente do ONTAP.

Após habilitar esse recurso, você pode executar as APIs REST do Unified Manager em *Barra de Menu* > *Botão Ajuda* > *Documentação da API* > categoria *gateway*.  Como alternativa, você pode inserir o nome do host ou endereço IP e a URL para acessar a página da API REST no formato `https://<hostname>/docs/api/`

Para obter mais informações sobre as APIs, consultelink:../api-automation/concept_get_started_with_um_apis.html["Introdução às APIs REST do Active IQ Unified Manager"] .
