---
permalink: config/concept_active_iq_platform_events.html 
sidebar: sidebar 
keywords: feature settings, active iq, portal, events 
summary: Você pode especificar se deseja habilitar ou desabilitar eventos do portal Active IQ .  Esta configuração permite que o portal Active IQ descubra e exiba eventos adicionais sobre configuração do sistema, cabeamento e assim por diante. Esta opção é habilitada por padrão. 
---
= Habilitar eventos do portal Active IQ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode especificar se deseja habilitar ou desabilitar eventos do portal Active IQ .  Esta configuração permite que o portal Active IQ descubra e exiba eventos adicionais sobre configuração do sistema, cabeamento e assim por diante. Esta opção é habilitada por padrão.

Ao habilitar esse recurso, o Active IQ Unified Manager exibe eventos descobertos pelo portal Active IQ .  Esses eventos são criados executando um conjunto de regras em mensagens do AutoSupport geradas de todos os sistemas de armazenamento monitorados.  Esses eventos são diferentes dos outros eventos do Unified Manager e identificam incidentes ou riscos relacionados à configuração do sistema, cabeamento, práticas recomendadas e problemas de disponibilidade.

Você pode escolher ativar ou desativar esse recurso em *Geral* > *Configurações de recursos* > *Eventos Active IQ *.  Em sites sem acesso à rede externa, você deve carregar as regras manualmente em *Gerenciamento de armazenamento* > *Configuração de evento* > *Carregar regras*.

Este recurso é habilitado por padrão.  Desabilitar esse recurso impede que os eventos do Active IQ sejam descobertos ou exibidos no Unified Manager.  Quando desabilitado, habilitar esse recurso permite que o Unified Manager receba os eventos do Active IQ em um cluster em um horário predefinido de 00:15 para o fuso horário desse cluster.
