---
permalink: config/concept_policy_based_storage_management.html 
sidebar: sidebar 
keywords: slo, storage efficiency policy, storage workloads 
summary: 'A opção de gerenciamento de armazenamento baseado em políticas permite o gerenciamento de armazenamento com base em objetivos de nível de serviço (SLOs). Esta opção é habilitada por padrão.' 
---
= Habilitar gerenciamento de armazenamento baseado em políticas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A opção *Gerenciamento de armazenamento baseado em políticas* permite o gerenciamento de armazenamento com base em objetivos de nível de serviço (SLOs). Esta opção é habilitada por padrão.

Ao ativar esse recurso, você pode provisionar cargas de trabalho de armazenamento nos clusters ONTAP adicionados à sua instância do Active IQ Unified Manager e gerenciar essas cargas de trabalho com base nos Níveis de Serviço de Desempenho e Políticas de Eficiência de Armazenamento atribuídos.

Você pode optar por ativar ou desativar esse recurso em *Geral* > *Configurações de recursos* > *Gerenciamento de armazenamento baseado em políticas*.  Ao ativar este recurso, as seguintes páginas estarão disponíveis para operação e monitoramento:

* Provisionamento (provisionamento de carga de trabalho de armazenamento)
* *Políticas* > *Níveis de Serviço de Desempenho*
* *Políticas* > *Eficiência de Armazenamento*
* Coluna Cargas de trabalho gerenciadas por nível de serviço de desempenho na página Configuração de clusters
* Painel de desempenho da carga de trabalho no *Painel*


Você pode usar as telas para criar Níveis de Serviço de Desempenho e Políticas de Eficiência de Armazenamento, além de provisionar cargas de trabalho de armazenamento.  Você também pode monitorar as cargas de trabalho de armazenamento que estão em conformidade com os Níveis de Serviço de Desempenho atribuídos, bem como as que não estão em conformidade.  O painel Desempenho da carga de trabalho e IOPS da carga de trabalho também permite que você avalie a capacidade e o desempenho (IOPS) total, disponível e usado dos clusters em seu data center com base nas cargas de trabalho de armazenamento provisionadas neles.

Após ativar esse recurso, você pode executar as APIs REST do Unified Manager para executar algumas dessas funções em *Barra de menus* > *Botão Ajuda* > *Documentação da API* > categoria *provedor de armazenamento*.  Como alternativa, você pode inserir o nome do host ou endereço IP e a URL para acessar a página da API REST no formato +https://<nome do host>/docs/api/+

Para obter mais informações sobre as APIs, consultelink:../api-automation/concept_get_started_with_um_apis.html["Introdução às APIs REST do Active IQ Unified Manager"] .
