---
permalink: config/reference_definitions_of_user_roles.html 
sidebar: sidebar 
keywords: definitions, user roles 
summary: O usuário de manutenção ou administrador do aplicativo atribui uma função a cada usuário.  Cada função contém certos privilégios.  O escopo de atividades que você pode executar no Unified Manager depende da função atribuída a você e dos privilégios que a função contém. 
---
= Definições de funções de usuário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O usuário de manutenção ou administrador do aplicativo atribui uma função a cada usuário.  Cada função contém certos privilégios.  O escopo de atividades que você pode executar no Unified Manager depende da função atribuída a você e dos privilégios que a função contém.

O Unified Manager inclui as seguintes funções de usuário predefinidas:

* *Operador*
+
Visualiza informações do sistema de armazenamento e outros dados coletados pelo Unified Manager, incluindo históricos e tendências de capacidade.  Essa função permite que o operador de armazenamento visualize, atribua, reconheça, resolva e adicione notas para os eventos.

* *Administrador de Armazenamento*
+
Configura operações de gerenciamento de armazenamento no Unified Manager.  Essa função permite que o administrador de armazenamento configure limites e crie alertas e outras opções e políticas específicas de gerenciamento de armazenamento.

* *Administrador do aplicativo*
+
Configura definições não relacionadas ao gerenciamento de armazenamento.  Esta função permite o gerenciamento de usuários, certificados de segurança, acesso ao banco de dados e opções administrativas, incluindo autenticação, SMTP, rede e AutoSupport.

+
[NOTE]
====
Quando o Unified Manager é instalado em sistemas Linux, o usuário inicial com a função de Administrador de Aplicativos é automaticamente nomeado "`umadmin`".

====
* *Esquema de Integração*
+
Esta função permite acesso somente leitura às visualizações do banco de dados do Unified Manager para integração com o OnCommand Workflow Automation (WFA).

* *Esquema de Relatório*
+
Essa função permite acesso somente leitura a relatórios e outras visualizações de banco de dados diretamente do banco de dados do Unified Manager.  Os bancos de dados que podem ser visualizados incluem:

+
** netapp_model_view
** netapp_desempenho
** ocum
** ocum_report
** ocum_report_birth
** opm
** monitor de escala



