---
permalink: config/reference_remote_authentication_page.html 
sidebar: sidebar 
keywords: remote authentication, page 
summary: Você pode usar a página Autenticação Remota para configurar o Unified Manager para se comunicar com seu servidor de autenticação para autenticar usuários remotos que tentam fazer login na interface da Web do Unified Manager. 
---
= Página de autenticação remota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a página Autenticação Remota para configurar o Unified Manager para se comunicar com seu servidor de autenticação para autenticar usuários remotos que tentam fazer login na interface da Web do Unified Manager.

Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Depois de marcar a caixa de seleção Habilitar autenticação remota, você pode habilitar a autenticação remota usando um servidor de autenticação.

* *Serviço de Autenticação*
+
Permite que você configure o servidor de gerenciamento para autenticar usuários em provedores de serviços de diretório, como Active Directory, OpenLDAP, ou especifique seu próprio mecanismo de autenticação.  Você pode especificar um serviço de autenticação somente se tiver habilitado a autenticação remota.

+
** *Diretório Ativo*
+
*** Nome do Administrador
+
Especifica o nome do administrador do servidor de autenticação.

*** Senha
+
Especifica a senha para acessar o servidor de autenticação.

*** Nome Distinto Base
+
Especifica a localização dos usuários remotos no servidor de autenticação.  Por exemplo, se o nome de domínio do servidor de autenticação for +ou@domain.com+, o nome distinto base será *cn=ou,dc=domain,dc=com*.

*** Desativar pesquisa de grupo aninhado
+
Especifica se a opção de pesquisa de grupo aninhado deve ser habilitada ou desabilitada.  Por padrão, esta opção está desabilitada.  Se você usar o Active Directory, poderá acelerar a autenticação desabilitando o suporte para grupos aninhados.

*** Usar conexão segura
+
Especifica o serviço de autenticação usado para comunicação com servidores de autenticação.



** *OpenLDAP*
+
*** Vincular nome distinto
+
Especifica o nome distinto de vinculação que é usado junto com o nome distinto base para localizar usuários remotos no servidor de autenticação.

*** Senha de vinculação
+
Especifica a senha para acessar o servidor de autenticação.

*** Nome Distinto Base
+
Especifica a localização dos usuários remotos no servidor de autenticação.  Por exemplo, se o nome de domínio do servidor de autenticação for +ou@domain.com+, o nome distinto base será *cn=ou,dc=domain,dc=com*.

*** Usar conexão segura
+
Especifica que o LDAP seguro é usado para comunicação com servidores de autenticação LDAP.



** *Outros*
+
*** Vincular nome distinto
+
Especifica o nome distinto de vinculação que é usado junto com o nome distinto base para localizar usuários remotos no servidor de autenticação que você configurou.

*** Senha de vinculação
+
Especifica a senha para acessar o servidor de autenticação.

*** Nome Distinto Base
+
Especifica a localização dos usuários remotos no servidor de autenticação.  Por exemplo, se o nome de domínio do servidor de autenticação for +ou@domain.com+, o nome distinto base será *cn=ou,dc=domain,dc=com*.

*** Versão do Protocolo
+
Especifica a versão do Lightweight Directory Access Protocol (LDAP) suportada pelo seu servidor de autenticação.  Você pode especificar se a versão do protocolo deve ser detectada automaticamente ou definir a versão como 2 ou 3.

*** Atributo de nome de usuário
+
Especifica o nome do atributo no servidor de autenticação que contém nomes de login de usuário a serem autenticados pelo servidor de gerenciamento.

*** Atributo de Associação de Grupo
+
Especifica um valor que atribui a associação do grupo do servidor de gerenciamento a usuários remotos com base em um atributo e valor especificados no servidor de autenticação do usuário.

*** UGID
+
Se os usuários remotos forem incluídos como membros de um objeto GroupOfUniqueNames no servidor de autenticação, esta opção permitirá que você atribua a associação de grupo do servidor de gerenciamento aos usuários remotos com base em um atributo especificado nesse objeto GroupOfUniqueNames.

*** Desativar pesquisa de grupo aninhado
+
Especifica se a opção de pesquisa de grupo aninhado deve ser habilitada ou desabilitada.  Por padrão, esta opção está desabilitada.  Se você usar o Active Directory, poderá acelerar a autenticação desabilitando o suporte para grupos aninhados.

*** Membro
+
Especifica o nome do atributo que seu servidor de autenticação usa para armazenar informações sobre os membros individuais de um grupo.

*** Classe de objeto do usuário
+
Especifica a classe de objeto de um usuário no servidor de autenticação remota.

*** Classe de Objeto de Grupo
+
Especifica a classe de objeto de todos os grupos no servidor de autenticação remota.

+

NOTE: Os valores inseridos para os atributos _Membro_, _Classe de Objeto de Usuário_ e _Classe de Objeto de Grupo_ devem ser os mesmos adicionados nas configurações do Active Directory, OpenLDAP e LDAP.  Caso contrário, a autenticação poderá falhar.

*** Usar conexão segura
+
Especifica o serviço de autenticação usado para comunicação com servidores de autenticação.





+
[NOTE]
====
Se você quiser modificar o serviço de autenticação, certifique-se de excluir todos os servidores de autenticação existentes e adicionar novos servidores de autenticação.

====




== Área de Servidores de Autenticação

A área Servidores de autenticação exibe os servidores de autenticação com os quais o servidor de gerenciamento se comunica para localizar e autenticar usuários remotos.  As credenciais para usuários ou grupos remotos são mantidas pelo servidor de autenticação.

* *Botões de comando*
+
Permite adicionar, editar ou excluir servidores de autenticação.

+
** Adicionar
+
Permite que você adicione um servidor de autenticação.

+
Se o servidor de autenticação que você está adicionando fizer parte de um par de alta disponibilidade (usando o mesmo banco de dados), você também poderá adicionar o servidor de autenticação do parceiro.  Isso permite que o servidor de gerenciamento se comunique com o parceiro quando um dos servidores de autenticação estiver inacessível.

** Editar
+
Permite que você edite as configurações de um servidor de autenticação selecionado.

** Excluir
+
Exclui os servidores de autenticação selecionados.



* *Nome ou endereço IP*
+
Exibe o nome do host ou endereço IP do servidor de autenticação usado para autenticar o usuário no servidor de gerenciamento.

* *Porta*
+
Exibe o número da porta do servidor de autenticação.

* *Teste de Autenticação*
+
Este botão valida a configuração do seu servidor de autenticação autenticando um usuário ou grupo remoto.

+
Durante o teste, se você especificar apenas o nome do usuário, o servidor de gerenciamento procurará o usuário remoto no servidor de autenticação, mas não autenticará o usuário.  Se você especificar o nome de usuário e a senha, o servidor de gerenciamento pesquisará e autenticará o usuário remoto.

+
Não é possível testar a autenticação se a autenticação remota estiver desabilitada.


