---
permalink: config/reference_identity_provider_requirements_um.html 
sidebar: sidebar 
keywords: identity, provider, requirements 
summary: 'Ao configurar o Unified Manager para usar um provedor de identidade (IdP) para executar a autenticação SAML para todos os usuários remotos, você precisa estar ciente de algumas configurações necessárias para que a conexão com o Unified Manager seja bem-sucedida.' 
---
= Requisitos do provedor de identidade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao configurar o Unified Manager para usar um provedor de identidade (IdP) para executar a autenticação SAML para todos os usuários remotos, você precisa estar ciente de algumas configurações necessárias para que a conexão com o Unified Manager seja bem-sucedida.

Você deve inserir o URI e os metadados do Unified Manager no servidor IdP.  Você pode copiar essas informações da página Autenticação SAML do Unified Manager.  O Unified Manager é considerado o provedor de serviços (SP) no padrão Security Assertion Markup Language (SAML).



[[supported-encryption-standards]]
== Padrões de criptografia suportados

* Padrão de Criptografia Avançada (AES): AES-128 e AES-256
* Algoritmo de Hash Seguro (SHA): SHA-1 e SHA-256




[[validated-identity-providers]]
== Provedores de identidade validados

* Shibboleth
* Serviços de Federação do Active Directory (ADFS)




[[adfs-configuration-requirements]]
== Requisitos de configuração do ADFS

* Você deve definir três regras de reivindicação na seguinte ordem que são necessárias para que o Unified Manager analise as respostas SAML do ADFS para esta entrada de confiança da parte confiável.
+
[cols="2*"]
|===
| Regra de reivindicação | Valor 


 a| 
Nome da conta SAM
 a| 
Nome ID



 a| 
Nome da conta SAM
 a| 
urna:oid:0.9.2342.19200300.100.1.1



 a| 
Grupos de tokens -- Nome não qualificado
 a| 
urna:oide:1.3.6.1.4.1.5923.1.5.1.1

|===
* Você deve definir o método de autenticação como "`Autenticação de formulários`" ou os usuários poderão receber um erro ao efetuar logout do Unified Manager. Siga estes passos:
+
.. Abra o Console de Gerenciamento do ADFS.
.. Clique na pasta Políticas de Autenticação na visualização em árvore à esquerda.
.. Em Ações à direita, clique em Editar política de autenticação primária global.
.. Defina o Método de Autenticação da Intranet como "`Autenticação de Formulários`" em vez do padrão "`Autenticação do Windows`".


* Em alguns casos, o login pelo IdP é rejeitado quando o certificado de segurança do Unified Manager é assinado pela CA.  Há duas soluções alternativas para resolver esse problema:
+
** Siga as instruções identificadas no link para desabilitar a verificação de revogação no servidor ADFS para a parte confiável associada ao certificado de CA encadeado:
+
http://www.torivar.com/2016/03/22/adfs-3-0-disable-revocation-check-windows-2012-r2/["Desabilitar verificação de revogação por parte confiável"]

** Faça com que o servidor CA resida no servidor ADFS para assinar a solicitação de certificado do servidor do Unified Manager.






[[other-configuration-requirements]]
== Outros requisitos de configuração

* O desvio de relógio do Unified Manager é definido como 5 minutos, portanto a diferença de tempo entre o servidor IdP e o servidor do Unified Manager não pode ser maior que 5 minutos, ou a autenticação falhará.

