---
permalink: config/reference_unified_manager_roles_and_capabilities.html 
sidebar: sidebar 
keywords: unified manager, user, roles, capabilities 
summary: Com base na função de usuário atribuída a você, você pode determinar quais operações pode executar no Unified Manager. 
---
= Funções e recursos do usuário do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Com base na função de usuário atribuída a você, você pode determinar quais operações pode executar no Unified Manager.

A tabela a seguir exibe as funções que cada função de usuário pode executar:

[cols="6*"]
|===
| Função | Operador | Administrador de Armazenamento | Administrador do aplicativo | Esquema de Integração | Esquema de Relatório 


 a| 
Exibir informações do sistema de armazenamento
 a| 
•
 a| 
•
 a| 
•
 a| 
•
 a| 
•



 a| 
Veja outros dados, como históricos e tendências de capacidade
 a| 
•
 a| 
•
 a| 
•
 a| 
•
 a| 
•



 a| 
Visualizar, atribuir e resolver eventos
 a| 
•
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Exibir objetos de serviço de armazenamento, como associações de SVM e pools de recursos
 a| 
•
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Ver políticas de limite
 a| 
•
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Gerenciar objetos de serviço de armazenamento, como associações SVM e pools de recursos
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Definir alertas
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Gerenciar opções de gerenciamento de armazenamento
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Gerenciar políticas de gerenciamento de armazenamento
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Gerenciar usuários
 a| 
 a| 
 a| 
•
 a| 
 a| 



 a| 
Gerenciar opções administrativas
 a| 
 a| 
 a| 
•
 a| 
 a| 



 a| 
Definir políticas de limite
 a| 
 a| 
 a| 
•
 a| 
 a| 



 a| 
Gerenciar acesso ao banco de dados
 a| 
 a| 
 a| 
•
 a| 
 a| 



 a| 
Gerenciar a integração com o WFA e fornecer acesso às visualizações do banco de dados
 a| 
 a| 
 a| 
 a| 
•
 a| 



 a| 
Agendar e salvar relatórios
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Executar operações "`Fix It`" a partir de Ações de Gerenciamento
 a| 
 a| 
•
 a| 
•
 a| 
 a| 



 a| 
Forneça acesso somente leitura às visualizações do banco de dados
 a| 
 a| 
 a| 
 a| 
 a| 
•

|===