---
permalink: config/task_configure_audit_logs.html 
sidebar: sidebar 
keywords: configure, audit logs 
summary: Você pode usar o botão Configurar na seção Logs de auditoria para configurar a política contínua para arquivos de Log de auditoria e também habilitar o registro remoto para os Logs de auditoria. 
---
= Configurar logs de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o botão *Configurar* na seção Logs de Auditoria para configurar a política contínua para arquivos de Log de Auditoria e também habilitar o registro remoto para os Logs de Auditoria.

Você pode definir os valores em *TAMANHO MÁXIMO DO ARQUIVO* e *DIAS DE RETENÇÃO DO LOG DE AUDITORIA* de acordo com a quantidade e a frequência desejadas de dados que você deseja armazenar no sistema.  O valor no campo *TAMANHO TOTAL DO LOG DE AUDITORIA* é o tamanho total dos dados do log de auditoria presentes no sistema.  A política de rollover é determinada pelos valores no campo *DIAS DE RETENÇÃO DO LOG DE AUDITORIA*, *TAMANHO MÁXIMO DO ARQUIVO* e *TAMANHO TOTAL DO LOG DE AUDITORIA*.  Quando o tamanho do backup do log de auditoria atinge o valor configurado em *TAMANHO TOTAL DO LOG DE AUDITORIA*, o arquivo que foi arquivado primeiro é excluído.  Isso significa que o arquivo mais antigo é excluído.  Mas a entrada do arquivo continua disponível no banco de dados e é marcada como "`Rollover Delete`".  O valor *DIAS DE RETENÇÃO DO LOG DE AUDITORIA* é para o número de dias em que os arquivos de log de auditoria são preservados.  Qualquer arquivo mais antigo que o valor definido neste campo será substituído.

.Passos
. Clique em *Registros de auditoria* > > *Configurar*.
. Insira valores em *TAMANHO MÁXIMO DO ARQUIVO*, *TAMANHO TOTAL DO LOG DE AUDITORIA* e *DIAS DE RETENÇÃO DO LOG DE AUDITORIA*.
+
Se você quiser habilitar o registro remoto, selecione *Habilitar registro remoto*.  /// 2025-6-11, OUTRODOC-133


