---
permalink: config/task_change_identity_provider_idp_used_for_saml_authentication.html 
sidebar: sidebar 
keywords: change, identity, provider, used, saml, authentication 
summary: 'Você pode alterar o provedor de identidade (IdP) que o Unified Manager usa para autenticar usuários remotos.' 
---
= Alterar o provedor de identidade usado para autenticação SAML
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar o provedor de identidade (IdP) que o Unified Manager usa para autenticar usuários remotos.

.Antes de começar
* Você deve ter o URL e os metadados do IdP.
* Você deve ter acesso ao IdP.


O novo IdP pode ser configurado antes ou depois da configuração do Unified Manager.

.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Autenticação SAML*.
. Insira o novo URI do IdP e os metadados do IdP necessários para conectar o servidor do Unified Manager ao IdP.
+
Se o IdP estiver acessível diretamente do servidor do Unified Manager, você poderá clicar no botão *Obter metadados do IdP* depois de inserir o URL do IdP para preencher o campo Metadados do IdP automaticamente.

. Copie o URI de metadados do Unified Manager ou salve os metadados em um arquivo de texto XML.
. Clique em *Salvar configuração*.
+
Uma caixa de mensagem é exibida para confirmar que você deseja alterar a configuração.

. Clique em *OK*.


Acesse o novo IdP e insira o URI e os metadados do servidor do Unified Manager para concluir a configuração.

Na próxima vez que usuários remotos autorizados tentarem acessar a interface gráfica do Unified Manager, eles inserirão suas credenciais na nova página de login do IdP em vez da antiga página de login do IdP.
