---
permalink: config/task_disable_saml_authentication_from_maintenance_console_um.html 
sidebar: sidebar 
keywords: disable, saml authentication, maintenance, console 
summary: Pode ser necessário desabilitar a autenticação SAML no console de manutenção quando não houver acesso à GUI do Unified Manager.  Isso pode acontecer em casos de configuração incorreta ou se o IdP não estiver acessível. 
---
= Desabilitar a autenticação SAML no console de manutenção
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode ser necessário desabilitar a autenticação SAML no console de manutenção quando não houver acesso à GUI do Unified Manager.  Isso pode acontecer em casos de configuração incorreta ou se o IdP não estiver acessível.

.Antes de começar
Você deve ter acesso ao console de manutenção como usuário de manutenção.

Quando a autenticação SAML está desabilitada, os provedores de serviços de diretório configurados, como Active Directory ou LDAP, executam a autenticação de logon.  Usuários locais e usuários de manutenção poderão acessar a interface gráfica do usuário, além dos usuários remotos configurados.

Você também pode desabilitar a autenticação SAML na página Configuração/Autenticação na interface do usuário.

[NOTE]
====
O Unified Manager é reiniciado automaticamente após a autenticação SAML ser desabilitada.

====
.Passos
. Efetue login no console de manutenção.
. No *Menu Principal*, insira o número da opção *Desativar autenticação SAML*.
+
Uma mensagem é exibida para confirmar que você deseja desabilitar a autenticação SAML e reiniciar o Unified Manager.

. Digite *y* e pressione Enter para reiniciar o Unified Manager.


Na próxima vez que usuários remotos tentarem acessar a interface gráfica do Unified Manager, eles inserirão suas credenciais na página de login do Unified Manager em vez da página de login do IdP.

Se necessário, acesse seu IdP e exclua o URL e os metadados do servidor do Unified Manager.
