---
permalink: config/task_change_um_host_name_on_rhel.html 
sidebar: sidebar 
keywords: change, unified manager, host name, linux systems 
summary: Em algum momento, você pode querer alterar o nome do host da máquina Red Hat Enterprise Linux na qual instalou o Unified Manager.  Por exemplo, você pode querer renomear o host para identificar mais facilmente seus servidores do Unified Manager por tipo, grupo de trabalho ou grupo de cluster monitorado ao listar suas máquinas Linux. 
---
= Alterar o nome do host do Unified Manager em sistemas Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em algum momento, você pode querer alterar o nome do host da máquina Red Hat Enterprise Linux na qual instalou o Unified Manager.  Por exemplo, você pode querer renomear o host para identificar mais facilmente seus servidores do Unified Manager por tipo, grupo de trabalho ou grupo de cluster monitorado ao listar suas máquinas Linux.

.Antes de começar
Você deve ter acesso de usuário root ao sistema Linux no qual o Unified Manager está instalado.

Você pode usar o nome do host (ou o endereço IP do host) para acessar a interface da Web do Unified Manager.  Se você configurou um endereço IP estático para sua rede durante a implantação, você teria designado um nome para o host da rede.  Se você configurou a rede usando DHCP, o nome do host deve ser obtido do servidor DNS.

Independentemente de como o nome do host foi atribuído, se você alterar o nome do host e pretende usar o novo nome do host para acessar a interface da Web do Unified Manager, será necessário gerar um novo certificado de segurança.

Se você acessar a interface da Web usando o endereço IP do servidor em vez do nome do host, não precisará gerar um novo certificado se alterar o nome do host.  No entanto, a melhor prática é atualizar o certificado para que o nome do host no certificado corresponda ao nome do host real.  O novo certificado não entrará em vigor até que a máquina Linux seja reiniciada.

Se você alterar o nome do host no Unified Manager, deverá atualizá-lo manualmente no OnCommand Workflow Automation (WFA).  O nome do host não é atualizado automaticamente no WFA.

.Passos
. Efetue login como usuário root no sistema Unified Manager que você deseja modificar.
. Pare o software Unified Manager e o software MySQL associado inserindo o seguinte comando:
+
`systemctl stop ocieau ocie mysqld`

. Alterar o nome do host usando o Linux `hostnamectl` comando:
+
`hostnamectl set-hostname new_FQDN`

+
`hostnamectl set-hostname nuhost.corp.widget.com`

. Regenere o certificado HTTPS para o servidor:
+
`/opt/netapp/essentials/bin/cert.sh create`

. Reinicie o serviço de rede:
+
`systemctl restart NetworkManager.service`

. Após o serviço ser reiniciado, verifique se o novo nome do host consegue fazer ping em si mesmo:
+
`ping new_hostname`

+
`ping nuhost`

+
Este comando deve retornar o mesmo endereço IP que foi definido anteriormente para o nome do host original.

. Após concluir e verificar a alteração do nome do host, reinicie o Unified Manager digitando o seguinte comando:
+
`systemctl start mysqld ocie ocieau`


