---
permalink: config/task_set_session_inactivity_timeout.html 
sidebar: sidebar 
keywords: inactivity, timeout 
summary: 'Você pode especificar o valor do tempo limite de inatividade do Unified Manager para que a sessão seja encerrada automaticamente após um determinado período de tempo.  Por padrão, o tempo limite é definido como 4.320 minutos (72 horas).' 
---
= Definir o tempo limite de inatividade da sessão
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode especificar o valor do tempo limite de inatividade do Unified Manager para que a sessão seja encerrada automaticamente após um determinado período de inatividade.  Por padrão, o tempo limite é definido como 4.320 minutos (72 horas).

.Antes de começar
Você deve ter a função de Administrador do Aplicativo.

Esta configuração afeta todas as sessões de usuários conectados.

[NOTE]
====
Esta opção não estará disponível se você tiver habilitado a autenticação Security Assertion Markup Language (SAML).

====
.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Configurações de recursos*.
. Na página *Configurações de recursos*, especifique o tempo limite de inatividade escolhendo uma das seguintes opções:
+
[cols="2*"]
|===
| Se você quiser... | Então faça isto... 


 a| 
Não defina nenhum tempo limite para que a sessão nunca seja fechada automaticamente
 a| 
No painel *Tempo limite de inatividade*, mova o botão deslizante para a esquerda (desligado) e clique em *Aplicar*.



 a| 
Defina um número específico de minutos como valor de tempo limite
 a| 
No painel *Tempo limite de inatividade*, mova o botão deslizante para a direita (ligado), especifique o valor do tempo limite de inatividade em minutos e clique em *Aplicar*.

|===

