---
permalink: config/task_change_local_user_password.html 
sidebar: sidebar 
keywords: change, local, user, password 
summary: Você pode alterar sua senha de login de usuário local para evitar potenciais riscos de segurança. 
---
= Alterar a senha do usuário local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar sua senha de login de usuário local para evitar potenciais riscos de segurança.

.Antes de começar
Você deve estar logado como usuário local.

As senhas do usuário de manutenção e dos usuários remotos não podem ser alteradas usando estas etapas.  Para alterar a senha de um usuário remoto, entre em contato com o administrador de senhas.  Para alterar a senha do usuário de manutenção, consultelink:task_use_maintenance_console.html["Usando o console de manutenção"] .

.Passos
. Efetue login no Unified Manager.
. Na barra de menu superior, clique no ícone do usuário e depois clique em *Alterar senha*.
+
A opção *Alterar senha* não será exibida se você for um usuário remoto.

. Na caixa de diálogo Alterar senha, digite a senha atual e a nova senha.
. Clique em *Salvar*.


Se o Unified Manager estiver configurado em uma configuração de alta disponibilidade, você deverá alterar a senha no segundo nó da configuração.  Ambas as instâncias devem ter a mesma senha.
