---
permalink: config/task_set_up_authentication_services.html 
sidebar: sidebar 
keywords: set up, authentication, services 
summary: 'Os serviços de autenticação permitem a autenticação de usuários remotos ou grupos remotos em um servidor de autenticação antes de fornecer a eles acesso ao Unified Manager.  Você pode autenticar usuários usando serviços de autenticação predefinidos (como Active Directory ou OpenLDAP) ou configurando seu próprio mecanismo de autenticação.' 
---
= Configurar serviços de autenticação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os serviços de autenticação permitem a autenticação de usuários remotos ou grupos remotos em um servidor de autenticação antes de fornecer a eles acesso ao Unified Manager.  Você pode autenticar usuários usando serviços de autenticação predefinidos (como Active Directory ou OpenLDAP) ou configurando seu próprio mecanismo de autenticação.

.Antes de começar
* Você deve ter habilitado a autenticação remota.
* Você deve ter a função de Administrador do Aplicativo.


.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Autenticação Remota*.
. Selecione um dos seguintes serviços de autenticação:
+
[cols="2*"]
|===
| Se você selecionar... | Então faça isto... 


 a| 
Diretório ativo
 a| 
.. Digite o nome e a senha do administrador.
.. Especifique o nome distinto base do servidor de autenticação.
+
Por exemplo, se o nome de domínio do servidor de autenticação for +ou@domain.com+, o nome distinto base será *cn=ou,dc=domain,dc=com*.





 a| 
OpenLDAP
 a| 
.. Digite o nome distinto e a senha de vinculação.
.. Especifique o nome distinto base do servidor de autenticação.
+
Por exemplo, se o nome de domínio do servidor de autenticação for +ou@domain.com+, o nome distinto base será *cn=ou,dc=domain,dc=com*.





 a| 
Outros
 a| 
.. Digite o nome distinto e a senha de vinculação.
.. Especifique o nome distinto base do servidor de autenticação.
+
Por exemplo, se o nome de domínio do servidor de autenticação for +ou@domain.com+, o nome distinto base será *cn=ou,dc=domain,dc=com*.

.. Especifique a versão do protocolo LDAP suportada pelo servidor de autenticação.
.. Insira o nome do usuário, a associação ao grupo, o grupo de usuários e os atributos do membro.


|===
+
[NOTE]
====
Se quiser modificar o serviço de autenticação, você deverá excluir todos os servidores de autenticação existentes e, em seguida, adicionar novos servidores de autenticação.

====
. Clique em *Salvar*.

