---
permalink: config/task_add_authentication_servers.html 
sidebar: sidebar 
keywords: add, authentication servers 
summary: Você pode adicionar servidores de autenticação e habilitar a autenticação remota no servidor de gerenciamento para que usuários remotos dentro do servidor de autenticação possam acessar o Unified Manager. 
---
= Adicionar servidores de autenticação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar servidores de autenticação e habilitar a autenticação remota no servidor de gerenciamento para que usuários remotos dentro do servidor de autenticação possam acessar o Unified Manager.

.Antes de começar
* As seguintes informações devem estar disponíveis:
+
** Nome do host ou endereço IP do servidor de autenticação
** Número da porta do servidor de autenticação


* Você deve ter habilitado a autenticação remota e configurado seu serviço de autenticação para que o servidor de gerenciamento possa autenticar usuários ou grupos remotos no servidor de autenticação.
* Você deve ter a função de Administrador do Aplicativo.


Se o servidor de autenticação que você está adicionando fizer parte de um par de alta disponibilidade (HA) (usando o mesmo banco de dados), você também poderá adicionar o servidor de autenticação do parceiro.  Isso permite que o servidor de gerenciamento se comunique com o parceiro quando um dos servidores de autenticação estiver inacessível.

.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Autenticação Remota*.
. Habilite ou desabilite a opção *Usar conexão segura*:
+
[cols="2*"]
|===
| Se você quiser... | Então faça isto... 


 a| 
Habilite-o
 a| 
.. Selecione a opção *Usar conexão segura*.
.. Na área Servidores de autenticação, clique em *Adicionar*.
.. Na caixa de diálogo Adicionar servidor de autenticação, insira o nome de autenticação ou endereço IP (IPv4 ou IPv6) do servidor.
.. Na caixa de diálogo Autorizar Host, clique em Exibir Certificado.
.. Na caixa de diálogo Exibir certificado, verifique as informações do certificado e clique em *Fechar*.
.. Na caixa de diálogo Autorizar Host, clique em *Sim*.
+
[NOTE]
====
Quando você habilita a opção *Usar autenticação de conexão segura*, o Unified Manager se comunica com o servidor de autenticação e exibe o certificado.  O Unified Manager usa 636 como porta padrão para comunicação segura e a porta número 389 para comunicação não segura.

====




 a| 
Desabilite-o
 a| 
.. Desmarque a opção *Usar conexão segura*.
.. Na área Servidores de autenticação, clique em *Adicionar*.
.. Na caixa de diálogo Adicionar servidor de autenticação, especifique o nome do host ou o endereço IP (IPv4 ou IPv6) do servidor e os detalhes da porta.
.. Clique em *Adicionar*.


|===
+
O servidor de autenticação que você adicionou é exibido na área Servidores.

. Execute um teste de autenticação para confirmar se você pode autenticar usuários no servidor de autenticação que você adicionou.

