---
permalink: config/task_disable_saml_authentication_um.html 
sidebar: sidebar 
keywords: disable, saml authentication 
summary: 'Você pode desabilitar a autenticação SAML quando quiser parar de autenticar usuários remotos por meio de um provedor de identidade seguro (IdP) antes que eles possam efetuar login na interface da Web do Unified Manager.  Quando a autenticação SAML está desabilitada, os provedores de serviços de diretório configurados, como Active Directory ou LDAP, executam a autenticação de logon.' 
---
= Desativar autenticação SAML
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desabilitar a autenticação SAML quando quiser parar de autenticar usuários remotos por meio de um provedor de identidade seguro (IdP) antes que eles possam efetuar login na interface da Web do Unified Manager.  Quando a autenticação SAML está desabilitada, os provedores de serviços de diretório configurados, como Active Directory ou LDAP, executam a autenticação de logon.

Após desabilitar a autenticação SAML, os usuários locais e de manutenção poderão acessar a interface gráfica do usuário, além dos usuários remotos configurados.

Você também pode desabilitar a autenticação SAML usando o console de manutenção do Unified Manager se não tiver acesso à interface gráfica do usuário.

[NOTE]
====
O Unified Manager é reiniciado automaticamente após a autenticação SAML ser desabilitada.

====
.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Autenticação SAML*.
. Desmarque a caixa de seleção *Ativar autenticação SAML*.
. Clique em *Salvar*.
+
Uma caixa de mensagem é exibida para confirmar que você deseja concluir a configuração e reiniciar o Unified Manager.

. Clique em *Confirmar e Sair* e o Unified Manager será reiniciado.


Na próxima vez que usuários remotos tentarem acessar a interface gráfica do Unified Manager, eles inserirão suas credenciais na página de login do Unified Manager em vez da página de login do IdP.

Acesse seu IdP e exclua o URI e os metadados do servidor do Unified Manager.
