---
permalink: config/task_update_saml_authentication_after_um_certificate_change.html 
sidebar: sidebar 
keywords: update, saml, authentication, settings, unified manager, security, certificate, change 
summary: Qualquer alteração no certificado de segurança HTTPS instalado no servidor do Unified Manager exige que você atualize as configurações de autenticação SAML.  O certificado será atualizado se você renomear o sistema host, atribuir um novo endereço IP para o sistema host ou alterar manualmente o certificado de segurança do sistema. 
---
= Atualizar as configurações de autenticação SAML após a alteração do certificado de segurança do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Qualquer alteração no certificado de segurança HTTPS instalado no servidor do Unified Manager exige que você atualize as configurações de autenticação SAML.  O certificado será atualizado se você renomear o sistema host, atribuir um novo endereço IP para o sistema host ou alterar manualmente o certificado de segurança do sistema.

Depois que o certificado de segurança for alterado e o servidor do Unified Manager for reiniciado, a autenticação SAML não funcionará e os usuários não poderão acessar a interface gráfica do Unified Manager.  Você deve atualizar as configurações de autenticação SAML no servidor IdP e no servidor do Unified Manager para reativar o acesso à interface do usuário.

.Passos
. Efetue login no console de manutenção.
. No *Menu Principal*, insira o número da opção *Desativar autenticação SAML*.
+
Uma mensagem é exibida para confirmar que você deseja desabilitar a autenticação SAML e reiniciar o Unified Manager.

. Inicie a interface do usuário do Unified Manager usando o FQDN ou endereço IP atualizado, aceite o certificado do servidor atualizado no seu navegador e efetue login usando as credenciais do usuário de manutenção.
. Na página *Configuração/Autenticação*, selecione a aba *Autenticação SAML* e configure a conexão IdP.
. Copie o URI de metadados do host do Unified Manager ou salve os metadados do host em um arquivo de texto XML.
. Clique em *Salvar*.
+
Uma caixa de mensagem é exibida para confirmar que você deseja concluir a configuração e reiniciar o Unified Manager.

. Clique em *Confirmar e Sair* e o Unified Manager será reiniciado.
. Acesse seu servidor IdP e insira o URI e os metadados do servidor do Unified Manager para concluir a configuração.
+
[cols="2*"]
|===
| Provedor de identidade | Etapas de configuração 


 a| 
ADFS
 a| 
.. Exclua a entrada de confiança da parte confiável existente na GUI de gerenciamento do ADFS.
.. Adicione uma nova entrada de confiança de terceira parte confiável usando o `saml_sp_metadata.xml` do servidor Unified Manager atualizado.
.. Defina as três regras de reivindicação necessárias para que o Unified Manager analise as respostas SAML do ADFS para esta entrada de confiança da parte confiável.
.. Reinicie o serviço ADFS do Windows.




 a| 
Shibboleth
 a| 
.. Atualize o novo FQDN do servidor Unified Manager no `attribute-filter.xml` e `relying-party.xml` arquivos.
.. Reinicie o servidor web Apache Tomcat e aguarde a porta 8005 ficar online.


|===
. Efetue login no Unified Manager e verifique se a autenticação SAML funciona conforme o esperado por meio do seu IdP.

