---
permalink: config/task_test_configuration_of_authentication_servers_um_6_0.html 
sidebar: sidebar 
keywords: test, configuration, authentication servers 
summary: Você pode validar a configuração dos seus servidores de autenticação para garantir que o servidor de gerenciamento consiga se comunicar com eles.  Você pode validar a configuração pesquisando um usuário remoto ou grupo remoto em seus servidores de autenticação e autenticando-os usando as configurações definidas. 
---
= Teste a configuração dos servidores de autenticação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode validar a configuração dos seus servidores de autenticação para garantir que o servidor de gerenciamento consiga se comunicar com eles.  Você pode validar a configuração pesquisando um usuário remoto ou grupo remoto em seus servidores de autenticação e autenticando-os usando as configurações definidas.

.Antes de começar
* Você deve ter habilitado a autenticação remota e configurado seu serviço de autenticação para que o servidor do Unified Manager possa autenticar o usuário ou grupo remoto.
* Você deve ter adicionado seus servidores de autenticação para que o servidor de gerenciamento possa procurar o usuário remoto ou grupo remoto nesses servidores e autenticá-los.
* Você deve ter a função de Administrador do Aplicativo.


Se o serviço de autenticação estiver definido como Active Directory e se você estiver validando a autenticação de usuários remotos que pertencem ao grupo principal do servidor de autenticação, as informações sobre o grupo principal não serão exibidas nos resultados da autenticação.

.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Autenticação Remota*.
. Clique em *Testar autenticação*.
. Na caixa de diálogo Testar usuário, especifique o nome de usuário e a senha do usuário remoto ou o nome de usuário do grupo remoto e clique em *Testar*.
+
Se você estiver autenticando um grupo remoto, não deverá digitar a senha.


