---
permalink: config/task_change_unified_manager_host_name_on_vmware.html 
sidebar: sidebar 
keywords: change, unified manager, virtual, appliance, host name 
summary: O host de rede recebe um nome quando o dispositivo virtual do Unified Manager é implantado pela primeira vez.  Você pode alterar o nome do host após a implantação.  Se você alterar o nome do host, também deverá gerar novamente o certificado HTTPS. 
---
= Alterar o nome do host do appliance virtual do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O host de rede recebe um nome quando o dispositivo virtual do Unified Manager é implantado pela primeira vez.  Você pode alterar o nome do host após a implantação.  Se você alterar o nome do host, também deverá gerar novamente o certificado HTTPS.

.Antes de começar
Você deve estar conectado ao Unified Manager como usuário de manutenção ou ter a função de Administrador de Aplicativos atribuída a você para executar essas tarefas.

Você pode usar o nome do host (ou o endereço IP do host) para acessar a interface da Web do Unified Manager.  Se você configurou um endereço IP estático para sua rede durante a implantação, você teria designado um nome para o host da rede.  Se você configurou a rede usando DHCP, o nome do host deve ser obtido do DNS.  Se o DHCP ou o DNS não estiver configurado corretamente, o nome do host "`Unified Manager`" será automaticamente atribuído e associado ao certificado de segurança.

Independentemente de como o nome do host foi atribuído, se você alterar o nome do host e pretende usar o novo nome do host para acessar a interface de usuário da Web do Unified Manager, será necessário gerar um novo certificado de segurança.

Se você acessar a interface da Web usando o endereço IP do servidor em vez do nome do host, não precisará gerar um novo certificado se alterar o nome do host.  No entanto, a melhor prática é atualizar o certificado para que o nome do host no certificado corresponda ao nome do host real.

Se você alterar o nome do host no Unified Manager, deverá atualizá-lo manualmente no OnCommand Workflow Automation (WFA).  O nome do host não é atualizado automaticamente no WFA.

O novo certificado não entrará em vigor até que a máquina virtual do Unified Manager seja reiniciada.

.Passos
. xref:task_generate_an_https_security_certificate_ocf.adoc[Gerar um certificado de segurança HTTPS]
+
Se quiser usar o novo nome de host para acessar a interface de usuário da Web do Unified Manager, você deverá gerar novamente o certificado HTTPS para associá-lo ao novo nome de host.

. xref:task_restart_unified_manager_virtual_machine.adoc[Reinicie a máquina virtual do Unified Manager]
+
Depois de regenerar o certificado HTTPS, você deve reiniciar a máquina virtual do Unified Manager.


