---
permalink: config/task_configure_unified_manager_to_send_alert_notifications.html 
sidebar: sidebar 
keywords: configure, unified manager, send, alert, notifications 
summary: Você pode configurar o Unified Manager para enviar notificações que o alertam sobre eventos no seu ambiente.  Antes que as notificações possam ser enviadas, você deve configurar várias outras opções do Unified Manager. 
---
= Configurar o Unified Manager para enviar notificações de alerta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o Unified Manager para enviar notificações que o alertam sobre eventos no seu ambiente.  Antes que as notificações possam ser enviadas, você deve configurar várias outras opções do Unified Manager.

.Antes de começar
Você deve ter a função de Administrador do Aplicativo.

Após implantar o Unified Manager e concluir a configuração inicial, você deve considerar configurar seu ambiente para acionar alertas e gerar e-mails de notificação ou interceptações SNMP com base no recebimento de eventos.

.Passos
. link:task_configure_event_notification_settings.html["Configurar as definições de notificação de eventos"].
+
Se você quiser que notificações de alerta sejam enviadas quando determinados eventos ocorrerem em seu ambiente, você deve configurar um servidor SMTP e fornecer um endereço de e-mail do qual a notificação de alerta será enviada.  Se você quiser usar traps SNMP, você pode selecionar essa opção e fornecer as informações necessárias.

. link:task_enable_remote_authentication.html["Habilitar autenticação remota"].
+
Se você quiser que usuários remotos do LDAP ou do Active Directory acessem a instância do Unified Manager e recebam notificações de alerta, será necessário habilitar a autenticação remota.

. link:task_add_authentication_servers.html["Adicionar servidores de autenticação"].
+
Você pode adicionar servidores de autenticação para que usuários remotos dentro do servidor de autenticação possam acessar o Unified Manager.

. link:task_add_users.html["Adicionar usuários"].
+
Você pode adicionar vários tipos diferentes de usuários locais ou remotos e atribuir funções específicas.  Ao criar um alerta, você atribui um usuário para receber as notificações de alerta.

. link:task_add_alerts.html["Adicionar alertas"].
+
Depois de adicionar o endereço de e-mail para enviar notificações, adicionar usuários para receber as notificações, configurar suas configurações de rede e configurar as opções SMTP e SNMP necessárias para seu ambiente, você poderá atribuir alertas.


