---
permalink: config/task_edit_user_setts.html 
sidebar: sidebar 
keywords: edit, user, settings 
summary: Você pode editar as configurações do usuário, como endereço de e-mail e função, que são especificadas para cada usuário.  Por exemplo, você pode querer alterar a função de um usuário que é um operador de armazenamento e atribuir privilégios de administrador de armazenamento ao usuário. 
---
= Editar as configurações do usuário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar as configurações do usuário — como endereço de e-mail e função — especificadas para cada usuário.  Por exemplo, você pode querer alterar a função de um usuário que é um operador de armazenamento e atribuir privilégios de administrador de armazenamento ao usuário.

.Antes de começar
Você deve ter a função de Administrador do Aplicativo.

Quando você modifica a função atribuída a um usuário, as alterações são aplicadas quando ocorre uma das seguintes ações:

* O usuário efetua logout e login novamente no Unified Manager.
* O tempo limite da sessão de 24 horas foi atingido.


.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Usuários*.
. Na página Usuários, selecione o usuário para o qual você deseja editar as configurações e clique em *Editar*.
. Na caixa de diálogo Editar usuário, edite as configurações apropriadas especificadas para o usuário.
. Clique em *Salvar*.

