---
permalink: config/task_access_unified_manager_web_ui.html 
sidebar: sidebar 
keywords: access, unified manager, web ui 
summary: Depois de instalar o Unified Manager, você pode acessar a interface de usuário da Web para configurar o Unified Manager e começar a monitorar seus sistemas ONTAP . 
---
= Acesse a interface da Web do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de instalar o Unified Manager, você pode acessar a interface de usuário da Web para configurar o Unified Manager e começar a monitorar seus sistemas ONTAP .

.Antes de começar
* Se esta for a primeira vez que você acessa a interface da web, você deve efetuar login como usuário de manutenção (ou usuário umadmin para instalações Linux).
* Se você planeja permitir que os usuários acessem o Unified Manager usando o nome curto em vez de usar o nome de domínio totalmente qualificado (FQDN) ou endereço IP, sua configuração de rede precisa resolver esse nome curto para um FQDN válido.
* Se o servidor usar um certificado digital autoassinado, o navegador poderá exibir um aviso indicando que o certificado não é confiável.  Você pode reconhecer o risco de continuar o acesso ou instalar um certificado digital assinado pela Autoridade de Certificação (CA) para autenticação do servidor.


.Passos
. Inicie a interface de usuário da Web do Unified Manager no seu navegador usando o URL exibido no final da instalação.  O URL é o endereço IP ou nome de domínio totalmente qualificado (FQDN) do servidor do Unified Manager.
+
O link está no seguinte formato: `\https://URL` .

. Efetue login na interface da Web do Unified Manager usando suas credenciais de usuário de manutenção.



NOTE: Se você fizer três tentativas consecutivas sem sucesso de login na interface da web em uma hora, seu acesso ao sistema será bloqueado e você precisará entrar em contato com o administrador do sistema.  Isso é aplicável somente a usuários locais.
