---
permalink: config/task_enable_remote_authentication.html 
sidebar: sidebar 
keywords: enable, remote, authentication 
summary: Você pode habilitar a autenticação remota para que o servidor do Unified Manager possa se comunicar com seus servidores de autenticação.  Os usuários do servidor de autenticação podem acessar a interface gráfica do Unified Manager para gerenciar objetos de armazenamento e dados. 
---
= Habilitar autenticação remota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode habilitar a autenticação remota para que o servidor do Unified Manager possa se comunicar com seus servidores de autenticação.  Os usuários do servidor de autenticação podem acessar a interface gráfica do Unified Manager para gerenciar objetos de armazenamento e dados.

.Antes de começar
Você deve ter a função de Administrador do Aplicativo.

[NOTE]
====
O servidor do Unified Manager deve ser conectado diretamente ao servidor de autenticação.  Você deve desabilitar todos os clientes LDAP locais, como SSSD (System Security Services Daemon) ou NSLCD (Name Service LDAP Caching Daemon).

====
Você pode habilitar a autenticação remota usando o Open LDAP ou o Active Directory.  Se a autenticação remota estiver desabilitada, os usuários remotos não poderão acessar o Unified Manager.

A autenticação remota é suportada por LDAP e LDAPS (LDAP seguro).  O Unified Manager usa 389 como a porta padrão para comunicação não segura e 636 como a porta padrão para comunicação segura.

[NOTE]
====
O certificado usado para autenticar usuários deve estar em conformidade com o formato X.509.

====
.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Autenticação Remota*.
. Marque a caixa *Ativar autenticação remota...*.
. No campo Serviço de autenticação, selecione o tipo de serviço e configure o serviço de autenticação.
+
[cols="2*"]
|===
| Para tipo de autenticação... | Insira as seguintes informações... 


 a| 
Diretório ativo
 a| 
** Nome do administrador do servidor de autenticação em um dos seguintes formatos:
+
*** `domainname\username`
*** `username@domainname`
*** `Bind Distinguished Name`(usando a notação LDAP apropriada)


** Senha do administrador
** Nome distinto base (usando a notação LDAP apropriada)




 a| 
Abra o LDAP
 a| 
** Vincular nome distinto (na notação LDAP apropriada)
** Vincular senha
** Nome distinto base


|===
+
Se a autenticação de um usuário do Active Directory demorar muito ou atingir o tempo limite, o servidor de autenticação provavelmente está demorando muito para responder.  Desabilitar o suporte para grupos aninhados no Unified Manager pode reduzir o tempo de autenticação.

+
Se você selecionar a opção Usar conexão segura para o servidor de autenticação, o Unified Manager se comunicará com o servidor de autenticação usando o protocolo Secure Sockets Layer (SSL).

. *Opcional:* Adicione servidores de autenticação e teste a autenticação.
. Clique em *Salvar*.

