---
permalink: config/task_download_an_https_certificate_sign_request_ocf.html 
sidebar: sidebar 
keywords: download, https, certificate, signing, request 
summary: Você pode baixar uma solicitação de assinatura de certificação para o certificado de segurança HTTPS atual para que você possa fornecer o arquivo para uma Autoridade de Certificação assinar.  Um certificado assinado por uma CA ajuda a evitar ataques do tipo man-in-the-middle e fornece melhor proteção de segurança do que um certificado autoassinado. 
---
= Baixe uma solicitação de assinatura de certificado HTTPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode baixar uma solicitação de assinatura de certificação para o certificado de segurança HTTPS atual para que você possa fornecer o arquivo para uma Autoridade de Certificação assinar.  Um certificado assinado por uma CA ajuda a evitar ataques do tipo man-in-the-middle e fornece melhor proteção de segurança do que um certificado autoassinado.

.Antes de começar
Você deve ter a função de Administrador do Aplicativo.

.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Certificado HTTPS*.
. Clique em *Baixar solicitação de assinatura de certificado HTTPS*.
. Salve o `<hostname>.csr` arquivo.


Você pode fornecer o arquivo para uma Autoridade de Certificação assinar e depois instalar o certificado assinado.
