---
permalink: install-linux/reference_red_hat_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: linux software, installation requirements, system, authorization,  requirements 
summary: O sistema Linux no qual você instala o Unified Manager requer versões específicas do sistema operacional e software de suporte. 
---
= Requisitos de instalação e software Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema Linux no qual você instala o Unified Manager requer versões específicas do sistema operacional e software de suporte.



== Software do sistema operacional

O sistema Linux deve ter as seguintes versões do sistema operacional e software de suporte instalados:

* Red Hat Enterprise Linux versões 8.x e 9.4, baseadas na arquitetura x86_64.


Consulte a Matriz de Interoperabilidade para obter a lista completa e mais atual de versões suportadas do Red Hat Enterprise Linux.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"^]

O servidor deve ser dedicado à execução do Unified Manager.  Nenhum outro aplicativo deve ser instalado no servidor.  É possível que um scanner de vulnerabilidades como o Qualys esteja instalado no seu sistema Linux devido a regulamentações da empresa.  Você deve desabilitar o scanner de vulnerabilidades antes de instalar o Unified Manager para evitar que a instalação falhe.


NOTE: Os scanners de vulnerabilidade (como o Qualys) podem levar ao alto uso da CPU ao escanear a máquina virtual (VM) internamente (onde o Unified Manager e o scanner de vulnerabilidade estão instalados na mesma VM) ou externamente (onde o Unified Manager e o scanner de vulnerabilidade estão instalados em dois servidores diferentes e o scanner de vulnerabilidade verifica a VM onde o Unified Manager está instalado).  Esse problema geralmente faz com que a VM não responda e afeta os serviços do Unified Manager.  Portanto, a NetApp recomenda desabilitar o scanner de vulnerabilidades na VM onde o Unified Manager está instalado.  Se desabilitar o scanner não for uma opção, faça a varredura da VM fora do horário comercial e reinicie os serviços após a conclusão da varredura.



== Software de terceiros

O Unified Manager é implantado em um servidor web WildFly.  O WildFly 26.1.3 é fornecido e configurado com o Unified Manager.

Os seguintes pacotes de terceiros são necessários, mas não estão incluídos no Unified Manager.  Esses pacotes são instalados automaticamente pelo `yum` instalador durante a instalação, desde que você tenha configurado os repositórios conforme mencionado nas seções a seguir.

* MySQL Community Edition versão 8.4.4 (do repositório MySQL)
* OpenJDK versão 11.0.25 (do repositório do Red Hat Extra Enterprise Linux Server)
* Python 3.9.x (do repositório do Red Hat Extra Enterprise Linux Server)
* p7zip versão 16.02 ou posterior (do repositório Red Hat Extra Packages for Enterprise Linux)


[NOTE]
====
Você deve desligar uma instância em execução do Unified Manager antes de atualizar qualquer software de terceiros.  Após a conclusão da instalação do software de terceiros, você pode reiniciar o Unified Manager.

====


== Requisitos de autorização do usuário

A instalação do Unified Manager em um sistema Linux pode ser realizada pelo usuário root ou por usuários não root usando o `sudo` comando.

Além disso, a instalação padrão do Unified Manager inclui o usuário umadmin (usuário de manutenção padrão) e o usuário jboss nos arquivos sudoers(`ocum_sudoers` e `ocie_sudoers` ) no `/etc/sudoers.d/` diretório.  Se você remover esse conteúdo do seu ambiente devido a políticas de segurança ou a uma ferramenta de monitoramento de segurança, será necessário adicioná-lo novamente.  Você precisa preservar a configuração do sudoers porque algumas operações do Unified Manager exigem esses privilégios de sudo.



== Requisitos de instalação

As melhores práticas para instalar o Red Hat Enterprise Linux e os repositórios associados no seu sistema estão listadas abaixo.  Sistemas instalados ou configurados de forma diferente, ou implantados externamente (na nuvem), podem exigir etapas adicionais, e o Unified Manager pode não ser executado corretamente nessas implantações.

* Você deve instalar o Red Hat Enterprise Linux de acordo com as práticas recomendadas do Red Hat e selecionar as seguintes opções padrão, o que requer a seleção do ambiente base "`Servidor com GUI`".
* Ao instalar o Unified Manager no Red Hat Enterprise Linux, o sistema deve ter acesso ao repositório apropriado para que o programa de instalação possa acessar e instalar todas as dependências de software necessárias.
* Para o `yum` instalador para encontrar software dependente nos repositórios do Red Hat Enterprise Linux, você deve ter registrado o sistema durante a instalação do Red Hat Enterprise Linux ou depois usando uma assinatura válida do Red Hat.
+
Consulte a documentação do Red Hat para obter informações sobre o Red Hat Subscription Manager.

* Você deve habilitar o repositório Extra Packages for Enterprise Linux (EPEL) para instalar com sucesso os utilitários de terceiros necessários no seu sistema.
+
Se o repositório EPEL não estiver configurado no seu sistema, você deverá baixar e configurar manualmente o repositório.

+
Verlink:task_manually_configure_epel_repository.html["Configurando manualmente o repositório EPEL"] .

* Se a versão correta do MySQL não estiver instalada, você deverá habilitar o repositório MySQL para instalar com sucesso o software MySQL no seu sistema.
+
Se o repositório MySQL não estiver configurado no seu sistema, você deverá baixar e configurar manualmente o repositório.

+
Verlink:task_manually_configure_mysql_repository.html["Configurando manualmente o repositório MySQL"] .

* Você deve instalar apenas uma versão do Java no seu host do Unified Manager; caso contrário, o sistema pode não conseguir determinar qual versão usar. Ver https://kb.netapp.com/data-mgmt/AIQUM/AIQUM_Kbs/After_updating_Java_on_the_Active_IQ_Unified_Manager_host_services_will_not_start["Após atualizar o Java no host do Active IQ Unified Manager , os serviços não serão iniciados"] .


Se o seu sistema não tiver acesso à Internet e os repositórios não forem espelhados de um sistema conectado à Internet para o sistema desconectado, você deverá seguir as instruções de instalação para determinar as dependências de software externo do seu sistema.  Em seguida, você pode baixar o software necessário para o sistema conectado à Internet e copiá-lo `.rpm` arquivos para o sistema no qual você planeja instalar o Unified Manager.  Para baixar os artefatos e pacotes, você deve usar o `yum install` comando.  Você deve garantir que os dois sistemas estejam executando a mesma versão do sistema operacional e que a licença de assinatura seja para o Red Hat Enterprise Linux apropriado.

[NOTE]
====
Você não deve instalar o software de terceiros necessário de repositórios diferentes dos listados aqui.  O software instalado dos repositórios do Red Hat foi projetado explicitamente para o Red Hat Enterprise Linux e está em conformidade com as práticas recomendadas do Red Hat (layouts de diretório, permissões e assim por diante).  Softwares de outros locais podem não seguir essas diretrizes, o que pode causar falha na instalação do Unified Manager ou problemas com atualizações futuras.

====


== Requisito da porta 443

Imagens genéricas do Red Hat Enterprise Linux podem bloquear o acesso externo à porta 443.  Devido a essa restrição, talvez você não consiga se conectar à interface da Web do administrador após instalar o Unified Manager.  Executar o comando a seguir permite acesso à porta 443 para todos os usuários e aplicativos externos em um Red Hat Enterprise Linux genérico.

`# firewall-cmd --zone=public --add-port=443/tcp --permanent; firewall-cmd --reload`

Você deve instalar o Red Hat Enterprise Linux com o ambiente base "`Servidor com GUI`".  Ele fornece os comandos usados pelas instruções de instalação do Unified Manager.  Outros ambientes base podem exigir que você instale comandos adicionais para validar ou concluir a instalação.  Se o `firewall-cmd` não estiver disponível em seu sistema, você deve instalá-lo executando o seguinte comando:

`# sudo yum install firewalld`

Entre em contato com seu departamento de TI antes de executar os comandos para verificar se suas políticas de segurança exigem um procedimento diferente.

[NOTE]
====
THP (Transparent Huge Pages) deve ser desabilitado em sistemas Red Hat.  Quando ativado, em alguns casos, pode fazer com que o Unified Manager seja desligado quando certos processos consomem muita memória e são encerrados.

====