---
permalink: install-linux/reference_users_created_in_unified_manager.html 
sidebar: sidebar 
keywords: users, created, unified manager, installation 
summary: 'Quando você instala o Unified Manager no Red Hat Enterprise Linux, os seguintes usuários são criados pelo Unified Manager e utilitários de terceiros: umadmin, jboss e mysql.' 
---
= Usuários criados durante a instalação do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você instala o Unified Manager no Red Hat Enterprise Linux, os seguintes usuários são criados pelo Unified Manager e utilitários de terceiros: umadmin, jboss e mysql.

* *umadmin*
+
Usado para efetuar login no Unified Manager pela primeira vez.  Este usuário recebe a função de usuário "`Administrador de Aplicativos`" e é configurado como o tipo "`Usuário de Manutenção`".  Este usuário foi criado pelo Unified Manager.

* *jboss*
+
Usado para executar serviços do Unified Manager relacionados ao utilitário JBoss.  Este usuário foi criado pelo Unified Manager.

* *mysql*
+
Usado para executar consultas de banco de dados MySQL do Unified Manager.  Este usuário é criado pelo utilitário de terceiros MySQL.



Além desses usuários, o Unified Manager também cria grupos correspondentes: manutenção, jboss e mysql.  Os grupos de manutenção e jboss são criados pelo Unified Manager, enquanto o grupo mysql é criado por um utilitário de terceiros.

[NOTE]
====
Se você criou um diretório inicial personalizado e definiu sua própria senha de usuário umadmin antes de instalar o Unified Manager, o programa de instalação não recriará o grupo de manutenção ou o usuário umadmin.

====