---
permalink: install-linux/reference_complete_worksheet_um.html 
sidebar: sidebar 
keywords: complete, worksheet, cluster, information, unified manager 
summary: Antes de instalar e configurar o Unified Manager, você deve ter informações específicas sobre seu ambiente prontamente disponíveis.  Você pode registrar as informações na planilha. 
---
= Complete a planilha
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar e configurar o Unified Manager, você deve ter informações específicas sobre seu ambiente prontamente disponíveis.  Você pode registrar as informações na planilha.



[[unified-manager-installation-information]]
== Informações de instalação do Unified Manager

Os detalhes necessários para instalar o Unified Manager.

[cols="2*"]
|===
| Sistema no qual o software é implantado | Seu valor 


 a| 
Hospedar nome de domínio totalmente qualificado
 a| 



 a| 
Endereço IP do host
 a| 



 a| 
Máscara de rede
 a| 



 a| 
Endereço IP do gateway
 a| 



 a| 
Endereço DNS primário
 a| 



 a| 
Endereço DNS secundário
 a| 



 a| 
Domínios de pesquisa
 a| 



 a| 
Nome de usuário de manutenção
 a| 



 a| 
Senha do usuário de manutenção
 a| 

|===


[[unified-manager-configuration-information]]
== Informações de configuração do Unified Manager

Os detalhes para configurar o Unified Manager após a instalação.  Alguns valores são opcionais dependendo da sua configuração.

[cols="2*"]
|===
| Contexto | Seu valor 


 a| 
Endereço de e-mail do usuário de manutenção
 a| 



 a| 
Nome do host ou endereço IP do servidor SMTP
 a| 



 a| 
Nome de usuário SMTP
 a| 



 a| 
Senha SMTP
 a| 



 a| 
Porta SMTP
 a| 
25 (Valor padrão)



 a| 
E-mail de onde as notificações de alerta são enviadas
 a| 



 a| 
Nome do host ou endereço IP do servidor de autenticação
 a| 



 a| 
Nome do administrador do Active Directory ou nome distinto do vínculo LDAP
 a| 



 a| 
Senha do Active Directory ou senha de vinculação LDAP
 a| 



 a| 
Nome distinto da base do servidor de autenticação
 a| 



 a| 
URL do provedor de identidade (IdP)
 a| 



 a| 
Metadados do provedor de identidade (IdP)
 a| 



 a| 
Endereços IP do host de destino da armadilha SNMP
 a| 



 a| 
Porta SNMP
 a| 

|===


[[cluster-information]]
== Informações do cluster

Os detalhes dos sistemas de armazenamento que você gerencia usando o Unified Manager.

[cols="2*"]
|===
| Cluster 1 de N | Seu valor 


 a| 
Nome do host ou endereço IP de gerenciamento de cluster
 a| 



 a| 
Nome de usuário do administrador ONTAP

[NOTE]
====
O administrador deve ter recebido a função "`admin`".

==== a| 



 a| 
Senha do administrador do ONTAP
 a| 



 a| 
Protocolo
 a| 
HTTPS

|===