---
permalink: install-linux/task_install_unified_manager_linux.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: Você pode instalar o Unified Manager em uma plataforma Red Hat Enterprise Linux física ou virtual. 
---
= Instalar o Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode instalar o Unified Manager em uma plataforma Red Hat Enterprise Linux física ou virtual.

.Antes de começar
* O sistema no qual você deseja instalar o Unified Manager deve atender aos requisitos de sistema e software.
+
Verlink:concept_virtual_infrastructure_or_hardware_system_requirements.html["Requisitos do sistema de hardware"] .

+
Verlink:reference_red_hat_software_and_installation_requirements.html["Requisitos de instalação e software Linux"] .

* Você deve ter baixado o Unified Manager `.zip` arquivo do site de suporte da NetApp para o sistema de destino.
* Você deve ter verificado a integridade do arquivo baixado `.zip` arquivo.
* Você deve ter um navegador da web compatível.
* Seu software de emulação de terminal deve ter o scrollback habilitado.


O sistema Red Hat Enterprise Linux pode ter todas as versões necessárias do software de suporte necessário (Java, MySQL, utilitários adicionais) instaladas, apenas alguns dos softwares necessários instalados ou pode ser um sistema recém-instalado sem nenhum dos softwares necessários instalados.

.Passos
. Efetue login no servidor no qual você está instalando o Unified Manager.
. Insira os comandos apropriados para avaliar qual software pode exigir instalação ou atualização no sistema de destino para dar suporte à instalação:
+
[cols="2*"]
|===
| Software necessário e versão mínima | Comando para verificar software e versão 


 a| 
OpenJDK versão 11.0.25
 a| 
`java -version`



 a| 
MySQL 8.4.4 Edição Comunitária
 a| 
`rpm -qa | grep -i mysql`



 a| 
p7zip 16.02
 a| 
`rpm -qa | grep p7zip`

|===
. Se a versão instalada do MySQL for anterior ao MySQL 8.4.4 Community Edition, digite o seguinte comando para desinstalá-lo:
+
`rpm -e <mysql_package_name>`

+
Se você receber erros de dependência, deverá adicionar o `--nodeps` opção para desinstalar o componente.

. Navegue até o diretório onde você baixou a instalação `.zip` arquivo e expanda o pacote do Unified Manager:
+
`unzip ActiveIQUnifiedManager-_<version>_.zip`

+
O necessário `.rpm` Os módulos do Unified Manager são descompactados no diretório de destino.

. Verifique se o seguinte módulo está disponível no diretório:
+
`ls *.rpm`

+
`netapp-um<version>.x86_64.rpm`

. Execute o script de pré-instalação para garantir que não haja configurações do sistema ou qualquer software instalado que possa entrar em conflito com a instalação do Unified Manager:
+
`sudo ./pre_install_check.sh`

+
O script de pré-instalação verifica se o sistema tem uma assinatura válida do Red Hat Enterprise Linux e se tem acesso aos repositórios de software necessários.  Se o script identificar algum problema, você deverá corrigi-lo antes de instalar o Unified Manager.

+
Para o sistema Red Hat Enterprise Linux 8, se você tiver repositórios internos com JDK 11 - OpenJDK, p7zip e outros pacotes de software fornecidos pelo repositório AppStream, você deve desabilitar seu repositório AppStream e instalar o MySQL Community Server. Execute o seguinte comando:

+
[listing]
----
# sudo yum --disablerepo=rhel-8-for-x86_64-appstream-rpms install  mysql-community-server
----
. *Opcional:* Você deve executar a etapa 7 somente se o seu sistema não estiver conectado à Internet e você tiver que baixar manualmente os pacotes necessários para sua instalação.  Se o seu sistema tiver acesso à Internet e todos os pacotes necessários estiverem disponíveis, vá para a etapa 8.  Para sistemas que não estão conectados à Internet ou que não estão usando os repositórios do Red Hat Enterprise Linux, execute as seguintes etapas para determinar se está faltando algum pacote necessário e, em seguida, baixe esses pacotes:
+
.. No sistema em que você está instalando o Unified Manager, visualize a lista de pacotes disponíveis e indisponíveis: +
`yum install netapp-um<version>.x86_64.rpm --assumeno`
+
Os itens na seção "`Instalando:`" são os pacotes que estão disponíveis no diretório atual, e os itens na seção "`Instalando para dependências:`" são os pacotes que estão faltando no seu sistema.

.. Em um sistema com acesso à Internet, baixe os pacotes que faltam:
+
`yum install <package_name> --downloadonly --downloaddir=.`

+
[NOTE]
====
Como o plug-in "`yum-plugin-downloadonly`" nem sempre está habilitado em sistemas Red Hat Enterprise Linux, talvez seja necessário habilitar a funcionalidade para baixar um pacote sem instalá-lo:
`yum install yum-plugin-downloadonly`

====
.. Copie os pacotes ausentes do sistema conectado à Internet para o seu sistema de instalação.


. Como usuário root, ou usando `sudo` , execute o seguinte comando para instalar o software:
+
`yum install netapp-um<version>.x86_64.rpm`

+
Este comando instala os pacotes .rpm, todos os outros softwares de suporte necessários e o software Unified Manager.

+
Se a instalação falhar com o erro GPG NOKEY, use `rpm --import` para importar as chaves de uma URL:

+
rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023[]

+
[NOTE]
====
Não tente instalar usando comandos alternativos (como `rpm -ivh` ).  Uma instalação bem-sucedida do Unified Manager em um sistema Red Hat Enterprise Linux requer que todos os arquivos do Unified Manager e arquivos relacionados sejam instalados em uma ordem específica em uma estrutura de diretório específica que é aplicada automaticamente pelo `yum install netapp-um<version>.x86_64.rpm` comando.

====
. Ignore a notificação por e-mail exibida imediatamente após as mensagens de instalação.
+
O e-mail notifica o usuário root sobre uma falha inicial na tarefa cron, que não tem efeito adverso na instalação.

. Após a conclusão das mensagens de instalação, role para trás pelas mensagens até ver a mensagem na qual o sistema exibe um endereço IP ou URL para a interface de usuário da Web do Unified Manager, o nome de usuário de manutenção (umadmin) e uma senha padrão.
+
A mensagem é semelhante à seguinte:

+
[listing]
----
Active IQ Unified Manager installed successfully.
Use a web browser and one of the following URL(s) to configure and access the Unified Manager GUI.
https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/

Log in to Unified Manager in a web browser by using following details:
  username: umadmin
  password: admin
----
. Registre o endereço IP ou URL, o nome de usuário atribuído (umadmin) e a senha atual.
. Se você criou uma conta de usuário umadmin com um diretório inicial personalizado antes de instalar o Unified Manager, deverá especificar o shell de login do usuário umadmin:
+
`usermod -s /bin/maintenance-user-shell.sh umadmin`



Acesse a interface da web para alterar a senha padrão do usuário umadmin e execute a configuração inicial do Unified Manager, conforme descrito emlink:../config/concept_configure_unified_manager.html["Configurando o Active IQ Unified Manager"] .  É obrigatório alterar a senha padrão do usuário umadmin.
