---
permalink: install-linux/task_selinux_requirements_for_mounting_opt_netapp.html 
sidebar: sidebar 
keywords: unified manager, selinux requirements, mounting, nfs, cifs, share 
summary: Se você estiver planejando montar /opt/netapp ou /opt/netapp/data em um dispositivo NAS ou SAN e tiver o SELinux habilitado, precisará estar ciente das seguintes considerações. 
---
= Requisitos do SELinux em compartilhamentos NFS e CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você está planejando montar `/opt/netapp` ou `/opt/netapp/data` em um dispositivo NAS ou SAN e você tem o SELinux habilitado, você precisa estar ciente de algumas considerações.

Se você está planejando montar `/opt/netapp` ou `/opt/netapp/data` de qualquer lugar que não seja o sistema de arquivos raiz e se você tiver o SELinux habilitado em seu ambiente, você deve definir o contexto correto para os diretórios montados.  Para o cenário aplicável em seu ambiente, siga estas etapas para definir e confirmar o contexto correto do SELinux.



[[configure-the-selinux-context-when-optnetappdata-is-mounted]]
== Configurar o contexto SELinux quando `/opt/netapp/data` está montado

Se você montou `/opt/netapp/data` no seu sistema e o SELinux está definido para `Enforcing` , certifique-se de que o tipo de contexto SELinux para `/opt/netapp/data` está definido para `mysqld_db_t` , que é o elemento de contexto padrão para o local dos arquivos de banco de dados.

. Execute este comando para verificar o contexto:
+
`ls -dZ /opt/netapp/data`

+
Um exemplo de saída:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp/data
----
+

NOTE: Nesta saída, o contexto é `default_t` .  Você deve mudar este contexto para `mysqld_db_t` .

. Execute estas etapas para definir o contexto com base em como você montou `/opt/netapp/data` .
+
.. Execute os seguintes comandos para definir o contexto para `mysqld_db_t` :
`semanage fcontext -a -t mysqld_db_t "/opt/netapp/data"
`restorecon -R -v /opt/netapp/data`
.. Se você configurou `/opt/netapp/data` em `/etc/fstab` , você deve editar o `/etc/fstab` arquivo.  Para o `/opt/netapp/data/` opção de montagem, adicione o rótulo MySQL como:
+
`context=system_u:object_r:mysqld_db_t:s0`

.. Desmontar e remontar `/opt/netapp/data/` para habilitar o contexto.
.. Se você tiver uma montagem NFS direta, execute o seguinte comando para definir o contexto para `mysqld_db_t` :
+
`mount <nfsshare>:/<mountpoint> /opt/netapp/data -o context=system_u:object_r:mysqld_db_t:s0`



. Verifique se o contexto está definido corretamente:


`ls -dZ /opt/netapp/data/`

Um exemplo de saída:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/
----


[[configure-the-selinux-context-when-optnetapp-is-mounted-and-optnetappdata-is-also-mounted-separately]]
== Configurar o contexto SELinux quando `/opt/netapp` é montado, e `/opt/netapp/data/` também é montado separadamente

Neste cenário, em primeiro lugar, você deve definir o contexto para `/opt/netapp/data/` conforme descrito na seção anterior.  Depois de definir o contexto correto para `/opt/netapp/data/` , certifique-se de que o diretório pai `/opt/netapp` não tem o contexto SELinux definido como `file_t` .

.Passos
. Execute este comando para verificar o contexto:
+
`ls -dZ /opt/netapp`

+
Um exemplo de saída:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:file_t:s0 /opt/netapp
----
+
Nesta saída, o contexto é `file_t` deve ser alterado.  Os comandos a seguir definem o contexto para `usr_t` .  Você pode definir o contexto para qualquer valor diferente de `file_t` com base em seus requisitos de segurança.

. Execute estas etapas para definir o contexto, com base em como você montou `/opt/netapp` .
+
.. Execute os seguintes comandos para definir o contexto:




[listing]
----
semanage fcontext -a -t usr_t "/opt/netapp"
restorecon -v /opt/netapp
----
. Se você configurou `/opt/netapp` em `/etc/fstab` , você deve editar o `/etc/fstab` arquivo.  Para o `/opt/netapp` opção de montagem, adicione o rótulo MySQL como:
+
`context=system_u:object_r:usr_t:s0`

. Desmonte e monte novamente `/opt/netapp` para habilitar o contexto.
. Se você tiver uma montagem NFS direta, execute o seguinte comando para definir o contexto:
+
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:usr_t:s0`

+
.. Verifique se o contexto está definido corretamente:
+
`ls -dZ /opt/netapp`

+
Uma saída de amostra





[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:usr_t:s0 /opt/netapp
----


[[configure-the-selinux-context-when-optnetapp-is-mounted-and-optnetappdata-is-not-mounted-separately]]
== Configurar o contexto SELinux quando `/opt/netapp` é montado, e `/opt/netapp/data/` não é montado separadamente

Se você montou `/opt/netapp` no seu sistema e o SELinux está definido para `Enforcing` , certifique-se de que o tipo de contexto SELinux para `/opt/netapp` está definido para `mysqld_db_t` , que é o elemento de contexto padrão para o local dos arquivos de banco de dados.

.Passos
. Execute este comando para verificar o contexto:
+
`ls -dZ /opt/netapp`

+
Um exemplo de saída:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp
----
+

NOTE: Nesta saída, o contexto é `default_t` .  Você deve mudar este contexto para `mysqld_db_t` .

. Execute as seguintes etapas para definir o contexto com base em como você montou `/opt/netapp` .
+
.. Execute os seguintes comandos para definir o contexto para `mysqld_db_t` :
`semanage fcontext -a -t mysqld_db_t "/opt/netapp"
`restorecon -R -v /opt/netapp`
.. Se você configurou `/opt/netapp` em `/etc/fstab` , edite o `/etc/fstab` arquivo.  Para o `/opt/netapp/` opção de montagem, adicione o rótulo MySQL como:
`context=system_u:object_r:mysqld_db_t:s0`
.. Desmonte e monte novamente `/opt/netapp/` para habilitar o contexto.
.. Se você tiver uma montagem NFS direta, execute o seguinte comando para definir o contexto para `mysqld_db_t` :
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:mysqld_db_t:s0`


. Verifique se o contexto está definido corretamente:


`ls -dZ /opt/netapp/`

Um exemplo de saída:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/
----
'''