---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: Você pode redefinir a senha do JBoss específica da instância definida durante a instalação.  Você pode redefinir a senha opcionalmente, caso seu site exija esse recurso de segurança para substituir a configuração de instalação do Unified Manager.  Esta operação também altera a senha que o JBoss usa para acessar o MySQL. 
---
= Alterar a senha do JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode redefinir a senha do JBoss específica da instância definida durante a instalação.  Você pode redefinir a senha opcionalmente, caso seu site exija esse recurso de segurança para substituir a configuração de instalação do Unified Manager.  Esta operação também altera a senha que o JBoss usa para acessar o MySQL.

* Você deve ter acesso de usuário root ao sistema Red Hat Enterprise Linux no qual o Unified Manager está instalado.
* Você deve ser capaz de acessar o NetApp fornecido `password.sh` script no diretório `/opt/netapp/essentials/bin` .


.Passos
. Efetue login como usuário root no sistema.
. Pare os serviços do Unified Manager inserindo os seguintes comandos na ordem mostrada:
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
Não interrompa o software MySQL associado.

. Digite o seguinte comando para iniciar o processo de alteração de senha:
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`

. Quando solicitado, digite a nova senha do JBoss e, em seguida, digite-a uma segunda vez para confirmação.
+
Observe que a senha deve ter entre 8 e 16 caracteres e deve conter pelo menos um dígito, uma letra maiúscula e uma minúscula e pelo menos um destes caracteres especiais:

+
`+!@%^*-_+=[]:<>.?/~+`

. Quando o script for concluído, inicie os serviços do Unified Manager inserindo os seguintes comandos na ordem mostrada:
+
`systemctl start ocie`

+
`systemctl start ocieau`

. Depois que todos os serviços forem iniciados, você poderá efetuar login na interface do usuário do Unified Manager.

