---
permalink: install-linux/task_download_unified_manager.html 
sidebar: sidebar 
keywords: download, Unified Manager 
summary: 'Você deve baixar o Unified Manager `.zip` arquivo do site de suporte da NetApp para instalar o Unified Manager.' 
---
= Baixar o Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve baixar o Unified Manager `.zip` arquivo do site de suporte da NetApp para instalar o Unified Manager.

.Antes de começar
Você precisa ter credenciais de login para o site de suporte da NetApp .

Baixe o pacote de instalação do Unified Manager para o sistema Red Hat Enterprise Linux.

.Passos
. Efetue login no site de suporte da NetApp e navegue até a página de download do Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Site de suporte da NetApp"]

. Selecione a versão necessária do Unified Manager e aceite o contrato de licença de usuário final (EULA).
. Baixe o arquivo de instalação do Unified Manager para Linux e salve-o `.zip` arquivo para um diretório no sistema de destino.
+
[NOTE]
====
** Certifique-se de baixar a versão correta do arquivo do instalador para o seu sistema Red Hat Enterprise Linux.  Dependendo se você tem o Red Hat Enterprise Linux 8 ou 9 instalado, certifique-se de baixar a versão apropriada do Unified Manager `.zip` arquivo.
** A NetApp recomenda que você baixe o certificado de assinatura de código(`.pem` ) e assinatura digital(`.sig` ) junto com o `.zip` arquivo.


====
. Verifique a soma de verificação para integridade do software baixado.
. Se você baixou o certificado de assinatura de código e a assinatura digital, poderá verificar a integridade do arquivo do instalador.  Você pode usar os seguintes comandos para verificar a integridade do arquivo do instalador:
+
** Este comando cria um arquivo com a chave pública do certificado de assinatura de código:
+
[listing]
----
openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>
----
+
*** Onde *AIQUM-RHEL-CLIENT-INTER-ROOT.pem* é o arquivo que contém o certificado de assinatura de código.


** Este comando verifica a assinatura no arquivo do instalador:
+
[listing]
----
openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip
----
+
A mensagem semelhante a `Verified Ok` confirma que o arquivo do instalador é seguro para uso.




