---
permalink: include/upgrade-path.html 
sidebar: sidebar 
keywords: supported upgrade path, upgrade path, n-2, which versions can be upgraded 
summary: Caminho de atualização suportado 
---
= Caminho de atualização com suporte para versões do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Active IQ Unified Manager oferece suporte a um caminho de atualização específico para cada versão.

Nem todas as versões do Unified Manager podem executar uma atualização local para versões posteriores. As atualizações do Unified Manager são limitadas a um modelo N-2, o que significa que uma atualização só pode ser realizada nas próximas 2 versões em todas as plataformas. Por exemplo, você pode executar uma atualização do Unified Manager 9.16 somente a partir do Unified Manager 9.13 e 9.14.

Se você estiver executando uma versão anterior às versões suportadas, sua instância do Unified Manager precisará ser atualizada para uma das versões suportadas primeiro e depois atualizada para a versão atual.

Por exemplo, se a sua versão instalada for o Unified Manager 9.9 e você quiser atualizar para o Unified Manager 9.14, siga uma sequência de atualizações.

.Caminho de atualização de exemplo:
. Atualização 9.11 -> 9.13
. Atualização 9.13 -> 9.14
. Atualização 9.13 -> 9.16
. Atualização 9.14 -> 9.16


Para obter mais informações sobre a matriz do caminho de atualização, consulte isto https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_the_upgrade_path_for_Active_IQ_Unified_Manager_versions["artigo da base de conhecimento (KB)"] .
