---
permalink: events/concept_manage_scripts.html 
sidebar: sidebar 
keywords: manage, scripts 
summary: Você pode usar scripts para modificar ou atualizar automaticamente vários objetos de armazenamento no Unified Manager.  O script está associado a um alerta.  Quando um evento dispara um alerta, o script é executado.  Você pode carregar scripts personalizados e testar sua execução quando um alerta for gerado. 
---
= Gerenciar scripts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar scripts para modificar ou atualizar automaticamente vários objetos de armazenamento no Unified Manager.  O script está associado a um alerta.  Quando um evento dispara um alerta, o script é executado.  Você pode carregar scripts personalizados e testar sua execução quando um alerta for gerado.

A capacidade de carregar scripts no Unified Manager e executá-los é habilitada por padrão.  Se sua organização não quiser permitir essa funcionalidade por motivos de segurança, você pode desabilitá-la em *Gerenciamento de armazenamento* > *Configurações de recursos*.

*Informações relacionadas*

link:../config/task_enable_and_disable_ability_to_upload_scripts.html["Habilitando e desabilitando a capacidade de fazer upload de scripts"]
