---
permalink: events/concept_what_active_iq_platform_events_are.html 
sidebar: sidebar 
keywords: active iq, platform, events 
summary: O Unified Manager pode exibir eventos que foram descobertos pela plataforma Active IQ .  Esses eventos são criados executando um conjunto de regras em mensagens do AutoSupport geradas de todos os sistemas de armazenamento monitorados pelo Unified Manager. 
---
= O que são os eventos da plataforma Active IQ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Unified Manager pode exibir eventos que foram descobertos pela plataforma Active IQ .  Esses eventos são criados executando um conjunto de regras em mensagens do AutoSupport geradas de todos os sistemas de armazenamento monitorados pelo Unified Manager.

Para mais informações, consulte link:../events/concept_how_active_iq_platform_events_are_generated.html["Como os eventos da plataforma Active IQ são gerados"].

O Unified Manager verifica automaticamente se há um novo arquivo de regras e só baixa um novo arquivo quando há regras mais recentes.  Em sites sem acesso à rede externa, você precisa carregar as regras manualmente em *Gerenciamento de armazenamento* > *Configuração de evento* > *Carregar regras*.

Esses eventos do Active IQ não se sobrepõem aos eventos existentes do Unified Manager e identificam incidentes ou riscos relacionados à configuração do sistema, cabeamento, práticas recomendadas e problemas de disponibilidade.

Para obter mais informações sobre como habilitar eventos de plataforma, consultelink:../config/concept_active_iq_platform_events.html["Habilitando eventos do portal Active IQ"] .  Para obter mais informações sobre o upload do arquivo de regras, consultelink:../events/task_upload_new_active_iq_rules_file.html["Carregando um novo arquivo de regras do Active IQ"] .

NetApp Active IQ é um serviço baseado em nuvem que fornece análises preditivas e suporte proativo para otimizar as operações do sistema de storage em toda a nuvem híbrida NetApp. Veja  https://docs.netapp.com/us-en/active-iq/index.html["NetApp Active IQ"^] para mais informações.
