---
permalink: events/concept_guidelines_for_adding_alerts.html 
sidebar: sidebar 
keywords: guidelines, adding, alerts 
summary: Você pode adicionar alertas com base em um recurso, como um cluster, nó, agregado ou volume, e eventos de um tipo de gravidade específico.  Como prática recomendada, você pode adicionar um alerta para qualquer um dos seus objetos críticos depois de adicionar o cluster ao qual o objeto pertence. 
---
= Diretrizes para adicionar alertas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar alertas com base em um recurso, como um cluster, nó, agregado ou volume, e eventos de um tipo de gravidade específico.  Como prática recomendada, você pode adicionar um alerta para qualquer um dos seus objetos críticos depois de adicionar o cluster ao qual o objeto pertence.

Você pode usar as seguintes diretrizes e considerações para criar alertas para gerenciar seus sistemas de forma eficaz:

* Descrição do alerta
+
Você deve fornecer uma descrição para o alerta para que ele ajude você a rastreá-los de forma eficaz.

* Recursos
+
Você deve decidir qual recurso físico ou lógico requer um alerta.  Você pode incluir e excluir recursos, conforme necessário.  Por exemplo, se você quiser monitorar de perto seus agregados configurando um alerta, deverá selecionar os agregados necessários na lista de recursos.

+
Se você selecionar uma categoria de recursos, por exemplo, *+<<All User or Group Quotas>> +*, você receberá alertas para todos os objetos nessa categoria.

+
[NOTE]
====
Selecionar um cluster como recurso não seleciona automaticamente os objetos de armazenamento dentro desse cluster.  Por exemplo, se você criar um alerta para todos os eventos críticos de todos os clusters, receberá alertas somente para eventos críticos do cluster.  Você não receberá alertas para eventos críticos em nós, agregados e assim por diante.

====
* Gravidade do evento
+
Você deve decidir se um evento de um tipo de gravidade especificado (Crítico, Erro, Aviso) deve acionar o alerta e, em caso afirmativo, qual tipo de gravidade.

* Eventos selecionados
+
Se você adicionar um alerta com base no tipo de evento gerado, deverá decidir quais eventos exigem um alerta.

+
Se você selecionar uma gravidade de evento, mas não selecionar nenhum evento individual (se deixar a coluna "Eventos selecionados" vazia), você receberá alertas para todos os eventos na categoria.

* Ações
+
Você deve fornecer os nomes de usuário e endereços de e-mail dos usuários que receberão a notificação.  Você também pode especificar uma interceptação SNMP como modo de notificação.  Você pode associar seus scripts a um alerta para que eles sejam executados quando um alerta for gerado.

* Frequência de notificação
+
Você pode configurar um alerta para enviar notificações repetidamente aos destinatários por um período específico.  Você deve determinar o horário a partir do qual a notificação de evento estará ativa para o alerta.  Se quiser que a notificação do evento seja repetida até que o evento seja reconhecido, você deve determinar com que frequência deseja que a notificação seja repetida.

* Executar script
+
Você pode associar seu script a um alerta.  Seu script é executado quando o alerta é gerado.


