---
permalink: events/concept_what_event_management_system_events_are.html 
sidebar: sidebar 
keywords: event management, system, 
summary: 'O Sistema de Gerenciamento de Eventos (EMS) coleta dados de eventos de diferentes partes do kernel ONTAP e fornece mecanismos de encaminhamento de eventos.  Esses eventos ONTAP podem ser relatados como eventos EMS no Unified Manager.  O monitoramento e o gerenciamento centralizados facilitam a configuração de eventos críticos de EMS e notificações de alerta com base nesses eventos de EMS.' 
---
= O que são eventos do Sistema de Gerenciamento de Eventos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Sistema de Gerenciamento de Eventos (EMS) coleta dados de eventos de diferentes partes do kernel ONTAP e fornece mecanismos de encaminhamento de eventos.  Esses eventos ONTAP podem ser relatados como eventos EMS no Unified Manager.  O monitoramento e o gerenciamento centralizados facilitam a configuração de eventos críticos de EMS e notificações de alerta com base nesses eventos de EMS.

O endereço do Unified Manager é adicionado como um destino de notificação ao cluster quando você adiciona o cluster ao Unified Manager.  Um evento EMS é relatado assim que o evento ocorre no cluster.

Há dois métodos para receber eventos EMS no Unified Manager:

* Um certo número de eventos importantes do EMS são relatados automaticamente.
* Você pode se inscrever para receber eventos individuais do EMS.


Os eventos EMS gerados pelo Unified Manager são relatados de forma diferente dependendo do método em que o evento foi gerado:

|===
| Funcionalidade | Mensagens EMS automáticas | Mensagens EMS assinadas 


 a| 
Eventos EMS disponíveis
 a| 
Subconjunto de eventos EMS
 a| 
Todos os eventos de EMS



 a| 
Nome da mensagem EMS quando acionada
 a| 
Nome do evento do Unified Manager (convertido do nome do evento do EMS)
 a| 
Não específico no formato "Erro EMS recebido".  A mensagem detalhada fornece o formato de notação de ponto do evento EMS real



 a| 
Mensagens recebidas
 a| 
Assim que o aglomerado for descoberto
 a| 
Após adicionar cada evento EMS necessário ao Unified Manager e após o próximo ciclo de pesquisa de 15 minutos



 a| 
Ciclo de vida do evento
 a| 
Igual a outros eventos do Unified Manager: estados Novo, Reconhecido, Resolvido e Obsoleto
 a| 
O evento EMS se torna obsoleto após a atualização do cluster, após 15 minutos, a partir da criação do evento.



 a| 
Captura eventos durante o tempo de inatividade do Unified Manager
 a| 
Sim, quando o sistema é inicializado, ele se comunica com cada cluster para adquirir eventos ausentes
 a| 
Não



 a| 
Detalhes do evento
 a| 
As ações corretivas sugeridas são importadas diretamente do ONTAP para fornecer resoluções consistentes
 a| 
Ações corretivas não disponíveis na página Detalhes do evento

|===
[NOTE]
====
Alguns dos novos eventos automáticos do EMS são eventos informativos que indicam que um evento anterior foi resolvido.  Por exemplo, o evento informativo "FlexGroup Constituents Space Status All OK" indica que o evento de erro "FlexGroup Constituents Have Space Issues" foi resolvido.  Eventos informativos não podem ser gerenciados usando o mesmo ciclo de vida de eventos que outros tipos de gravidade de eventos. No entanto, o evento se torna obsoleto automaticamente se o mesmo volume receber outro evento de erro "`Problemas de espaço`".

====