---
permalink: events/reference_event_setup_page.html 
sidebar: sidebar 
keywords: event, setup, page, command, buttons, list, view 
summary: A página Configuração de evento exibe a lista de eventos que estão desabilitados e fornece informações como o tipo de objeto associado e a gravidade do evento.  Você também pode executar tarefas como desabilitar ou habilitar eventos globalmente. 
---
= Página de configuração do evento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página Configuração de evento exibe a lista de eventos que estão desabilitados e fornece informações como o tipo de objeto associado e a gravidade do evento.  Você também pode executar tarefas como desabilitar ou habilitar eventos globalmente.

Você só poderá acessar esta página se tiver a função de Administrador de Aplicativos ou Administrador de Armazenamento.



[[command-buttons]]
== Botões de comando

Os botões de comando permitem que você execute as seguintes tarefas para eventos selecionados:

* *Desativar*
+
Inicia a caixa de diálogo Desativar eventos, que você pode usar para desativar eventos.

* *Habilitar*
+
Habilita eventos selecionados que você escolheu desabilitar anteriormente.

* *Regras de upload*
+
Inicia a caixa de diálogo Regras de upload, que permite que sites sem acesso à rede externa carreguem manualmente o arquivo de regras do Active IQ para o Unified Manager.  As regras são executadas em mensagens do AutoSupport do cluster para gerar eventos para configuração do sistema, cabeamento, práticas recomendadas e disponibilidade, conforme definido pela plataforma Active IQ .

* *Inscreva-se nos eventos do EMS*
+
Inicia a caixa de diálogo Inscrever-se em eventos do EMS, que permite que você se inscreva para receber eventos específicos do Sistema de Gerenciamento de Eventos (EMS) dos clusters que você está monitorando.  O EMS coleta informações sobre eventos que ocorrem no cluster.  Quando uma notificação é recebida para um evento EMS inscrito, um evento do Unified Manager é gerado com a gravidade apropriada.





[[list-view]]
== Visualização de lista

A exibição de lista exibe (em formato tabular) informações sobre eventos que estão desabilitados.  Você pode usar os filtros de coluna para personalizar os dados exibidos.

* *Evento*
+
Exibe o nome do evento que está desabilitado.

* *Gravidade*
+
Exibe a gravidade do evento.  A gravidade pode ser Crítica, Erro, Aviso ou Informação.

* *Tipo de fonte*
+
Exibe o tipo de fonte para a qual o evento é gerado.


