---
permalink: events/reference_notifications_page.html 
sidebar: sidebar 
keywords: notifications page, email, smtp, server, snmp 
summary: Você pode configurar o servidor do Unified Manager para enviar notificações quando um evento for gerado ou quando for atribuído a um usuário.  Você também pode configurar os mecanismos de notificação.  Por exemplo, notificações podem ser enviadas como e-mails ou traps SNMP. 
---
= Página de notificações
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o servidor do Unified Manager para enviar notificações quando um evento for gerado ou quando for atribuído a um usuário.  Você também pode configurar os mecanismos de notificação.  Por exemplo, notificações podem ser enviadas como e-mails ou traps SNMP.

Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.



[[email]]
== E-mail

Esta área permite que você configure as seguintes configurações de e-mail para notificação de alerta:

* *Endereço de origem*
+
Especifica o endereço de e-mail do qual a notificação de alerta é enviada.  Este valor também é usado como endereço de origem para um relatório quando compartilhado.  Se o Endereço De estiver preenchido com o endereço "ActiveIQUnifiedManager@localhost.com", você deverá alterá-lo para um endereço de e-mail real e funcional para garantir que todas as notificações por e-mail sejam entregues com sucesso.





[[smtp-server]]
== Servidor SMTP

Esta área permite que você configure as seguintes configurações do servidor SMTP:

* *Nome do host ou endereço IP*
+
Especifica o nome do host do seu servidor host SMTP, que é usado para enviar a notificação de alerta aos destinatários especificados.

* *Nome de usuário*
+
Especifica o nome de usuário SMTP.  O nome de usuário SMTP é necessário somente quando o SMTPAUTH está habilitado no servidor SMTP.

* *Senha*
+
Especifica a senha SMTP.  O nome de usuário SMTP é necessário somente quando o SMTPAUTH está habilitado no servidor SMTP.

* *Porta*
+
Especifica a porta usada pelo servidor host SMTP para enviar notificações de alerta.

+
O valor padrão é 25.

* *Use START/TLS*
+
Marcar esta caixa fornece comunicação segura entre o servidor SMTP e o servidor de gerenciamento usando os protocolos TLS/SSL (também conhecidos como start_tls e StartTLS).

* *Use SSL*
+
Marcar esta caixa fornece comunicação segura entre o servidor SMTP e o servidor de gerenciamento usando o protocolo SSL.





[[snmp]]
== SNMP

Esta área permite que você configure as seguintes configurações de interceptação SNMP:

* *Versão*
+
Especifica a versão SNMP que você deseja usar dependendo do tipo de segurança necessária.  As opções incluem Versão 1, Versão 3, Versão 3 com Autenticação e Versão 3 com Autenticação e Criptografia.  O valor padrão é Versão 1.

* *Anfitrião do Destino da Armadilha*
+
Especifica o nome do host ou endereço IP (IPv4 ou IPv6) que recebe as interceptações SNMP enviadas pelo servidor de gerenciamento.  Para especificar vários destinos de interceptação, separe cada host com uma vírgula.

+
[NOTE]
====
Todas as outras configurações SNMP, como "Versão" e "Porta de saída", devem ser as mesmas para todos os hosts na lista.

====
* *Porta de Armadilha de Saída*
+
Especifica a porta pela qual o servidor SNMP recebe as interceptações enviadas pelo servidor de gerenciamento.

+
O valor padrão é 162.

* *Comunidade*
+
A sequência de caracteres da comunidade para acessar o host.

* *ID do motor*
+
Especifica o identificador exclusivo do agente SNMP e é gerado automaticamente pelo servidor de gerenciamento.  O Engine ID está disponível com SNMP Versão 3, SNMP Versão 3 com Autenticação e SNMP Versão 3 com Autenticação e Criptografia.

* *Nome de usuário*
+
Especifica o nome de usuário SNMP.  O nome de usuário está disponível com SNMP versão 3, SNMP versão 3 com autenticação e SNMP versão 3 com autenticação e criptografia.

* *Protocolo de Autenticação*
+
Especifica o protocolo usado para autenticar um usuário.  As opções de protocolo incluem MD5 e SHA.  MD5 é o valor padrão.  O protocolo de autenticação está disponível com SNMP Versão 3 com Autenticação e SNMP Versão 3 com Autenticação e Criptografia.

* *Senha de autenticação*
+
Especifica a senha usada ao autenticar um usuário.  A senha de autenticação está disponível com SNMP Versão 3 com Autenticação e SNMP Versão 3 com Autenticação e Criptografia.

* *Protocolo de Privacidade*
+
Especifica o protocolo de privacidade usado para criptografar mensagens SNMP.  As opções de protocolo incluem AES 128 e DES.  O valor padrão é AES 128.  O protocolo de privacidade está disponível com SNMP Versão 3 com Autenticação e Criptografia.

* *Senha de privacidade*
+
Especifica a senha ao usar o protocolo de privacidade.  A senha de privacidade está disponível com SNMP versão 3 com autenticação e criptografia.



Para obter mais informações sobre objetos e armadilhas SNMP, você pode baixar olink:https://mysupport.netapp.com/site/tools/tool-eula/aiqum-mib["MIB do Active IQ Unified Manager"^] do site de suporte da NetApp .
