---
permalink: events/reference_supported_unified_manager_cli_commands.html 
sidebar: sidebar 
keywords: supported, unified manager, cli, commands, cmd, um cli, um run, 
summary: Como administrador de armazenamento, você pode usar os comandos da CLI para executar consultas nos objetos de armazenamento; por exemplo, em clusters, agregados, volumes, qtrees e LUNs. 
---
= Comandos CLI do Unified Manager suportados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como administrador de armazenamento, você pode usar os comandos da CLI para executar consultas nos objetos de armazenamento; por exemplo, em clusters, agregados, volumes, qtrees e LUNs.  Você pode usar os comandos CLI para consultar o banco de dados interno do Unified Manager e o banco de dados ONTAP .  Você também pode usar comandos CLI em scripts que são executados no início ou no final de uma operação ou são executados quando um alerta é acionado.

Todos os comandos devem ser precedidos pelo comando `um cli login` e um nome de usuário e senha válidos para autenticação.


NOTE: Para executar o comando _um run_, certifique-se de que sua conta tenha acesso ao aplicativo _console_.

|===
| Comando CLI | Descrição | Saída 


 a| 
`um cli login -u <username> [-p <password>]`
 a| 
Efetua login na CLI.  Por questões de segurança, você deve inserir somente o nome de usuário após a opção "-u".  Quando usado dessa maneira, você será solicitado a inserir a senha, e ela não será capturada no histórico ou na tabela de processos.  A sessão expira após três horas a partir do momento do login, após o qual o usuário deve efetuar login novamente.
 a| 
Exibe a mensagem correspondente.



 a| 
`um cli logout`
 a| 
Efetua logout da CLI.
 a| 
Exibe a mensagem correspondente.



 a| 
`um help`
 a| 
Exibe todos os subcomandos de primeiro nível.
 a| 
Exibe todos os subcomandos de primeiro nível.



 a| 
`um run cmd [ -t <timeout> ] <cluster> <command>`
 a| 
A maneira mais simples de executar um comando em um ou mais hosts.  Usado principalmente para scripts de alerta para obter ou executar uma operação no ONTAP.  O argumento opcional timeout define um limite de tempo máximo (em segundos) para o comando ser concluído no cliente.  O padrão é 0 (esperar para sempre).
 a| 
Conforme recebido da ONTAP.



 a| 
`um run query <sql command>`
 a| 
Executa uma consulta SQL.  Somente consultas que leem do banco de dados são permitidas.  Nenhuma operação de atualização, inserção ou exclusão é suportada.
 a| 
Os resultados são exibidos em forma de tabela.  Se um conjunto vazio for retornado, ou se houver algum erro de sintaxe ou solicitação incorreta, ele exibirá a mensagem de erro apropriada.



 a| 
`um datasource add -u <username> -P <password> [ -t <protocol> ] [ -p <port> ] <hostname-or-ip>`
 a| 
Adiciona uma fonte de dados à lista de sistemas de armazenamento gerenciados.  Uma fonte de dados descreve como as conexões com sistemas de armazenamento são feitas.  As opções -u (nome de usuário) e -P (senha) devem ser especificadas ao adicionar uma fonte de dados.  A opção -t (protocolo) especifica o protocolo usado para se comunicar com o cluster (http ou https).  Se o protocolo não for especificado, ambos os protocolos serão tentados. A opção -p (porta) especifica a porta usada para comunicação com o cluster.  Se a porta não for especificada, o valor padrão do protocolo apropriado será tentado.  Este comando pode ser executado somente pelo administrador de armazenamento.
 a| 
Solicita que o usuário aceite o certificado e imprime a mensagem correspondente.



 a| 
`um datasource list [ <datasource-id>]`
 a| 
Exibe as fontes de dados para sistemas de armazenamento gerenciados.
 a| 
Exibe os seguintes valores em formato tabular: `ID Address Port, Protocol Acquisition Status, Analysis Status, Communication status, Acquisition Message, and Analysis Message` .



 a| 
`um datasource modify [ -h <hostname-or-ip> ] [ -u <username> ] [ -P <password> ] [ -t <protocol> ] [ -p <port> ] <datasource-id>`
 a| 
Modifica uma ou mais opções de fonte de dados.  Pode ser executado somente pelo administrador de armazenamento.
 a| 
Exibe a mensagem correspondente.



 a| 
`um datasource remove <datasource-id>`
 a| 
Remove a fonte de dados (cluster) do Unified Manager.
 a| 
Exibe a mensagem correspondente.



 a| 
`um option list [ <option> .. ]`
 a| 
Lista todas as opções que você pode configurar usando o comando set.
 a| 
Exibe os seguintes valores em formato tabular: `Name, Value, Default Value, and Requires Restart.`



 a| 
`um option set <option-name>=<option-value> [ <option-name>=<option-value> ... ]`
 a| 
Define uma ou mais opções.  O comando pode ser executado somente pelo administrador de armazenamento.
 a| 
Exibe a mensagem correspondente.



 a| 
`um version`
 a| 
Exibe a versão do software Unified Manager.
 a| 
`Version ("9.6")`



 a| 
`um lun list [-q] [ -ObjectType <object-id>]`
 a| 
Lista os LUNs após filtrar o objeto especificado.  -q é aplicável para todos os comandos para não mostrar nenhum cabeçalho.  ObjectType pode ser lun, qtree, cluster, volume, quota ou svm.

Por exemplo:

*`um lun list -cluster 1`*

Neste exemplo, "-cluster" é o objectType e "1" é o objectId.  O comando lista todos os LUNs dentro do cluster com ID 1.
 a| 
Exibe os seguintes valores em formato tabular: `ID and LUN path.`



 a| 
`um svm list [-q] [ -ObjectType <object-id>]`
 a| 
Lista as VMs de armazenamento após filtrar pelo objeto especificado.  ObjectType pode ser lun, qtree, cluster, volume, quota ou svm.

Por exemplo:

*`um svm list -cluster 1`*

Neste exemplo, "-cluster" é o objectType e "1" é o objectId.  O comando lista todas as VMs de armazenamento dentro do cluster com ID 1.
 a| 
Exibe os seguintes valores em formato tabular: `Name and Cluster ID.`



 a| 
`um qtree list [-q] [ -ObjectType <object-id>]`
 a| 
Lista as qtrees após filtrar pelo objeto especificado.  -q é aplicável para todos os comandos para não mostrar nenhum cabeçalho.  ObjectType pode ser lun, qtree, cluster, volume, quota ou svm.

Por exemplo:

*`um qtree list -cluster 1`*

Neste exemplo, "-cluster" é o objectType e "1" é o objectId.  O comando lista todas as qtrees dentro do cluster com ID 1.
 a| 
Exibe os seguintes valores em formato tabular: `Qtree ID and Qtree Name.`



 a| 
`um disk list [-q] [-ObjectType <object-id>]`
 a| 
Lista os discos após filtrar pelo objeto especificado.  ObjectType pode ser disco, aggr, nó ou cluster.

Por exemplo:

*`um disk list -cluster 1`*

Neste exemplo, "-cluster" é o objectType e "1" é o objectId.  O comando lista todos os discos dentro do cluster com ID 1.
 a| 
Exibe os seguintes valores em formato tabular `ObjectType and object-id` .



 a| 
`um cluster list [-q] [-ObjectType <object-id>]`
 a| 
Lista os clusters após filtrar pelo objeto especificado.  ObjectType pode ser disco, aggr, nó, cluster, lun, qtree, volume, quota ou svm.

Por exemplo:

*`um cluster list -aggr 1`*

Neste exemplo, "-aggr" é o objectType e "1" é o objectId.  O comando lista o cluster ao qual o agregado com ID 1 pertence.
 a| 
Exibe os seguintes valores em formato tabular: `Name, Full Name, Serial Number, Datasource Id, Last Refresh Time, and Resource Key` .



 a| 
`um cluster node list [-q] [-ObjectType <object-id>]`
 a| 
Lista os nós do cluster após filtrar pelo objeto especificado.  ObjectType pode ser disco, aggr, nó ou cluster.

Por exemplo:

*`um cluster node list -cluster 1`*

Neste exemplo, "-cluster" é o objectType e "1" é o objectId.  O comando lista todos os nós dentro do cluster com ID 1.
 a| 
Exibe os seguintes valores em formato tabular `Name and Cluster ID` .



 a| 
`um volume list [-q] [-ObjectType <object-id>]`
 a| 
Lista os volumes após filtrar pelo objeto especificado.  ObjectType pode ser lun, qtree, cluster, volume, quota, svm ou aggregate.

Por exemplo:

*`um volume list -cluster 1`*

Neste exemplo, "-cluster" é o objectType e "1" é o objectId.  O comando lista todos os volumes dentro do cluster com ID 1.
 a| 
Exibe os seguintes valores em formato tabular `Volume ID and Volume Name` .



 a| 
`um quota user list [-q] [-ObjectType <object-id>]`
 a| 
Lista os usuários da cota após filtrar pelo objeto especificado.  ObjectType pode ser qtree, cluster, volume, quota ou svm.

Por exemplo:

*`um quota user list -cluster 1`*

Neste exemplo, "-cluster" é o objectType e "1" é o objectId.  O comando lista todos os usuários de cota dentro do cluster com ID 1.
 a| 
Exibe os seguintes valores em formato tabular `ID, Name, SID and Email` .



 a| 
`um aggr list [-q] [-ObjectType <object-id>]`
 a| 
Lista os agregados após filtrar o objeto especificado.  ObjectType pode ser disco, aggr, nó, cluster ou volume.

Por exemplo:

*`um aggr list -cluster 1`*

Neste exemplo, "-cluster" é o objectType e "1" é o objectId.  O comando lista todos os agregados dentro do cluster com ID 1.
 a| 
Exibe os seguintes valores em formato tabular `Aggr ID, and Aggr Name` .



 a| 
`um event ack <event-ids>`
 a| 
Reconhece um ou mais eventos.
 a| 
Exibe a mensagem correspondente.



 a| 
`um event resolve <event-ids>`
 a| 
Resolve um ou mais eventos.
 a| 
Exibe a mensagem correspondente.



 a| 
`um event assign -u <username> <event-id>`
 a| 
Atribui um evento a um usuário.
 a| 
Exibe a mensagem correspondente.



 a| 
`um event list [ -s <source> ] [ -S <event-state-filter-list>.. ] [ <event-id> .. ]`
 a| 
Lista os eventos gerados pelo sistema ou usuário.  Filtra eventos com base na origem, estado e IDs.
 a| 
Exibe os seguintes valores em formato tabular `Source, Source type, Name, Severity, State, User and Timestamp` .



 a| 
`um backup restore -f <backup_file_path_and_name>`
 a| 
Restaura um backup de banco de dados MySQL usando arquivos .7z.
 a| 
Exibe a mensagem correspondente.

|===