---
permalink: events/reference_storage_services_events.html 
sidebar: sidebar 
keywords: storage, services, events, impact area, configuration, protection 
summary: Os eventos de serviços de armazenamento fornecem informações sobre a criação e assinatura de serviços de armazenamento para que você possa monitorar possíveis problemas.  Os eventos são agrupados por área de impacto e incluem o nome do evento e da armadilha, nível de impacto, tipo de fonte e gravidade. 
---
= Eventos de serviços de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os eventos de serviços de armazenamento fornecem informações sobre a criação e assinatura de serviços de armazenamento para que você possa monitorar possíveis problemas.  Os eventos são agrupados por área de impacto e incluem o nome do evento e da armadilha, nível de impacto, tipo de fonte e gravidade.



[[impact-area-configuration]]
== Área de impacto: configuração

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
Serviço de armazenamento criado (não aplicável)
 a| 
Evento
 a| 
Serviço de armazenamento
 a| 
Informação



 a| 
Serviço de armazenamento assinado (não aplicável)
 a| 
Evento
 a| 
Serviço de armazenamento
 a| 
Informação



 a| 
Serviço de armazenamento cancelado (não aplicável)
 a| 
Evento
 a| 
Serviço de armazenamento
 a| 
Informação

|===


[[impact-area-protection]]
== Área de impacto: proteção

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
Exclusão inesperada do relacionamento SnapMirror gerenciadoocumEvtStorageServiceUnsupportedRelationshipDeletion
 a| 
Risco
 a| 
Serviço de armazenamento
 a| 
Aviso



 a| 
Exclusão inesperada do volume do membro do serviço de armazenamento (ocumEvtStorageServiceUnexpectedVolumeDeletion)
 a| 
Incidente
 a| 
Serviço de armazenamento
 a| 
Crítico

|===