---
permalink: events/reference_cluster_events.html 
sidebar: sidebar 
keywords: cluster events, impact, area, availability, capacity, configuration, performance, security 
summary: Os eventos de cluster fornecem informações sobre o status dos clusters, o que permite monitorar os clusters em busca de possíveis problemas.  Os eventos são agrupados por área de impacto e incluem o nome do evento, o nome da armadilha, o nível de impacto, o tipo de fonte e a gravidade. 
---
= Eventos de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os eventos de cluster fornecem informações sobre o status dos clusters, o que permite monitorar os clusters em busca de possíveis problemas.  Os eventos são agrupados por área de impacto e incluem o nome do evento, o nome da armadilha, o nível de impacto, o tipo de fonte e a gravidade.



== Área de impacto: disponibilidade

Um asterisco (*) identifica eventos do EMS que foram convertidos em eventos do Unified Manager.

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
O cluster não possui discos sobressalentes (ocumEvtDisksNoSpares)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Cluster não alcançável (ocumEvtClusterUnreachable)
 a| 
Risco
 a| 
Conjunto
 a| 
Erro



 a| 
Falha no monitoramento de cluster (ocumEvtClusterMonitoringFailed)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Limites de capacidade da licença do Cluster FabricPool violados (ocumEvtExternalCapacityTierSpaceFull)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Período de carência NVMe-oF iniciado *(nvmfGracePeriodStart)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Período de carência NVMe-oF ativo *(nvmfGracePeriodActive)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Período de carência NVMe-oF expirado *(nvmfGracePeriodExpired)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Janela de manutenção de objeto iniciada (objectMaintenanceWindowStarted)
 a| 
Evento
 a| 
Conjunto
 a| 
Crítico



 a| 
Janela de manutenção de objeto encerrada (objectMaintenanceWindowEnded)
 a| 
Evento
 a| 
Conjunto
 a| 
Informação



 a| 
Discos sobressalentes do MetroCluster deixados para trás (ocumEvtSpareDiskLeftBehind)
 a| 
Risco
 a| 
Conjunto
 a| 
Erro



 a| 
Comutação automática não planejada do MetroCluster desabilitada (ocumEvtMccAutomaticUnplannedSwitchOverDisabled)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Senha do usuário do cluster alterada *(cluster.passwd.changed)
 a| 
Evento
 a| 
Conjunto
 a| 
Informação

|===


== Área de impacto: capacidade

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
Limite de desequilíbrio de capacidade do cluster violado (ocumConformanceNodeImbalanceWarning)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Planejamento da camada de nuvem do cluster (clusterCloudTierPlanningWarning)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Ressincronização de replicação do espelho do FabricPool concluída *(waflCaResyncComplete)
 a| 
Evento
 a| 
Conjunto
 a| 
Aviso



 a| 
Espaço do FabricPool quase cheio *(fabricpoolNearlyFull)
 a| 
Risco
 a| 
Conjunto
 a| 
Erro

|===


== Área de impacto: configuração

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
Nó adicionado (não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Informação



 a| 
Nó removido (não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Informação



 a| 
Cluster removido (não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Informação



 a| 
Falha ao adicionar cluster (não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Erro



 a| 
Nome do cluster alterado (não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Informação



 a| 
EMS de emergência recebido (não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Crítico



 a| 
EMS crítico recebido (não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Crítico



 a| 
Alerta EMS recebido (Não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Erro



 a| 
Erro EMS recebido (Não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Aviso



 a| 
Aviso EMS recebido (Não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Aviso



 a| 
Depurar EMS recebido (Não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Aviso



 a| 
Aviso EMS recebido (Não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Aviso



 a| 
EMS informativo recebido (Não aplicável)
 a| 
Evento
 a| 
Conjunto
 a| 
Aviso

|===
Os eventos do ONTAP EMS são categorizados em três níveis de gravidade de eventos do Unified Manager.

|===


| Nível de gravidade do evento do Unified Manager | Nível de gravidade do evento ONTAP EMS 


 a| 
Crítico
 a| 
Emergência

Crítico



 a| 
Erro
 a| 
Alerta



 a| 
Aviso
 a| 
Erro

Aviso

Depurar

Perceber

Informativo

|===


== Área de impacto: desempenho

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
Limite de desequilíbrio de carga do cluster violado()
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Limite crítico de IOPS do cluster violado (ocumClusterIopsIncident)
 a| 
Incidente
 a| 
Conjunto
 a| 
Crítico



 a| 
Limite de aviso de IOPS de cluster violado (ocumClusterIopsWarning)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Limite crítico de MB/s do cluster violado (ocumClusterMbpsIncident)
 a| 
Incidente
 a| 
Conjunto
 a| 
Crítico



 a| 
Limite de alerta de cluster MB/s violado (ocumClusterMbpsWarning)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Limite dinâmico do cluster violado (ocumClusterDynamicEventWarning)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso

|===


== Área de impacto: segurança

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
Transporte HTTPS de AutoSupport desabilitado (ocumClusterASUPHttpsConfiguredDisabled)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Encaminhamento de log não criptografado (ocumClusterAuditLogUnencrypted)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Usuário administrador local padrão habilitado (ocumClusterDefaultAdminEnabled)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Modo FIPS desabilitado (ocumClusterFipsDisabled)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Banner de login desabilitado (ocumClusterLoginBannerDisabled)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Banner de login alterado (ocumClusterLoginBannerChanged)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Destinos de encaminhamento de log alterados (ocumLogForwardDestinationsChanged)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Nomes de servidores NTP alterados (ocumNtpServerNamesChanged)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
A contagem do servidor NTP está baixa (securityConfigNTPServerCountLowRisk)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Comunicação entre pares do cluster não criptografada (ocumClusterPeerEncryptionDisabled)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
SSH está usando cifras inseguras (ocumClusterSSHInsecure)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Protocolo Telnet habilitado (ocumClusterTelnetEnabled)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
As senhas de algumas contas de usuários do ONTAP usam a função de hash MD5 menos segura (ocumClusterMD5PasswordHashUsed)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
O cluster usa certificado autoassinado (ocumClusterSelfSignedCertificate)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
O Cluster Remote Shell está habilitado (ocumClusterRshDisabled)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Certificado de cluster prestes a expirar (ocumEvtClusterCertificateAboutToExpire)
 a| 
Risco
 a| 
Conjunto
 a| 
Aviso



 a| 
Certificado de cluster expirado (ocumEvtClusterCertificateExpired)
 a| 
Risco
 a| 
Conjunto
 a| 
Erro

|===