---
permalink: events/reference_edit_alert_dialog_box.html 
sidebar: sidebar 
keywords: edit, alert, dialog box, name, resources, events, actions 
summary: Você pode editar propriedades de alerta, como o recurso ao qual o alerta está associado, eventos, script e opções de notificação. 
---
= Caixa de diálogo Editar alerta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar propriedades de alerta, como o recurso ao qual o alerta está associado, eventos, script e opções de notificação.



== Nome

Esta área permite que você edite o nome e a descrição do alerta.

* *Nome do Alerta*
+
Permite que você edite o nome do alerta.

* *Descrição do Alerta*
+
Permite que você especifique uma descrição para o alerta.

* *Estado de Alerta*
+
Permite que você habilite ou desabilite o alerta.





== Recursos

Esta área permite que você selecione um recurso individual ou agrupe os recursos com base em uma regra dinâmica para a qual você deseja acionar o alerta.  Você pode pesquisar recursos selecionando um tipo de recurso na lista suspensa ou pode especificar o nome exato do recurso para exibir um recurso específico.

* *Incluir*
+
Permite que você inclua os recursos para os quais deseja acionar alertas.  Você pode especificar uma sequência de texto para agrupar recursos que correspondem à sequência e selecionar esse grupo para ser incluído no alerta.  Por exemplo, você pode agrupar todos os volumes cujo nome contém a string "`vol0`".

* *Excluir*
+
Permite que você exclua recursos para os quais não deseja acionar alertas.  Por exemplo, você pode excluir todos os volumes cujo nome contém a string "`xyz`".

+
[NOTE]
====
A guia Excluir é exibida somente quando você seleciona todos os recursos de um tipo de recurso específico - por exemplo, +<<All Volumes>> + ou +<<All Volumes whose name contains 'xyz'>> +.

====




== Eventos

Esta área permite que você selecione os eventos para os quais deseja acionar os alertas.  Você pode acionar um alerta para eventos com base em uma gravidade específica ou para um conjunto de eventos.

* *Gravidade do Evento*
+
Permite selecionar eventos com base no tipo de gravidade, que pode ser Crítico, Erro ou Aviso.

* *Nome do evento contém*
+
Permite selecionar eventos cujo nome contém os caracteres especificados.





== Ações

Esta área permite que você especifique o método de notificação e a frequência da notificação.

* *Alertar esses usuários*
+
Permite que você edite o endereço de e-mail ou nome de usuário, ou especifique um novo endereço de e-mail ou nome de usuário para receber notificações.

* *Frequência de Notificação*
+
Permite que você edite a frequência com que o servidor de gerenciamento envia notificações até que o evento seja reconhecido, resolvido ou movido para o estado obsoleto.

+
Você pode escolher os seguintes métodos de notificação:

+
** Notificar apenas uma vez
** Notificar com uma frequência específica
** Notificar em uma frequência específica dentro do intervalo de tempo especificado


* *Emitir armadilha SNMP*
+
Permite que você especifique se as interceptações SNMP devem ser enviadas ao host SNMP configurado globalmente.

* *Executar Script*
+
Permite que você associe um script ao alerta.  Este script é executado quando um alerta é gerado.





== Botões de comando

* *Salvar*
+
Salva as alterações e fecha a caixa de diálogo.

* *Cancelar*
+
Descarta as alterações e fecha a caixa de diálogo.


