---
permalink: events/reference_node_events.html 
sidebar: sidebar 
keywords: node, events, impact area, availability, capacity, configuration, performance, security 
summary: Os eventos do nó fornecem informações sobre o status do nó para que você possa monitorar possíveis problemas.  Os eventos são agrupados por área de impacto e incluem o nome do evento e da armadilha, nível de impacto, tipo de fonte e gravidade. 
---
= Eventos de nó
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os eventos do nó fornecem informações sobre o status do nó para que você possa monitorar possíveis problemas.  Os eventos são agrupados por área de impacto e incluem o nome do evento e da armadilha, nível de impacto, tipo de fonte e gravidade.

Um asterisco (*) identifica eventos do EMS que foram convertidos em eventos do Unified Manager.



[[impact-area-availability]]
== Área de impacto: disponibilidade

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
Espaço do volume raiz do nó quase cheio (ocumEvtClusterNodeRootVolumeSpaceNearlyFull)
 a| 
Risco
 a| 
Nó
 a| 
Aviso



 a| 
Nuvem AWS MetaDataConnFail *(ocumCloudAwsMetadataConnFail)
 a| 
Risco
 a| 
Nó
 a| 
Erro



 a| 
Nuvem AWS IAMCredsExpirado *(ocumCloudAwsIamCredsExpired)
 a| 
Risco
 a| 
Nó
 a| 
Erro



 a| 
Nuvem AWS IAMCredsInvalid *(ocumCloudAwsIamCredsInvalid)
 a| 
Risco
 a| 
Nó
 a| 
Erro



 a| 
Nuvem AWS IAMCredsNotFound *(ocumCloudAwsIamCredsNotFound)
 a| 
Risco
 a| 
Nó
 a| 
Erro



 a| 
Nuvem AWS IAMCredsNotInitialized *(ocumCloudAwsIamCredsNotInitialized)
 a| 
Evento
 a| 
Nó
 a| 
Informação



 a| 
Nuvem AWS IAMRoleInválido *(ocumCloudAwsIamRoleInválido)
 a| 
Risco
 a| 
Nó
 a| 
Erro



 a| 
Nuvem AWS IAMRoleNotFound *(ocumCloudAwsIamRoleNotFound)
 a| 
Risco
 a| 
Nó
 a| 
Erro



 a| 
Host da camada de nuvem não resolvível *(ocumObjstoreHostUnresolvable)
 a| 
Risco
 a| 
Nó
 a| 
Erro



 a| 
Interface de rede intercluster da camada de nuvem inativa *(ocumObjstoreInterClusterLifDown)
 a| 
Risco
 a| 
Nó
 a| 
Erro



 a| 
Um dos pools NFSv4 esgotados *(nbladeNfsv4PoolEXhaust)
 a| 
Incidente
 a| 
Nó
 a| 
Crítico



 a| 
Assinatura da camada de nuvem de incompatibilidade de solicitação *(oscSignatureMismatch)
 a| 
Risco
 a| 
Nó
 a| 
Erro

|===


[[impact-area-capacity]]
== Área de impacto: capacidade

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
Memória do monitor QoS máxima *(ocumQosMonitorMemoryMaxed)
 a| 
Risco
 a| 
Nó
 a| 
Erro



 a| 
Memória do monitor QoS reduzida *(ocumQosMonitorMemoryAbated)
 a| 
Evento
 a| 
Nó
 a| 
Informação

|===


[[impact-area-configuration]]
== Área de impacto: configuração

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
Nó renomeado (não aplicável)
 a| 
Evento
 a| 
Nó
 a| 
Informação

|===


[[impact-area-performance]]
== Área de impacto: desempenho

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
Limite crítico de IOPS do nó violado (ocumNodeIopsIncident)
 a| 
Incidente
 a| 
Nó
 a| 
Crítico



 a| 
Limite de aviso de IOPS de nó violado (ocumNodeIopsWarning)
 a| 
Risco
 a| 
Nó
 a| 
Aviso



 a| 
Limite crítico de MB/s do nó violado (ocumNodeMbpsIncident)
 a| 
Incidente
 a| 
Nó
 a| 
Crítico



 a| 
Limite de aviso de MB/s do nó violado (ocumNodeMbpsWarning)
 a| 
Risco
 a| 
Nó
 a| 
Aviso



 a| 
Limite crítico de latência do nó ms/op violado (ocumNodeLatencyIncident)
 a| 
Incidente
 a| 
Nó
 a| 
Crítico



 a| 
Limite de alerta de latência do nó ms/op violado (ocumNodeLatencyWarning)
 a| 
Risco
 a| 
Nó
 a| 
Aviso



 a| 
Limite crítico de capacidade de desempenho do nó violado (ocumNodePerfCapacityUsedIncident)
 a| 
Incidente
 a| 
Nó
 a| 
Crítico



 a| 
Limite de aviso de capacidade de desempenho do nó violado (ocumNodePerfCapacityUsedWarning)
 a| 
Risco
 a| 
Nó
 a| 
Aviso



 a| 
Capacidade de desempenho do nó usada - Limite crítico de aquisição violado (ocumNodePerfCapacityUsedTakeoverIncident)
 a| 
Incidente
 a| 
Nó
 a| 
Crítico



 a| 
Capacidade de desempenho do nó usada - Limite de aviso de aquisição violado (ocumNodePerfCapacityUsedTakeoverWarning)
 a| 
Risco
 a| 
Nó
 a| 
Aviso



 a| 
Limite crítico de utilização do nó violado (ocumNodeUtilizationIncident)
 a| 
Incidente
 a| 
Nó
 a| 
Crítico



 a| 
Limite de aviso de utilização do nó violado (ocumNodeUtilizationWarning)
 a| 
Risco
 a| 
Nó
 a| 
Aviso



 a| 
Limite de superutilização do par de HA do nó violado (ocumNodeHaPairOverUtilizedInformation)
 a| 
Evento
 a| 
Nó
 a| 
Informação



 a| 
Limite de fragmentação de disco do nó violado (ocumNodeDiskFragmentationWarning)
 a| 
Risco
 a| 
Nó
 a| 
Aviso



 a| 
Limite de capacidade de desempenho usada violado (ocumNodeOverUtilizedWarning)
 a| 
Risco
 a| 
Nó
 a| 
Aviso



 a| 
Limite dinâmico do nó violado (ocumNodeDynamicEventWarning)
 a| 
Risco
 a| 
Nó
 a| 
Aviso

|===


[[impact-area-security]]
== Área de impacto: segurança

|===
| Nome do evento (nome da armadilha) | Nível de impacto | Tipo de fonte | Gravidade 


 a| 
ID do aviso: NTAP-<__ID do aviso__>(ocumx)
 a| 
Risco
 a| 
Nó
 a| 
Crítico

|===