---
permalink: events/reference_add_alert_dialog_box.html 
sidebar: sidebar 
keywords: add, alert, dialog, box, name, resources, events, actions, command buttons 
summary: Você pode criar alertas para notificá-lo quando um evento específico for gerado, para que você possa resolver o problema rapidamente e, assim, minimizar o impacto no seu ambiente.  Você pode criar alertas para um único recurso ou um conjunto de recursos e para eventos de um tipo de gravidade específico.  Você também pode especificar o método de notificação e a frequência dos alertas. 
---
= Caixa de diálogo Adicionar alerta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar alertas para notificá-lo quando um evento específico for gerado, para que você possa resolver o problema rapidamente e, assim, minimizar o impacto no seu ambiente.  Você pode criar alertas para um único recurso ou um conjunto de recursos e para eventos de um tipo de gravidade específico.  Você também pode especificar o método de notificação e a frequência dos alertas.

Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.



== Nome

Esta área permite que você especifique um nome e uma descrição para o alerta:

* *Nome do Alerta*
+
Permite que você especifique um nome de alerta.

* *Descrição do Alerta*
+
Permite que você especifique uma descrição para o alerta.





== Recursos

Esta área permite que você selecione um recurso individual ou agrupe os recursos com base em uma regra dinâmica para a qual você deseja acionar o alerta.  Uma _regra dinâmica_ é o conjunto de recursos filtrados com base na sequência de texto que você especifica.  Você pode pesquisar recursos selecionando um tipo de recurso na lista suspensa ou pode especificar o nome exato do recurso para exibir um recurso específico.

Se você estiver criando um alerta de qualquer uma das páginas de detalhes do objeto de armazenamento, o objeto de armazenamento será automaticamente incluído no alerta.

* *Incluir*
+
Permite que você inclua os recursos para os quais deseja acionar alertas.  Você pode especificar uma sequência de texto para agrupar recursos que correspondem à sequência e selecionar esse grupo para ser incluído no alerta.  Por exemplo, você pode agrupar todos os volumes cujo nome contém a string "abc".

* *Excluir*
+
Permite que você exclua recursos para os quais não deseja acionar alertas.  Por exemplo, você pode excluir todos os volumes cujo nome contém a string "xyz".

+
A guia Excluir é exibida somente quando você seleciona todos os recursos de um tipo de recurso específico: por exemplo, +<<All Volumes>> ou<<All Volumes whose name contains 'xyz'>> +.

+
Se um recurso estiver em conformidade com as regras de inclusão e exclusão especificadas, a regra de exclusão terá precedência sobre a regra de inclusão e o alerta não será gerado para o evento.





== Eventos

Esta área permite que você selecione os eventos para os quais deseja criar os alertas.  Você pode criar alertas para eventos com base em uma gravidade específica ou para um conjunto de eventos.

Para selecionar mais de um evento, você deve manter pressionada a tecla Ctrl enquanto faz suas seleções.

* *Gravidade do Evento*
+
Permite selecionar eventos com base no tipo de gravidade, que pode ser Crítico, Erro ou Aviso.

* *Nome do evento contém*
+
Permite selecionar eventos cujo nome contém caracteres especificados.





== Ações

Esta área permite que você especifique os usuários que deseja notificar quando um alerta for disparado.  Você também pode especificar o método de notificação e a frequência da notificação.

* *Alertar esses usuários*
+
Permite que você especifique o endereço de e-mail ou nome de usuário do usuário que receberá notificações.

+
Se você modificar o endereço de e-mail especificado para o usuário e reabrir o alerta para edição, o campo Nome aparecerá em branco porque o endereço de e-mail modificado não estará mais mapeado para o usuário selecionado anteriormente.  Além disso, se você tiver modificado o endereço de e-mail do usuário selecionado na página Usuários, o endereço de e-mail modificado não será atualizado para o usuário selecionado.

* *Frequência de Notificação*
+
Permite que você especifique a frequência com que o servidor de gerenciamento envia notificações até que o evento seja reconhecido, resolvido ou movido para o estado obsoleto.

+
Você pode escolher os seguintes métodos de notificação:

+
** Notificar apenas uma vez
** Notificar com uma frequência específica
** Notificar em uma frequência específica dentro do intervalo de tempo especificado


* *Emitir armadilha SNMP*
+
Selecionar esta caixa permite que você especifique se as interceptações SNMP devem ser enviadas ao host SNMP configurado globalmente.

* *Executar Script*
+
Permite que você adicione seu script personalizado ao alerta.  Este script é executado quando um alerta é gerado.

+
[NOTE]
====
Se você não vir esse recurso disponível na interface do usuário, é porque a funcionalidade foi desabilitada pelo seu administrador.  Se necessário, você pode habilitar essa funcionalidade em *Gerenciamento de armazenamento* > *Configurações de recursos*.

====




== Botões de comando

* *Salvar*
+
Cria um alerta e fecha a caixa de diálogo.

* *Cancelar*
+
Descarta as alterações e fecha a caixa de diálogo.


