---
permalink: events/reference_description_of_event_impact_levels.html 
sidebar: sidebar 
keywords: description, event, impact, levels 
summary: 'Cada evento está associado a um nível de impacto (incidente, risco, evento ou atualização) para ajudar você a priorizar os eventos que exigem ação corretiva imediata.' 
---
= Descrição dos níveis de impacto do evento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada evento está associado a um nível de impacto (incidente, risco, evento ou atualização) para ajudar você a priorizar os eventos que exigem ação corretiva imediata.

* *Incidente*
+
Um incidente é um conjunto de eventos que podem fazer com que um cluster pare de fornecer dados ao cliente e fique sem espaço para armazenar dados.  Eventos com nível de impacto Incidente são os mais graves.  Medidas corretivas imediatas devem ser tomadas para evitar interrupção do serviço.

* *Risco*
+
Um risco é um conjunto de eventos que podem fazer com que um cluster pare de fornecer dados ao cliente e fique sem espaço para armazenar dados.  Eventos com nível de impacto de Risco podem causar interrupção do serviço.  Pode ser necessária uma ação corretiva.

* *Evento*
+
Um evento é uma mudança de estado ou status de objetos de armazenamento e seus atributos.  Eventos com nível de impacto Evento são informativos e não exigem ação corretiva.

* *Atualizar*
+
Eventos de atualização são um tipo específico de evento relatado pela plataforma Active IQ .  Esses eventos identificam problemas cuja resolução exige que você atualize o software ONTAP , o firmware do nó ou o software do sistema operacional (para avisos de segurança).  Talvez você queira executar ações corretivas imediatas para alguns desses problemas, enquanto outros podem esperar até a próxima manutenção programada.


