---
permalink: events/task_upload_new_active_iq_rules_file.html 
sidebar: sidebar 
keywords: upload, new, active iq AIQ rules, rules file, CA secure rules, config advisor rules 
summary: O Unified Manager verifica automaticamente se há um novo arquivo de regras do Active IQ e baixa um novo arquivo quando há regras mais recentes.  No entanto, em sites sem acesso à rede externa, você precisa carregar o arquivo de regras manualmente. 
---
= Carregar um novo arquivo de regras do Active IQ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Unified Manager verifica automaticamente se há um novo arquivo de eventos (regras) do Active IQ e baixa um novo arquivo quando há regras mais recentes.  No entanto, em sites sem acesso à rede externa, você precisa carregar o arquivo de regras manualmente.


NOTE: As regras do Active IQ também são chamadas de regras seguras do Config Advisor (CA).

Ao instalar ou atualizar o Unified Manager para uma versão específica em um site sem conectividade de rede, as regras do Active IQ incluídas ficam automaticamente disponíveis para upload.  No entanto, é recomendável que você baixe um novo arquivo de regras aproximadamente uma vez por mês no site de suporte da NetApp para garantir que eventos atualizados sejam gerados e que seus sistemas de armazenamento continuem funcionando perfeitamente.

.Antes de começar
* O relatório de eventos do portal Active IQ deve estar habilitado.  Este recurso é habilitado por padrão.  Para obter informações, consultelink:../config/concept_active_iq_platform_events.html["Habilitando eventos do portal Active IQ"] .
* Você deve baixar o arquivo de regras do site de suporte da NetApp .
+
O arquivo de regras está localizado em: https://mysupport.netapp.com/api/content-service/staticcontents/content/public/tools/unifiedmanager/ca/secure_rules.zip[]



.Passos
. Em um computador com acesso à rede, navegue até o site de suporte da NetApp e baixe as regras atuais `.zip` arquivo.
+
O pacote de regras inclui o repositório de regras, fontes de dados e um artigo da base de conhecimento da NetApp .

+

NOTE: Em sistemas Windows, em um site sem conectividade de rede, o artigo da KB da NetApp não é incluído por padrão com o instalador.  Você pode baixar o arquivo _secure_rules.zip_ do site de suporte e enviá-lo para visualizar o artigo da KB com todas as regras.

. Transfira o arquivo de regras para alguma mídia que você possa levar para a área segura e depois copie-o para um sistema na área segura.
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de evento*.
. Na página *Configuração do evento*, clique no botão *Carregar regras*.
. Na caixa de diálogo *Regras de upload*, navegue e selecione as regras `.zip` arquivo que você baixou e clique em *Upload*.
+
Este processo pode levar alguns minutos.



O arquivo de regras é descompactado no servidor do Unified Manager.  Depois que os clusters gerenciados geram um arquivo AutoSupport após a meia-noite, o Unified Manager verifica os clusters em relação ao arquivo de regras e gera novos eventos de risco e incidente, conforme necessário.

Para obter mais informações, consulte este artigo da Base de Conhecimento (KB): https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/How_to_update_AIQCASecure_rules_manually_in_Active_IQ_Unified_Manager["Como atualizar as regras do AIQCASecure manualmente no Active IQ Unified Manager"] .
