---
permalink: events/task_manage_host_system_resource_events.html 
sidebar: sidebar 
keywords: manage, host, system, resource, events 
summary: O Unified Manager inclui um serviço que monitora problemas de recursos no sistema host no qual o Unified Manager está instalado.  Problemas como falta de espaço em disco disponível ou falta de memória no sistema host podem acionar eventos da estação de gerenciamento que são exibidos como mensagens de banner na parte superior da interface do usuário. 
---
= Gerenciar eventos de recursos do sistema host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Unified Manager inclui um serviço que monitora problemas de recursos no sistema host no qual o Unified Manager está instalado.  Problemas como falta de espaço em disco disponível ou falta de memória no sistema host podem acionar eventos da estação de gerenciamento que são exibidos como mensagens de banner na parte superior da interface do usuário.

Os eventos da estação de gerenciamento indicam um problema com o sistema host no qual o Unified Manager está instalado.  Exemplos de problemas de estação de gerenciamento incluem espaço em disco insuficiente no sistema host; o Unified Manager não realiza um ciclo regular de coleta de dados; e não conclusão ou conclusão tardia da análise de estatísticas porque a próxima pesquisa de coleta foi iniciada.

Diferentemente de todas as outras mensagens de eventos do Unified Manager, esses eventos críticos e de aviso específicos da estação de gerenciamento são exibidos em mensagens de banner.

.Etapa
. Para visualizar informações sobre eventos da estação de gerenciamento, execute estas ações:
+
|===
| Se você quiser... | Faça isso... 


 a| 
Ver detalhes do evento
 a| 
Clique no banner do evento para exibir a página de detalhes do evento que inclui soluções sugeridas para o problema.



 a| 
Ver todos os eventos da estação de gerenciamento
 a| 
.. No painel de navegação esquerdo, clique em *Gerenciamento de eventos*.
.. No painel Filtros na página de inventário do Gerenciamento de Eventos, clique na caixa Estação de Gerenciamento na lista Tipo de Fonte.


|===

