---
permalink: events/task_assign_events_to_specific_users.html 
sidebar: sidebar 
keywords: assign, events, specific, users 
summary: Você pode atribuir eventos não atribuídos a si mesmo ou a outros usuários, incluindo usuários remotos.  Você pode reatribuir eventos atribuídos a outro usuário, se necessário.  Por exemplo, quando ocorrem problemas frequentes em um objeto de armazenamento, você pode atribuir os eventos desses problemas ao usuário que gerencia esse objeto. 
---
= Atribuir eventos a usuários específicos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atribuir eventos não atribuídos a si mesmo ou a outros usuários, incluindo usuários remotos.  Você pode reatribuir eventos atribuídos a outro usuário, se necessário.  Por exemplo, quando ocorrem problemas frequentes em um objeto de armazenamento, você pode atribuir os eventos desses problemas ao usuário que gerencia esse objeto.

.Antes de começar
* O nome do usuário e o ID de e-mail devem ser configurados corretamente.
* Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.


.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de eventos*.
. Na página de inventário *Gerenciamento de eventos*, selecione um ou mais eventos que você deseja atribuir.
. Atribua o evento escolhendo uma das seguintes opções:
+
|===
| Se você quiser atribuir o evento a... | Então faça isto... 


 a| 
Você mesmo
 a| 
Clique em *Atribuir a* > *Eu*.



 a| 
Outro usuário
 a| 
.. Clique em *Atribuir a* > *Outro usuário*.
.. Na caixa de diálogo Atribuir proprietário, insira o nome do usuário ou selecione um usuário na lista suspensa.
.. Clique em *Atribuir*.
+
Uma notificação por e-mail é enviada ao usuário.

+
[NOTE]
====
Se você não inserir um nome de usuário ou selecionar um usuário na lista suspensa e clicar em *Atribuir*, o evento permanecerá não atribuído.

====


|===

