---
permalink: events/task_change_or_cancel_scheduled_maintenance_window.html 
sidebar: sidebar 
keywords: change, cancel, scheduled, maintenance, window 
summary: Se você configurou uma janela de manutenção do Unified Manager para ocorrer no futuro, poderá alterar os horários de início e término ou cancelar a ocorrência da janela de manutenção. 
---
= Alterar ou cancelar uma janela de manutenção programada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você configurou uma janela de manutenção do Unified Manager para ocorrer no futuro, poderá alterar os horários de início e término ou cancelar a ocorrência da janela de manutenção.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Cancelar uma janela de manutenção em execução é útil se você tiver concluído a manutenção do cluster antes do horário de término da janela de manutenção agendada e quiser começar a receber eventos e alertas do cluster novamente.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de cluster*.
. Na coluna *Modo de manutenção* do cluster:
+
|===
| Se você quiser... | Execute esta etapa... 


 a| 
Alterar o período para uma janela de manutenção programada
 a| 
.. Clique no texto "Agendado" ao lado do botão deslizante.
.. Altere a data e hora de início e/ou término e clique em *Aplicar*.




 a| 
Prolongue a duração de uma janela de manutenção ativa
 a| 
.. Clique no texto "Ativo" ao lado do botão deslizante.
.. Altere a data e hora de término e clique em *Aplicar*.




 a| 
Cancelar uma janela de manutenção programada
 a| 
Selecione o botão deslizante e mova-o para a esquerda.



 a| 
Cancelar uma janela de manutenção ativa
 a| 
Selecione o botão deslizante e mova-o para a esquerda.

|===

