---
permalink: events/task_disable_unwanted_events.html 
sidebar: sidebar 
keywords: disable, unwanted, events 
summary: Todos os eventos são ativados por padrão.  Você pode desabilitar eventos globalmente para evitar a geração de notificações para eventos que não são importantes no seu ambiente.  Você pode habilitar eventos que estão desabilitados quando quiser voltar a receber notificações sobre eles. 
---
= Desativar eventos indesejados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Todos os eventos são ativados por padrão.  Você pode desabilitar eventos globalmente para evitar a geração de notificações para eventos que não são importantes no seu ambiente.  Você pode habilitar eventos que estão desabilitados quando quiser voltar a receber notificações sobre eles.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Quando você desabilita eventos, os eventos gerados anteriormente no sistema são marcados como obsoletos, e os alertas configurados para esses eventos não são acionados.  Quando você habilita eventos que estão desabilitados, as notificações para esses eventos são geradas a partir do próximo ciclo de monitoramento.

Quando você desabilita um evento para um objeto (por exemplo, o `vol offline` evento) e, depois, você habilita o evento, o Unified Manager não gera novos eventos para objetos que ficaram offline quando o evento estava no estado desabilitado.  O Unified Manager gera um novo evento somente quando há uma alteração no estado do objeto após o evento ter sido reativado.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de evento*.
. Na página *Configuração de eventos*, desabilite ou habilite eventos escolhendo uma das seguintes opções:
+
|===
| Se você quiser... | Então faça isto... 


 a| 
Desativar eventos
 a| 
.. Clique em *Desativar*.
.. Na caixa de diálogo Desativar eventos, selecione a gravidade do evento.
.. Na coluna Eventos correspondentes, selecione os eventos que você deseja desabilitar com base na gravidade do evento e clique na seta para a direita para mover esses eventos para a coluna Desabilitar eventos.
.. Clique em *Salvar e Fechar*.
.. Verifique se os eventos que você desativou são exibidos na exibição de lista da página Configuração de eventos.




 a| 
Habilitar eventos
 a| 
.. Marque a caixa de seleção do evento ou eventos que você deseja habilitar.
.. Clique em *Ativar*.


|===

