---
permalink: events/task_add_alerts.html 
sidebar: sidebar 
keywords: add, alerts 
summary: Você pode configurar alertas para notificá-lo quando um evento específico for gerado.  Você pode configurar alertas para um único recurso, para um grupo de recursos ou para eventos de um tipo de gravidade específico.  Você pode especificar a frequência com que deseja ser notificado e associar um script ao alerta. 
---
= Adicionar alertas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar alertas para notificá-lo quando um evento específico for gerado.  Você pode configurar alertas para um único recurso, para um grupo de recursos ou para eventos de um tipo de gravidade específico.  Você pode especificar a frequência com que deseja ser notificado e associar um script ao alerta.

.Antes de começar
* Você deve ter configurado as configurações de notificação, como o endereço de e-mail do usuário, o servidor SMTP e o host de interceptação SNMP para permitir que o servidor Active IQ Unified Manager use essas configurações para enviar notificações aos usuários quando um evento for gerado.
* Você deve saber os recursos e eventos para os quais deseja acionar o alerta, além dos nomes de usuário ou endereços de e-mail dos usuários que deseja notificar.
* Se quiser que um script seja executado com base no evento, você deve adicionar o script ao Unified Manager usando a página Scripts.
* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.


Você pode criar um alerta diretamente na página Detalhes do evento após receber um evento, além de criar um alerta na página Configuração de alerta, conforme descrito aqui.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de alerta*.
. Na página *Configuração de alerta*, clique em *Adicionar*.
. Na caixa de diálogo *Adicionar alerta*, clique em *Nome* e insira um nome e uma descrição para o alerta.
. Clique em *Recursos* e selecione os recursos a serem incluídos ou excluídos do alerta.
+
Você pode definir um filtro especificando uma sequência de texto no campo *Nome contém* para selecionar um grupo de recursos.  Com base na sequência de texto especificada, a lista de recursos disponíveis exibe apenas aqueles que correspondem à regra de filtro.  A sequência de texto que você especificar diferencia maiúsculas de minúsculas.

+
Se um recurso estiver em conformidade com as regras de inclusão e exclusão especificadas, a regra de exclusão terá precedência sobre a regra de inclusão, e o alerta não será gerado para eventos relacionados ao recurso excluído.

. Clique em *Eventos* e selecione os eventos com base no nome do evento ou no tipo de gravidade do evento para o qual você deseja acionar um alerta.
+
[TIP]
====
Para selecionar mais de um evento, pressione a tecla Ctrl enquanto faz suas seleções.

====
. Clique em *Ações* e selecione os usuários que deseja notificar, escolha a frequência de notificação, escolha se uma armadilha SNMP será enviada ao receptor da armadilha e atribua um script a ser executado quando um alerta for gerado.
+
[NOTE]
====
Se você modificar o endereço de e-mail especificado para o usuário e reabrir o alerta para edição, o campo Nome aparecerá em branco porque o endereço de e-mail modificado não estará mais mapeado para o usuário selecionado anteriormente.  Além disso, se você modificar o endereço de e-mail do usuário selecionado na página Usuários, o endereço de e-mail modificado não será atualizado para o usuário selecionado.

====
+
Você também pode optar por notificar os usuários por meio de traps SNMP.

. Clique em *Salvar*.




== Exemplo de adição de um alerta

Este exemplo mostra como criar um alerta que atende aos seguintes requisitos:

* Nome do alerta: HealthTest
* Recursos: inclui todos os volumes cujo nome contém "abc" e exclui todos os volumes cujo nome contém "xyz"
* Eventos: inclui todos os eventos críticos de saúde
* Ações: inclui "sample@domain.com", um script de "Teste" e o usuário deve ser notificado a cada 15 minutos


Execute as seguintes etapas na caixa de diálogo Adicionar alerta:

. Clique em *Nome* e digite*`HealthTest` * no campo *Nome do alerta*.
. Clique em *Recursos* e, na guia Incluir, selecione *Volumes* na lista suspensa.
+
.. Digitar*`abc` * no campo *Nome contém* para exibir os volumes cujo nome contém "abc".
.. Selecione *+<<All Volumes whose name contains 'abc'>> +* da área Recursos Disponíveis e mova-o para a área Recursos Selecionados.
.. Clique em *Excluir* e digite*`xyz` * no campo *Nome contém* e clique em *Adicionar*.


. Clique em *Eventos* e selecione *Crítico* no campo Gravidade do Evento.
. Selecione *Todos os Eventos Críticos* na área Eventos Correspondentes e mova-os para a área Eventos Selecionados.
. Clique em *Ações* e digite*`sample@domain.com` * no campo Alertar estes usuários.
. Selecione *Lembrar a cada 15 minutos* para notificar o usuário a cada 15 minutos.
+
Você pode configurar um alerta para enviar notificações repetidamente aos destinatários por um período específico.  Você deve determinar o horário a partir do qual a notificação de evento estará ativa para o alerta.

. No menu Selecionar script para executar, selecione o script *Teste*.
. Clique em *Salvar*.

