---
permalink: events/task_test_alerts.html 
sidebar: sidebar 
keywords: test, alerts 
summary: Você pode testar um alerta para verificar se ele foi configurado corretamente.  Quando um evento é acionado, um alerta é gerado e um e-mail de alerta é enviado aos destinatários configurados.  Você pode verificar se a notificação foi enviada e se o seu script foi executado usando o alerta de teste. 
---
= Alertas de teste
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode testar um alerta para verificar se ele foi configurado corretamente.  Quando um evento é acionado, um alerta é gerado e um e-mail de alerta é enviado aos destinatários configurados.  Você pode verificar se a notificação foi enviada e se o seu script foi executado usando o alerta de teste.

.Antes de começar
* Você deve ter configurado as configurações de notificação, como o endereço de e-mail dos destinatários, o servidor SMTP e a interceptação SNMP.
+
O servidor do Unified Manager pode usar essas configurações para enviar notificações aos usuários quando um evento é gerado.

* Você deve ter atribuído um script e configurado o script para ser executado quando o alerta for gerado.
* Você deve ter a função de Administrador do Aplicativo.


.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de alerta*.
. Na página *Configuração de alerta*, selecione o alerta que deseja testar e clique em *Testar*.
+
Um e-mail de alerta de teste é enviado para os endereços de e-mail que você especificou ao criar o alerta.


