---
permalink: events/task_view_event_details.html 
sidebar: sidebar 
keywords: view, events, details 
summary: Você pode visualizar detalhes sobre um evento acionado pelo Unified Manager para tomar medidas corretivas.  Por exemplo, se houver um evento de saúde Volume Offline, você pode clicar nesse evento para visualizar os detalhes e executar ações corretivas. 
---
= Ver eventos e detalhes dos eventos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar detalhes sobre um evento acionado pelo Unified Manager para tomar medidas corretivas.  Por exemplo, se houver um evento de saúde Volume Offline, você pode clicar nesse evento para visualizar os detalhes e executar ações corretivas.

.Antes de começar
Você deve ter a função de Operador, Administrador de Aplicativos ou Administrador de Armazenamento.

Os detalhes do evento incluem informações como a origem do evento, a causa do evento e quaisquer notas relacionadas ao evento.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de eventos*.
+
Por padrão, a exibição Todos os eventos ativos exibe os eventos Novos e Reconhecidos (ativos) que foram gerados nos últimos 7 dias e que têm um Nível de Impacto de Incidente ou Risco.

. Se você quiser visualizar uma categoria específica de eventos, por exemplo, eventos de capacidade ou eventos de desempenho, clique em *Exibir* e selecione no menu de tipos de eventos.
. Clique no nome do evento cujos detalhes você deseja visualizar.
+
Os detalhes do evento são exibidos na página Detalhes do evento.


