---
permalink: data-protection/concept_what_resource_pools_are.html 
sidebar: sidebar 
keywords: resource pools 
summary: Pools de recursos são grupos de agregados criados por um administrador de armazenamento usando o Unified Manager para fornecer provisionamento a aplicativos parceiros para gerenciamento de backup. 
---
= O que são pools de recursos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pools de recursos são grupos de agregados criados por um administrador de armazenamento usando o Unified Manager para fornecer provisionamento a aplicativos parceiros para gerenciamento de backup.

Você pode reunir seus recursos com base em atributos como desempenho, custo, localização física ou disponibilidade.  Ao agrupar recursos relacionados em um pool, você pode tratá-lo como uma única unidade para monitoramento e provisionamento.  Isso simplifica o gerenciamento desses recursos e permite um uso mais flexível e eficiente do armazenamento.

Durante o provisionamento de armazenamento secundário, o Unified Manager determina o agregado mais adequado no pool de recursos para proteção usando os seguintes critérios:

* O agregado é um agregado de dados (não um agregado raiz) e está ONLINE.
* O agregado está em um nó de cluster de destino cuja versão do ONTAP é igual ou superior à versão principal do cluster de origem.
* O agregado tem o maior espaço disponível de todos os agregados no pool de recursos.
* Após o provisionamento do volume de destino, o espaço agregado fica dentro do limite quase cheio e quase supercomprometido definido para o agregado (limite global ou local, o que for aplicável).
* O número de volumes FlexVol no nó de destino não deve exceder o limite da plataforma.

