---
permalink: data-protection/concept_what_jobs_are.html 
sidebar: sidebar 
keywords: jobs 
summary: Um trabalho é uma série de tarefas que você pode monitorar usando o Unified Manager.  Visualizar os trabalhos e suas tarefas associadas permite que você determine se eles foram concluídos com sucesso. 
---
= Quais são os empregos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um trabalho é uma série de tarefas que você pode monitorar usando o Unified Manager.  Visualizar os trabalhos e suas tarefas associadas permite que você determine se eles foram concluídos com sucesso.

Os trabalhos são iniciados quando você cria relacionamentos SnapMirror e SnapVault , quando você executa qualquer operação de relacionamento (interromper, editar, desativar, remover, retomar, ressincronizar e ressincronizar reversamente), quando você executa tarefas de restauração de dados, quando você efetua login em um cluster e assim por diante.

Ao iniciar um trabalho, você pode usar a página Trabalhos e a página Detalhes do trabalho para monitorar o trabalho e o progresso das tarefas associadas.
