---
permalink: data-protection/concept_manage_and_monitor_protection_relationships.html 
sidebar: sidebar 
keywords: manage, monitor, protection, relationships 
summary: O Active IQ Unified Manager permite que você crie relacionamentos de proteção, monitore e solucione problemas de relacionamentos SnapMirror e SnapVault em clusters gerenciados e restaure dados quando eles forem substituídos ou perdidos. 
---
= Gerenciar e monitorar relacionamentos de proteção
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Active IQ Unified Manager permite que você crie relacionamentos de proteção, monitore e solucione problemas de relacionamentos SnapMirror e SnapVault em clusters gerenciados e restaure dados quando eles forem substituídos ou perdidos.

Para operações do SnapMirror , há dois tipos de replicação:

* Assíncrono
+
A replicação do volume primário para o secundário é determinada por um cronograma.

* Síncrono
+
A replicação é realizada simultaneamente no volume primário e secundário.



Você pode executar até 10 tarefas de proteção simultaneamente sem impacto no desempenho.  Você pode sentir algum impacto no desempenho ao executar entre 11 e 30 tarefas simultaneamente.  Não é recomendado executar mais de 30 tarefas simultaneamente.
