---
permalink: data-protection/reference_create_snapmirror_policy_dialog_box.html 
sidebar: sidebar 
keywords: create, snapmirror, policy, dialog box 
summary: A caixa de diálogo Criar política do SnapMirror permite que você crie uma política para definir a prioridade das transferências do SnapMirror .  Você usa políticas para maximizar a eficiência das transferências da origem para o destino. 
---
= Caixa de diálogo Criar política do SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A caixa de diálogo Criar política do SnapMirror permite que você crie uma política para definir a prioridade das transferências do SnapMirror .  Você usa políticas para maximizar a eficiência das transferências da origem para o destino.

* *Grupo de Destinos*
+
O nome do cluster que você selecionou na guia SnapMirror da caixa de diálogo Configurar proteção.

* *Destino SVM*
+
O nome do SVM que você selecionou na guia SnapMirror da caixa de diálogo Configurar proteção.

* *Nome da Política*
+
O nome que você fornece para a nova política.  Os nomes de políticas podem consistir nos caracteres de A a Z, de a a z, de 0 a 9, ponto (.), hífen (-) e sublinhado (_).

* *Prioridade de transferência*
+
A prioridade na qual uma transferência é executada para operações assíncronas.  Você pode selecionar Normal ou Baixo.  Relacionamentos de transferência com políticas que especificam uma prioridade de transferência normal são executados antes daqueles com políticas que especificam uma prioridade de transferência baixa.

* *Comentário*
+
Um campo opcional no qual você pode adicionar comentários sobre a política.

* *Reinício da transferência*
+
Indica qual ação de reinicialização tomar quando uma transferência é interrompida por uma operação de aborto ou qualquer tipo de falha, como uma queda de rede.  Você pode selecionar uma das seguintes opções:

+
** Sempre
+
Especifica que uma nova cópia do Snapshot é criada antes de reiniciar uma transferência. Então, se houver uma, a transferência é reiniciada a partir de um ponto de verificação, seguida por uma transferência incremental da cópia do Snapshot recém-criada.

** Nunca
+
Especifica que transferências interrompidas nunca são reiniciadas.







== Botões de comando

Os botões de comando permitem que você execute as seguintes tarefas:

* *Cancelar*
+
Descarta as seleções e fecha a caixa de diálogo Configurar proteção.

* *Aplicar*
+
Aplica suas seleções e inicia o processo de proteção.


