---
permalink: data-protection/reference_create_schedule_dialog_box.html 
sidebar: sidebar 
keywords: create, schedule, dialog box 
summary: A caixa de diálogo Criar agendamento permite que você crie um agendamento de proteção básico ou avançado para transferências de relacionamento do SnapMirror e do SnapVault .  Você pode criar um novo cronograma para aumentar a frequência das transferências de dados devido às atualizações frequentes de dados ou pode criar um cronograma menos frequente quando os dados mudam com pouca frequência. 
---
= Caixa de diálogo Criar agendamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A caixa de diálogo Criar agendamento permite que você crie um agendamento de proteção básico ou avançado para transferências de relacionamento do SnapMirror e do SnapVault .  Você pode criar um novo cronograma para aumentar a frequência das transferências de dados devido às atualizações frequentes de dados ou pode criar um cronograma menos frequente quando os dados mudam com pouca frequência.

Não é possível configurar agendamentos para relacionamentos síncronos do SnapMirror .

* *Grupo de Destinos*
+
O nome do cluster que você selecionou na guia SnapVault ou SnapMirror da caixa de diálogo Configurar proteção.

* *Nome da programação*
+
O nome que você fornece para o cronograma.  Os nomes das programações podem consistir nos caracteres de A a Z, de a a z, de 0 a 9, bem como em qualquer um dos seguintes caracteres especiais: !  @ # $ % {caret} & * ( ) _ -.  Os nomes das programações não podem incluir os seguintes caracteres: < >.

* *Básico ou Avançado*
+
O modo de programação que você deseja usar.

+
O modo básico inclui os seguintes elementos:

+
** Repita
+
Com que frequência ocorre uma transferência agendada.  As opções incluem por hora, diariamente e semanalmente.

** Dia
+
Quando uma repetição semanal é selecionada, o dia da semana em que uma transferência ocorre.

** Tempo
+
Quando Diário ou Semanal é selecionado, a hora do dia em que uma transferência ocorre.



+
O modo avançado inclui os seguintes elementos:

+
** Meses
+
Uma lista numérica separada por vírgulas representando os meses do ano.  Os valores válidos são de 0 a 11, com zero representando janeiro e assim por diante.  Este elemento é opcional.  Deixar o campo em branco implica que as transferências ocorrem todos os meses.

** Dias
+
Uma lista numérica separada por vírgulas representando o dia do mês.  Os valores válidos são de 1 a 31.  Este elemento é opcional.  Deixar o campo em branco implica que uma transferência ocorre todos os dias do mês.

** Dias da semana
+
Uma lista numérica separada por vírgulas representando os dias da semana.  Os valores válidos são de 0 a 6, com 0 representando domingo e assim por diante.  Este elemento é opcional.  Deixar o campo em branco implica que uma transferência ocorre todos os dias da semana.  Se um dia da semana for especificado, mas um dia do mês não for especificado, uma transferência ocorrerá somente no dia especificado da semana e não todos os dias.

** Horas
+
Uma lista numérica separada por vírgulas que representa o número de horas em um dia.  Os valores válidos são de 0 a 23, com 0 representando meia-noite.  Este elemento é opcional.

** Minutos
+
Uma lista numérica separada por vírgulas representando os minutos em uma hora.  Os valores válidos são de 0 a 59.  Este elemento é obrigatório.




