---
permalink: data-protection/reference_select_source_snapshot_copy_dialog_box.html 
sidebar: sidebar 
keywords: select, source, snapshot, copy, dialog box 
summary: Use a caixa de diálogo Selecionar cópia de instantâneo de origem para selecionar uma cópia de instantâneo específica para transferir dados entre relacionamentos de proteção ou selecione o comportamento padrão, que varia dependendo se você está inicializando, atualizando ou ressincronizando um relacionamento e se o relacionamento é um SnapMirror ou SnapVault. 
---
= Caixa de diálogo Selecionar cópia do instantâneo de origem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use a caixa de diálogo Selecionar cópia de instantâneo de origem para selecionar uma cópia de instantâneo específica para transferir dados entre relacionamentos de proteção ou selecione o comportamento padrão, que varia dependendo se você está inicializando, atualizando ou ressincronizando um relacionamento e se o relacionamento é um SnapMirror ou SnapVault.



[[default]]
== Padrão

Permite que você selecione o comportamento padrão para determinar qual cópia do Snapshot é usada para inicializar, atualizar e ressincronizar transferências para relacionamentos SnapVault e SnapMirror .

Se você estiver realizando uma transferência do SnapVault , o comportamento padrão para cada operação será o seguinte:

[cols="3*"]
|===
| Operação | Comportamento padrão do SnapVault quando a origem é de leitura/gravação | Comportamento padrão do SnapVault quando a origem é Proteção de Dados (DP) 


 a| 
Inicializar
 a| 
Cria uma nova cópia do Snapshot e a transfere.
 a| 
Transfere a última cópia exportada do Snapshot.



 a| 
Atualizar
 a| 
Transfere apenas cópias de Snapshot rotuladas, conforme especificado na política.
 a| 
Transfere a última cópia exportada do Snapshot.



 a| 
Ressincronizar
 a| 
Transfere todas as cópias de Snapshot rotuladas criadas após a cópia de Snapshot comum mais recente.
 a| 
Transfere a cópia mais recente do Snapshot rotulada.

|===
Se você estiver realizando uma transferência do SnapMirror , o comportamento padrão para cada operação será o seguinte:

[cols="3*"]
|===
| Operação | Comportamento padrão do SnapMirror | Comportamento padrão do SnapMirror quando o relacionamento é o segundo salto em uma cascata SnapMirror para SnapMirror 


 a| 
Inicializar
 a| 
Cria uma nova cópia do Snapshot e a transfere, juntamente com todas as cópias do Snapshot criadas antes da nova cópia do Snapshot.
 a| 
Transfere todas as cópias do Snapshot da origem.



 a| 
Atualizar
 a| 
Cria uma nova cópia do Snapshot e a transfere, juntamente com todas as cópias do Snapshot criadas antes da nova cópia do Snapshot.
 a| 
Transfere todas as cópias do Snapshot.



 a| 
Ressincronizar
 a| 
Cria uma nova cópia do Snapshot e então transfere todas as cópias do Snapshot da origem.
 a| 
Transfere todas as cópias do Snapshot do volume secundário para o volume terciário e exclui todos os dados adicionados após a criação da cópia comum mais recente do Snapshot.

|===


[[existing-snapshot-copy]]
== Cópia de instantâneo existente

Permite que você selecione uma cópia de Snapshot existente na lista se a seleção de cópia de Snapshot for permitida para essa operação.

* *Cópia instantânea*
+
Exibe as cópias existentes do Snapshot que você pode selecionar para uma transferência.

* *Data de criação*
+
Exibe a data e a hora em que a cópia do Snapshot foi criada.  As cópias de instantâneos são listadas da mais recente para a menos recente, com a mais recente no topo da lista.



Se você estiver executando uma transferência do SnapVault e quiser selecionar uma cópia existente do Snapshot para transferir de uma origem para um destino, o comportamento de cada operação será o seguinte:

[cols="3*"]
|===
| Operação | Comportamento do SnapVault ao especificar uma cópia do Snapshot | Comportamento do SnapVault ao especificar uma cópia do Snapshot em uma cascata 


 a| 
Inicializar
 a| 
Transfere a cópia do Snapshot especificada.
 a| 
A seleção de cópias do instantâneo de origem não é suportada para volumes de proteção de dados.



 a| 
Atualizar
 a| 
Transfere a cópia do Snapshot especificada.
 a| 
A seleção de cópias do instantâneo de origem não é suportada para volumes de proteção de dados.



 a| 
Ressincronizar
 a| 
Transfere a cópia do Snapshot selecionada.
 a| 
A seleção de cópias do instantâneo de origem não é suportada para volumes de proteção de dados.

|===
Se você estiver executando uma transferência do SnapMirror e quiser selecionar uma cópia do Snapshot existente para transferir de uma origem para um destino, o comportamento de cada operação será o seguinte:

[cols="3*"]
|===
| Operação | Comportamento do SnapMirror ao especificar uma cópia do Snapshot | Comportamento do SnapMirror ao especificar uma cópia do Snapshot em uma cascata 


 a| 
Inicializar
 a| 
Transfere todas as cópias do Snapshot na origem, até a cópia do Snapshot especificada.
 a| 
A seleção de cópias do instantâneo de origem não é suportada para volumes de proteção de dados.



 a| 
Atualizar
 a| 
Transfere todas as cópias do Snapshot na origem, até a cópia do Snapshot especificada.
 a| 
A seleção de cópias do instantâneo de origem não é suportada para volumes de proteção de dados.



 a| 
Ressincronizar
 a| 
Transfere todas as cópias do Snapshot da origem, até a cópia do Snapshot selecionada, e então exclui todos os dados adicionados após a criação da cópia comum mais recente do Snapshot.
 a| 
A seleção de cópias do instantâneo de origem não é suportada para volumes de proteção de dados.

|===


[[command-buttons]]
== Botões de comando

Os botões de comando permitem que você execute as seguintes tarefas:

* *Enviar*
+
Envia suas seleções e fecha a caixa de diálogo Selecionar cópia de instantâneo de origem.

* *Cancelar*
+
Descarta suas seleções e fecha a caixa de diálogo Selecionar cópia de instantâneo de origem.


