---
permalink: data-protection/reference_configure_protection_dialog_box.html 
sidebar: sidebar 
keywords: configure, protection, dialog box 
summary: Você pode usar a caixa de diálogo Configurar proteção para criar relacionamentos SnapMirror e SnapVault para todos os volumes de leitura, gravação e proteção de dados em clusters para garantir que os dados em um volume de origem ou volume primário sejam replicados. 
---
= Caixa de diálogo Configurar proteção
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a caixa de diálogo Configurar proteção para criar relacionamentos SnapMirror e SnapVault para todos os volumes de leitura, gravação e proteção de dados em clusters para garantir que os dados em um volume de origem ou volume primário sejam replicados.



== Guia Fonte

* *Visualização de topologia*
+
Exibe uma representação visual do relacionamento que você está criando.  A origem na topologia é destacada por padrão.

* *Informações da fonte*
+
Exibe detalhes sobre os volumes de origem selecionados, incluindo as seguintes informações:

+
** Nome do cluster de origem
** Nome do SVM de origem
** Tamanho total do volume cumulativo
+
Exibe o tamanho total de todos os volumes de origem selecionados.

** Tamanho do volume cumulativo usado
+
Exibe o tamanho do volume cumulativo usado para todos os volumes de origem selecionados.

** Volume de origem
+
Exibe as seguintes informações em uma tabela:

+
*** Volume de origem
+
Exibe os nomes dos volumes de origem selecionados.

*** Tipo
+
Exibe o tipo de volume.

*** Tipo SnapLock
+
Exibe o tipo SnapLock do volume.  As opções são Conformidade, Corporativo e Não SnapLock.

*** Cópia instantânea
+
Exibe a cópia do Snapshot usada para a transferência de linha de base.  Se o volume de origem for de leitura/gravação, o valor Padrão na coluna Cópia do instantâneo indica que uma nova cópia do instantâneo é criada por padrão e usada para a transferência de linha de base.  Se o volume de origem for um volume de proteção de dados, o valor Padrão na coluna Cópia de instantâneo indica que nenhuma nova cópia de instantâneo é criada e todas as cópias de instantâneo existentes são transferidas para o destino.  Clicar no valor Cópia do Snapshot exibe uma lista de cópias do Snapshot da qual você pode selecionar uma cópia do Snapshot existente para usar na transferência de linha de base.  Não é possível selecionar uma cópia de Snapshot padrão diferente se o tipo de origem for proteção de dados.









== Guia SnapMirror

Permite que você especifique um cluster de destino, uma máquina virtual de armazenamento (SVM) e um agregado para um relacionamento de proteção, bem como uma convenção de nomenclatura para destinos ao criar um relacionamento SnapMirror .  Você também pode especificar uma política e agendamento do SnapMirror .

* *Visualização de topologia*
+
Exibe uma representação visual do relacionamento que você está criando.  O recurso de destino do SnapMirror na topologia é destacado por padrão.

* *Informações de destino*
+
Permite selecionar os recursos de destino para um relacionamento de proteção:

+
** Link avançado
+
Inicia a caixa de diálogo Configurações avançadas de destino quando você está criando um relacionamento SnapMirror .

** Conjunto
+
Lista os clusters que estão disponíveis como hosts de destino de proteção.  Este campo é obrigatório.

** máquina virtual de armazenamento (SVM)
+
Lista as SVMs que estão disponíveis no cluster selecionado.  Um cluster deve ser selecionado antes que a lista SVM seja preenchida.  Este campo é obrigatório.

** Agregar
+
Lista os agregados que estão disponíveis no SVM selecionado.  Um cluster deve ser selecionado antes que a lista Agregada seja preenchida.  Este campo é obrigatório.  A lista Agregada exibe as seguintes informações:

+
*** Classificação
+
Quando vários agregados satisfazem todos os requisitos para um destino, a classificação indica a prioridade na qual o agregado é listado, de acordo com as seguintes condições:

+
.... Um agregado localizado em um nó diferente do nó do volume de origem é preferível para permitir a separação do domínio de falhas.
.... Um agregado em um nó com menos volumes é preferível para permitir o balanceamento de carga entre os nós de um cluster.
.... Um agregado que tenha mais espaço livre do que outros agregados é preferível para permitir o balanceamento de capacidade.  Uma classificação 1 significa que o agregado é o mais preferido de acordo com os três critérios.


*** Nome do Agregado
+
Nome do agregado

*** Capacidade disponível
*** Quantidade de espaço disponível no agregado para dados
*** Pool de Recursos
+
Nome do pool de recursos ao qual o agregado pertence



** Convenção de nomenclatura
+
Especifica a convenção de nomenclatura padrão aplicada ao volume de destino.  Você pode aceitar a convenção de nomenclatura fornecida ou criar uma personalizada.  A convenção de nomenclatura pode ter os seguintes atributos: %C, %M, %V e %N, onde %C é o nome do cluster, %M é o nome do SVM, %V é o volume de origem e %N é o nome do nó de destino da topologia.

+
O campo de convenção de nomenclatura será destacado em vermelho se sua entrada for inválida.  Clicar no link "`Visualizar nome`" exibe uma prévia da convenção de nomenclatura que você inseriu, e o texto de visualização é atualizado dinamicamente conforme você digita uma convenção de nomenclatura no campo de texto.  Um sufixo entre 001 e 999 é anexado ao nome do destino quando o relacionamento é criado, substituindo o nnn exibido no texto de visualização, com 001 sendo atribuído primeiro, 002 atribuído em segundo e assim por diante.



* *Configurações de relacionamento*
+
Permite que você especifique a taxa máxima de transferência, a política do SnapMirror e a programação que o relacionamento de proteção usa:

+
** Taxa máxima de transferência
+
Especifica a taxa máxima na qual os dados são transferidos entre clusters pela rede.  Se você optar por não usar uma taxa de transferência máxima, a transferência básica entre relacionamentos será ilimitada.

** Política do SnapMirror
+
Especifica a política ONTAP SnapMirror para o relacionamento.  O padrão é DPDefault.

** Criar política
+
Inicia a caixa de diálogo Criar política do SnapMirror , que permite criar e usar uma nova política do SnapMirror .

** Cronograma do SnapMirror
+
Especifica a política ONTAP SnapMirror para o relacionamento.  Os horários disponíveis incluem Nenhum, 5 minutos, 8 horas, diário, por hora e semanal.  O padrão é Nenhum, indicando que nenhuma programação está associada ao relacionamento.  Relacionamentos sem agendamentos não têm valores de status de atraso, a menos que pertençam a um serviço de armazenamento.

** Criar agendamento
+
Inicia a caixa de diálogo Criar agendamento, que permite criar um novo agendamento do SnapMirror .







== Guia SnapVault

Permite que você especifique um cluster secundário, SVM e agregado para um relacionamento de proteção, bem como uma convenção de nomenclatura para volumes secundários ao criar um relacionamento SnapVault .  Você também pode especificar uma política e uma programação do SnapVault .

* *Visualização de topologia*
+
Exibe uma representação visual do relacionamento que você está criando.  O recurso secundário do SnapVault na topologia é destacado por padrão.

* *Informações secundárias*
+
Permite selecionar os recursos secundários para um relacionamento de proteção:

+
** Link avançado
+
Inicia a caixa de diálogo Configurações secundárias avançadas.

** Conjunto
+
Lista os clusters que estão disponíveis como hosts de proteção secundários.  Este campo é obrigatório.

** máquina virtual de armazenamento (SVM)
+
Lista as SVMs que estão disponíveis no cluster selecionado.  Um cluster deve ser selecionado antes que a lista SVM seja preenchida.  Este campo é obrigatório.

** Agregar
+
Lista os agregados que estão disponíveis no SVM selecionado.  Um cluster deve ser selecionado antes que a lista Agregada seja preenchida.  Este campo é obrigatório.  A lista Agregada exibe as seguintes informações:

+
*** Classificação
+
Quando vários agregados satisfazem todos os requisitos para um destino, a classificação indica a prioridade na qual o agregado é listado, de acordo com as seguintes condições:

+
.... Um agregado localizado em um nó diferente do nó do volume primário é preferível para permitir a separação do domínio de falhas.
.... Um agregado em um nó com menos volumes é preferível para permitir o balanceamento de carga entre os nós de um cluster.
.... Um agregado que tenha mais espaço livre do que outros agregados é preferível para permitir o balanceamento de capacidade.  Uma classificação 1 significa que o agregado é o mais preferido de acordo com os três critérios.


*** Nome do Agregado
+
Nome do agregado

*** Capacidade disponível
*** Quantidade de espaço disponível no agregado para dados
*** Pool de Recursos
+
Nome do pool de recursos ao qual o agregado pertence



** Convenção de nomenclatura
+
Especifica a convenção de nomenclatura padrão aplicada ao volume secundário.  Você pode aceitar a convenção de nomenclatura fornecida ou criar uma personalizada.  A convenção de nomenclatura pode ter os seguintes atributos: %C, %M, %V e %N, onde %C é o nome do cluster, %M é o nome do SVM, %V é o volume de origem e %N é o nome do nó secundário da topologia.

+
O campo de convenção de nomenclatura será destacado em vermelho se sua entrada for inválida.  Clicar no link "`Visualizar nome`" exibe uma prévia da convenção de nomenclatura que você inseriu, e o texto de visualização é atualizado dinamicamente conforme você digita uma convenção de nomenclatura no campo de texto.  Se você digitar um valor inválido, as informações inválidas serão exibidas como pontos de interrogação vermelhos na área de visualização.  Um sufixo entre 001 e 999 é anexado ao nome secundário quando o relacionamento é criado, substituindo o nnn exibido no texto de visualização, com 001 sendo atribuído primeiro, 002 atribuído em segundo e assim por diante.



* *Configurações de relacionamento*
+
Permite que você especifique a taxa máxima de transferência, a política do SnapVault e a programação do SnapVault que o relacionamento de proteção usa:

+
** Taxa máxima de transferência
+
Especifica a taxa máxima na qual os dados são transferidos entre clusters pela rede.  Se você optar por não usar uma taxa de transferência máxima, a transferência básica entre relacionamentos será ilimitada.

** Política do SnapVault
+
Especifica a política do ONTAP SnapVault para o relacionamento.  O padrão é XDPDefault.

** Criar política
+
Inicia a caixa de diálogo Criar política do SnapVault , que permite criar e usar uma nova política do SnapVault .

** Agendamento do SnapVault
+
Especifica o agendamento do ONTAP SnapVault para o relacionamento.  Os horários disponíveis incluem Nenhum, 5 minutos, 8 horas, diário, por hora e semanal.  O padrão é Nenhum, indicando que nenhuma programação está associada ao relacionamento.  Relacionamentos sem agendamentos não têm valores de status de atraso, a menos que pertençam a um serviço de armazenamento.

** Criar agendamento
+
Inicia a caixa de diálogo Criar agendamento, que permite criar um agendamento do SnapVault .







== Botões de comando

Os botões de comando permitem que você execute as seguintes tarefas:

* *Cancelar*
+
Descarta suas seleções e fecha a caixa de diálogo Configurar proteção.

* *Aplicar*
+
Aplica suas seleções e inicia o processo de proteção.


