---
permalink: data-protection/reference_advanced_destination_settings_dialog_box.html 
sidebar: sidebar 
keywords: advanced, destination, settings, dialog box 
summary: Você pode usar a caixa de diálogo Configurações avançadas de destino para habilitar as configurações de garantia de espaço em um volume de destino.  Você pode selecionar configurações avançadas quando a garantia de espaço estiver desabilitada na origem, mas você quer que ela seja habilitada no destino.  As configurações de desduplicação, compactação e crescimento automático em um relacionamento SnapMirror são herdadas do volume de origem e não podem ser alteradas. 
---
= Caixa de diálogo Configurações avançadas de destino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a caixa de diálogo Configurações avançadas de destino para habilitar as configurações de garantia de espaço em um volume de destino.  Você pode selecionar configurações avançadas quando a garantia de espaço estiver desabilitada na origem, mas você quer que ela seja habilitada no destino.  As configurações de desduplicação, compactação e crescimento automático em um relacionamento SnapMirror são herdadas do volume de origem e não podem ser alteradas.



[[space-guarantee]]
== Garantia de Espaço

Garante que espaço suficiente seja alocado no volume de destino para que as transferências de dados sempre sejam bem-sucedidas.  A configuração de garantia de espaço pode ser uma das seguintes:

* Arquivo
* Volume
* Nenhum


Por exemplo, você pode ter um volume de 200 GB que contém arquivos totalizando 50 GB; no entanto, esses arquivos contêm apenas 10 GB de dados.  A garantia de volume aloca 200 GB ao volume de destino, independentemente do conteúdo na origem.  A garantia de arquivo aloca 50 GB para garantir que espaço suficiente seja reservado para arquivos de origem no destino; selecionar *Nenhum* neste cenário significa que apenas 10 GB são alocados no destino para o espaço real usado pelos dados do arquivo na origem.

A garantia de espaço é definida como Volume por padrão.
