---
permalink: data-protection/task_create_snapvault_protection_relationship.html 
sidebar: sidebar 
keywords: create, snapvault, protection, relationship, health, volumes view 
summary: 'Você pode usar a exibição Integridade: Todos os volumes para criar relacionamentos do SnapVault para um ou mais volumes na mesma VM de armazenamento para habilitar backups de dados para fins de proteção.' 
---
= Crie um relacionamento de proteção SnapVault na visualização Saúde: Todos os volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a exibição Integridade: Todos os volumes para criar relacionamentos do SnapVault para um ou mais volumes na mesma VM de armazenamento para habilitar backups de dados para fins de proteção.

.Antes de começar
* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter configurado a Automação de Fluxo de Trabalho.


O menu *Proteger* não é exibido nas seguintes instâncias:

* Se as configurações do RBAC não permitirem esta ação: por exemplo, se você tiver apenas privilégios de operador
* Quando o ID do volume é desconhecido: por exemplo, quando você tem um relacionamento entre clusters e o cluster de destino ainda não foi descoberto


.Passos
. No painel de navegação esquerdo, clique em *Armazenamento* > *Volumes*.
. Na exibição *Saúde: Todos os volumes*, selecione um volume que você deseja proteger e clique em *Proteger*.
+
Como alternativa, para criar vários relacionamentos de proteção na mesma máquina virtual de armazenamento (SVM), selecione um ou mais volumes na exibição Integridade: Todos os volumes e clique em *Proteger* na barra de ferramentas.

. Selecione * SnapVault* no menu.
+
A caixa de diálogo Configurar proteção é iniciada.

. Clique em * SnapVault* para visualizar a guia * SnapVault* e configurar as informações do volume secundário.
. Clique em *Avançado* para definir a desduplicação, a compactação, o crescimento automático e a garantia de espaço conforme necessário e, em seguida, clique em *Aplicar*.
. Preencha a área *Informações de destino* e a área *Configurações de relacionamento* na aba * SnapVault*.
. Clique em *Aplicar*.
+
Você retornará à visualização Saúde: Todos os volumes.

. Clique no link do trabalho de configuração de proteção na parte superior da exibição *Saúde: Todos os volumes*.
+
Se você estiver criando apenas um relacionamento de proteção, a página Detalhes do trabalho será exibida; no entanto, se você estiver criando mais de um relacionamento de proteção, uma lista filtrada de todos os trabalhos associados à operação de proteção será exibida.

. Faça um dos seguintes:
+
** Se você tiver apenas uma tarefa, clique em *Atualizar* para atualizar a lista de tarefas e os detalhes das tarefas associadas à tarefa de configuração de proteção e para determinar quando a tarefa será concluída.
** Se você tem mais de um emprego:
+
... Clique em um trabalho na lista de trabalhos.
... Clique em *Atualizar* para atualizar a lista de tarefas e os detalhes das tarefas associadas ao trabalho de configuração de proteção e para determinar quando o trabalho será concluído.
... Use o botão *Voltar* para retornar à lista filtrada e visualizar outro trabalho.





