---
permalink: data-protection/task_abort_active_data_protection_transfer_from_health_volume.html 
sidebar: sidebar 
keywords: abort, active, data protection, transfer, volume health details page 
summary: Você pode abortar uma transferência de proteção de dados ativa quando quiser interromper uma replicação do SnapMirror que esteja em andamento.  Você também pode limpar o ponto de verificação de reinicialização de uma transferência se ela não for uma transferência de linha de base.  Você pode abortar uma transferência quando ela entra em conflito com outra operação, como uma movimentação de volume. 
---
= Abortar uma transferência ativa de proteção de dados na página de detalhes de Volume/Saúde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode abortar uma transferência de proteção de dados ativa quando quiser interromper uma replicação do SnapMirror que esteja em andamento.  Você também pode limpar o ponto de verificação de reinicialização de uma transferência se ela não for uma transferência de linha de base.  Você pode abortar uma transferência quando ela entra em conflito com outra operação, como uma movimentação de volume.

[NOTE]
====
Não é possível abortar relacionamentos de volumes protegidos pelo Grupo de Consistência.

====
.Antes de começar
* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter configurado a Automação de Fluxo de Trabalho.


A ação de aborto não é exibida nas seguintes instâncias:

* Se as configurações do RBAC não permitirem esta ação: por exemplo, se você tiver apenas privilégios de operador
* Quando o ID do volume é desconhecido: por exemplo, quando você tem um relacionamento entre clusters e o cluster de destino ainda não foi descoberto


Não é possível limpar o ponto de verificação de reinicialização para uma transferência de linha de base.

.Passos
. Na guia *Proteção* da página de detalhes *Volume / Saúde*, clique com o botão direito do mouse no relacionamento na exibição de topologia da transferência de dados que você deseja abortar e selecione *Abortar*.
+
A caixa de diálogo Abortar transferência é exibida.

. Se você quiser limpar o ponto de verificação de reinicialização para uma transferência que não seja uma transferência de linha de base, selecione *Limpar pontos de verificação*.
. Clique em *Continuar*.
+
A caixa de diálogo Abortar transferência é fechada, e o status da operação de aborto é exibido na parte superior da página de detalhes Volume/Integridade, juntamente com um link para os detalhes do trabalho.

. *Opcional:* Clique no link *Exibir detalhes* para ir para a página de detalhes do *Trabalho* para obter detalhes adicionais e visualizar o andamento do trabalho.
. Clique em cada tarefa para visualizar seus detalhes.
. Clique na seta Voltar no seu navegador para retornar à página de detalhes *Volume / Saúde*.
+
A operação de aborto é concluída quando todas as tarefas do trabalho são concluídas com sucesso.


