---
permalink: data-protection/task_initialize_or_update_protection_relationships.html 
sidebar: sidebar 
keywords: initialize, update, protection, relationships, volume, page 
summary: Na página Relacionamentos de Volume, você pode executar uma transferência de linha de base pela primeira vez em um novo relacionamento de proteção ou atualizar um relacionamento se ele já estiver inicializado e você quiser executar uma atualização incremental manual e não programada para transferir imediatamente. 
---
= Inicializar ou atualizar relacionamentos de proteção na página Relacionamentos de Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na página Relacionamentos de Volume, você pode executar uma transferência de linha de base pela primeira vez em um novo relacionamento de proteção ou atualizar um relacionamento se ele já estiver inicializado e você quiser executar uma atualização incremental manual e não programada para transferir imediatamente.


NOTE: Você não pode inicializar ou atualizar volumes protegidos por Grupos de Consistência.

.Antes de começar
* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter configurado o OnCommand Workflow Automation.


.Passos
. Na página *Relacionamentos de Volume*, clique com o botão direito do mouse em um volume e selecione um ou mais volumes com relacionamentos que você deseja atualizar ou inicializar e, em seguida, na barra de ferramentas, clique em *Inicializar/Atualizar*.
+
A caixa de diálogo *Inicializar/Atualizar* é exibida.

. Na aba *Opções de transferência*, selecione uma prioridade de transferência e a taxa máxima de transferência.
. Clique em *Cópias de instantâneo de origem*; em seguida, na coluna *Cópia de instantâneo*, clique em *Padrão*.
+
A caixa de diálogo Selecionar cópia do instantâneo de origem é exibida.

. Se você quiser especificar uma cópia de Snapshot existente em vez de transferir a cópia de Snapshot padrão, clique em *Cópia de Snapshot existente* e selecione uma cópia de Snapshot na lista.
. Clique em *Enviar*.
+
Você retornará à caixa de diálogo *Inicializar/Atualizar*.

. Se você selecionou mais de uma fonte para inicializar ou atualizar, clique em *Padrão* para a próxima fonte para a qual deseja especificar uma cópia de Snapshot existente.
. Clique em *Enviar* para iniciar o trabalho de inicialização ou atualização.
+
O trabalho de inicialização ou atualização é iniciado, você retorna à página Relacionamentos de Volume e um link de trabalhos é exibido na parte superior da página.

. *Opcional:* Clique em *Exibir trabalhos* na exibição *Saúde: Todos os volumes* para rastrear o status de cada trabalho de inicialização ou atualização.
+
Uma lista filtrada de trabalhos é exibida.

. *Opcional:* Clique em cada trabalho para ver seus detalhes.
. *Opcional:* Clique na seta *Voltar* no seu navegador para retornar à página *Relacionamentos de volume*.
+
A operação de inicialização ou atualização é concluída quando todas as tarefas são concluídas com sucesso.


