---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volume.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship,  volume, health details page 
summary: Você pode usar a página de detalhes Volume/Saúde para criar um relacionamento SnapMirror para que a replicação de dados seja habilitada para fins de proteção.  A replicação do SnapMirror permite restaurar dados do volume de destino em caso de perda de dados na origem. 
---
= Crie um relacionamento de proteção SnapMirror na página de detalhes Volume/Saúde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a página de detalhes Volume/Saúde para criar um relacionamento SnapMirror para que a replicação de dados seja habilitada para fins de proteção.  A replicação do SnapMirror permite restaurar dados do volume de destino em caso de perda de dados na origem.

.Antes de começar
* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter configurado a Automação de Fluxo de Trabalho.


O menu *Proteger* não é exibido nas seguintes instâncias:

* Se as configurações do RBAC não permitirem esta ação: por exemplo, se você tiver apenas privilégios de operador
* Quando o ID do volume é desconhecido: por exemplo, quando você tem um relacionamento entre clusters e o cluster de destino ainda não foi descoberto


Você pode executar até 10 tarefas de proteção simultaneamente sem impacto no desempenho.  Você pode sentir algum impacto no desempenho ao executar entre 11 e 30 tarefas simultaneamente.  Não é recomendado executar mais de 30 tarefas simultaneamente.

.Passos
. Na *guia Proteção* da página de detalhes *Volume / Integridade*, clique com o botão direito do mouse na exibição de topologia no nome de um volume que você deseja proteger.
. Selecione *Proteger* > * SnapMirror* no menu.
+
A caixa de diálogo Configurar proteção é exibida.

. Clique em * SnapMirror* para visualizar a aba * SnapMirror* e configurar as informações de destino.
. Clique em *Avançado* para definir a garantia de espaço, conforme necessário, e depois clique em *Aplicar*.
. Preencha a área *Informações de destino* e a área *Configurações de relacionamento* na caixa de diálogo *Configurar proteção*.
. Clique em *Aplicar*.
+
Você retornará à página de detalhes de Volume/Saúde.

. Clique no link da tarefa de configuração de proteção na parte superior da página de detalhes *Volume / Saúde*.
+
As tarefas e os detalhes do trabalho são exibidos na página Detalhes do trabalho.

. Na página de detalhes do *Trabalho*, clique em *Atualizar* para atualizar a lista de tarefas e os detalhes das tarefas associadas ao trabalho de configuração de proteção e para determinar quando o trabalho será concluído.
. Quando as tarefas do trabalho estiverem concluídas, clique em *Voltar* no seu navegador para retornar à página de detalhes *Volume / Saúde*.
+
O novo relacionamento é exibido na exibição de topologia da página de detalhes Volume/Integridade.



Dependendo do SVM de destino especificado durante a configuração ou das opções habilitadas nas configurações avançadas, o relacionamento SnapMirror resultante pode ser uma das diversas variações possíveis:

* Se você especificou um SVM de destino que é executado na mesma versão ou em uma versão mais recente do ONTAP em comparação ao volume de origem, um relacionamento SnapMirror baseado em replicação de bloco é o resultado padrão.
* Se você especificou um SVM de destino que é executado na mesma versão ou em uma versão mais recente do ONTAP em comparação com a do volume de origem, mas ativou a replicação flexível de versão nas configurações avançadas, o resultado será um relacionamento SnapMirror com replicação flexível de versão.
* Se você especificou um SVM de destino que é executado em uma versão anterior do ONTAP ou uma versão superior à do volume de origem e a versão anterior oferece suporte à replicação flexível de versão, um relacionamento SnapMirror com replicação flexível de versão é o resultado automático.

