---
permalink: data-protection/task_configure_protection_destination_settings.html 
sidebar: sidebar 
keywords: configure, destination, efficiency, settings 
summary: Você pode configurar as definições de eficiência de destino, como desduplicação, compactação, crescimento automático e garantia de espaço em um destino de proteção usando a caixa de diálogo Configurações avançadas de destino.  Use essas configurações quando quiser maximizar a utilização do espaço em um volume de destino ou secundário. 
---
= Configurar as definições de eficiência do destino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar as definições de eficiência de destino, como desduplicação, compactação, crescimento automático e garantia de espaço em um destino de proteção usando a caixa de diálogo Configurações avançadas de destino.  Use essas configurações quando quiser maximizar a utilização do espaço em um volume de destino ou secundário.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Por padrão, as configurações de eficiência correspondem às do volume de origem, exceto as configurações de compactação em um relacionamento SnapVault , que são desabilitadas por padrão.

.Passos
. Clique na aba * SnapMirror* ou na aba * SnapVault* na caixa de diálogo *Configurar proteção*, dependendo do tipo de relacionamento que você está configurando.
. Clique em *Avançado* na área *Informações de destino*.
+
A caixa de diálogo Configurações avançadas de destino é aberta.

. Habilite ou desabilite as configurações de eficiência para desduplicação, compactação, crescimento automático e garantia de espaço, conforme necessário.
. Clique em *Aplicar* para salvar suas seleções e retornar à caixa de diálogo *Configurar proteção*.

