---
permalink: data-protection/task_set_up_protection_relationships_in_unified_manager.html 
sidebar: sidebar 
keywords: set, protection, relationships, unified manager 
summary: Há várias etapas que você deve executar para usar o Unified Manager e o OnCommand Workflow Automation para configurar relacionamentos do SnapMirror e do SnapVault para proteger seus dados. 
---
= Configurar relacionamentos de proteção no Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Há várias etapas que você deve executar para usar o Unified Manager e o OnCommand Workflow Automation para configurar relacionamentos do SnapMirror e do SnapVault para proteger seus dados.

.Antes de começar
* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter estabelecido relacionamentos de pares entre dois clusters ou duas máquinas virtuais de armazenamento (SVMs).
* O OnCommand Workflow Automation deve ser integrado ao Unified Manager:
+
** link:task_configure_connection_between_workflow_automation_um.html["Configurar a OnCommand Workflow Automation"].
** link:task_verify_um_data_source_caching_in_workflow_automation.html["Verificando o cache da fonte de dados do Unified Manager no Workflow Automation"].




.Passos
. Dependendo do tipo de relacionamento de proteção que você deseja criar, faça um dos seguintes:
+
** link:task_create_snapmirror_relationship_from_health_volume.html["Criar um relacionamento de proteção SnapMirror"].
** link:task_create_snapvault_protection_relationship_from_health_volume_details.html["Criar um relacionamento de proteção SnapVault"].


. Se você quiser criar uma política para o relacionamento, dependendo do tipo de relacionamento que estiver criando, faça um dos seguintes procedimentos:
+
** link:task_create_snapvault_policy_to_maximize_transfer_efficiency.html["Criar uma política do SnapVault"].
** link:task_create_snapmirror_policy_to_maximize_transfer_efficiency.html["Criar uma política do SnapMirror"].


. link:task_create_snapmirror_and_snapvault_schedules.html["Crie uma programação SnapMirror ou SnapVault"].

