---
permalink: data-protection/task_reverse_protection_relationships.html 
sidebar: sidebar 
keywords: reverse, protection, relationships, volume, relationships page 
summary: Quando um desastre desabilita o volume de origem no seu relacionamento de proteção, você pode usar o volume de destino para fornecer dados, convertendo-o em um volume de leitura/gravação enquanto repara ou substitui a origem.  Quando a origem estiver novamente disponível para receber dados, você poderá usar a operação de ressincronização reversa para estabelecer o relacionamento na direção reversa, sincronizando os dados na origem com os dados no destino de leitura/gravação. 
---
= Relações de proteção reversa na página Relações de Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um desastre desabilita o volume de origem no seu relacionamento de proteção, você pode usar o volume de destino para fornecer dados, convertendo-o em um volume de leitura/gravação enquanto repara ou substitui a origem.  Quando a origem estiver novamente disponível para receber dados, você poderá usar a operação de ressincronização reversa para estabelecer o relacionamento na direção reversa, sincronizando os dados na origem com os dados no destino de leitura/gravação.

.Antes de começar
* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter configurado a Automação de Fluxo de Trabalho.
* O relacionamento não deve ser um relacionamento SnapVault .
* Uma relação de proteção já deve existir.
* A relação de proteção deve ser quebrada.
* Tanto a origem quanto o destino devem estar online.
* A origem não deve ser o destino de outro volume de proteção de dados.
* Ao executar esta tarefa, os dados na origem que são mais recentes que os dados na cópia comum do Snapshot são excluídos.
* As políticas e programações criadas em relacionamentos de ressincronização reversa são as mesmas que aquelas no relacionamento de proteção original.
+
Se políticas e cronogramas não existirem, eles serão criados.



.Passos
. Na página *Relacionamentos de Volume*, selecione um ou mais volumes com relacionamentos que você deseja reverter e, na barra de ferramentas, clique em *Ressincronização reversa*.
+
A caixa de diálogo Ressincronização reversa é exibida.

. Verifique se os relacionamentos exibidos na caixa de diálogo *Ressincronização reversa* são aqueles para os quais você deseja executar a operação de ressincronização reversa e clique em *Enviar*.
+
A operação de ressincronização reversa é iniciada, você retorna à página Relacionamentos de Volume e um link de tarefas é exibido na parte superior da página.

. *Opcional:* Clique em *Exibir trabalhos* na página *Relacionamentos de volume* para rastrear o status de cada trabalho de ressincronização reversa.
+
Uma lista filtrada de trabalhos relacionados a esta operação é exibida.

. *Opcional:* Clique na seta *Voltar* no seu navegador para retornar à página *Relacionamentos de volume*.
+
A operação de ressincronização reversa é concluída quando todas as tarefas do trabalho são concluídas com sucesso.


