---
permalink: data-protection/task_create_snapvault_protection_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: create, snapvault, protection, relationship, volume, health details page 
summary: Você pode criar um relacionamento SnapVault usando a página de detalhes Volume/Saúde para que os backups de dados sejam habilitados para fins de proteção nos volumes. 
---
= Crie um relacionamento de proteção SnapVault na página de detalhes Volume/Saúde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar um relacionamento SnapVault usando a página de detalhes Volume/Saúde para que os backups de dados sejam habilitados para fins de proteção nos volumes.

.Antes de começar
* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter configurado a Automação de Fluxo de Trabalho para executar esta tarefa.


O menu *Proteger* não é exibido nas seguintes instâncias:

* Se as configurações do RBAC não permitirem esta ação: por exemplo, se você tiver apenas privilégios de operador
* Quando o ID do volume é desconhecido: por exemplo, quando você tem um relacionamento entre clusters e o cluster de destino ainda não foi descoberto


.Passos
. Na guia *Proteção* da página de detalhes *Volume / Integridade*, clique com o botão direito do mouse em um volume na exibição de topologia que você deseja proteger.
. Selecione *Proteger* > * SnapVault* no menu.
+
A caixa de diálogo Configurar proteção é iniciada.

. Clique em * SnapVault* para visualizar a guia * SnapVault* e configurar as informações do recurso secundário.
. Clique em *Avançado* para definir a desduplicação, a compactação, o crescimento automático e a garantia de espaço conforme necessário e, em seguida, clique em *Aplicar*.
. Preencha a área *Informações de destino* e a área *Configurações de relacionamento* na caixa de diálogo *Configurar proteção*.
. Clique em *Aplicar*.
+
Você retornará à página de detalhes de Volume/Saúde.

. Clique no link da tarefa de configuração de proteção na parte superior da página de detalhes *Volume / Saúde*.
+
A página Detalhes do trabalho é exibida.

. Clique em *Atualizar* para atualizar a lista de tarefas e os detalhes das tarefas associadas ao trabalho de configuração de proteção e para determinar quando o trabalho será concluído.
+
Quando as tarefas do trabalho são concluídas, os novos relacionamentos são exibidos na exibição de topologia da página de detalhes de Volume/Integridade.


