---
permalink: data-protection/task_delete_resource_pools.html 
sidebar: sidebar 
keywords: delete, resource, pools 
summary: Você pode excluir pools de recursos quando eles não forem mais necessários.  Por exemplo, você pode querer redistribuir os agregados de membros de um pool de recursos para vários outros pools de recursos, tornando o pool de recursos original obsoleto. 
---
= Excluir pools de recursos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode excluir pools de recursos quando eles não forem mais necessários.  Por exemplo, você pode querer redistribuir os agregados de membros de um pool de recursos para vários outros pools de recursos, tornando o pool de recursos original obsoleto.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

O botão *Excluir* é habilitado somente quando pelo menos um pool de recursos é selecionado.

.Passos
. No painel de navegação esquerdo, clique em *Proteção* > *Pools de recursos*.
. Selecione o pool de recursos que você deseja excluir.
. Clique em *Excluir*.
+
O pool de recursos é removido da lista de pools de recursos e seus agregados são removidos da lista de membros.


