---
permalink: data-protection/task_remove_protection_relationship_voldtls.html 
sidebar: sidebar 
keywords: remove, protection, relationship,  volume, health details page 
summary: 'Você pode remover um relacionamento de proteção para excluir permanentemente um relacionamento existente entre a origem e o destino selecionados: por exemplo, quando você deseja criar um relacionamento usando um destino diferente.  Esta operação remove todos os metadados e não pode ser desfeita.' 
---
= Remover um relacionamento de proteção da página de detalhes de Volume/Saúde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode remover um relacionamento de proteção para excluir permanentemente um relacionamento existente entre a origem e o destino selecionados: por exemplo, quando você deseja criar um relacionamento usando um destino diferente.  Esta operação remove todos os metadados e não pode ser desfeita.

.Antes de começar
* Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.
* Você deve ter configurado a Automação de Fluxo de Trabalho.


.Passos
. Na guia *Proteção* da página de detalhes *Volume / Saúde*, selecione na topologia o relacionamento SnapMirror que você deseja remover.
. Clique com o botão direito do mouse no nome do destino e selecione *Remover* no menu.
+
A caixa de diálogo Remover relacionamento é exibida.

. Clique em *Continuar* para remover o relacionamento.
+
O relacionamento é removido da página de detalhes Volume/Saúde.


