---
permalink: data-protection/task_retry_failed_protection_job.html 
sidebar: sidebar 
keywords: retry, failed, protection job 
summary: Depois de tomar medidas para corrigir uma tarefa de proteção com falha, você pode usar Repetir para executar a tarefa novamente.  Tentar executar uma tarefa novamente cria uma nova tarefa usando o ID da tarefa original. 
---
= Repetir uma tarefa de proteção com falha
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de tomar medidas para corrigir uma tarefa de proteção com falha, você pode usar *Repetir* para executar a tarefa novamente.  Tentar executar uma tarefa novamente cria uma nova tarefa usando o ID da tarefa original.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Você pode tentar novamente apenas uma tarefa com falha por vez.  Selecionar mais de um trabalho desabilita o botão *Repetir*.  Somente tarefas do tipo Configuração de Proteção e Operação de Relacionamento de Proteção podem ser repetidas.

.Passos
. No painel de navegação esquerdo, clique em *Proteção* > *Trabalhos*.
. Na lista de trabalhos, selecione um único trabalho do tipo Configuração de Proteção ou Operação de Relacionamento de Proteção com falha.
+
O botão *Repetir* está habilitado.

. Clique em *Repetir*.
+
O trabalho é reiniciado.


