---
permalink: data-protection/task_edit_protection_relationships_from_protection_volume.html 
sidebar: sidebar 
keywords: edit, protection, relationships, volume, relationships, page 
summary: Você pode editar relacionamentos de proteção existentes para alterar a taxa máxima de transferência, a política de proteção ou o cronograma de proteção.  Você pode editar um relacionamento para diminuir a largura de banda usada para transferências ou para aumentar a frequência de transferências agendadas, pois os dados mudam com frequência. 
---
= Editar relacionamentos de proteção na página Relacionamentos de Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar relacionamentos de proteção existentes para alterar a taxa máxima de transferência, a política de proteção ou o cronograma de proteção.  Você pode editar um relacionamento para diminuir a largura de banda usada para transferências ou para aumentar a frequência de transferências agendadas, pois os dados mudam com frequência.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Os volumes selecionados devem ser destinos de relacionamento de proteção.  Não é possível editar relacionamentos quando volumes de origem, volumes de compartilhamento de carga ou volumes que não são o destino de um relacionamento SnapMirror ou SnapVault são selecionados.

.Passos
. Na página *Relacionamentos de Volume*, selecione na lista de volumes um ou mais volumes no mesmo SVM para os quais você deseja editar as configurações de relacionamento e, em seguida, selecione *Editar* na barra de ferramentas.
+
A caixa de diálogo Editar relacionamento é exibida.

. Na caixa de diálogo *Editar relacionamento*, edite a taxa máxima de transferência, a política de proteção ou o cronograma de proteção, conforme necessário.
. Clique em *Aplicar*.
+
As alterações são aplicadas aos relacionamentos selecionados.


