---
permalink: data-protection/task_add_resource_pool_members.html 
sidebar: sidebar 
keywords: add, resource, pool, members 
summary: Um pool de recursos consiste em vários agregados de membros.  Você pode adicionar agregados a pools de recursos existentes para aumentar a quantidade de espaço disponível para provisionamento de volume secundário. 
---
= Adicionar membros do pool de recursos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um pool de recursos consiste em vários agregados de membros.  Você pode adicionar agregados a pools de recursos existentes para aumentar a quantidade de espaço disponível para provisionamento de volume secundário.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Você não pode adicionar mais de 200 agregados a um pool de recursos ao mesmo tempo.  Os agregados mostrados na caixa de diálogo Agregados não pertencem a nenhum outro pool de recursos.

.Passos
. No painel de navegação esquerdo, clique em *Proteção* > *Pools de recursos*.
. Selecione um pool de recursos na lista *Pools de recursos*.
+
Os membros do pool de recursos são exibidos na área abaixo da lista do pool de recursos.

. Na área de membros do pool de recursos, clique em *Adicionar*.
+
A caixa de diálogo Agregados é exibida.

. Selecione um ou mais agregados.
. Clique em *Adicionar*.
+
A caixa de diálogo é fechada e os agregados são exibidos na lista de membros do pool de recursos selecionado.


