---
permalink: data-protection/task_remove_aggregates_from_resource_pools.html 
sidebar: sidebar 
keywords: remove, aggregates, resource pools 
summary: 'Você pode remover agregados de um pool de recursos existente: por exemplo, quando quiser usar um agregado para alguma outra finalidade.' 
---
= Remover agregados de pools de recursos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode remover agregados de um pool de recursos existente: por exemplo, quando quiser usar um agregado para alguma outra finalidade.

.Antes de começar
Você deve ter a função de Administrador de Aplicativos ou Administrador de Armazenamento.

Os membros do pool de recursos são exibidos somente quando um pool de recursos é selecionado.

.Passos
. No painel de navegação esquerdo, clique em *Proteção* > *Pools de recursos*.
. Selecione o pool de recursos do qual você deseja remover agregados de membros.
+
A lista de agregados de membros é exibida no painel Membros.

. Selecione um ou mais agregados.
+
O botão *Remover* está habilitado.

. Clique em *Remover.*
+
Uma caixa de diálogo de aviso é exibida.

. Clique em *Sim* para continuar.
+
Os agregados selecionados são removidos do painel Membros.


