---
permalink: data-protection/view-lun-relationships.html 
sidebar: sidebar 
keywords: LUN, SnapMirror active sync, Consistency Group, CG 
summary: Visão unificada de LUNs protegidos pela sincronização ativa do SnapMirror . 
---
= Monitorar LUNs em um relacionamento de grupo de consistência
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o seu ambiente ONTAP oferecer suporte à sincronização ativa do SnapMirror para proteger aplicativos com LUNs, você poderá visualizar e monitorar esses LUNs no Active IQ Unified Manager.

A sincronização ativa do SnapMirror garante objetivo de tempo de recuperação zero (RTO) durante failover em ambientes SAN.  Em uma implantação típica que oferece suporte à sincronização ativa do SnapMirror , os LUNs nos volumes são protegidos por relacionamentos de Grupo de Consistência.

Esses LUNs primários e secundários são LUNs compostos ou um par de LUNs de réplica com o mesmo UUID e número de série.  As operações de E/S (leitura e gravação) são multiplexadas entre os sites de origem e destino nesses LUNs compostos, garantindo transparência.

Para visualizar LUNs compostos, os clusters primário e secundário com os LUNs que fazem parte do relacionamento do Grupo de Consistência devem ser adicionados e descobertos no Unified Manager.  Somente LUNs iSCSI e FCP são suportados.

Para obter informações sobre a sincronização ativa do SnapMirror , consultelink:https://docs.netapp.com/us-en/ontap/smbc/index.html["Documentação do ONTAP 9 para sincronização ativa do SnapMirror (anteriormente SM-BC)"] .

Para visualizar LUNs compostos em seu ambiente, siga estas etapas:

.Passos
. No painel de navegação esquerdo, clique em *Armazenamento* > *LUNs*.
. No menu Exibir, selecione *Relacionamento* > *Todos os LUNs*.
+
A exibição Relacionamento: Todos os LUNs é exibida.



Você pode visualizar os detalhes do LUN, como o nome do LUN, o volume, a VM de armazenamento que hospeda o LUN, o cluster, o grupo de consistência e o LUN parceiro.  Você pode clicar em cada um desses componentes para obter uma visão detalhada.  Clicar no Grupo de Consistência leva você para a página Relacionamentos.

Clicar no LUN do parceiro permite que você visualize os detalhes de configuração na guia SAN da página Detalhes da VM de armazenamento da VM de armazenamento na qual o LUN do parceiro está hospedado.  Informações como iniciadores e grupos de iniciadores e outros aspectos do LUN parceiro são exibidas.

Você pode executar as funções padrão de nível de grade de classificação, filtragem, geração e upload de relatórios para os LUNs protegidos em seu ambiente.
